PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('list_report_data_sort_dir','DESC');
INSERT INTO "general_params" VALUES('entry_sproc','AddNewInstrument');
INSERT INTO "general_params" VALUES('post_submission_link_tag','instrument');
INSERT INTO "general_params" VALUES('alternate_title_create','Create New Instrument');
INSERT INTO "general_params" VALUES('alternate_title_edit','Edit New Instrument');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO "form_fields" VALUES(1,'iName','Instrument Name','text','24','24','','','VOrbi0x','trim|required|max_length[24]');
INSERT INTO "form_fields" VALUES(2,'iClass','Instrument Class','text','32','32','','','LTQ_FT','trim|required|max_length[32]');
INSERT INTO "form_fields" VALUES(3,'InstrumentGroup','Instrument Group','text','50','64','','','Other','trim|required|max_length[64]');
INSERT INTO "form_fields" VALUES(4,'iMethod','Capture Method','text','10','10','','','secfso','trim|required|max_length[10]');
INSERT INTO "form_fields" VALUES(5,'iRoomNum','Room Number','text','50','50','','','EMSL 14??','trim|required|max_length[50]');
INSERT INTO "form_fields" VALUES(6,'iDescription','Description','area','','','4','80','Description is required','trim|required|max_length[200]');
INSERT INTO "form_fields" VALUES(7,'Usage','Usage','text','50','50','','','','trim');
INSERT INTO "form_fields" VALUES(8,'OperationsRole','Operations Role','text','50','50','','','Production','trim');
INSERT INTO "form_fields" VALUES(9,'PercentEMSLOwned','Percent EMSL Owned','text','50','50','','','0','trim');
INSERT INTO "form_fields" VALUES(10,'sourceMachineName','Instrument Workstation Name','text','80','128','','','\\VOrbi0x.bionet\','trim|required|max_length[128]');
INSERT INTO "form_fields" VALUES(11,'sourcePath','Instrument XFer Folder (UNC)','area','','','2','60','ProteomicsData\','trim|required|max_length[255]');
INSERT INTO "form_fields" VALUES(12,'spPath','Storage Path','area','','','2','60','VOrbi0x\','trim|required|max_length[255]');
INSERT INTO "form_fields" VALUES(13,'spVolClient','Storage Vol Client (remote)','text','80','128','','','\\proto-x\','trim|required|max_length[128]');
INSERT INTO "form_fields" VALUES(14,'spVolServer','Storage Vol Server (local)','text','80','128','','','F:\','trim|required|max_length[128]');
INSERT INTO "form_fields" VALUES(15,'archivePath','Archive Path','text','50','50','','','/archive/dmsarch/VOrbi0x','trim|required|max_length[50]');
INSERT INTO "form_fields" VALUES(16,'archiveServer','Archive Server Name','text','50','50','','','agate.emsl.pnl.gov','trim|required|max_length[50]');
INSERT INTO "form_fields" VALUES(17,'archiveNote','Archive Note','text','50','50','','','VOrbi0x','trim|required|max_length[50]');
INSERT INTO "form_fields" VALUES(18,'AutoDefineStoragePath','Auto Define Storage Path','text','32','32','','','Y','trim|required|max_length[32]');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO "form_field_choosers" VALUES(1,'iClass','picker.replace','instrumentClassPickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(2,'iMethod','picker.replace','captureMethodPickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(3,'OperationsRole','picker.replace','instrumentOpsRolePickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(5,'InstrumentGroup','picker.replace','instrumentGroupPickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(6,'AutoDefineStoragePath','picker.replace','YNPickList','','',',','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO "sproc_args" VALUES(1,'iName','iName','varchar','input','24','AddNewInstrument');
INSERT INTO "sproc_args" VALUES(2,'iClass','iClass','varchar','input','32','AddNewInstrument');
INSERT INTO "sproc_args" VALUES(3,'iMethod','iMethod','varchar','input','10','AddNewInstrument');
INSERT INTO "sproc_args" VALUES(4,'iRoomNum','iRoomNum','varchar','input','50','AddNewInstrument');
INSERT INTO "sproc_args" VALUES(5,'iDescription','iDescription','varchar','input','255','AddNewInstrument');
INSERT INTO "sproc_args" VALUES(6,'sourceMachineName','sourceMachineName','varchar','input','128','AddNewInstrument');
INSERT INTO "sproc_args" VALUES(7,'sourcePath','sourcePath','varchar','input','255','AddNewInstrument');
INSERT INTO "sproc_args" VALUES(8,'spPath','spPath','varchar','input','255','AddNewInstrument');
INSERT INTO "sproc_args" VALUES(9,'spVolClient','spVolClient','varchar','input','128','AddNewInstrument');
INSERT INTO "sproc_args" VALUES(10,'spVolServer','spVolServer','varchar','input','128','AddNewInstrument');
INSERT INTO "sproc_args" VALUES(11,'archivePath','archivePath','varchar','input','50','AddNewInstrument');
INSERT INTO "sproc_args" VALUES(12,'archiveServer','archiveServer','varchar','input','50','AddNewInstrument');
INSERT INTO "sproc_args" VALUES(13,'archiveNote','archiveNote','varchar','input','50','AddNewInstrument');
INSERT INTO "sproc_args" VALUES(14,'Usage','Usage','varchar','input','50','AddNewInstrument');
INSERT INTO "sproc_args" VALUES(15,'OperationsRole','OperationsRole','varchar','input','50','AddNewInstrument');
INSERT INTO "sproc_args" VALUES(16,'InstrumentGroup','InstrumentGroup','varchar','input','64','AddNewInstrument');
INSERT INTO "sproc_args" VALUES(17,'PercentEMSLOwned','PercentEMSLOwned','varchar','input','24','AddNewInstrument');
INSERT INTO "sproc_args" VALUES(18,'<local>','message','varchar','output','512','AddNewInstrument');
INSERT INTO "sproc_args" VALUES(19,'AutoDefineStoragePath','AutoDefineStoragePath','varchar','input','32','AddNewInstrument');
COMMIT;
