PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('list_report_data_table','V_Storage_List_Report');
INSERT INTO "general_params" VALUES('list_report_data_sort_dir','DESC');
INSERT INTO "general_params" VALUES('detail_report_data_table','V_Storage_Detail_Report');
INSERT INTO "general_params" VALUES('detail_report_data_id_col','ID');
INSERT INTO "general_params" VALUES('detail_report_data_id_type','integer');
INSERT INTO "general_params" VALUES('entry_sproc','AddUpdateStorage');
INSERT INTO "general_params" VALUES('entry_page_data_table','V_Storage_Entry');
INSERT INTO "general_params" VALUES('entry_page_data_id_col','SP_ID');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO "form_fields" VALUES(1,'SP_ID','ID','non-edit','','','','','0','trim');
INSERT INTO "form_fields" VALUES(2,'SP_path','Path','text','40','255','','','','trim|required|max_length[255]');
INSERT INTO "form_fields" VALUES(3,'SP_vol_name_client','Volume (client)','text','40','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(4,'SP_vol_name_server','Volume (server)','text','40','128','','','','trim|required|max_length[128]');
INSERT INTO "form_fields" VALUES(5,'SP_function','Function','text','40','80','','','','trim|required|max_length[50]');
INSERT INTO "form_fields" VALUES(6,'SP_instrument_name','Instrument','text','40','80','','','','trim|required|max_length[50]');
INSERT INTO "form_fields" VALUES(7,'SP_description','Description','area','','','4','50','','trim|max_length[255]');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO "form_field_choosers" VALUES(1,'SP_function','picker.replace','storageFunctionPickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(2,'SP_instrument_name','picker.replace','instrumentNamePickList','','',',','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO "list_report_hotlinks" VALUES(1,'ID','invoke_entity','value','storage/show/','');
INSERT INTO "list_report_hotlinks" VALUES(2,'Instrument','invoke_entity','value','instrument/show/','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO "sproc_args" VALUES(1,'SP_path','path','varchar','input','255','AddUpdateStorage');
INSERT INTO "sproc_args" VALUES(2,'SP_vol_name_client','volNameClient','varchar','input','128','AddUpdateStorage');
INSERT INTO "sproc_args" VALUES(3,'SP_vol_name_server','volNameServer','varchar','input','128','AddUpdateStorage');
INSERT INTO "sproc_args" VALUES(4,'SP_function','storFunction','varchar','input','50','AddUpdateStorage');
INSERT INTO "sproc_args" VALUES(5,'SP_instrument_name','instrumentName','varchar','input','50','AddUpdateStorage');
INSERT INTO "sproc_args" VALUES(6,'SP_description','description','varchar','input','255','AddUpdateStorage');
INSERT INTO "sproc_args" VALUES(7,'SP_ID','ID','varchar','output','32','AddUpdateStorage');
INSERT INTO "sproc_args" VALUES(8,'<local>','mode','varchar','input','12','AddUpdateStorage');
INSERT INTO "sproc_args" VALUES(9,'<local>','message','varchar','output','512','AddUpdateStorage');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO "list_report_primary_filter" VALUES(1,'pf_vol_client','Vol Client','20','','Vol Client','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(2,'pf_instrument','Instrument','20','','Instrument','ContainsText','text','50','','');
INSERT INTO "list_report_primary_filter" VALUES(3,'pf_function','Function','20','','Function','ContainsText','text','50','','');
INSERT INTO "list_report_primary_filter" VALUES(4,'pf_description','Description','20','','Description','ContainsText','text','255','','');
INSERT INTO "list_report_primary_filter" VALUES(5,'pf_path','Path','20','','Path','ContainsText','text','255','','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO "detail_report_hotlinks" VALUES(1,'Instrument','detail-report','Instrument','instrument/show/','labelCol','dl_Instrument','');
COMMIT;
