PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('list_report_data_table','V_Cell_Culture_List_Report_2');
INSERT INTO "general_params" VALUES('list_report_data_sort_dir','DESC');
INSERT INTO "general_params" VALUES('detail_report_data_table','V_Cell_Culture_Detail_Report');
INSERT INTO "general_params" VALUES('detail_report_data_id_col','Name');
INSERT INTO "general_params" VALUES('entry_sproc','AddUpdateCellCulture');
INSERT INTO "general_params" VALUES('entry_page_data_table','V_Cell_Culture_Entry');
INSERT INTO "general_params" VALUES('entry_page_data_id_col','Name');
INSERT INTO "general_params" VALUES('detail_report_aux_info_target','Cell Culture');
INSERT INTO "general_params" VALUES('operations_sproc','DoMaterialItemOperation');
INSERT INTO "general_params" VALUES('post_submission_detail_id','Name');
INSERT INTO "general_params" VALUES('alternate_title_report','Biomaterial (Cell Culture) Report');
INSERT INTO "general_params" VALUES('alternate_title_search','Biomaterial (Cell Culture) Search');
INSERT INTO "general_params" VALUES('alternate_title_show','Biomaterial (Cell Culture) Detail Report');
INSERT INTO "general_params" VALUES('alternate_title_create','Create New Biomaterial (Cell Culture)');
INSERT INTO "general_params" VALUES('alternate_title_edit','Edit Biomaterial (Cell Culture)');
INSERT INTO "general_params" VALUES('alternate_title_param','Biomaterial (Cell Culture)');
INSERT INTO "general_params" VALUES('alternate_title_export','Biomaterial (Cell Culture)');
INSERT INTO "general_params" VALUES('detail_report_cmds','file_attachment_cmds');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO "form_fields" VALUES(1,'Name','Name','text-if-new','60','80','','','','trim|required|max_length[64]|alpha_dash|min_length[8]');
INSERT INTO "form_fields" VALUES(2,'CultureTypeName','Type','text','60','80','','','','trim|required|max_length[32]');
INSERT INTO "form_fields" VALUES(3,'CC_Source_Name','Supplier','text','60','80','','','','trim|required|max_length[64]');
INSERT INTO "form_fields" VALUES(4,'CC_Contact_PRN','Contact (usually PNNL Staff)','text','60','128','','','','trim|required|max_length[128]');
INSERT INTO "form_fields" VALUES(5,'CC_Reason','Reason for creation','area','','','4','50','','trim|required|max_length[500]');
INSERT INTO "form_fields" VALUES(6,'Campaign_Num','Campaign','text','60','80','','','','trim|required|max_length[64]');
INSERT INTO "form_fields" VALUES(7,'CC_PI_PRN','Principle Investigator (PRN)','text','60','80','','','','trim|required|max_length[32]');
INSERT INTO "form_fields" VALUES(8,'Container','Container','text','60','128','','','','trim|required|max_length[128]');
INSERT INTO "form_fields" VALUES(9,'CC_Comment','Comment','area','','','4','50','','trim|max_length[255]');
INSERT INTO "form_fields" VALUES(10,'Organism_List','Organism List','area','','','6','50','','trim');
INSERT INTO "form_fields" VALUES(11,'Mutation','Mutation','text','60','80','','','','trim|max_length[64]');
INSERT INTO "form_fields" VALUES(12,'Plasmid','Plasmid','text','60','80','','','','trim|max_length[64]');
INSERT INTO "form_fields" VALUES(13,'Cell_Line','Cell Line','text','60','80','','','','trim|max_length[64]');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO "form_field_choosers" VALUES(1,'CultureTypeName','picker.replace','cellCultureTypePickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(2,'CC_Contact_PRN','picker.replace','userPRNPickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(3,'Campaign_Num','list-report.helper','','helper_campaign/report','',',','');
INSERT INTO "form_field_choosers" VALUES(4,'CC_PI_PRN','picker.replace','userPRNPickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(5,'Container','list-report.helper','','helper_material_container/report','',',','');
INSERT INTO "form_field_choosers" VALUES(7,'Organism_List','picker.append','orgPickList','','',',','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO "list_report_primary_filter" VALUES(1,'pf_name','Name','20!','','Name','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(2,'pf_campaign','Campaign','20!','','Campaign','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(3,'pf_source','Source','32','','Source','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(4,'pf_contact','Contact','32','','Contact','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(5,'pf_pi','PI','32','','PI','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(6,'pf_comment','Comment','32','','Comment','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(7,'pf_organism','Organism(s)','30!','','Organisms','ContainsText','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO "list_report_hotlinks" VALUES(1,'Name','invoke_entity','value','cell_culture/show/','');
INSERT INTO "list_report_hotlinks" VALUES(2,'Reason','min_col_width','value','60','');
INSERT INTO "list_report_hotlinks" VALUES(3,'Comment','min_col_width','value','60','');
CREATE TABLE detail_report_commands ( id INTEGER PRIMARY KEY,  "name" text, "Type" text, "Command" text, "Target" text, "Tooltip" text, "Prompt" text );
INSERT INTO "detail_report_commands" VALUES(1,'Retire Biomaterial','cmd_op','retire_biomaterial','cell_culture','Make this biomaterial inactive and move it to null container','Are you sure that you want to retire this biomaterial?');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO "detail_report_hotlinks" VALUES(1,'Campaign','detail-report','Campaign','campaign/show','labelCol','campaign',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(2,'Container','detail-report','Container','material_items/report/~','labelCol','dl_container','');
INSERT INTO "detail_report_hotlinks" VALUES(3,'+Container','detail-report','Container','material_move_items/report/~','valueCol','dl_container_move','');
INSERT INTO "detail_report_hotlinks" VALUES(4,'Location','detail-report','Location','material_items/report/-/','labelCol','dl_location','');
INSERT INTO "detail_report_hotlinks" VALUES(5,'+Location','detail-report','Location','material_move_items/report/-/','valueCol','dl_location_move','');
INSERT INTO "detail_report_hotlinks" VALUES(6,'Organism_List','link_table','Organism_List','organism/report/~@','valueCol','dl_organism_list','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO "sproc_args" VALUES(1,'Name','cellCultureName','varchar','input','64','AddUpdateCellCulture');
INSERT INTO "sproc_args" VALUES(2,'CC_Source_Name','sourceName','varchar','input','64','AddUpdateCellCulture');
INSERT INTO "sproc_args" VALUES(3,'CC_Contact_PRN','contactPRN','varchar','input','64','AddUpdateCellCulture');
INSERT INTO "sproc_args" VALUES(4,'CC_PI_PRN','piPRN','varchar','input','32','AddUpdateCellCulture');
INSERT INTO "sproc_args" VALUES(5,'CultureTypeName','cultureType','varchar','input','32','AddUpdateCellCulture');
INSERT INTO "sproc_args" VALUES(6,'CC_Reason','reason','varchar','input','500','AddUpdateCellCulture');
INSERT INTO "sproc_args" VALUES(7,'CC_Comment','comment','varchar','input','500','AddUpdateCellCulture');
INSERT INTO "sproc_args" VALUES(8,'Campaign_Num','campaignNum','varchar','input','64','AddUpdateCellCulture');
INSERT INTO "sproc_args" VALUES(9,'<local>','mode','varchar','input','12','AddUpdateCellCulture');
INSERT INTO "sproc_args" VALUES(10,'<local>','message','varchar','output','512','AddUpdateCellCulture');
INSERT INTO "sproc_args" VALUES(11,'Container','container','varchar','input','128','AddUpdateCellCulture');
INSERT INTO "sproc_args" VALUES(12,'Organism_List','organismList','varchar','input','8000','AddUpdateCellCulture');
INSERT INTO "sproc_args" VALUES(13,'Mutation','mutation','varchar','input','64','AddUpdateCellCulture');
INSERT INTO "sproc_args" VALUES(14,'Plasmid','plasmid','varchar','input','64','AddUpdateCellCulture');
INSERT INTO "sproc_args" VALUES(15,'Cell_Line','cellLine','varchar','varchar','64','AddUpdateCellCulture');
INSERT INTO "sproc_args" VALUES(16,'ID','name','varchar','input','128','DoMaterialItemOperation');
INSERT INTO "sproc_args" VALUES(17,'<local>','callingUser','varchar','input','128','AddUpdateCellCulture');
INSERT INTO "sproc_args" VALUES(18,'<local>','mode','varchar','input','32','DoMaterialItemOperation');
INSERT INTO "sproc_args" VALUES(19,'<local>','message','varchar','output','512','DoMaterialItemOperation');
INSERT INTO "sproc_args" VALUES(20,'<local>','callingUser','varchar','input','128','DoMaterialItemOperation');
CREATE TABLE external_sources ( id INTEGER PRIMARY KEY,  "source_page" text, "field" text, "type" text, "value" text );
INSERT INTO "external_sources" VALUES(1,'sample_submission','Campaign_Num','ColName','Campaign');
INSERT INTO "external_sources" VALUES(2,'sample_submission','Container','ColName','Container List');
INSERT INTO "external_sources" VALUES(3,'sample_submission','CC_Contact_PRN','ColName','Received By');
INSERT INTO "external_sources" VALUES(4,'sample_submission','CC_Reason','ColName','Description');
COMMIT;
