PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('base_table','T_Enzymes');
INSERT INTO "general_params" VALUES('list_report_data_table','V_Enzymes_List_Report');
INSERT INTO "general_params" VALUES('list_report_data_sort_col','Enzyme_ID');
INSERT INTO "general_params" VALUES('list_report_data_sort_dir','ASC');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO "list_report_hotlinks" VALUES(1,'Enzyme_Name','invoke_entity','value','experiment/report/-/-/-/-/-/-/-/sfx/AND/Enzyme/MatchesText/@','');
INSERT INTO "list_report_hotlinks" VALUES(2,'Protein Collection','invoke_entity','value','protein_collection/report/~','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO "list_report_primary_filter" VALUES(1,'pf_ID','ID','','','Enzyme_ID','Equals','int','','','');
INSERT INTO "list_report_primary_filter" VALUES(2,'pf_name','Name','','','Enzyme_Name','ContainsText','text','','','');
INSERT INTO "list_report_primary_filter" VALUES(3,'pf_left_residues','Left Residues','','','Left Cleave Residues','ContainsText','text','','','');
INSERT INTO "list_report_primary_filter" VALUES(4,'pf_right_residues','Right Residues','','','Right Cleave Residues','ContainsText','text','','','');
INSERT INTO "list_report_primary_filter" VALUES(5,'pf_offset','Offset','','','Cleavage Offset','ContainsText','text','','','');
INSERT INTO "list_report_primary_filter" VALUES(6,'pf_protein_collection','Protein Collection','','','Protein Collection','ContainsText','text','','','');
COMMIT;
