PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('list_report_data_table','V_Instrument_List_Report');
INSERT INTO "general_params" VALUES('list_report_data_sort_dir','DESC');
INSERT INTO "general_params" VALUES('detail_report_data_table','V_Instrument_Detail_Report');
INSERT INTO "general_params" VALUES('detail_report_data_id_col','Name');
INSERT INTO "general_params" VALUES('detail_report_data_id_type','text');
INSERT INTO "general_params" VALUES('entry_sproc','AddUpdateInstrument');
INSERT INTO "general_params" VALUES('entry_page_data_table','V_Instrument_Entry');
INSERT INTO "general_params" VALUES('entry_page_data_id_col','InstrumentName');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO "form_fields" VALUES(1,'ID','ID','non-edit','','','','','0','trim');
INSERT INTO "form_fields" VALUES(2,'InstrumentName','InstrumentName','non-edit','','','','','To add an instrument, use https://dms2.pnl.gov/new_instrument/create','trim');
INSERT INTO "form_fields" VALUES(3,'Description','Description','area','50','255','4','60','','trim');
INSERT INTO "form_fields" VALUES(4,'InstrumentClass','InstrumentClass','text','32','32','','','LTQ_FT','trim');
INSERT INTO "form_fields" VALUES(5,'InstrumentGroup','InstrumentGroup','text','32','32','','','Other','trim');
INSERT INTO "form_fields" VALUES(6,'RoomNumber','RoomNumber','text','50','50','','','','trim');
INSERT INTO "form_fields" VALUES(7,'CaptureMethod','CaptureMethod','text','10','10','','','fso','trim');
INSERT INTO "form_fields" VALUES(8,'Status','Status','text','8','8','','','active','trim');
INSERT INTO "form_fields" VALUES(9,'Usage','Usage','text','50','50','','','','trim');
INSERT INTO "form_fields" VALUES(10,'OperationsRole','OperationsRole','text','50','50','','','Production','trim');
INSERT INTO "form_fields" VALUES(11,'TrackUsageWhenInactive','Track Usage When Inactive','text','32','32','','','Y','trim|required|max_length[12]');
INSERT INTO "form_fields" VALUES(12,'Scan_SourceDir','Scan Source Directory','text','32','32','','','Y','trim|required|max_length[12]');
INSERT INTO "form_fields" VALUES(13,'PercentEMSLOwned','Percent EMSL Owned','text','50','50','','','0','trim');
INSERT INTO "form_fields" VALUES(14,'AutoDefineStoragePath','Auto Define Storage Path','text','32','32','','','Y','trim|required|max_length[12]');
INSERT INTO "form_fields" VALUES(16,'AutoSPVolNameClient','Auto Storage VolNameClient','text','50','128','','','','trim');
INSERT INTO "form_fields" VALUES(17,'AutoSPVolNameServer','Auto Storage VolNameServer','text','50','128','','','','trim');
INSERT INTO "form_fields" VALUES(18,'AutoSPPathRoot','Auto Storage Path Root','text','50','128','','','','trim');
INSERT INTO "form_fields" VALUES(19,'AutoSPArchiveServerName','Auto Storage Archive Server Name','text','50','64','','','','trim');
INSERT INTO "form_fields" VALUES(20,'AutoSPArchivePathRoot','Auto Storage Archive Path Root','text','64','128','','','','trim');
INSERT INTO "form_fields" VALUES(21,'AutoSPArchiveSharePathRoot','Auto Storage Archive Share Path Root','text','64','128','','','','trim');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO "form_field_choosers" VALUES(1,'InstrumentClass','picker.replace','instrumentClassPickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(2,'CaptureMethod','picker.replace','captureMethodPickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(3,'Status','picker.replace','instrumentStatusPickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(4,'OperationsRole','picker.replace','instrumentOpsRolePickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(5,'InstrumentGroup','picker.replace','instrumentGroupPickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(6,'AutoDefineStoragePath','picker.replace','YNPickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(7,'Scan_SourceDir','picker.replace','YNPickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(8,'TrackUsageWhenInactive','picker.replace','YNPickList','','',',','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO "list_report_primary_filter" VALUES(1,'pf_name','Name','15!','','Name','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(2,'pf_class','Class','32','','Class','ContainsText','text','64','','');
INSERT INTO "list_report_primary_filter" VALUES(3,'pf_group','Group','32','','Group','ContainsText','text','64','','');
INSERT INTO "list_report_primary_filter" VALUES(4,'pf_ops_role','Ops Role','32','','Ops Role','ContainsText','text','64','','');
INSERT INTO "list_report_primary_filter" VALUES(5,'pf_status','Status','32','','Status','StartsWithText','text','64','','');
INSERT INTO "list_report_primary_filter" VALUES(6,'pf_assigned_storage','Assigned Storage','32','','Assigned Storage','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(7,'pf_assigned_source','Assigned Source','32','','Assigned Source','ContainsText','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO "list_report_hotlinks" VALUES(1,'ID','invoke_entity','Name','instrument/show/','');
INSERT INTO "list_report_hotlinks" VALUES(2,'Allowed Dataset Types','min_col_width','value','60','');
INSERT INTO "list_report_hotlinks" VALUES(3,'Group','invoke_entity','value','instrument_group/show/','');
INSERT INTO "list_report_hotlinks" VALUES(4,'Class','invoke_entity','value','instrumentclass/show/','');
INSERT INTO "list_report_hotlinks" VALUES(5,'Name','invoke_entity','value','helper_inst_source/view/','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO "sproc_args" VALUES(1,'ID','instrumentID','int','output','','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(2,'InstrumentName','instrumentName','varchar','input','24','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(3,'InstrumentClass','instrumentClass','varchar','input','32','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(4,'InstrumentGroup','instrumentGroup','varchar','intput','64','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(5,'CaptureMethod','captureMethod','varchar','input','10','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(6,'Status','status','varchar','input','8','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(7,'RoomNumber','roomNumber','varchar','input','50','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(8,'Description','description','varchar','input','2550','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(9,'Usage','usage','varchar','input','50','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(10,'OperationsRole','operationsRole','varchar','input','50','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(11,'TrackUsageWhenInactive','trackUsageWhenInactive','varchar','input','12','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(12,'Scan_SourceDir','scanSourceDir','varchar','input','32','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(13,'PercentEMSLOwned','percentEMSLOwned','varchar','input','24','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(14,'<local>','mode','varchar','input','12','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(15,'<local>','message','varchar','output','512','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(16,'AutoDefineStoragePath','autoDefineStoragePath','varchar','input','32','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(17,'AutoSPVolNameClient','autoSPVolNameClient','varchar','input','128','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(18,'AutoSPVolNameServer','autoSPVolNameServer','varchar','input','128','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(19,'AutoSPPathRoot','autoSPPathRoot','varchar','input','128','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(20,'AutoSPArchiveServerName','autoSPArchiveServerName','varchar','input','64','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(21,'AutoSPArchivePathRoot','autoSPArchivePathRoot','varchar','input','128','AddUpdateInstrument');
INSERT INTO "sproc_args" VALUES(22,'AutoSPArchiveSharePathRoot','autoSPArchiveSharePathRoot','varchar','input','128','AddUpdateInstrument');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO "detail_report_hotlinks" VALUES(1,'Allowed Dataset Types','detail-report','Instrument Group','instrument_allowed_dataset_type/report','labelCol','dl_instrument',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(2,'Name','detail-report','Name','instrument_operation_history/report','valueCol','dl_name_operation_history',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(3,'Instrument Group','detail-report','Instrument Group','instrument_group/show/','labelCol','dl_instrument_group',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(4,'Assigned Archive Path','detail-report','Name','archive_path/report','labelCol','dl_archive_path',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(5,'Assigned Storage','detail-report','Name','storage/report/-/~','labelCol','dl_assigned_storage',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(6,'Archive Share Path','href-folder','Archive Share Path','','labelCol','dl_archive_share_path',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(7,'Class','detail-report','Class','instrumentclass/show/','labelCol','dl_instrument_class',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(8,'+Name','detail-report','Name','instrument_config_history/report','labelCol','dl_name_config_history',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(9,'Allocation_Tag','detail-report','Instrument Group','instrument_group/show/','labelCol','dl_allocation_tag','');
INSERT INTO "detail_report_hotlinks" VALUES(10,'ID','detail-report','ID','instrumentid/show/','labelCol','dl_instrumentid','');
COMMIT;
