PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('list_report_sproc','GetFactorCrosstabByBatch');
INSERT INTO "general_params" VALUES('list_report_cmds','requested_run_batch_blocking_cmds');
INSERT INTO "general_params" VALUES('operations_sproc','UpdateRequestedRunBlockingAndFactors');
INSERT INTO "general_params" VALUES('list_report_cmds_url','requested_run_batch_blocking/operation');
INSERT INTO "general_params" VALUES('batch_sproc','MakeAutomaticRequestedRunFactors');
INSERT INTO "general_params" VALUES('requested_run_data_sproc','GetRequestedRunParametersAndFactors');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO "sproc_args" VALUES(1,'BatchID','BatchID','int','input','','GetFactorCrosstabByBatch');
INSERT INTO "sproc_args" VALUES(2,'NameContains','NameContains','varchar','input','48','GetFactorCrosstabByBatch');
INSERT INTO "sproc_args" VALUES(4,'infoOnly','infoOnly','tinyint','input','','GetFactorCrosstabByBatch');
INSERT INTO "sproc_args" VALUES(5,'<local>','message','varchar','output','512','GetFactorCrosstabByBatch');
INSERT INTO "sproc_args" VALUES(9,'blockingList','blockingList','text','input','2147483647','UpdateRequestedRunBlockingAndFactors');
INSERT INTO "sproc_args" VALUES(10,'factorList','factorList','text','input','2147483647','UpdateRequestedRunBlockingAndFactors');
INSERT INTO "sproc_args" VALUES(11,'<local>','message','varchar','output','512','UpdateRequestedRunBlockingAndFactors');
INSERT INTO "sproc_args" VALUES(12,'<local>','callingUser','varchar','input','128','UpdateRequestedRunBlockingAndFactors');
INSERT INTO "sproc_args" VALUES(13,'batchID','batchID','int','input','','MakeAutomaticRequestedRunFactors');
INSERT INTO "sproc_args" VALUES(14,'<local>','mode','varchar','input','32','MakeAutomaticRequestedRunFactors');
INSERT INTO "sproc_args" VALUES(15,'<local>','message','varchar','output','512','MakeAutomaticRequestedRunFactors');
INSERT INTO "sproc_args" VALUES(16,'<local>','callingUser','varchar','input','128','MakeAutomaticRequestedRunFactors');
INSERT INTO "sproc_args" VALUES(17,'itemList','itemList','text','input','2147483647','GetRequestedRunParametersAndFactors');
INSERT INTO "sproc_args" VALUES(18,'infoOnly','infoOnly','tinyint','input','','GetRequestedRunParametersAndFactors');
INSERT INTO "sproc_args" VALUES(19,'<local>','message','varchar','output','512','GetRequestedRunParametersAndFactors');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO "form_fields" VALUES(1,'BatchID',' Batch ID','text','12','12','','','','trim|max_length[12]');
INSERT INTO "form_fields" VALUES(2,'NameContains',' Name Contains','text','48','48','','','','trim|max_length[48]');
INSERT INTO "form_fields" VALUES(4,'infoOnly','Info Only','hidden','12','12','','','0','trim|max_length[12]');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO "list_report_hotlinks" VALUES(1,'Sel','CHECKBOX','Request','','');
INSERT INTO "list_report_hotlinks" VALUES(2,'@exclude','inplace_edit','Request','ajax','["Sel","BatchID", "Name", "Status", "Dataset_ID", "Request","Experiment"]');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO "form_field_choosers" VALUES(1,'BatchID','list-report.helper','','helper_requested_run_batch/report','',',','');
COMMIT;
