PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_analysis_request_jobs_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_requestid','Request ID','6','','request_id','Equals','text','30','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_state','State','6','','state','ContainsText','text','30','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_job_min','Min Job ID','6','','job','GreaterThanOrEqualTo','text','30','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_job_max','Max Job ID','6','','job','LessThanOrEqualTo','text','30','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_dataset','Dataset','40!','','dataset','ContainsTextTPO','text','90','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_tool','Tool','6','','tool_name','ContainsText','text','30','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'job','invoke_entity','value','analysis_job/show','');
INSERT INTO list_report_hotlinks VALUES(2,'dataset','invoke_entity','value','dataset/show','');
INSERT INTO list_report_hotlinks VALUES(3,'request_id','invoke_entity','value','analysis_job_request/show','');
INSERT INTO list_report_hotlinks VALUES(4,'comment','min_col_width','value','60','');
COMMIT;
