PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_aj_batch_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_batch','Batch','','','batch','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_description','Description','','','description','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_created','Created After','','','created','LaterThan','text','','','');
COMMIT;
