PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_archive_path_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('detail_report_data_table','v_archive_path_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','id');
INSERT INTO general_params VALUES('detail_report_data_id_type','integer');
INSERT INTO general_params VALUES('entry_sproc','add_update_archive_path');
INSERT INTO general_params VALUES('entry_page_data_table','v_archive_path_entry');
INSERT INTO general_params VALUES('entry_page_data_id_col','archive_path_id');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO form_fields VALUES(1,'archive_path_id','ID','non-edit','','','','','','trim');
INSERT INTO form_fields VALUES(2,'archive_path','Archive Path','text','64','128','','','','trim|required|max_length[128]');
INSERT INTO form_fields VALUES(3,'server_name','Archive Server','text','32','64','','','','trim|max_length[64]');
INSERT INTO form_fields VALUES(4,'network_share_path','Network Share Path','text','60','128','','','','trim|max_length[128]');
INSERT INTO form_fields VALUES(5,'instrument_name','Instrument Name','text','25','80','','','','trim|required|max_length[24]');
INSERT INTO form_fields VALUES(6,'note','Note','text','40','128','','','','trim|max_length[128]');
INSERT INTO form_fields VALUES(7,'archive_path_function','Status','text','24','24','','','','trim|required|max_length[24]');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO form_field_choosers VALUES(1,'instrument_name','picker.replace','instrumentNameAdminPickList','','',',','');
INSERT INTO form_field_choosers VALUES(2,'archive_path_function','picker.replace','archiveFunctionPickList','','',',','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_instrument_name','Instrument Name','60','','instrument_name','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_archive_path','Archive Path','60','','archive_path','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_description','Description','60','','description','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_path_id','Path ID','12','','path_id','Equals','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'path_id','invoke_entity','value','archive_path/show/','');
INSERT INTO list_report_hotlinks VALUES(2,'instrument_name','invoke_entity','value','instrument/show/','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'archive_path_id','archivePathID','varchar','output','32','add_update_archive_path');
INSERT INTO sproc_args VALUES(2,'archive_path','archivePath','varchar','input','128','add_update_archive_path');
INSERT INTO sproc_args VALUES(3,'server_name','archiveServer','varchar','input','64','add_update_archive_path');
INSERT INTO sproc_args VALUES(4,'instrument_name','instrumentName','varchar','input','24','add_update_archive_path');
INSERT INTO sproc_args VALUES(5,'network_share_path','networkSharePath','varchar','input','128','add_update_archive_path');
INSERT INTO sproc_args VALUES(6,'note','archiveNote','varchar','input','128','add_update_archive_path');
INSERT INTO sproc_args VALUES(7,'archive_path_function','archiveFunction','varchar','input','32','add_update_archive_path');
INSERT INTO sproc_args VALUES(8,'<local>','mode','varchar','input','12','add_update_archive_path');
INSERT INTO sproc_args VALUES(9,'<local>','message','varchar','output','512','add_update_archive_path');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO detail_report_hotlinks VALUES(1,'instrument_name','detail-report','instrument_name','instrument/report/~','labelCol','dl_Instrument','');
COMMIT;
