PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_archive_list_report_2');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('detail_report_data_table','v_archive_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','dataset');
INSERT INTO general_params VALUES('operations_sproc','DoArchiveOperation');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_dataset','Dataset','45!','','dataset','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_id','ID','10','','id','Equals','text','24','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_state','State','32','','state','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_update','Update','32','','update','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_instrument','Instrument','32','','instrument','ContainsText','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'dataset','invoke_entity','value','archive/show/','');
CREATE TABLE detail_report_commands ( id INTEGER PRIMARY KEY,  "name" text, "Type" text, "Command" text, "Target" text, "Tooltip" text, "Prompt" text );
INSERT INTO detail_report_commands VALUES(1,'Reset Archive State','cmd_op','archivereset','archive','','Are you sure that you want to reset the archive state to New for this dataset?');
INSERT INTO detail_report_commands VALUES(2,'Reset Update State','cmd_op','update_req','archive','','Are you sure that you want to set the archive update state to Update Required for this dataset?');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO detail_report_hotlinks VALUES(1,'dataset','detail-report','dataset','dataset/show','labelCol','dataset',NULL);
INSERT INTO detail_report_hotlinks VALUES(2,'network_share_path','href-folder','network_share_path','','labelCol','dl_network_share_path',NULL);
INSERT INTO detail_report_hotlinks VALUES(3,'archive_url','literal_link','archive_url','','valueCol','dl_archive_url',NULL);
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'ID','datasetNum','varchar','input','128','DoArchiveOperation');
INSERT INTO sproc_args VALUES(2,'<local>','mode','varchar','input','12','DoArchiveOperation');
INSERT INTO sproc_args VALUES(3,'<local>','message','varchar','output','512','DoArchiveOperation');
INSERT INTO sproc_args VALUES(4,'<local>','callingUser','varchar','input','128','DoArchiveOperation');
COMMIT;
