PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_aux_info_definition_with_allowed_values');
INSERT INTO general_params VALUES('list_report_data_sort_dir','ASC');
INSERT INTO general_params VALUES('list_report_data_cols','target, category, subcategory, item, item_id, allowed_values');
INSERT INTO general_params VALUES('list_report_data_order_by','target, category, subcategory');
INSERT INTO general_params VALUES('operations_sproc','add_update_aux_info');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_target','Target','10','','target','StartsWithText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_category','Category','12','','category','StartsWithText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_subcategory','Subcategory','12','','subcategory','StartsWithText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_item','Item','12','','item','StartsWithText','text','80','','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'targetName','targetName','varchar','input','128','add_update_aux_info');
INSERT INTO sproc_args VALUES(2,'targetEntityName','targetEntityName','varchar','input','128','add_update_aux_info');
INSERT INTO sproc_args VALUES(3,'categoryName','categoryName','varchar','input','128','add_update_aux_info');
INSERT INTO sproc_args VALUES(4,'subCategoryName','subCategoryName','varchar','input','128','add_update_aux_info');
INSERT INTO sproc_args VALUES(5,'itemNameList','itemNameList','varchar','input','4000','add_update_aux_info');
INSERT INTO sproc_args VALUES(6,'itemValueList','itemValueList','varchar','input','3000','add_update_aux_info');
INSERT INTO sproc_args VALUES(7,'<local>','mode','varchar','input','12','add_update_aux_info');
INSERT INTO sproc_args VALUES(8,'<local>','message','varchar','output','512','add_update_aux_info');
CREATE TABLE utility_queries ( id integer PRIMARY KEY, name text, label text, db text, "table" text, columns text, sorting text, filters text, hotlinks text );
INSERT INTO utility_queries VALUES(1,'definitions','Aux Info Definition Details','','V_Aux_Info_Definition_with_ID','*, dbo.get_aux_info_allowed_values(Item_ID) AS Allowed_Values','{"col":"target", "dir":"ASC"}','{"target":"CTx", "category":"CTx",  "subcategory":"CTx",  "item":"CTx"}','');
INSERT INTO utility_queries VALUES(2,'experiment_values','Aux Info Values for Experiments','','V_Aux_Info_Experiment_Values','*','{"col":"id", "dir":"DESC"}','{"experiment":"CTx", "category":"CTx",  "subcategory":"CTx",  "item":"CTx"}','');
INSERT INTO utility_queries VALUES(3,'biomaterial_values','Aux Info Values for Biomaterial','','V_Aux_Info_Biomaterial_Values','*','{"col":"id", "dir":"DESC"}','{"biomaterial":"CTx", "category":"CTx",  "subcategory":"CTx",  "item":"CTx"}','');
INSERT INTO utility_queries VALUES(4,'prep_request_values','Aux Info Values for Sample Prep Request','','V_Aux_Info_Sample_Prep_Request_Values','*','{"col":"id", "dir":"DESC"}','{"request":"CTx", "category":"CTx",  "subcategory":"CTx",  "item":"CTx"}','');
INSERT INTO utility_queries VALUES(5,'aux_info_targets','(internal)','','T_Aux_Info_Target','*','','','');
INSERT INTO utility_queries VALUES(6,'aux_info_categories','(internal)','','T_Aux_Info_Category','*','{"col":"Sequence", "dir":"ASC"}','{"Target_Type_ID":"EQn"}','');
INSERT INTO utility_queries VALUES(7,'aux_info_subcategories','(internal)','','T_Aux_Info_Subcategory','*','{"col":"Sequence", "dir":"ASC"}','{"Aux_Category_ID":"EQn"}','');
INSERT INTO utility_queries VALUES(8,'aux_info_items','(internal)','','T_Aux_Info_Description','*','{"col":"Sequence", "dir":"ASC"}','{"Aux_Subcategory_ID":"EQn"}','');
INSERT INTO utility_queries VALUES(9,'aux_info_allowed_values','(internal)','','T_Aux_Info_Allowed_Values','Value as ID, Value as Name','{"col":"Value", "dir":"ASC"}','{"Aux_Description_ID":"EQn"}','');
COMMIT;
