PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','T_Bionet_Hosts');
INSERT INTO general_params VALUES('list_report_data_table','v_bionet_list_report');
INSERT INTO general_params VALUES('detail_report_data_table','v_bionet_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','host');
INSERT INTO general_params VALUES('entry_page_data_table','v_bionet_entry');
INSERT INTO general_params VALUES('entry_sproc','add_update_bionet_host');
INSERT INTO general_params VALUES('entry_page_data_id_col','host');
INSERT INTO general_params VALUES('post_submission_detail_id','host');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'host','invoke_entity','host','bionet/show','');
INSERT INTO list_report_hotlinks VALUES(2,'instruments','link_list','instruments','helper_inst_source/view','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_host','Host','20','','host','ContainsText','text','64','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_ip','IP','20','','ip','ContainsText','text','20','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_alias','Alias','20','','alias','ContainsText','text','64','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_tag','Tag','20','','tag','ContainsText','text','20','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_instruments','Instruments','20','','instruments','ContainsText','text','64','','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO detail_report_hotlinks VALUES(1,'instruments','link_table','instruments','instrument/report','valueCol','dl_Instruments',NULL);
INSERT INTO detail_report_hotlinks VALUES(4,'instrument_datasets','link_table','instrument_datasets','helper_inst_source/view/','valueCol','dl_InstrumentDatasets',NULL);
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO form_fields VALUES(1,'host','Host','text-if-new','50','64','','','','trim');
INSERT INTO form_fields VALUES(2,'ip','IP','text','15','15','','','','trim|max_length[15]');
INSERT INTO form_fields VALUES(3,'alias','Alias','text','50','64','','','','trim|max_length[64]');
INSERT INTO form_fields VALUES(4,'tag','Tag','text','24','24','','','','trim|max_length[24]');
INSERT INTO form_fields VALUES(5,'instruments','Instruments','area','','','2','40','','trim|max_length[1024]');
INSERT INTO form_fields VALUES(6,'comment','Comment','area','','','4','70','','trim|max_length[1024]');
INSERT INTO form_fields VALUES(7,'active','Active','text','12','12','','','','trim|max_length[12]');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'host','host','varchar','input','64','add_update_bionet_host');
INSERT INTO sproc_args VALUES(2,'ip','ip','varchar','input','15','add_update_bionet_host');
INSERT INTO sproc_args VALUES(3,'alias','alias','varchar','input','64','add_update_bionet_host');
INSERT INTO sproc_args VALUES(4,'tag','tag','varchar','input','24','add_update_bionet_host');
INSERT INTO sproc_args VALUES(5,'instruments','instruments','varchar','input','1024','add_update_bionet_host');
INSERT INTO sproc_args VALUES(6,'comment','comment','varchar','intput','1024','add_update_bionet_host');
INSERT INTO sproc_args VALUES(7,'active','active','tinyint','input','','add_update_bionet_host');
INSERT INTO sproc_args VALUES(8,'<local>','mode','varchar','input','12','add_update_bionet_host');
INSERT INTO sproc_args VALUES(9,'<local>','message','varchar','output','512','add_update_bionet_host');
INSERT INTO sproc_args VALUES(10,'<local>','callingUser','varchar','input','128','add_update_bionet_host');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO form_field_choosers VALUES(1,'active','picker.replace','yesNoAsOneZeroPickList','','',',','');
INSERT INTO form_field_choosers VALUES(2,'instruments','picker.append','instrumentNameAdminPickList','','',',','');
COMMIT;
