PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','V_Capture_Check_Report');
INSERT INTO general_params VALUES('my_db_group','capture');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'Job','invoke_entity','value','capture_jobs/show/','');
INSERT INTO list_report_hotlinks VALUES(2,'Steps','invoke_entity','Job','capture_job_steps/report','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_script','Script','6','','Script','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_job_state_b','State','6','','State','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_dataset','Dataset','6','','Dataset','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_job','Job','6','','Job','Equals','text','80','','');
COMMIT;
