PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_capture_log_list_report');
INSERT INTO general_params VALUES('my_db_group','capture');
INSERT INTO general_params VALUES('list_report_data_sort_col','id');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_posted_by','Posted_By','20','','posted_by','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_type','Type','20','','type','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_message','Message','20','','message','ContainsText','text','4096','','');
COMMIT;
