PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_charge_code_list_report');
INSERT INTO general_params VALUES('detail_report_data_table','v_charge_code_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','charge_code');
INSERT INTO general_params VALUES('list_report_data_sort_col','sort_key');
INSERT INTO general_params VALUES('list_report_data_sort_dir','ASC');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'charge_code','invoke_entity','value','charge_code/show','');
INSERT INTO list_report_hotlinks VALUES(2,'usage_requested_run','invoke_entity','charge_code','requested_run/report/-/-/-/-/-/-/-/-/~','');
INSERT INTO list_report_hotlinks VALUES(3,'usage_sample_prep','invoke_entity','charge_code','sample_prep_request/report/-/-/-/-/-/~','');
INSERT INTO list_report_hotlinks VALUES(4,'state','color_label','activation_state','','{"0":"clr_30","1":"clr_45","2":"clr_60","3":"clr_90","4":"clr_120","5":"clr_120"}');
INSERT INTO list_report_hotlinks VALUES(5,'owner_username','invoke_entity','value','user/report/','');
INSERT INTO list_report_hotlinks VALUES(6,'activation_state','no_display','value','','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_charge_code','Code','20','','charge_code','ContainsText','text','20','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_wbs','WBS','20','','wbs','ContainsText','text','60','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_title','Title','20','','title','ContainsText','text','30','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_subaccount','SubAcct','20','','sub_account','ContainsText','text','60','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_owner_name','Owner','20','','owner_name','ContainsText','text','50','','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO detail_report_hotlinks VALUES(1,'sub_account','detail-report','sub_account','charge_code/report/-/-/-/~','labelCol','dl_SubAccount',NULL);
INSERT INTO detail_report_hotlinks VALUES(2,'wbs','detail-report','wbs','charge_code/report/-/~','labelCol','dl_WBS',NULL);
INSERT INTO detail_report_hotlinks VALUES(3,'title','detail-report','title','charge_code/report/-/-/~','labelCol','dl_Title',NULL);
INSERT INTO detail_report_hotlinks VALUES(4,'usage_requested_run','detail-report','charge_code','requested_run/report/-/-/-/-/-/-/-/-/~','labelCol','dl_Usage_Requested_Run','');
INSERT INTO detail_report_hotlinks VALUES(5,'usage_sample_prep','detail-report','charge_code','sample_prep_request/report/-/-/-/-/-/~','labelCol','dl_Usage_Sample_Prep','');
INSERT INTO detail_report_hotlinks VALUES(6,'state','color_label','wp_activation_state','','valueCol','dl_State','{"3":"clr_90","4":"clr_120", "5":"clr_120","10":"clr_120"}');
INSERT INTO detail_report_hotlinks VALUES(7,'owner_username','detail-report','owner_username','user/report/','labelCol','dl_Owner','');
INSERT INTO detail_report_hotlinks VALUES(8,'wp_activation_state','no_display','value','',NULL,NULL,'');
COMMIT;
