PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_service_use_list_report');
INSERT INTO general_params VALUES('detail_report_data_table','v_service_use_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','id');
INSERT INTO general_params VALUES('detail_report_data_id_type','integer');
INSERT INTO general_params VALUES('entry_page_data_table','v_service_use_entry');
INSERT INTO general_params VALUES('entry_page_data_id_col','id');
INSERT INTO general_params VALUES('entry_sproc','add_update_service_use_entry');
INSERT INTO general_params VALUES('list_report_data_sort_col','report_id, dataset_id');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'id','invoke_entity','value','service_use/show','');
INSERT INTO list_report_hotlinks VALUES(2,'dataset_id','invoke_entity','value','datasetid/show','');
INSERT INTO list_report_hotlinks VALUES(3,'service_type_id','invoke_entity','value','service_type/report/','');
INSERT INTO list_report_hotlinks VALUES(4,'report_id','invoke_entity','value','service_use_report/report/','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_report_id','Report ID','','','report_id','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_dataset_id','Dataset ID','','','dataset_id','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_charge_code','Charge Code','','','charge_code','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_service_type_id','Service Type ID','','','service_type_id','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_service_type','Service Type','','','service_type','ContainsText','text','','','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text, "options" text );
INSERT INTO detail_report_hotlinks VALUES(1,'report_id','detail-report','report_id','service_use/report','valueCol','','');
INSERT INTO detail_report_hotlinks VALUES(2,'+report_id','detail-report','report_id','service_use_report/report','labelCol','','');
COMMIT;
