PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','T_Factors');
INSERT INTO general_params VALUES('list_report_data_table','V_Custom_Factors_List_Report');
INSERT INTO general_params VALUES('list_report_data_sort_col','Batch, Request');
INSERT INTO general_params VALUES('list_report_data_sort_dir','Desc');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_batch','Batch','20','','Batch','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_request','Request','20','','Request','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_dataset','Dataset','20','','Dataset','ContainsText','text','64','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_experiment','Experiment','20','','Experiment','ContainsText','text','64','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_campaign','Campaign','20','','Campaign','ContainsText','text','64','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_factor','Factor','20','','Factor','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_dataset_id','Dataset_ID','20','','Dataset_ID','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(8,'pf_experiment_id','Experiment_ID','20','','Experiment_ID','Equals','text','20','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'Batch','invoke_entity','value','requested_run_batch/show','');
INSERT INTO list_report_hotlinks VALUES(2,'Request','invoke_entity','value','requested_run/show','');
INSERT INTO list_report_hotlinks VALUES(3,'Value','invoke_entity','Batch','requested_run_factors/param','');
INSERT INTO list_report_hotlinks VALUES(4,'+Value','min_col_width','value','35','');
INSERT INTO list_report_hotlinks VALUES(5,'Experiment','invoke_entity','value','experiment/show','');
INSERT INTO list_report_hotlinks VALUES(6,'Dataset','invoke_entity','value','dataset/show','');
COMMIT;
