PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_data_package_eus_proposals_list_report');
INSERT INTO general_params VALUES('my_db_group','package');
INSERT INTO general_params VALUES('list_report_data_sort_col','id, proposal_id');
INSERT INTO general_params VALUES('list_report_data_sort_dir','asc');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'proposal_id','invoke_entity','value','eus_proposals/show','');
INSERT INTO list_report_hotlinks VALUES(2,'title','min_col_width','value','70','');
INSERT INTO list_report_hotlinks VALUES(3,'id','invoke_entity','value','data_package/show','');
INSERT INTO list_report_hotlinks VALUES(4,'state','color_label','value','','{"Active":"clr_30", "Permanently Active":"clr_60", "Closed":"clr_90", "Inactive":"clr_90"}');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_id','ID','5!','','id','Equals','text','24','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_proposal','Proposal','12','','proposal_id','ContainsText','text','12','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_title','Title','20!','','title','ContainsText','text','32','','');
COMMIT;
