PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_data_analysis_request_active_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_col','id');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'id','invoke_entity','id','data_analysis_request/show/','');
INSERT INTO list_report_hotlinks VALUES(2,'days_in_queue','color_label','days_in_queue_bin','','{"30":"clr_30","60":"clr_60","90":"clr_90","120":"clr_120"}');
INSERT INTO list_report_hotlinks VALUES(3,'work_package','invoke_entity','value','charge_code/show','');
INSERT INTO list_report_hotlinks VALUES(4,'wp_state','color_label','wp_activation_state','','{"0":"clr_30","1":"clr_45","2":"clr_60","3":"clr_90","4":"clr_120","5":"clr_120","10":"clr_120"}');
INSERT INTO list_report_hotlinks VALUES(5,'state_comment','min_col_width','value','60','');
INSERT INTO list_report_hotlinks VALUES(6,'description','min_col_width','value','60','');
INSERT INTO list_report_hotlinks VALUES(7,'batch','invoke_entity','value','requested_run_batch/show','');
INSERT INTO list_report_hotlinks VALUES(8,'data_package','invoke_entity','value','data_package/show','');
INSERT INTO list_report_hotlinks VALUES(9,'exp_group','invoke_entity','value','experiment_group/show','');
INSERT INTO list_report_hotlinks VALUES(10,'eus_proposal','invoke_entity','value','eus_proposals/show','');
INSERT INTO list_report_hotlinks VALUES(11,'organism','invoke_entity','value','organism/report/~','');
INSERT INTO list_report_hotlinks VALUES(12,'campaign','invoke_entity','value','campaign/show','');
INSERT INTO list_report_hotlinks VALUES(13,'analysis_type','invoke_entity','value','data_analysis_request/report/-/-/~','');
INSERT INTO list_report_hotlinks VALUES(14,'days_in_queue_bin','no_display','value','','');
INSERT INTO list_report_hotlinks VALUES(15,'wp_activation_state','no_display','value','','');
INSERT INTO list_report_hotlinks VALUES(16,'+id','export_align','value','','{"Align":"Center"}');
INSERT INTO list_report_hotlinks VALUES(17,'+dataset_count','export_align','value','','{"Align":"Center"}');
INSERT INTO list_report_hotlinks VALUES(18,'+days_in_queue','export_align','value','','{"Align":"Center"}');
INSERT INTO list_report_hotlinks VALUES(19,'+work_package','export_align','value','','{"Align":"Center"}');
INSERT INTO list_report_hotlinks VALUES(20,'+wp_state','export_align','value','','{"Align":"Center"}');
INSERT INTO list_report_hotlinks VALUES(21,'+eus_proposal','export_align','value','','{"Align":"Center"}');
INSERT INTO list_report_hotlinks VALUES(22,'files','invoke_entity','id','file_attachment/report/-/StartsWith__data_analysis_request/@','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_state','State','32','','state','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_request_name','Request Name','32','','request_name','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_type','Type','32','','analysis_type','ContainsText','text','32','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_requester','Requester','32','','requester','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_organism','Organism','32','','organism','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_campaign','Campaign','20','','campaign','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_WP','WP','32','','wp','ContainsText','text','50','','');
INSERT INTO list_report_primary_filter VALUES(8,'pf_requested_personnel','Req. Personnel','32','','requested_personnel','ContainsText','text','32','','');
INSERT INTO list_report_primary_filter VALUES(9,'pf_assigned_personnel','Assigned Personnel','32','','assigned_personnel','ContainsText','text','32','','');
INSERT INTO list_report_primary_filter VALUES(10,'pf_batch','Batch','32','','batch','Equals','text','32','','');
INSERT INTO list_report_primary_filter VALUES(11,'pf_data_package','Data Package','32','','data_package','Equals','text','32','','');
INSERT INTO list_report_primary_filter VALUES(12,'pf_experiment_group','Exp. Group','32','','exp_group','Equals','text','32','','');
COMMIT;
