PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_data_package_campaigns_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_dir','asc');
INSERT INTO general_params VALUES('my_db_group','package');
INSERT INTO general_params VALUES('list_report_data_sort_col','id, campaign');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'id','invoke_entity','value','data_package/show','');
INSERT INTO list_report_hotlinks VALUES(2,'campaign','invoke_entity','value','campaign/show/','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_id','Pkg ID','5!','','id','Equals','text','24','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_campaign','Campaign','25!','','campaign','ContainsText','text','128','','');
COMMIT;
