PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('list_report_data_table','V_Data_Analysis_Request_Active_List_Report');
INSERT INTO "general_params" VALUES('list_report_data_sort_col','ID');
INSERT INTO "general_params" VALUES('list_report_data_sort_dir','DESC');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO "list_report_hotlinks" VALUES(1,'ID','invoke_entity','ID','data_analysis_request/show/','');
INSERT INTO "list_report_hotlinks" VALUES(2,'Days In Queue','color_label','#days_in_queue','','{"30":"clr_30","60":"clr_60","90":"clr_90","120":"clr_120"}');
INSERT INTO "list_report_hotlinks" VALUES(3,'Work Package','invoke_entity','value','charge_code/show','');
INSERT INTO "list_report_hotlinks" VALUES(4,'WP State','color_label','#WPActivationState','','{"0":"clr_30","1":"clr_45","2":"clr_60","3":"clr_90","4":"clr_120","5":"clr_120","10":"clr_120"}');
INSERT INTO "list_report_hotlinks" VALUES(5,'State Comment','min_col_width','value','60','');
INSERT INTO "list_report_hotlinks" VALUES(6,'Description','min_col_width','value','60','');
INSERT INTO "list_report_hotlinks" VALUES(7,'Batch','invoke_entity','value','requested_run_batch/show','');
INSERT INTO "list_report_hotlinks" VALUES(8,'Data Package','invoke_entity','value','data_package/show','');
INSERT INTO "list_report_hotlinks" VALUES(9,'Exp. Group','invoke_entity','value','experiment_group/show','');
INSERT INTO "list_report_hotlinks" VALUES(10,'EUS Proposal','invoke_entity','value','eus_proposals/show','');
INSERT INTO "list_report_hotlinks" VALUES(11,'Organism','invoke_entity','value','organism/report/~','');
INSERT INTO "list_report_hotlinks" VALUES(12,'Campaign','invoke_entity','value','campaign/show','');
INSERT INTO "list_report_hotlinks" VALUES(13,'Analysis Type','invoke_entity','value','data_analysis_request/report/-/-/~','');
INSERT INTO "list_report_hotlinks" VALUES(14,'#days_in_queue','no_export','value','','');
INSERT INTO "list_report_hotlinks" VALUES(15,'#WPActivationState','no_export','value','','');
INSERT INTO "list_report_hotlinks" VALUES(16,'+ID','export_align','value','','{"Align":"Center"}');
INSERT INTO "list_report_hotlinks" VALUES(17,'+Dataset Count','export_align','value','','{"Align":"Center"}');
INSERT INTO "list_report_hotlinks" VALUES(18,'+Days In Queue','export_align','value','','{"Align":"Center"}');
INSERT INTO "list_report_hotlinks" VALUES(19,'+Work Package','export_align','value','','{"Align":"Center"}');
INSERT INTO "list_report_hotlinks" VALUES(20,'+WP State','export_align','value','','{"Align":"Center"}');
INSERT INTO "list_report_hotlinks" VALUES(21,'+EUS Proposal','export_align','value','','{"Align":"Center"}');
INSERT INTO "list_report_hotlinks" VALUES(22,'Files','invoke_entity','ID','file_attachment/report/-/StartsWith__data_analysis_request/@','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO "list_report_primary_filter" VALUES(1,'pf_state','State','32','','State','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(2,'pf_request_name','Request Name','32','','Request Name','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(3,'pf_type','Type','32','','Analysis Type','ContainsText','text','32','','');
INSERT INTO "list_report_primary_filter" VALUES(4,'pf_requester','Requester','32','','Requester','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(5,'pf_organism','Organism','32','','Organism','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(6,'pf_campaign','Campaign','20','','Campaign','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(7,'pf_WP','WP','32','','WP','ContainsText','text','50','','');
INSERT INTO "list_report_primary_filter" VALUES(8,'pf_requested_personnel','Req. Personnel','32','','Requested Personnel','ContainsText','text','32','','');
INSERT INTO "list_report_primary_filter" VALUES(9,'pf_assigned_personnel','Assigned Personnel','32','','Assigned Personnel','ContainsText','text','32','','');
INSERT INTO "list_report_primary_filter" VALUES(10,'pf_batch','Batch','32','','Batch','Equals','text','32','','');
INSERT INTO "list_report_primary_filter" VALUES(11,'pf_data_package','Data Package','32','','Data Package','Equals','text','32','','');
INSERT INTO "list_report_primary_filter" VALUES(12,'pf_experiment_group','Exp. Group','32','','Exp. Group','Equals','text','32','','');
COMMIT;
