PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_data_package_aggregation_list_report');
INSERT INTO general_params VALUES('my_db_group','package');
INSERT INTO general_params VALUES('list_report_cmds','data_package_job_coverage_cmds');
INSERT INTO general_params VALUES('operations_sproc','UpdateXxx');
INSERT INTO general_params VALUES('list_report_cmds_url','/xxx/operation');
INSERT INTO general_params VALUES('list_report_data_sort_col','dataset');
INSERT INTO general_params VALUES('list_report_data_sort_dir','ASC');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'sel','CHECKBOX','value','','');
INSERT INTO list_report_hotlinks VALUES(2,'job','invoke_entity','job','analysis_job/show','');
INSERT INTO list_report_hotlinks VALUES(3,'data_package_id','invoke_entity','value','data_package/show','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_data_package_id','ID','4!','','data_package_id','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_dataset','Dataset','30!','','dataset','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_tool','Tool','','','tool','ContainsText','text','64','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_in_package','In_Package','3!','','in_package','ContainsText','text','3','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_state','State','','','state','ContainsText','text','32','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_param_file','Param_File','45!','','param_file','ContainsText','text','256','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_settings_file','Settings_File','','','settings_file','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(8,'pf_protein_collection','Protein_Col','45!','','protein_collection_list','ContainsText','text','256','','');
INSERT INTO list_report_primary_filter VALUES(9,'pf_job','Job','','','job','Equals','text','20','','');
COMMIT;
