PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE home_menu_sections (
    "id" INTEGER PRIMARY KEY NOT NULL,
    "section_name" TEXT,
    "section_header" TEXT,
    "section_number" TEXT,
    "section_comment" TEXT
);
INSERT INTO "home_menu_sections" VALUES(1,'General','General','1','The DMS is part of PRISM, the Proteomics Research Information Storage and Management System. DMS acquires data from mass spectrometers, collects laboratory information, and tracks and controls the intermediate data processing. ');
INSERT INTO "home_menu_sections" VALUES(2,'Campaign','Campaign','2','Campaign is the overarching umbrella for a particular research interest. Everything in DMS flows up to a campaign.');
INSERT INTO "home_menu_sections" VALUES(3,'Material Storage','Material Storage','3','Material Storage is used to keep track of Biomaterial and injectable samples (Experiments) in our freezers. All tracked biomaterial must be in a container and that container (box) must have its freezer location recorded in DMS.');
INSERT INTO "home_menu_sections" VALUES(4,'Biomaterial','Cell Culture/Biomaterial','4','Biomaterial/Cell Culture refers to the physical sample of biological material, often in its raw form. It is usually something sent to us by a user or collaborator.');
INSERT INTO "home_menu_sections" VALUES(5,'Sample Prep','Sample Preparation','5','Biomaterial is typically processed into injectable samples (Experiments) by one or more of the sample prep staff.  There is a request system for PIs and post-docs to use for scheduling sample preparation.');
INSERT INTO "home_menu_sections" VALUES(6,'Experiments','Experiments (Prepared Sample)','6','Experiments are injectable samples that are prepared from biomaterial. All experiments must be entered into DMS in order to be run on the instruments. You would enter a sample prep request to have your biomaterial processed into experiments.');
INSERT INTO "home_menu_sections" VALUES(7,'Requested Run','Requested Run','7','A Requested Run is a request that a specific experiment be run on an LCMS instrument to produce a Dataset.  An individual LCMS request must be entered for each instrument run, including replicates and blanks.');
INSERT INTO "home_menu_sections" VALUES(8,'Datasets','Datasets (LCMS Run)','8','Datasets represent a specific injectable sample (i.e. an aliquot of an Experiment) that is run on a particular instrument. An individual LCMS request must be entered for each instrument run, including replicates and blanks.');
INSERT INTO "home_menu_sections" VALUES(9,'Analysis Request','Analysis Job Request','9','An Analysis Job Request is a request that data analysis be performed on one or more Datasets.');
INSERT INTO "home_menu_sections" VALUES(10,'Data Analysis','Data Analysis','10','An analysis job is an automated process that analyzes the spectra for a single Dataset using a specific analysis tool (SEQUEST / X!Tandem/ ICR-2LS, etc.). You must enter an analysis job request to define the analysis job to be run.');
CREATE TABLE home_menu_items (
    "id" INTEGER PRIMARY KEY,
    "section_name" TEXT,
    "page" TEXT,
    "link" TEXT,
    "label" TEXT
);
INSERT INTO "home_menu_items" VALUES(1,'Biomaterial','cell_culture/report','Display','a list of existing biomaterial items');
INSERT INTO "home_menu_items" VALUES(2,'Biomaterial','cell_culture/create','Create','a new biomaterial item');
INSERT INTO "home_menu_items" VALUES(4,'Biomaterial','cell_culture/search','Search','for existing biomaterial items');
INSERT INTO "home_menu_items" VALUES(5,'Biomaterial','organism/report','Display','a list of existing organisms');
INSERT INTO "home_menu_items" VALUES(6,'Biomaterial','organism/create','Create','a new organism');
INSERT INTO "home_menu_items" VALUES(7,'Biomaterial','upload/main','Load','biomaterial from spreadsheet tsv file');
INSERT INTO "home_menu_items" VALUES(8,'Campaign','campaign/report','Display','a list of existing research campaigns');
INSERT INTO "home_menu_items" VALUES(9,'Campaign','campaign/create','Create','a new research campaign');
INSERT INTO "home_menu_items" VALUES(10,'Campaign','campaign/search','Search','for an existing campaign');
INSERT INTO "home_menu_items" VALUES(12,'Analysis Request','analysis_job_request/report/-/-/-/-','Display','a list of analysis job requests');
INSERT INTO "home_menu_items" VALUES(13,'Analysis Request','analysis_job_request_psm/create','Create','a new MS/MS search request');
INSERT INTO "home_menu_items" VALUES(14,'Analysis Request','analysis_job_request/create','Create','a new analysis job request');
INSERT INTO "home_menu_items" VALUES(15,'Analysis Request','upload/main','Load','analysis job requests from spreadsheet tsv file');
INSERT INTO "home_menu_items" VALUES(16,'Data Analysis','analysis_job/report','Display','a list of existing analysis jobs');
INSERT INTO "home_menu_items" VALUES(17,'Data Analysis','analysis_job/search','Search','for an existing analysis job');
INSERT INTO "home_menu_items" VALUES(18,'Data Analysis','analysis_job/report/-/-/StartsWith__Decon2LS','Display','a list of Decon2LS analysis jobs');
INSERT INTO "home_menu_items" VALUES(19,'Data Analysis','analysis_job/report/-/-/StartsWith__MASIC','Display','a list of MASIC analysis jobs');
INSERT INTO "home_menu_items" VALUES(20,'Data Analysis','analysis_job/report/-/-/StartsWith__MODa','Display','a list of MODa analysis jobs');
INSERT INTO "home_menu_items" VALUES(21,'Data Analysis','analysis_job/report/-/-/StartsWith__MSAlign','Display','a list of MSAlign analysis jobs');
INSERT INTO "home_menu_items" VALUES(22,'Data Analysis','analysis_job/report/-/-/StartsWith__MSGFPlus','Display','a list of MSGFPlus analysis jobs');
INSERT INTO "home_menu_items" VALUES(23,'Data Analysis','analysis_job/report/-/-/StartsWith__MSPathFinder','Display','a list of MSPathFinder analysis jobs');
INSERT INTO "home_menu_items" VALUES(24,'Data Analysis','analysis_job/report/-/-/StartsWith__MSXML_Gen','Display','a list of MSXML_Gen analysis jobs');
INSERT INTO "home_menu_items" VALUES(25,'Data Analysis','analysis_job/report/-/-/StartsWith__NOMSI','Display','a list of NOMSI analysis jobs');
INSERT INTO "home_menu_items" VALUES(26,'Data Analysis','analysis_job/report/-/-/StartsWith__Phospho_FDR_Aggregator','Display','a list of Phospho_FDR_Aggregator analysis jobs');
INSERT INTO "home_menu_items" VALUES(27,'Data Analysis','analysis_job/report/-/-/StartsWith__PRIDE_Converter','Display','a list of PRIDE_Converter analysis jobs');
INSERT INTO "home_menu_items" VALUES(28,'Data Analysis','analysis_job/report/-/-/StartsWith__SEQUEST','Display','a list of SEQUEST analysis jobs');
INSERT INTO "home_menu_items" VALUES(29,'Data Analysis','analysis_job/report/-/-/StartsWith__XTandem','Display','a list of X!Tandem analysis jobs');
INSERT INTO "home_menu_items" VALUES(30,'Data Analysis','get_paramfile_crosstab/param','Display','the paramfile crosstab report');
INSERT INTO "home_menu_items" VALUES(31,'Requested Run','requested_run/report','Display','a list of existing requested runs');
INSERT INTO "home_menu_items" VALUES(32,'Requested Run','requested_run/create','Create','a new requested run (for experiment)');
INSERT INTO "home_menu_items" VALUES(33,'Requested Run','requested_run_group/create','Create','new requested runs (for experiment group)');
INSERT INTO "home_menu_items" VALUES(34,'Requested Run','requested_run/search','Search','for existing requested runs');
INSERT INTO "home_menu_items" VALUES(35,'Requested Run','upload/main','Load','requested runs from spreadsheet tsv file');
INSERT INTO "home_menu_items" VALUES(36,'Datasets','dataset/report','Display','a list of existing datasets');
INSERT INTO "home_menu_items" VALUES(37,'Datasets','dataset/search','Search','for existing datasets');
INSERT INTO "home_menu_items" VALUES(38,'Datasets','dataset_disposition/search','Disposition','pending datasets');
INSERT INTO "home_menu_items" VALUES(39,'Datasets','dataset_redisposition/create','Redisposition','datasets that have been released');
INSERT INTO "home_menu_items" VALUES(40,'Datasets','run_planning/report','Display','the planning report');
INSERT INTO "home_menu_items" VALUES(41,'Datasets','production_instrument_stats/param','Display','production instrument statistics report');
INSERT INTO "home_menu_items" VALUES(42,'Experiments','experiment/report','Display','a list of existing experiments');
INSERT INTO "home_menu_items" VALUES(43,'Experiments','experiment/create','Create','a new experiment');
INSERT INTO "home_menu_items" VALUES(44,'Experiments','experiment/search','Search','for existing experiments');
INSERT INTO "home_menu_items" VALUES(45,'Experiments','experiment_group/report','Display','a list of existing experiment groups');
INSERT INTO "home_menu_items" VALUES(46,'Experiments','experiment_fraction/create','Create','a new experiment fraction group');
INSERT INTO "home_menu_items" VALUES(47,'Experiments','experiment_group/create','Create','a new group for existing experiments');
INSERT INTO "home_menu_items" VALUES(48,'Experiments','experiment_plex_members/create','Create','a new experiment plex mapping');
INSERT INTO "home_menu_items" VALUES(49,'Material Storage','material_container/report/-/-/-','Display','list of active material containers');
INSERT INTO "home_menu_items" VALUES(50,'Material Storage','material_container/create','Create','a new storage container');
INSERT INTO "home_menu_items" VALUES(51,'Material Storage','material_items/report/-/-/-','Display','list of active material items');
INSERT INTO "home_menu_items" VALUES(52,'Material Storage','material_location/report/-/-/-','Display','a list of active material locations');
INSERT INTO "home_menu_items" VALUES(53,'Material Storage','material_move_container/report/-/-/-','Move','containers between locations');
INSERT INTO "home_menu_items" VALUES(54,'Material Storage','material_move_items/report/-/-/-','Move','material (Cell Culture, Experiments) between containers');
INSERT INTO "home_menu_items" VALUES(55,'Material Storage','material_log/report/-/-/-','Display','material movement and status log');
INSERT INTO "home_menu_items" VALUES(56,'Material Storage','wellplate/report/-/-/-','Display','a list of existing wellplates');
INSERT INTO "home_menu_items" VALUES(57,'Material Storage','wellplate/create','Create','a new wellplate');
INSERT INTO "home_menu_items" VALUES(58,'Sample Prep','sample_prep_request/report/-/-/-/-','Display','a list of all existing sample prep requests');
INSERT INTO "home_menu_items" VALUES(59,'Sample Prep','sample_prep_request/create','Create','a new sample prep request');
INSERT INTO "home_menu_items" VALUES(60,'Sample Prep','sample_prep_request/search','Search','for existing sample prep requests');
INSERT INTO "home_menu_items" VALUES(61,'Sample Prep','sample_prep_request_assignment/report','Assign','staff to requests (admin function)');
INSERT INTO "home_menu_items" VALUES(62,'Sample Prep','prep_lc_run/report','Display','a list of all prep LC runs');
INSERT INTO "home_menu_items" VALUES(63,'Sample Prep','prep_lc_run/create','Create','a new prep LC run');
INSERT INTO "home_menu_items" VALUES(64,'Sample Prep','prep_lc_column/report','Display','a list of all prep LC columns');
INSERT INTO "home_menu_items" VALUES(65,'Sample Prep','prep_lc_column/create','Create','a new prep LC column');
INSERT INTO "home_menu_items" VALUES(66,'Campaign','staff_roles/report','Display','a list of staff roles and assignments');
CREATE TABLE menu_def (
    "id" INTEGER PRIMARY KEY,
    "owner_menu" TEXT,
    "item_type" TEXT,
    "item_name" TEXT,
    "item_label" TEXT
);
INSERT INTO "menu_def" VALUES(1,'','submenu','Datasets','Datasets');
INSERT INTO "menu_def" VALUES(2,'Datasets','link','dataset/report','Report');
INSERT INTO "menu_def" VALUES(3,'Datasets','link','dataset/search','Search');
INSERT INTO "menu_def" VALUES(4,'Datasets','link','dataset/create','Entry');
INSERT INTO "menu_def" VALUES(5,'Datasets','link','dataset_disposition/search','Disposition');
INSERT INTO "menu_def" VALUES(6,'Datasets','link','dataset_disposition_lite','Disposition (No plots)');
INSERT INTO "menu_def" VALUES(7,'Datasets','link','main_log/report','Log');
INSERT INTO "menu_def" VALUES(8,'Datasets','submenu','Special Reports','Special Reports');
INSERT INTO "menu_def" VALUES(9,'Special Reports','link','ai_user_funded_datasets_list_report/report/-/-/-/-/12','User funded');
INSERT INTO "menu_def" VALUES(10,'Special Reports','link','dataset_funding/report/-/-/-/-/12','All funded');
INSERT INTO "menu_def" VALUES(11,'Special Reports','link','dataset_instrument/report','Instrument Usage');
INSERT INTO "menu_def" VALUES(12,'Special Reports','link','find_datasets_by_instrument/param','Most Recent Datasets by Instrument');
INSERT INTO "menu_def" VALUES(13,'Special Reports','link','production_instrument_stats/param','Dataset Production Statistics');
INSERT INTO "menu_def" VALUES(14,'Special Reports','link','dataset_qc/search','Dataset QC report');
INSERT INTO "menu_def" VALUES(15,'Special Reports','link','reporter_ion_observation_rate/search','Rep Ion Obs Rate Report');
INSERT INTO "menu_def" VALUES(16,'Special Reports','link','dataset_pm_and_psm/report/4/-/Exact','High Res Peak Matching Stats');
INSERT INTO "menu_def" VALUES(17,'Special Reports','link','dataset_psm_and_pm/report/4/StartsWith__msgfplus','PSM and Peak Matching Stats');
INSERT INTO "menu_def" VALUES(19,'Special Reports','link','data_package_dataset_psm_and_pm/report/-/4/StartsWith__msgfplus','Data Pkg PSM Stats');
INSERT INTO "menu_def" VALUES(20,'Datasets','separator','','');
INSERT INTO "menu_def" VALUES(21,'','submenu','Experiments','Experiments');
INSERT INTO "menu_def" VALUES(22,'Experiments','link','experiment/report','Report');
INSERT INTO "menu_def" VALUES(23,'Experiments','link','experiment/search','Search');
INSERT INTO "menu_def" VALUES(24,'Experiments','link','experiment/create','Entry');
INSERT INTO "menu_def" VALUES(25,'Experiments','submenu','Experiment Groups','Groups');
INSERT INTO "menu_def" VALUES(26,'Experiment Groups','link','experiment_group/report','Report');
INSERT INTO "menu_def" VALUES(27,'Experiment Groups','link','experiment_fraction/create','Make Fraction Group');
INSERT INTO "menu_def" VALUES(28,'Experiment Groups','link','experiment_group/create','Make General Group');
INSERT INTO "menu_def" VALUES(29,'Experiments','submenu','Experiment Factors','Factors');
INSERT INTO "menu_def" VALUES(30,'Experiment Factors','link','requested_run_factors/param','Define Factors');
INSERT INTO "menu_def" VALUES(31,'Experiment Factors','link','custom_factors/report/-','Browse Factors');
INSERT INTO "menu_def" VALUES(32,'Experiments','submenu','Experiment Labelling','Labelling');
INSERT INTO "menu_def" VALUES(33,'Experiment Labelling','link','experiment_plex_members/report/-/-/-','Plex Members');
INSERT INTO "menu_def" VALUES(34,'Experiment Labelling','link','experiment_plex_members_tsv/report/-/-/-','Plex Members TSV');
INSERT INTO "menu_def" VALUES(35,'Experiment Labelling','link','experiment_plex_members/create','Plex Members Entry');
INSERT INTO "menu_def" VALUES(36,'Experiment Labelling','link','sample_label_reporter_ions/report/-/-/-','Reporter Ions');
INSERT INTO "menu_def" VALUES(37,'Experiments','submenu','Experiment Organisms','Organisms');
INSERT INTO "menu_def" VALUES(38,'Experiment Organisms','link','organism/report','Report');
INSERT INTO "menu_def" VALUES(39,'Experiment Organisms','link','organism/create','Entry');
INSERT INTO "menu_def" VALUES(40,'Experiments','separator','','');
INSERT INTO "menu_def" VALUES(41,'','submenu','Cell Culture','Biomaterial');
INSERT INTO "menu_def" VALUES(42,'Cell Culture','link','cell_culture/report','Report');
INSERT INTO "menu_def" VALUES(43,'Cell Culture','link','cell_culture/search','Search');
INSERT INTO "menu_def" VALUES(44,'Cell Culture','link','cell_culture/create','Entry');
INSERT INTO "menu_def" VALUES(45,'','submenu','Campaigns','Campaigns');
INSERT INTO "menu_def" VALUES(46,'Campaigns','link','campaign/report','Report');
INSERT INTO "menu_def" VALUES(47,'Campaigns','link','campaign/search','Search');
INSERT INTO "menu_def" VALUES(48,'Campaigns','link','campaign/create','Entry');
INSERT INTO "menu_def" VALUES(49,'Campaigns','link','staff_roles/report','Staff Roles');
INSERT INTO "menu_def" VALUES(50,'Campaigns','link','campaign_dataset_stats/param','Campaign Dataset Stats');
INSERT INTO "menu_def" VALUES(51,'','separator',' ',' ');
INSERT INTO "menu_def" VALUES(52,'','submenu','Sample Prep','Sample Prep');
INSERT INTO "menu_def" VALUES(53,'Sample Prep','submenu','Sample Prep Report','Report');
INSERT INTO "menu_def" VALUES(54,'Sample Prep Report','link','sample_prep_request/report/-/-/-/-','All');
INSERT INTO "menu_def" VALUES(55,'Sample Prep Report','link','sample_prep_request/report/~Pending Approval','Pending Approval');
INSERT INTO "menu_def" VALUES(56,'Sample Prep Report','link','sample_prep_request/report/~Open','Open');
INSERT INTO "menu_def" VALUES(57,'Sample Prep Report','link','sample_prep_request/report/~Prep in Progress','Prep in Progress');
INSERT INTO "menu_def" VALUES(58,'Sample Prep Report','link','sample_prep_request/report/~Prep Complete','Prep Complete');
INSERT INTO "menu_def" VALUES(59,'Sample Prep Report','link','sample_prep_request/report/~Closed','Closed');
INSERT INTO "menu_def" VALUES(60,'Sample Prep Report','link','sample_prep_request_active/report','Active');
INSERT INTO "menu_def" VALUES(61,'Sample Prep','link','sample_prep_request/create','Entry');
INSERT INTO "menu_def" VALUES(62,'Sample Prep','link','sample_prep_request_assignment/report/-/:Closed','Assignment');
INSERT INTO "menu_def" VALUES(63,'Sample Prep','link','sample_prep_request_planning/report/','Planning Report');
INSERT INTO "menu_def" VALUES(64,'Sample Prep','submenu','Sample Prep Report Active','Active (by staff)');
INSERT INTO "menu_def" VALUES(65,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Burnet','Burnet');
INSERT INTO "menu_def" VALUES(66,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Gritsenko','Gritsenko');
INSERT INTO "menu_def" VALUES(67,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Hansen','Hansen');
INSERT INTO "menu_def" VALUES(68,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Hutchinson','Hutchinson');
INSERT INTO "menu_def" VALUES(69,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Nicora','Nicora');
INSERT INTO "menu_def" VALUES(70,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Paurus','Paurus');
INSERT INTO "menu_def" VALUES(71,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Olson','Olson');
INSERT INTO "menu_def" VALUES(72,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Schepmoes','Schepmoes');
INSERT INTO "menu_def" VALUES(74,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Smith','Smith');
INSERT INTO "menu_def" VALUES(75,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Trejo','Trejo');
INSERT INTO "menu_def" VALUES(76,'Sample Prep','submenu','OSM Packages','OSM Packages');
INSERT INTO "menu_def" VALUES(77,'OSM Packages','link','osm_package/report','Report');
INSERT INTO "menu_def" VALUES(78,'OSM Packages','link','osm_package/create','Entry');
INSERT INTO "menu_def" VALUES(79,'Sample Prep','submenu','Ops Tasks','Ops Tasks');
INSERT INTO "menu_def" VALUES(80,'Ops Tasks','link','operations_tasks/report','Report');
INSERT INTO "menu_def" VALUES(81,'Ops Tasks','link','operations_tasks/report/-/-/-/:Completed','Active');
INSERT INTO "menu_def" VALUES(82,'Ops Tasks','link','operations_tasks/create','Create');
INSERT INTO "menu_def" VALUES(83,'Sample Prep','submenu','Ops Tasks By Staff','Ops Tasks (by staff)');
INSERT INTO "menu_def" VALUES(84,'Ops Tasks By Staff','link','operations_tasks/report/-/-/Acosta/-/-','Acosta');
INSERT INTO "menu_def" VALUES(85,'Ops Tasks By Staff','link','operations_tasks/report/-/-/Culver/-/-','Culver');
INSERT INTO "menu_def" VALUES(86,'Ops Tasks By Staff','link','operations_tasks/report/-/-/Lawrence/-/-','Lawrence');
INSERT INTO "menu_def" VALUES(87,'Ops Tasks By Staff','link','operations_tasks/report/-/-/Lawver/-/-','Lawver');
INSERT INTO "menu_def" VALUES(88,'Ops Tasks By Staff','link','operations_tasks/report/-/-/Miller/-/-','Miller');
INSERT INTO "menu_def" VALUES(89,'Ops Tasks By Staff','link','operations_tasks/report/-/-/Prozapas/-/-','Prozapas');
INSERT INTO "menu_def" VALUES(90,'Ops Tasks By Staff','link','operations_tasks/report/-/-/Rosenstock/-/-','Rosenstock');
INSERT INTO "menu_def" VALUES(91,'Ops Tasks By Staff','link','operations_tasks/report/-/-/Wright/-/-','Wright');
INSERT INTO "menu_def" VALUES(92,'Sample Prep','submenu','Transcriptomics','Transcriptomics');
INSERT INTO "menu_def" VALUES(93,'Transcriptomics','link','rna_prep_request/report/-/-/-/-','Requests');
INSERT INTO "menu_def" VALUES(94,'Transcriptomics','link','rna_prep_request/create','Entry');
INSERT INTO "menu_def" VALUES(95,'Sample Prep','separator','','');
INSERT INTO "menu_def" VALUES(96,'','submenu','Prep LC','Prep LC');
INSERT INTO "menu_def" VALUES(97,'Prep LC','submenu','Prep LC Columns','Prep LC Columns');
INSERT INTO "menu_def" VALUES(98,'Prep LC Columns','link','prep_lc_column/report/-/-/-/-/NoMatch__Retired','Report');
INSERT INTO "menu_def" VALUES(99,'Prep LC Columns','link','prep_lc_column/create','Entry');
INSERT INTO "menu_def" VALUES(100,'Prep LC','submenu','Prep LC Runs','Prep LC Runs');
INSERT INTO "menu_def" VALUES(101,'Prep LC Runs','link','prep_lc_run/report','Report');
INSERT INTO "menu_def" VALUES(102,'Prep LC Runs','link','prep_lc_run/create','Entry');
INSERT INTO "menu_def" VALUES(103,'','separator',' ',' ');
INSERT INTO "menu_def" VALUES(104,'','submenu','Material Storage','Material Storage');
INSERT INTO "menu_def" VALUES(105,'Material Storage','link','material_location_available/report/-/-/-','Available Locations');
INSERT INTO "menu_def" VALUES(106,'Material Storage','link','material_location/report/-/-/-/-/-/-/Active','Active Locations');
INSERT INTO "menu_def" VALUES(107,'Material Storage','link','material_container/report/-/-/-/-/Active','Active Containers');
INSERT INTO "menu_def" VALUES(108,'Material Storage','link','material_items/report/-/-/-/-/Active','Active Items');
INSERT INTO "menu_def" VALUES(109,'Material Storage','link','freezers/report','Freezers');
INSERT INTO "menu_def" VALUES(110,'Material Storage','link','freezer/tree','Freezer Location Mgmt');
INSERT INTO "menu_def" VALUES(111,'Material Storage','link','material_container/create','New Container');
INSERT INTO "menu_def" VALUES(112,'Material Storage','link','material_log/report/-/-/-','Log');
INSERT INTO "menu_def" VALUES(113,'','submenu','Reference Compounds','Reference Compounds');
INSERT INTO "menu_def" VALUES(114,'Reference Compounds','link','reference_compound/report','Report');
INSERT INTO "menu_def" VALUES(116,'Reference Compounds','link','reference_compound/create','Entry');
INSERT INTO "menu_def" VALUES(117,'','submenu','Sample Submission','Sample Submission');
INSERT INTO "menu_def" VALUES(118,'Sample Submission','link','sample_submission/report','Report');
INSERT INTO "menu_def" VALUES(119,'Sample Submission','link','sample_submission/create','Entry');
INSERT INTO "menu_def" VALUES(120,'','submenu','Wellplates','Wellplates');
INSERT INTO "menu_def" VALUES(121,'Wellplates','link','wellplate/report/-/-/-','Report');
INSERT INTO "menu_def" VALUES(122,'Wellplates','link','wellplate/create','Entry');
INSERT INTO "menu_def" VALUES(123,'','separator','','');
INSERT INTO "menu_def" VALUES(124,'','submenu','Data Analysis','Data Analysis');
INSERT INTO "menu_def" VALUES(125,'Data Analysis','submenu','Data Analysis Reports','Reports (last 12 months)');
INSERT INTO "menu_def" VALUES(126,'Data Analysis Reports','link','analysis_job/report/-/-/-/-/-/-/-/-/52','All');
INSERT INTO "menu_def" VALUES(128,'Data Analysis Reports','link','analysis_job/report/-/-/StartsWith__MSGFPlus/-/-/-/-/-/52','MS-GF+');
INSERT INTO "menu_def" VALUES(130,'Data Analysis Reports','link','analysis_job/report/-/-/StartsWith__Decon2LS/-/-/-/-/-/52','DeconTools');
INSERT INTO "menu_def" VALUES(135,'Data Analysis Reports','link','analysis_job/report/-/-/StartsWith__MASIC/-/-/-/-/-/52','MASIC');
INSERT INTO "menu_def" VALUES(136,'Data Analysis Reports','link','analysis_job/report/-/-/StartsWith__MSPathFinder/-/-/-/-/-/52','MSPathFinder');
INSERT INTO "menu_def" VALUES(137,'Data Analysis Reports','link','analysis_job/report/-/-/StartsWith__XTandem/-/-/-/-/-/52','X!Tandem');
INSERT INTO "menu_def" VALUES(138,'Data Analysis','link','analysis_job/search','Search');
INSERT INTO "menu_def" VALUES(139,'Data Analysis','submenu','Analysis Job Requests','Job Requests');
INSERT INTO "menu_def" VALUES(140,'Analysis Job Requests','link','analysis_job_request/report/-/-/-/-','All');
INSERT INTO "menu_def" VALUES(141,'Analysis Job Requests','link','analysis_job_request/report/New','New');
INSERT INTO "menu_def" VALUES(142,'Analysis Job Requests','link','analysis_job_request/report/Used','Used');
INSERT INTO "menu_def" VALUES(144,'Analysis Job Requests','separator','','');
INSERT INTO "menu_def" VALUES(146,'Analysis Job Requests','link','analysis_job_request_psm/create','MS/MS Job Request Wizard');
INSERT INTO "menu_def" VALUES(147,'Analysis Job Requests','link','analysis_job_request/create','Create generic request');
INSERT INTO "menu_def" VALUES(149,'Analysis Job Requests','link','pipeline_job_steps/report/-/-/-/StartsWith__running','Running Job Steps');
INSERT INTO "menu_def" VALUES(150,'Data Analysis','submenu','MAC Jobs','MAC Jobs');
INSERT INTO "menu_def" VALUES(151,'MAC Jobs','link','pipeline_jobs/report/-/-/~Aggregation','Report');
INSERT INTO "menu_def" VALUES(152,'MAC Jobs','link','pipeline_jobs_history/report/-/-/~Aggregation','Report (older jobs)');
INSERT INTO "menu_def" VALUES(153,'MAC Jobs','link','mac_jobs/create','MAC Job Wizard');
INSERT INTO "menu_def" VALUES(154,'MAC Jobs','link','pipeline_jobs/create','Create generic MAC Job');
INSERT INTO "menu_def" VALUES(155,'Data Analysis','link','protein_collection/report','Protein Collections');
INSERT INTO "menu_def" VALUES(156,'Data Analysis','submenu','Analysis Job PSM Stats','PSM Stats');
INSERT INTO "menu_def" VALUES(157,'Analysis Job PSM Stats','link','analysis_job_psm/report/','Job PSM Stats');
INSERT INTO "menu_def" VALUES(158,'Analysis Job PSM Stats','link','data_package_analysis_job_psm/report/-/-/-/StartsWith__msgfplus','Data Pkg Job PSM Stats');
INSERT INTO "menu_def" VALUES(159,'Analysis Job PSM Stats','link','dataset_psm_and_pm/report/4/StartsWith__msgfplus','Dataset PSM Stats');
INSERT INTO "menu_def" VALUES(160,'Analysis Job PSM Stats','link','data_package_dataset_psm_and_pm/report/-/4/StartsWith__msgfplus','Data Pkg Dataset PSM Stats');
INSERT INTO "menu_def" VALUES(161,'Data Analysis','submenu','Data Analysis Requests','Data Analysis Requests');
INSERT INTO "menu_def" VALUES(162,'Data Analysis Requests','link','data_analysis_request/report/-/-/-','All');
INSERT INTO "menu_def" VALUES(163,'Data Analysis Requests','link','data_analysis_request/report/-/-/Lipidomics','Lipidomics');
INSERT INTO "menu_def" VALUES(164,'Data Analysis Requests','link','data_analysis_request/report/-/-/Metabolomics','Metabolomics');
INSERT INTO "menu_def" VALUES(165,'Data Analysis Requests','link','data_analysis_request/report/-/-/Proteomics','Proteomics');
INSERT INTO "menu_def" VALUES(166,'Data Analysis Requests','link','data_analysis_request/create','Create new request');
INSERT INTO "menu_def" VALUES(167,'','submenu','Data Packages','Data Packages');
INSERT INTO "menu_def" VALUES(168,'Data Packages','link','data_package/report','Report');
INSERT INTO "menu_def" VALUES(169,'Data Packages','link','data_package/create','Entry');
INSERT INTO "menu_def" VALUES(170,'','separator','','');
INSERT INTO "menu_def" VALUES(171,'','submenu','MS Scheduling','MS Scheduling');
INSERT INTO "menu_def" VALUES(172,'MS Scheduling','submenu','Requested Run Reports','Reports');
INSERT INTO "menu_def" VALUES(174,'Requested Run Reports','link','requested_run/report/-/-/-/-','Requests - All');
INSERT INTO "menu_def" VALUES(175,'Requested Run Reports','link','requested_run/report/-/-/Active','Requests - Active');
INSERT INTO "menu_def" VALUES(176,'Requested Run Reports','link','requested_run/report/-/-/Inactive','Requests - Inactive');
INSERT INTO "menu_def" VALUES(177,'Requested Run Reports','link','requested_run/report/-/-/Completed','Requests - Completed');
INSERT INTO "menu_def" VALUES(178,'Requested Run Reports','link','run_planning/report','Planning Report');
INSERT INTO "menu_def" VALUES(179,'Requested Run Reports','link','requested_run_admin/report','Admin Report');
INSERT INTO "menu_def" VALUES(180,'Requested Run Reports','link','dataset_instrument_runtime/param','Instrument Runtimes');
INSERT INTO "menu_def" VALUES(181,'MS Scheduling','submenu','MS Scheduling Entry','Entry');
INSERT INTO "menu_def" VALUES(182,'MS Scheduling Entry','link','requested_run/create','Single Entry');
INSERT INTO "menu_def" VALUES(183,'MS Scheduling Entry','link','requested_run_group/create','Group Entry');
INSERT INTO "menu_def" VALUES(184,'','submenu','Usage Tracking','Usage Tracking');
INSERT INTO "menu_def" VALUES(185,'Usage Tracking','link','run_tracking/cal','Inst. Usage Tracking');
INSERT INTO "menu_def" VALUES(186,'Usage Tracking','link','instrument_usage_report/grid','ERS Instrument Usage Grid');
INSERT INTO "menu_def" VALUES(187,'Usage Tracking','link','run_interval/report','Run Intervals');
INSERT INTO "menu_def" VALUES(188,'Usage Tracking','submenu','Tracking Datasets','Tracking Datasets');
INSERT INTO "menu_def" VALUES(189,'Tracking Datasets','link','tracking_dataset/report','Report');
INSERT INTO "menu_def" VALUES(190,'Tracking Datasets','link','tracking_dataset/create','Entry');
INSERT INTO "menu_def" VALUES(191,'MS Scheduling Entry','separator','','');
INSERT INTO "menu_def" VALUES(192,'MS Scheduling','submenu','MRM Transition List','MRM Transition List');
INSERT INTO "menu_def" VALUES(193,'MRM Transition List','link','mrm_list_attachment/report','Report');
INSERT INTO "menu_def" VALUES(194,'MRM Transition List','link','mrm_list_attachment/create','Upload');
INSERT INTO "menu_def" VALUES(195,'MRM Transition List','separator',' ',' ');
INSERT INTO "menu_def" VALUES(196,'MS Scheduling','submenu','MS Scheduling Batches','Run Batches');
INSERT INTO "menu_def" VALUES(197,'MS Scheduling Batches','link','requested_run_batch/report','Report');
INSERT INTO "menu_def" VALUES(198,'MS Scheduling Batches','link','requested_run_batch/report/-/-/-/-/-/-/-/1','Report Active Requests');
INSERT INTO "menu_def" VALUES(199,'MS Scheduling Batches','link','requested_run_batch/report/-/-/-/-/-/-/High/1','Report High Priority');
INSERT INTO "menu_def" VALUES(200,'MS Scheduling Batches','link','requested_run_batch/create','Entry');
INSERT INTO "menu_def" VALUES(201,'MS Scheduling Batches','link','batch_tracking/report/-/-/-/-','Tracking');
INSERT INTO "menu_def" VALUES(202,'MS Scheduling Batches','separator','','');
INSERT INTO "menu_def" VALUES(203,'MS Scheduling','submenu','Requested Run Blocking','Run Blocking');
INSERT INTO "menu_def" VALUES(204,'Requested Run Blocking','separator','','');
INSERT INTO "menu_def" VALUES(205,'Requested Run Blocking','link','requested_run_batch_blocking/param','Define Blocking');
INSERT INTO "menu_def" VALUES(206,'Requested Run Blocking','link','requested_run_batch_blocking/grid','Define Blocking (grid)');
INSERT INTO "menu_def" VALUES(207,'MS Scheduling','submenu','Requested Run Factors','Run Factors');
INSERT INTO "menu_def" VALUES(209,'Requested Run Factors','link','requested_run_factors/param','Define Factors');
INSERT INTO "menu_def" VALUES(210,'Requested Run Factors','link','custom_factors/report/-','Browse Factors');
INSERT INTO "menu_def" VALUES(211,'','separator',' ',' ');
INSERT INTO "menu_def" VALUES(212,'MS Scheduling','link','run_assignment_wellplate/report','Wellplates');
INSERT INTO "menu_def" VALUES(213,'','submenu','MS LC','MS LC');
INSERT INTO "menu_def" VALUES(214,'MS LC','submenu','LC Columns','LC Columns');
INSERT INTO "menu_def" VALUES(215,'LC Columns','link','lc_column/report','Report');
INSERT INTO "menu_def" VALUES(216,'LC Columns','link','lc_column/create','Entry');
INSERT INTO "menu_def" VALUES(217,'LC Columns','submenu','Special LC Columns Reports','Special Reports');
INSERT INTO "menu_def" VALUES(218,'Special LC Columns Reports','link','lc_column_dataset/report','Dataset Count');
INSERT INTO "menu_def" VALUES(219,'LC Columns','separator',' ',' ');
INSERT INTO "menu_def" VALUES(220,'MS LC','submenu','LC Carts','LC Carts');
INSERT INTO "menu_def" VALUES(221,'LC Carts','link','lc_cart/report','Report');
INSERT INTO "menu_def" VALUES(222,'LC Carts','link','lc_cart/create','Entry');
INSERT INTO "menu_def" VALUES(224,'LC Carts','link','lc_cart_request_loading/report','Configure loading (Req)');
INSERT INTO "menu_def" VALUES(225,'LC Carts','link','lc_cart_loading/report','Loading List');
INSERT INTO "menu_def" VALUES(226,'LC Carts','link','lc_cart_configuration/report','LC Cart Configurations');
INSERT INTO "menu_def" VALUES(227,'LC Carts','link','lc_cart_config_history/report','LC Cart Service Notes');
INSERT INTO "menu_def" VALUES(228,'LC Carts','separator','','');
INSERT INTO "menu_def" VALUES(229,'MS LC','submenu','Instrument Config','Instrument Config.');
INSERT INTO "menu_def" VALUES(230,'Instrument Config','link','instrument_config/report','Inst. List');
INSERT INTO "menu_def" VALUES(231,'Instrument Config','link','instrument_config_history/report','Config. History');
INSERT INTO "menu_def" VALUES(232,'Instrument Config','link','instrument_config_history/create','New Inst. Service Note');
INSERT INTO "menu_def" VALUES(233,'Instrument Config','separator','','');
INSERT INTO "menu_def" VALUES(234,'MS LC','link','run_op_logs/grid','Operation Log Grid');
INSERT INTO "menu_def" VALUES(235,'MS LC','link','instrument_operation_history/report','Inst. Operation Notes ');
INSERT INTO "menu_def" VALUES(236,'','separator',' ',' ');
INSERT INTO "menu_def" VALUES(237,'','submenu','MTS','MTS');
INSERT INTO "menu_def" VALUES(238,'MTS','submenu','Databases','Databases');
INSERT INTO "menu_def" VALUES(239,'Databases','link','mts_pt_dbs/report','Peptide DBs');
INSERT INTO "menu_def" VALUES(240,'Databases','link','mts_mt_dbs/report','AMT Tag DBs');
INSERT INTO "menu_def" VALUES(242,'MTS','submenu','MTS DB Jobs','Database Jobs');
INSERT INTO "menu_def" VALUES(243,'MTS DB Jobs','link','mts_pt_db_jobs/report','Peptide DB Jobs');
INSERT INTO "menu_def" VALUES(244,'MTS DB Jobs','link','mts_mt_db_jobs/report','AMT Tag DB Jobs');
INSERT INTO "menu_def" VALUES(245,'MTS','submenu','Peak Matching Results','Results');
INSERT INTO "menu_def" VALUES(246,'Peak Matching Results','link','mts_pm_results/report','Peak Matching');
INSERT INTO "menu_def" VALUES(247,'','separator',' ',' ');
INSERT INTO "menu_def" VALUES(248,'','submenu','Search','Search');
INSERT INTO "menu_def" VALUES(249,'Search','link','analysis_job/search','Analysis Jobs');
INSERT INTO "menu_def" VALUES(250,'Search','link','dataset/search','Datasets');
INSERT INTO "menu_def" VALUES(251,'Search','link','archive/search','Archive');
INSERT INTO "menu_def" VALUES(252,'Search','link','requested_run/search','Requested Runs');
INSERT INTO "menu_def" VALUES(254,'Search','link','experiment/search','Experiments');
INSERT INTO "menu_def" VALUES(255,'Search','link','sample_prep_request/search','Sample Prep Req.');
INSERT INTO "menu_def" VALUES(256,'Search','link','campaign/search','Campaigns');
INSERT INTO "menu_def" VALUES(257,'Search','separator','','');
INSERT INTO "menu_def" VALUES(258,'','submenu','Admin','Admin');
INSERT INTO "menu_def" VALUES(259,'Admin','submenu','Activity Reports','Activity Reports');
INSERT INTO "menu_def" VALUES(261,'Activity Reports','link','dataset_instrument_daily/param','Daily Dataset By Instrument');
INSERT INTO "menu_def" VALUES(262,'Activity Reports','link','request_daily/param','Daily Requests');
INSERT INTO "menu_def" VALUES(263,'Activity Reports','link','production_instrument_stats/param','Prod. Inst. Stats.');
INSERT INTO "menu_def" VALUES(264,'Activity Reports','link','dataset_instrument_runtime/param','Dataset Inst. Runtime');
INSERT INTO "menu_def" VALUES(265,'Activity Reports','link','campaign_dataset_stats/param','Campaign Dataset Stats');
INSERT INTO "menu_def" VALUES(266,'Activity Reports','link','project_usage/report/__ThisYear__/__ThisWeek__/user','Project Usage Stats');
INSERT INTO "menu_def" VALUES(267,'Activity Reports','link','tissue_stats/param/__TodayLastYear__/__Today__','Tissue Usage Statistics');
INSERT INTO "menu_def" VALUES(268,'Activity Reports','separator','','');
INSERT INTO "menu_def" VALUES(269,'Admin','submenu','Data Analysis Admin','Data Analysis');
INSERT INTO "menu_def" VALUES(270,'Data Analysis Admin','link','analysis_tools/report','Analysis Tools');
INSERT INTO "menu_def" VALUES(272,'Data Analysis Admin','link','get_paramfile_crosstab/param','Paramfile Crosstab');
INSERT INTO "menu_def" VALUES(273,'Data Analysis Admin','link','mass_correction_factors/report','Mass Correction Factors');
INSERT INTO "menu_def" VALUES(274,'Data Analysis Admin','link','param_file/report','Param File List Report');
INSERT INTO "menu_def" VALUES(275,'Data Analysis Admin','link','param_file_mass_mods/report','Param File Mass Mods');
INSERT INTO "menu_def" VALUES(276,'Data Analysis Admin','link','maxquant_mods/report','MaxQuant Mods');
INSERT INTO "menu_def" VALUES(277,'Data Analysis Admin','link','update_analysis_jobs/create','Multi-Job Update');
INSERT INTO "menu_def" VALUES(278,'Data Analysis Admin','link','analysis_batch/report','Batches');
INSERT INTO "menu_def" VALUES(279,'Data Analysis Admin','link','analysis_group/create','Job Entry');
INSERT INTO "menu_def" VALUES(280,'Data Analysis Admin','submenu','Processor Groups Admin','Processor Groups');
INSERT INTO "menu_def" VALUES(281,'Processor Groups Admin','link','analysis_job_processor_group/report','Report');
INSERT INTO "menu_def" VALUES(282,'Processor Groups Admin','link','analysis_job_processor_group/create','Entry');
INSERT INTO "menu_def" VALUES(283,'Data Analysis Admin','submenu','Processors Admin','Processors');
INSERT INTO "menu_def" VALUES(284,'Processors Admin','link','analysis_job_processors/report','Report');
INSERT INTO "menu_def" VALUES(285,'Processors Admin','link','analysis_job_processors/create','Entry');
INSERT INTO "menu_def" VALUES(286,'Data Analysis Admin','submenu','Predefines Admin','Predefines');
INSERT INTO "menu_def" VALUES(287,'Predefines Admin','submenu','Predefines Admin Report','Report');
INSERT INTO "menu_def" VALUES(288,'Predefines Admin Report','link','predefined_analysis/report/-','All');
INSERT INTO "menu_def" VALUES(289,'Predefines Admin Report','link','predefined_analysis/report/Agilent_Ion_Trap','Agilent_Ion_Trap');
INSERT INTO "menu_def" VALUES(290,'Predefines Admin Report','link','predefined_analysis/report/Agilent_TOF','Agilent_TOF');
INSERT INTO "menu_def" VALUES(291,'Predefines Admin Report','link','predefined_analysis/report/BRUKERFTMS','BRUKERFTMS');
INSERT INTO "menu_def" VALUES(292,'Predefines Admin Report','link','predefined_analysis/report/Finnigan_FTICR','Finnigan_FTICR');
INSERT INTO "menu_def" VALUES(293,'Predefines Admin Report','link','predefined_analysis/report/Finnigan_Ion_Trap','Finnigan_Ion_Trap');
INSERT INTO "menu_def" VALUES(294,'Predefines Admin Report','link','predefined_analysis/report/LTQ_FT','LTQ_FT');
INSERT INTO "menu_def" VALUES(295,'Predefines Admin Report','link','predefined_analysis/report/Micromass_QTOF','Micromass_QTOF');
INSERT INTO "menu_def" VALUES(296,'Predefines Admin Report','link','predefined_analysis/report/QStar_QTOF','QStar_QTOF');
INSERT INTO "menu_def" VALUES(297,'Predefines Admin Report','link','predefined_analysis_disabled/report','(Disabled)');
INSERT INTO "menu_def" VALUES(298,'Predefines Admin','separator','','');
INSERT INTO "menu_def" VALUES(299,'Predefines Admin','link','predefined_analysis/create','Entry');
INSERT INTO "menu_def" VALUES(300,'Predefines Admin','submenu','Predefines Admin Preview','Preview');
INSERT INTO "menu_def" VALUES(301,'Predefines Admin Preview','link','predefined_analysis_preview/param','Jobs');
INSERT INTO "menu_def" VALUES(302,'Predefines Admin Preview','link','predefined_analysis_preview_mds/param','Jobs (MDS)');
INSERT INTO "menu_def" VALUES(303,'Predefines Admin Preview','link','predefined_analysis_datasets/param','Datasets');
INSERT INTO "menu_def" VALUES(304,'Predefines Admin Preview','separator',' ',' ');
INSERT INTO "menu_def" VALUES(305,'Predefines Admin','submenu','Predefines Admin Scheduling Rules','Scheduling Rules');
INSERT INTO "menu_def" VALUES(306,'Predefines Admin Scheduling Rules','link','predefined_analysis_scheduling_rules/report','Report');
INSERT INTO "menu_def" VALUES(307,'Predefines Admin Scheduling Rules','link','predefined_analysis_scheduling_rules/create','Entry');
INSERT INTO "menu_def" VALUES(308,'Predefines Admin Scheduling Rules','separator','','');
INSERT INTO "menu_def" VALUES(309,'Admin','submenu','Data Analysis Pipeline','Data Analysis Pipeline');
INSERT INTO "menu_def" VALUES(310,'Data Analysis Pipeline','link','settings_files/report','Settings Files');
INSERT INTO "menu_def" VALUES(311,'Data Analysis Pipeline','link','pipeline_script/report','Script');
INSERT INTO "menu_def" VALUES(312,'Data Analysis Pipeline','link','pipeline_jobs/report','Jobs');
INSERT INTO "menu_def" VALUES(313,'Data Analysis Pipeline','link','pipeline_job_steps/report','Job Steps');
INSERT INTO "menu_def" VALUES(314,'Data Analysis Pipeline','link','pipeline_jobs/create','Pipeline Job Entry');
INSERT INTO "menu_def" VALUES(315,'Data Analysis Pipeline','link','pipeline_local_processors/report','Local Processors');
INSERT INTO "menu_def" VALUES(316,'Data Analysis Pipeline','link','pipeline_step_tools/report','Step Tools');
INSERT INTO "menu_def" VALUES(317,'Data Analysis Pipeline','link','pipeline_processor_tool_crosstab/report','Processor Tool Crosstab');
INSERT INTO "menu_def" VALUES(318,'Data Analysis Pipeline','link','pipeline_processor_step_tools/report','Processor Step Tools');
INSERT INTO "menu_def" VALUES(319,'Admin','submenu','Capture Pipeline','Capture Pipeline');
INSERT INTO "menu_def" VALUES(320,'Capture Pipeline','link','capture_script/report','Script');
INSERT INTO "menu_def" VALUES(321,'Capture Pipeline','link','capture_jobs/report','Jobs');
INSERT INTO "menu_def" VALUES(322,'Capture Pipeline','link','capture_job_steps/report','Job Steps');
INSERT INTO "menu_def" VALUES(323,'Capture Pipeline','link','capture_local_processors/report','Local Processors');
INSERT INTO "menu_def" VALUES(324,'Capture Pipeline','link','capture_step_tools/report','Step Tools');
INSERT INTO "menu_def" VALUES(326,'Capture Pipeline','link','capture_processor_step_tools/report','Processor Step Tools');
INSERT INTO "menu_def" VALUES(327,'Admin','submenu','Capture Status Checks','Capture Status Checks');
INSERT INTO "menu_def" VALUES(328,'Admin','submenu','Dataset Admin','Dataset');
INSERT INTO "menu_def" VALUES(331,'Dataset Admin','link','dataset_redisposition/create','Redisposition Dataset');
INSERT INTO "menu_def" VALUES(332,'Dataset Admin','separator','','');
INSERT INTO "menu_def" VALUES(333,'Admin','submenu','Archive Admin','Archive');
INSERT INTO "menu_def" VALUES(334,'Archive Admin','link','archive/report','Datasets');
INSERT INTO "menu_def" VALUES(335,'Archive Admin','link','archive_assigned_storage/report','Assigned');
INSERT INTO "menu_def" VALUES(336,'Archive Admin','link','archive_path/report','Archive Path');
INSERT INTO "menu_def" VALUES(338,'Archive Admin','link','archive/search','Search');
INSERT INTO "menu_def" VALUES(339,'Archive Admin','separator','','');
INSERT INTO "menu_def" VALUES(340,'Admin','submenu','Daily Status Checks','Daily Status Checks');
INSERT INTO "menu_def" VALUES(341,'Daily Status Checks','link','dataset_daily_check/report','Dataset');
INSERT INTO "menu_def" VALUES(342,'Daily Status Checks','link','main_log/report/Warning','Log - Warnings');
INSERT INTO "menu_def" VALUES(343,'Daily Status Checks','link','archive_daily_check/report','Archive');
INSERT INTO "menu_def" VALUES(344,'Daily Status Checks','link','archive_daily_check_update/report','Archive Update');
INSERT INTO "menu_def" VALUES(345,'Daily Status Checks','link','analysis_daily_check/report','Analysis');
INSERT INTO "menu_def" VALUES(346,'Daily Status Checks','link','manager_daily_check/param/72','Managers');
INSERT INTO "menu_def" VALUES(347,'Daily Status Checks','link','dms_activity/report','DMS Activity');
INSERT INTO "menu_def" VALUES(348,'Daily Status Checks','separator','','');
INSERT INTO "menu_def" VALUES(349,'Admin','submenu','Event Log','Event Log');
INSERT INTO "menu_def" VALUES(350,'Event Log','link','event_log_dataset/report','Dataset');
INSERT INTO "menu_def" VALUES(351,'Event Log','link','event_log_analysis_job/report','Analyses');
INSERT INTO "menu_def" VALUES(352,'Event Log','link','event_log_archive/report','Archive');
INSERT INTO "menu_def" VALUES(353,'Admin','submenu','Instruments Admin','Instruments');
INSERT INTO "menu_def" VALUES(354,'Instruments Admin','link','instrument/report','Report');
INSERT INTO "menu_def" VALUES(355,'Instruments Admin','link','new_instrument/create','New');
INSERT INTO "menu_def" VALUES(356,'Instruments Admin','link','run_op_logs/grid','Operation Log Grid');
INSERT INTO "menu_def" VALUES(357,'Instruments Admin','link','bionet/report','Bionet Hosts and IPs');
INSERT INTO "menu_def" VALUES(358,'Admin','submenu','Instrument Class','Instrument Class');
INSERT INTO "menu_def" VALUES(359,'Instrument Class','link','instrumentclass/report','Report');
INSERT INTO "menu_def" VALUES(360,'Instrument Class','link','new_instrumentclass/create','Entry');
INSERT INTO "menu_def" VALUES(361,'Admin','submenu','Material Storage Admin','Material Storage');
INSERT INTO "menu_def" VALUES(362,'Material Storage Admin','link','material_location/report','Material Locations');
INSERT INTO "menu_def" VALUES(363,'Material Storage Admin','link','material_log/report','Material Log');
INSERT INTO "menu_def" VALUES(364,'Material Storage Admin','link','material_move_container/report/-/-/-','Move Containers');
INSERT INTO "menu_def" VALUES(365,'Material Storage Admin','link','material_move_items/report/-/-/-','Move Items');
INSERT INTO "menu_def" VALUES(366,'Admin','submenu','EMSL Admin','EMSL');
INSERT INTO "menu_def" VALUES(367,'EMSL Admin','submenu','EMSL Admin EUS Proposals','EUS Proposals');
INSERT INTO "menu_def" VALUES(368,'EMSL Admin EUS Proposals','link','eus_proposals/report/-','Report (all)');
INSERT INTO "menu_def" VALUES(369,'EMSL Admin EUS Proposals','link','eus_proposals/report/New','Report (new)');
INSERT INTO "menu_def" VALUES(370,'EMSL Admin EUS Proposals','link','eus_proposals/report/Active','Report (active)');
INSERT INTO "menu_def" VALUES(371,'EMSL Admin EUS Proposals','link','eus_proposals/create','Entry');
INSERT INTO "menu_def" VALUES(372,'EMSL Admin','submenu','EMSL Admin EUS Users','EUS Users');
INSERT INTO "menu_def" VALUES(373,'EMSL Admin EUS Users','link','eus_users/report','Report');
INSERT INTO "menu_def" VALUES(374,'EMSL Admin EUS Users','link','eus_users/create','Entry');
INSERT INTO "menu_def" VALUES(378,'EMSL Admin','submenu','EMSL Admin Instrument Usage','Instrument Usage');
INSERT INTO "menu_def" VALUES(380,'EMSL Admin Instrument Usage','link','instrument_actual/report/__ThisYear__','Actual Instrument Usage');
INSERT INTO "menu_def" VALUES(382,'EMSL Admin Instrument Usage','link','instrument_actual_monthly/report/__ThisYear__/__ThisMonth__','Monthly Instrument Usage');
INSERT INTO "menu_def" VALUES(383,'EMSL Admin Instrument Usage','link','instrument_usage_report/report/__ThisYear__/__LastMonth__','ERS Instrument Usage Report');
INSERT INTO "menu_def" VALUES(384,'EMSL Admin Instrument Usage','link','instrument_usage_report/grid','ERS Instrument Usage Grid');
INSERT INTO "menu_def" VALUES(385,'EMSL Admin Instrument Usage','link','run_tracking/cal','Inst. Usage Tracking');
INSERT INTO "menu_def" VALUES(386,'EMSL Admin Instrument Usage','link','run_interval/report','Run Intervals');
INSERT INTO "menu_def" VALUES(387,'EMSL Admin Instrument Usage','link','project_usage/report/__ThisYear__/__ThisWeek__/user','Weekly usage by project');
INSERT INTO "menu_def" VALUES(388,'Admin','submenu','Ontology','Ontology / Unimod');
INSERT INTO "menu_def" VALUES(389,'Ontology','link','ncbi_taxonomy/report','NCBI Taxonomy Names');
INSERT INTO "menu_def" VALUES(390,'Ontology','link','ontology/report/NEWT/-/-/mus mus/-/-/','Species (NEWT)');
INSERT INTO "menu_def" VALUES(391,'Ontology','link','tissue/report','Tissue (BTO)');
INSERT INTO "menu_def" VALUES(392,'Ontology','link','ontology/report/CL/-/-/blood/-/-/','Cell Type (CL)');
INSERT INTO "menu_def" VALUES(393,'Ontology','link','ontology/report/DOID/-/-/diab/-/-/','Disease (DOID)');
INSERT INTO "menu_def" VALUES(394,'Ontology','link','unimod/report/','Unimod Mods');
INSERT INTO "menu_def" VALUES(395,'Admin','submenu','Organisms Admin','Organisms');
INSERT INTO "menu_def" VALUES(396,'Organisms Admin','link','organism/report','Report');
INSERT INTO "menu_def" VALUES(397,'Organisms Admin','link','organism/create','Entry');
INSERT INTO "menu_def" VALUES(398,'Organisms Admin','link','ncbi_taxonomy/report','NCBI Taxonomy Names');
INSERT INTO "menu_def" VALUES(399,'Organisms Admin','link','protein_collection/report','Protein Collections');
INSERT INTO "menu_def" VALUES(400,'Organisms Admin','link','helper_organism_db/report','Legacy FASTA files');
INSERT INTO "menu_def" VALUES(401,'Admin','submenu','File Storage','Storage');
INSERT INTO "menu_def" VALUES(402,'File Storage','link','storage/report','Report');
INSERT INTO "menu_def" VALUES(403,'File Storage','link','storage/create','Entry');
INSERT INTO "menu_def" VALUES(405,'Admin','submenu','User Admin','Users');
INSERT INTO "menu_def" VALUES(406,'User Admin','link','user/report','Report');
INSERT INTO "menu_def" VALUES(407,'User Admin','link','user/create','Entry');
INSERT INTO "menu_def" VALUES(408,'User Admin','link','user_operation/report','Operations');
INSERT INTO "menu_def" VALUES(409,'Admin','submenu','Internal Standards Admin','Internal Standards');
INSERT INTO "menu_def" VALUES(410,'Internal Standards Admin','link','internal_standards/report','Report');
INSERT INTO "menu_def" VALUES(411,'Admin','submenu','Manager Control','Manager Control');
INSERT INTO "menu_def" VALUES(412,'Manager Control','link','mc_params/report','Parameters');
INSERT INTO "menu_def" VALUES(413,'Manager Control','link','mc_enable_control_by_manager/report','Manager Control');
INSERT INTO "menu_def" VALUES(414,'Manager Control','link','mc_enable_control_by_manager_type/report','Manager Type Control');
INSERT INTO "menu_def" VALUES(415,'Admin','submenu','Metadata Dump','Metadata Dump');
INSERT INTO "menu_def" VALUES(416,'Metadata Dump','link','dump_metadata_for_multiple_experiments/param','Experiment Metadata');
INSERT INTO "menu_def" VALUES(417,'Metadata Dump','link','dump_metadata_for_multiple_datasets/param','Dataset Metadata');
INSERT INTO "menu_def" VALUES(418,'Admin','submenu','Aux Info Definition','Aux Info Definition');
INSERT INTO "menu_def" VALUES(419,'Aux Info Definition','link','aux_info_def/report/Cell Culture','Cell Culture');
INSERT INTO "menu_def" VALUES(420,'Aux Info Definition','link','aux_info_def/report/Experiment','Experiment');
INSERT INTO "menu_def" VALUES(421,'Aux Info Definition','link','aux_info_def/report/Dataset','Dataset');
INSERT INTO "menu_def" VALUES(422,'Aux Info Definition','link','aux_info_def/report/SamplePrepRequest','Sample Prep Request');
INSERT INTO "menu_def" VALUES(423,'Admin','submenu','Spreadsheet Loader','Spreadsheet Loader');
INSERT INTO "menu_def" VALUES(424,'Spreadsheet Loader','link','upload/main','Load Spreadsheet');
INSERT INTO "menu_def" VALUES(425,'Capture Status Checks','link','capture_daily_check/report/-','All');
INSERT INTO "menu_def" VALUES(426,'Capture Status Checks','link','capture_daily_check/report/DatasetCapture','Dataset Capture');
INSERT INTO "menu_def" VALUES(427,'Capture Status Checks','link','capture_daily_check/report/ArchiveUpdate','Archive Update');
INSERT INTO "menu_def" VALUES(428,'Capture Status Checks','link','capture_daily_check/report/DatasetArchive','Dataset Archive');
INSERT INTO "menu_def" VALUES(429,'Capture Status Checks','link','capture_daily_check/report/SourceFileRename','Source File Rename');
INSERT INTO "menu_def" VALUES(431,'Capture Pipeline','link','capture_log/report','Capture Log');
INSERT INTO "menu_def" VALUES(432,'Data Analysis Requests','submenu','Data Analysis Requests Active','Active (by staff)');
INSERT INTO "menu_def" VALUES(433,'Data Analysis Requests Active','link','data_analysis_request_active/report/-/-/-/-/-/-/-/StartsWith__Couvillion/-/-/-/-','Couvillion');
INSERT INTO "menu_def" VALUES(434,'Data Analysis Requests Active','link','data_analysis_request_active/report/-/-/-/-/-/-/-/StartsWith__Hixson/-/-/-/-','Hixson');
INSERT INTO "menu_def" VALUES(435,'Data Analysis Requests Active','link','data_analysis_request_active/report/-/-/-/-/-/-/-/StartsWith__Kim/-/-/-/-','Kim');
INSERT INTO "menu_def" VALUES(436,'Data Analysis Requests Active','link','data_analysis_request_active/report/-/-/-/-/-/-/-/StartsWith__Munoz/-/-/-/-','Munoz');
INSERT INTO "menu_def" VALUES(437,'Data Analysis Requests Active','link','data_analysis_request_active/report/-/-/-/-/-/-/-/StartsWith__Nakayasu/-/-/-/-','Nakayasu');
CREATE TABLE nav_def (
    "id" INTEGER PRIMARY KEY,
    "owner_menu" TEXT,
    "item_type" TEXT,
    "item_name" TEXT,
    "item_label" TEXT,
    "item_help" TEXT
);
INSERT INTO "nav_def" VALUES(1,'','header_context','side_panel_toggle','','');
INSERT INTO "nav_def" VALUES(2,'','header_context','home_link','','');
INSERT INTO "nav_def" VALUES(3,'','header_context','admin_page_link','','');
INSERT INTO "nav_def" VALUES(4,'','submenu','General','General','');
INSERT INTO "nav_def" VALUES(5,'General','separator','','Navigation','');
INSERT INTO "nav_def" VALUES(6,'General','link','gen/welcome','Home','');
INSERT INTO "nav_def" VALUES(7,'General','link','javascript:gamma.kill_frames()','Hide Side Menu','');
INSERT INTO "nav_def" VALUES(8,'General','link','javascript:gamma.open_frames()','Show Side Menu','');
INSERT INTO "nav_def" VALUES(9,'General','link','http://prismwiki.pnl.gov/wiki/PRISM_QuickStart_Guide','PRISM Wiki','');
INSERT INTO "nav_def" VALUES(10,'General','separator','','Preferences','');
INSERT INTO "nav_def" VALUES(11,'General','link','preferences','Preferences','');
INSERT INTO "nav_def" VALUES(12,'General','link_context','save_settings_link','Save Page Settings','Save current settings as defaults');
INSERT INTO "nav_def" VALUES(13,'General','link_context','clear_settings_link','Clear Page Settings','Clear any saved defaults');
INSERT INTO "nav_def" VALUES(14,'General','separator','','Notification','');
INSERT INTO "nav_def" VALUES(15,'General','link_context','user_notification_link','Notification','Show my current notifications');
INSERT INTO "nav_def" VALUES(16,'General','link_context','email_notification_link','EMail settings','Set email notification preferences');
INSERT INTO "nav_def" VALUES(17,'General','separator','','Campaigns','');
INSERT INTO "nav_def" VALUES(18,'General','link','campaign/report','Report','Display list of campaigns');
INSERT INTO "nav_def" VALUES(19,'General','link','campaign/search','Search','');
INSERT INTO "nav_def" VALUES(20,'General','link','campaign/create','Entry','Create a new campaign');
INSERT INTO "nav_def" VALUES(21,'General','link','staff_roles/report','Staff Roles','Display staff roles and responsibilities for campaigns');
INSERT INTO "nav_def" VALUES(22,'General','separator','','Data Packages','');
INSERT INTO "nav_def" VALUES(23,'General','link','data_package/report','Report','Display list of data packages');
INSERT INTO "nav_def" VALUES(24,'General','link','data_package/create','Entry','Create a new data package');
INSERT INTO "nav_def" VALUES(25,'General','separator','','File Attachments','');
INSERT INTO "nav_def" VALUES(26,'General','link','file_attachment/report','Report','Display list of file attachments');
INSERT INTO "nav_def" VALUES(27,'','submenu','Samples','Samples','');
INSERT INTO "nav_def" VALUES(28,'Samples','separator','','Material Storage','');
INSERT INTO "nav_def" VALUES(29,'Samples','link','material_location_available/report/-/-/-','Available Locations','Display list of material locations with space available');
INSERT INTO "nav_def" VALUES(30,'Samples','link','material_location/report/-/-/-/-/-/-/Active','Active Locations','Display list of material locations');
INSERT INTO "nav_def" VALUES(31,'Samples','link','material_container/report/-/-/-/-/Active','Active Containers','Display list of material containers');
INSERT INTO "nav_def" VALUES(32,'Samples','link','material_items/report/-/-/-/-/Active','Active Items','Display list of material items (experiments, biomaterial)');
INSERT INTO "nav_def" VALUES(33,'Samples','link','material_container/create','New Container','Create new container');
INSERT INTO "nav_def" VALUES(34,'Samples','link','material_log/report/-/-/-','Log','Display material tracking log');
INSERT INTO "nav_def" VALUES(35,'Samples','separator','','Sample Submission','');
INSERT INTO "nav_def" VALUES(36,'Samples','link','sample_submission/report','Report','Show list of sample submissions');
INSERT INTO "nav_def" VALUES(37,'Samples','link','sample_submission/create','Entry','Make new sample submission');
INSERT INTO "nav_def" VALUES(38,'Samples','separator','','Sample Prep Req','');
INSERT INTO "nav_def" VALUES(39,'Samples','link','sample_prep_request/report','Report','Display list of sample prep requests');
INSERT INTO "nav_def" VALUES(40,'Samples','link','sample_prep_request/create','Entry','Create a new sample prep request');
INSERT INTO "nav_def" VALUES(41,'Samples','link','sample_prep_request_assignment/report','Assignment','');
INSERT INTO "nav_def" VALUES(43,'Samples','separator','','Experiments','');
INSERT INTO "nav_def" VALUES(44,'Samples','link','experiment/report','Report','Display a list of experiments');
INSERT INTO "nav_def" VALUES(45,'Samples','link','experiment/search','Search','Search for experiments');
INSERT INTO "nav_def" VALUES(46,'Samples','link','experiment/create','Entry','Create a new experiment');
INSERT INTO "nav_def" VALUES(47,'Samples','separator','','Experiment Groups','');
INSERT INTO "nav_def" VALUES(48,'Samples','link','experiment_group/report','Report','Display a list of experiment fractionation groups');
INSERT INTO "nav_def" VALUES(49,'Samples','link','experiment_fraction/create','Entry - Fractions','Create a new experiment fractionation group');
INSERT INTO "nav_def" VALUES(50,'Samples','link','experiment_group/create','Entry - General','Create a new general experiment group');
INSERT INTO "nav_def" VALUES(51,'Samples','separator','','Biomaterial and Ref Comp','');
INSERT INTO "nav_def" VALUES(52,'Samples','link','cell_culture/report','Biomaterial Report','Display list of biomaterial items');
INSERT INTO "nav_def" VALUES(53,'Samples','link','cell_culture/create','Biomaterial Entry','Create a new biomaterial item');
INSERT INTO "nav_def" VALUES(54,'Samples','link','reference_compound/report','Reference Compounds','Show list of reference compounds');
INSERT INTO "nav_def" VALUES(55,'','submenu','Instrument Runs','Instrument Runs','');
INSERT INTO "nav_def" VALUES(56,'Instrument Runs','separator','','Requested Runs','');
INSERT INTO "nav_def" VALUES(57,'Instrument Runs','link','requested_run/report/-/-/Active','Report - Active','Display list of active requested runs');
INSERT INTO "nav_def" VALUES(59,'Instrument Runs','link','requested_run/report/-/-/Completed','Report - Completed','Display list of requesed runs that have been completed by datasets');
INSERT INTO "nav_def" VALUES(61,'Instrument Runs','link','requested_run/create','Single Entry','Create a new requested run for a single experiment');
INSERT INTO "nav_def" VALUES(62,'Instrument Runs','link','requested_run_group/create','Group Entry','Create a new requested run for an experiment fractionation group');
INSERT INTO "nav_def" VALUES(64,'Instrument Runs','separator','','Run Batches','');
INSERT INTO "nav_def" VALUES(65,'Instrument Runs','link','requested_run_batch/report','Report','Display list of requested run batches');
INSERT INTO "nav_def" VALUES(67,'Instrument Runs','link','requested_run_batch/create','Entry','Create a new requested run batch');
INSERT INTO "nav_def" VALUES(68,'Instrument Runs','link','batch_tracking/report/-/-/-/-','Tracking','Display requested run batch tracking report');
INSERT INTO "nav_def" VALUES(69,'Instrument Runs','separator','','Run Blocking','');
INSERT INTO "nav_def" VALUES(70,'Instrument Runs','link','requested_run_batch_blocking/param','Define Blocking','Define run blocking for a batch');
INSERT INTO "nav_def" VALUES(71,'Instrument Runs','link','requested_run_batch_blocking/grid','Define Blocking (grid)','Define run blocking for a batch');
INSERT INTO "nav_def" VALUES(72,'Instrument Runs','link','requested_run_factors/param','Define Factors','Define factors for requested runs');
INSERT INTO "nav_def" VALUES(73,'Instrument Runs','link','custom_factors/report/-','Browse Factors','View existing factors associated with requests');
INSERT INTO "nav_def" VALUES(74,'Instrument Runs','separator','','Wellplates','');
INSERT INTO "nav_def" VALUES(75,'Instrument Runs','link','wellplate/report','Report','Display list of wellplates');
INSERT INTO "nav_def" VALUES(76,'Instrument Runs','separator','','Datasets','');
INSERT INTO "nav_def" VALUES(78,'Instrument Runs','link','dataset/search','Search','Search for datasets');
INSERT INTO "nav_def" VALUES(79,'Instrument Runs','link','dataset_disposition/search','Disposition','Disposition datasets that are waiting for inspection');
INSERT INTO "nav_def" VALUES(80,'Instrument Runs','link','dataset_disposition_lite/report','Disposition (No plots)','Disposition datasets that are waiting for inspection');
INSERT INTO "nav_def" VALUES(81,'Instrument Runs','link','dataset/create','Entry','Create a new dataset');
INSERT INTO "nav_def" VALUES(82,'Instrument Runs','link','main_log/report','Log','Show log of dataset creation and capture');
INSERT INTO "nav_def" VALUES(83,'Instrument Runs','separator','','Usage Tracking','');
INSERT INTO "nav_def" VALUES(84,'Instrument Runs','link','run_tracking/cal','Inst. Usage Tracking','');
INSERT INTO "nav_def" VALUES(85,'','submenu','Data Analysis','Data Analysis','');
INSERT INTO "nav_def" VALUES(86,'Data Analysis','separator','','Analysis Job Requests','');
INSERT INTO "nav_def" VALUES(87,'Data Analysis','link','analysis_job_request/report/-/-/-','Report All','Display list of analysis job requests');
INSERT INTO "nav_def" VALUES(88,'Data Analysis','link','analysis_job_request/report/New','Report - New','Display list of analysis job requests that are in New state');
INSERT INTO "nav_def" VALUES(89,'Data Analysis','link','analysis_job_request/report/Used','Report - Used','Display list of analysis job requests that are in Used state');
INSERT INTO "nav_def" VALUES(90,'Data Analysis','link','analysis_job_request_psm/create','MS/MS Job Wizard','Create a new MS/MS analysis job request based on suggested defaults');
INSERT INTO "nav_def" VALUES(91,'Data Analysis','link','analysis_job_request/create','Generic Entry','Create a new analysis job request');
INSERT INTO "nav_def" VALUES(92,'Data Analysis','separator','','Analysis Jobs','');
INSERT INTO "nav_def" VALUES(93,'Data Analysis','link','analysis_job/search','Search','Search for analysis jobs');
INSERT INTO "nav_def" VALUES(94,'Data Analysis','separator','','Analysis Job Reports','');
INSERT INTO "nav_def" VALUES(97,'Data Analysis','link','analysis_job/report/-/-/StartsWith__MSGFPlus/-/-/-/-/-/52','MS-GF+','Display list of MS-GF+ analysis jobs (last 12 months)');
INSERT INTO "nav_def" VALUES(98,'Data Analysis','link','analysis_job/report/-/-/StartsWith__Decon2LS/-/-/-/-/-/52','DeconTools','Display list of DeconTools analysis jobs (last 12 months)');
INSERT INTO "nav_def" VALUES(99,'Data Analysis','link','analysis_job/report/-/-/StartsWith__MASIC/-/-/-/-/-/52','MASIC','Display list of MASIC analysis jobs (last 12 months)');
INSERT INTO "nav_def" VALUES(100,'Data Analysis','link','analysis_job/report/-/-/StartsWith__MSAlign/-/-/-/-/-/52','MSAlign','Display list of MSAlign analysis jobs (last 12 months)');
INSERT INTO "nav_def" VALUES(101,'Data Analysis','link','analysis_job/report/-/-/StartsWith__MSPathFinder/-/-/-/-/-/52','MSPathFinder','Display list of MSPathFinder analysis jobs (last 12 months)');
INSERT INTO "nav_def" VALUES(103,'Data Analysis','separator','','PSM Stats','');
INSERT INTO "nav_def" VALUES(104,'Data Analysis','link','analysis_job_psm/report/','Job PSM Stats','');
INSERT INTO "nav_def" VALUES(105,'Data Analysis','link','data_package_analysis_job_psm/report/-/-/-/StartsWith__msgfplus','Data Pkg Job PSM Stats','');
INSERT INTO "nav_def" VALUES(106,'Data Analysis','link','dataset_psm_and_pm/report/4/StartsWith__msgfplus','Dataset PSM Stats','');
INSERT INTO "nav_def" VALUES(107,'Data Analysis','link','data_package_dataset_psm_and_pm/report/-/4/StartsWith__msgfplus','Data Pkg Dataset PSM Stats','');
INSERT INTO "nav_def" VALUES(108,'','submenu','LC','LC','');
INSERT INTO "nav_def" VALUES(109,'LC','separator','','Columns','');
INSERT INTO "nav_def" VALUES(110,'LC','link','lc_column/report','Report','Display list of LC columns');
INSERT INTO "nav_def" VALUES(111,'LC','link','lc_column/create','Entry','Create a new LC column');
INSERT INTO "nav_def" VALUES(112,'LC','link','lc_column_dataset/report','Dataset Count','Display list of LC columns showing number of samples run');
INSERT INTO "nav_def" VALUES(113,'LC','link','separation_type/report','Separation Type','');
INSERT INTO "nav_def" VALUES(114,'LC','separator','','Carts','');
INSERT INTO "nav_def" VALUES(115,'LC','link','lc_cart/report','Report','Display list of LC carts');
INSERT INTO "nav_def" VALUES(116,'LC','link','lc_cart/create','Entry','Create new LC Cart');
INSERT INTO "nav_def" VALUES(119,'LC','link','lc_cart_request_loading/report','Configure loading (Req)','Prepare sample loading for LC Cart by requested runs');
INSERT INTO "nav_def" VALUES(120,'LC','link','lc_cart_loading/report','Loading List','Display requested run queue');
INSERT INTO "nav_def" VALUES(121,'LC','link','lc_cart_configuration/report','Cart Configurations','Display LC Cart configurations');
INSERT INTO "nav_def" VALUES(122,'LC','separator','','Cart Maintenance','');
INSERT INTO "nav_def" VALUES(124,'LC','link','lc_cart_config_history/report','Service Notes','Display LC cart service notes');
INSERT INTO "nav_def" VALUES(125,'LC','link','lc_cart_config_history/create','New Service Note','Add a new cart service note');
INSERT INTO "nav_def" VALUES(126,'LC','separator','','Instrument Config.','');
INSERT INTO "nav_def" VALUES(127,'LC','link','instrument_config/report','Inst. List','Display list of instruments');
INSERT INTO "nav_def" VALUES(128,'LC','link','instrument_config_history/report','Config. History','Display instrument config history');
INSERT INTO "nav_def" VALUES(129,'LC','link','instrument_config_history/Create','New Service Note','Create new instrument config note');
INSERT INTO "nav_def" VALUES(130,'LC','link','instrument_operation_history/report','Operation Notes','Display instrument operation notes');
INSERT INTO "nav_def" VALUES(131,'LC','link','instrument_operation_history/create','Add Operation Note..','Add new instrument operation notes');
INSERT INTO "nav_def" VALUES(132,'','submenu','Search','Search','');
INSERT INTO "nav_def" VALUES(133,'Search','separator','','Simple Search','');
INSERT INTO "nav_def" VALUES(134,'Search','link','analysis_job/search','Analysis Jobs','');
INSERT INTO "nav_def" VALUES(135,'Search','link','dataset/search','Datasets','');
INSERT INTO "nav_def" VALUES(136,'Search','link','archive/search','Archive','');
INSERT INTO "nav_def" VALUES(137,'Search','link','requested_run/search','Requested Runs','');
INSERT INTO "nav_def" VALUES(139,'Search','link','experiment/search','Experiments','');
INSERT INTO "nav_def" VALUES(140,'Search','link','sample_prep_request/search','Sample Prep Req.','');
INSERT INTO "nav_def" VALUES(141,'Search','link','campaign/search','Campaigns','');
INSERT INTO "nav_def" VALUES(142,'Search','link','custom_factors/search','Factors','');
INSERT INTO "nav_def" VALUES(143,'','submenu','MTS','MTS','');
INSERT INTO "nav_def" VALUES(144,'MTS','separator','','Databases','');
INSERT INTO "nav_def" VALUES(145,'MTS','link','mts_pt_dbs/report','Peptide DBs','Display list of peptide databases');
INSERT INTO "nav_def" VALUES(146,'MTS','link','mts_mt_dbs/report','AMT Tag DBs','Display list of AMT tag databases');
INSERT INTO "nav_def" VALUES(147,'MTS','separator','','Database Jobs','');
INSERT INTO "nav_def" VALUES(148,'MTS','link','mts_pt_db_jobs/report','Peptide DB Jobs','Display list of peptide databases by job');
INSERT INTO "nav_def" VALUES(149,'MTS','link','mts_mt_db_jobs/report','AMT Tag DB Jobs','Display list of AMT tag databases by job');
INSERT INTO "nav_def" VALUES(150,'MTS','separator','','Results','');
INSERT INTO "nav_def" VALUES(151,'MTS','link','mts_pm_results/report','Peak Matching','Display list of peak matching results');
INSERT INTO "nav_def" VALUES(152,'','submenu','Help',' Help','');
INSERT INTO "nav_def" VALUES(153,'Help','separator','','Help','');
INSERT INTO "nav_def" VALUES(154,'Help','link_context','help_basic_link','Help for page type','Show help page for this type of DMS page');
INSERT INTO "nav_def" VALUES(155,'Help','link_context','help_page_link','Help for specific page','Show help page for this DMS page');
INSERT INTO "nav_def" VALUES(156,'Help','separator','','Info','');
INSERT INTO "nav_def" VALUES(157,'Help','link_context','page_info_link','Page info','');
INSERT INTO "nav_def" VALUES(158,'Help','link_context','config_db_link','Page config','');
INSERT INTO "nav_def" VALUES(159,'','header_context','server_info','Page config','');
INSERT INTO "nav_def" VALUES(160,'Help','link_context','sql_link','SQL','Show SQL that returned data for this page');
INSERT INTO "nav_def" VALUES(161,'Help','link_context','url_link','URL','Show URL and filter information');
COMMIT;
