PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','T_Enzymes');
INSERT INTO general_params VALUES('list_report_data_table','v_enzymes_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_col','enzyme_id');
INSERT INTO general_params VALUES('list_report_data_sort_dir','ASC');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'enzyme_name','invoke_entity','value','experiment/report/-/-/-/-/-/-/-/sfx/and/enzyme/matchestext/@','');
INSERT INTO list_report_hotlinks VALUES(2,'protein_collection','invoke_entity','value','protein_collection/report/~','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_ID','ID','','','enzyme_id','Equals','int','','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_name','Name','','','enzyme_name','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_left_residues','Left Residues','','','left_cleave_residues','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_right_residues','Right Residues','','','right_cleave_residues','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_offset','Offset','','','cleavage_offset','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_protein_collection','Protein Collection','','','protein_collection','ContainsText','text','','','');
COMMIT;
