PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','t_emsl_instruments');
INSERT INTO general_params VALUES('list_report_data_table','v_eus_instruments_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_col','eus_instrument_name');
INSERT INTO general_params VALUES('list_report_data_sort_dir','ASC');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'dms_instrument_id','invoke_entity','value','instrument/report/-/-/-/-/-/','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_eus_instrument_id','EUS Instrument ID','10','','eus_instrument_id','Equals','text','32','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_eus_instrument_name','EUS Instrument Name','25!','','eus_instrument_name','ContainsText','text','256','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_dms_instrument_id','DMS Instrument ID','10','','dms_instrument_id','Equals','text','32','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_dms_instrument_name','DMS Instrument Name','25!','','instrument','ContainsText','text','128','','');
COMMIT;
