PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_custom_factors_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_col','request');
INSERT INTO general_params VALUES('list_report_data_sort_dir','Desc');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_batch','Batch','20','','batch','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_request','Request','20','','request','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_factor','Factor','20','','factor','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_value','Value','20','','value','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_dataset_id','Dataset_ID','20','','dataset_id','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_dataset','Dataset','20','','dataset','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_experiment_id','Experiment_ID','20','','experiment_id','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(8,'pf_experiment','Experiment','20','','experiment','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(9,'pf_campaign','Campaign','20','','campaign','ContainsText','text','64','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'campaign','invoke_entity','value','campaign/show','');
INSERT INTO list_report_hotlinks VALUES(2,'experiment','invoke_entity','value','experiment/show','');
INSERT INTO list_report_hotlinks VALUES(3,'dataset','invoke_entity','value','dataset/show','');
INSERT INTO list_report_hotlinks VALUES(4,'batch','invoke_entity','value','requested_run_batch/show','');
INSERT INTO list_report_hotlinks VALUES(5,'request','invoke_entity','value','requested_run/show','');
COMMIT;
