PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','T_Material_Freezers');
INSERT INTO general_params VALUES('list_report_data_table','V_Freezer_List_Report');
INSERT INTO general_params VALUES('detail_report_data_table','V_Freezer_List_Report');
INSERT INTO general_params VALUES('detail_report_data_id_col','Freezer');
INSERT INTO general_params VALUES('detail_report_data_id_type','string');
INSERT INTO general_params VALUES('list_report_data_sort_col','Freezer');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_Freezer','Freezer','32','','Freezer','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_Comment','Comment','32','','Comment','ContainsText','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'Containers','invoke_entity','Freezer','material_location/report/-/~@','');
COMMIT;
