PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','T_Sample_Submission');
INSERT INTO general_params VALUES('list_report_data_table','v_sample_submission_list_report');
INSERT INTO general_params VALUES('list_report_data_cols','id AS Sel, *');
INSERT INTO general_params VALUES('list_report_helper_multiple_selection','yes');
INSERT INTO general_params VALUES('list_report_data_sort_col','id');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'sel','CHECKBOX','id','','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_id','ID','20','','id','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_received_by','Received_By','20','','received_by','ContainsText','text','103','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_description','Description','20','','description','ContainsText','text','4096','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_container_list','Container_List','20','','container_list','ContainsText','text','1024','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_campaign','Campaign','20','','campaign','ContainsText','text','64','','');
COMMIT;
