PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_helper_ncbi_taxonomy_report');
INSERT INTO general_params VALUES('list_report_data_sort_col','name');
INSERT INTO general_params VALUES('list_report_data_sort_dir','ASC');
INSERT INTO general_params VALUES('list_report_helper_multiple_selection','no');
INSERT INTO general_params VALUES('my_db_group','ontology');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'tax_id','update_opener','value','','');
INSERT INTO list_report_hotlinks VALUES(2,'parent_tax_id','invoke_entity','value','helper_ncbi_taxonomy_id/report/','');
INSERT INTO list_report_hotlinks VALUES(3,'children','invoke_entity','tax_id','helper_ncbi_taxonomy_id/report/-/-/-/','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_taxonomy_id','Tax_ID','20','','tax_id','Equals','text','24','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_taxonomy_name','Name','40!','','name','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_rank','Rank','20','','rank','ContainsText','text','64','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_parent_tax_id','Parent Tax_ID','','','parent_tax_id','Equals','text','24','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_parent_name','Parent Name','40!','','parent_name','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_division','Division','20','','division','ContainsText','text','128','','');
COMMIT;
