PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','V_Active_Requested_Runs');
INSERT INTO general_params VALUES('list_report_data_sort_col','Created');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('list_report_data_cols','Request, Name, Instrument, Experiment, Requester, Created, Comment, Note, Wellplate, Well');
INSERT INTO general_params VALUES('list_report_helper_multiple_selection','no');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_name','Name','32','','Name','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_experiment','Experiment','32','','Experiment','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_instrument','Instrument','32','','Instrument','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_requester','Requester','32','','Requester','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_comment','Comment','32','','Comment','ContainsText','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'Request','update_opener','value','','');
COMMIT;
