PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_osm_package_list_report');
INSERT INTO general_params VALUES('list_report_helper_multiple_selection','no');
INSERT INTO general_params VALUES('my_db_group','package');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'id','update_opener','value','','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_id','ID','20','','id','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_name','Name','20','','name','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_keywords','Keywords','20','','keywords','ContainsText','text','2048','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_type','Type','20','','type','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_description','Description','20','','description','ContainsText','text','2048','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_comment','Comment','20','','comment','ContainsText','text','1024','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_owner','Owner','20','','owner','ContainsText','text','181','','');
COMMIT;
