PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_analysis_job_processor_group_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_col','id');
INSERT INTO general_params VALUES('list_report_helper_multiple_selection','no');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_group_name','Group Name','32','','group_name','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_group_description','Group Description','32','','group_description','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_group_enabled','Group Enabled','32','','group_enabled','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_general_processing','General Processing','32','','general_processing','ContainsText','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'group_name','update_opener','value','','');
COMMIT;
