PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_sample_prep_request_picklist');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('list_report_helper_multiple_selection','no');
INSERT INTO general_params VALUES('list_report_data_sort_col','id');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_requestname','Name','35!','','request_name','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_type','Type','16','','type','ContainsText','text','16','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_organism','Organism','32','','organism','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_campaign','Campaign','30!','','campaign','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_state','State','32','','state','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_reason','Reason','32','','reason','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_assignedpersonnel','AssignedPersonnel','32','','assigned_personnel','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(8,'pf_prepmethod','PrepMethod','32','','prep_method','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(9,'pf_priority','Priority','32','','priority','ContainsText','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'id','update_opener','value','','');
COMMIT;
