PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_predefined_analysis_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('list_report_data_sort_col','instrument_class, level, seq, id');
INSERT INTO general_params VALUES('list_report_helper_multiple_selection','no');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_instrument_class','Instrument Class','60','','instrument_class','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_analysis_tool','Analysis Tool','60','','analysis_tool','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_campaign_crit','Campaign Crit.','60','','campaign_crit','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_instrument_crit','Instrument Crit.','60','','instrument_crit','ContainsText','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'id','update_opener','value','','');
COMMIT;
