PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_eus_active_proposal_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_col','proposal_id');
INSERT INTO general_params VALUES('list_report_data_sort_dir','ASC');
INSERT INTO general_params VALUES('list_report_helper_multiple_selection','no');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(2,'pf_title','Title','70!','','title','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_proposal','ID','20','','proposal_id','StartsWithText','text','32','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_user_last_name','Last Name','25!','','user_last_names','ContainsText','text','64','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'proposal_id','update_opener','value','','');
INSERT INTO list_report_hotlinks VALUES(2,'start_date','format_date','value','15','{"Format":"Y-m-d"}');
INSERT INTO list_report_hotlinks VALUES(3,'end_date','format_date','value','15','{"Format":"Y-m-d"}');
INSERT INTO list_report_hotlinks VALUES(4,'state','color_label','value','','{"Active":"clr_30", "Permanently Active":"clr_60", "Closed":"clr_90", "Inactive":"clr_90"}');
COMMIT;
