PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_instrument_actual_montly_list_report');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_year','Year','20','','year','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_month','Month','20','','month','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_proposal_id','Proposal_ID','20','','proposal_id','ContainsText','text','20','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_title','Title','20','','title','ContainsText','text','64','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_status','Status','20','','status','ContainsText','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'proposal_id','invoke_entity','proposal_id','eus_proposals/show','');
COMMIT;
