PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_instrument_class_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('detail_report_data_table','v_instrument_class_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','instrument_class');
INSERT INTO general_params VALUES('entry_sproc','AddUpdateInstrumentClass');
INSERT INTO general_params VALUES('entry_page_data_table','v_instrument_class_entry');
INSERT INTO general_params VALUES('entry_page_data_id_col','instrument_class');
INSERT INTO general_params VALUES('entry_block_new','True');
INSERT INTO general_params VALUES('post_submission_detail_id','instrument_class');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO form_fields VALUES(1,'instrument_class','Instrument Class','non-edit','32','32','','','','trim|required|max_length[32]');
INSERT INTO form_fields VALUES(2,'is_purgeable','Is Purgeable','text','1','1','','','','trim|required|max_length[1]');
INSERT INTO form_fields VALUES(3,'raw_data_type','Raw Data Type','text','32','32','','','','trim|required|max_length[32]');
INSERT INTO form_fields VALUES(5,'comment','Comment','area','','','3','70','','trim|max_length[255]');
INSERT INTO form_fields VALUES(6,'params','Params','area','','','18','70','<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True"/><item key="SaveLCMS2DPlots" value="True"/><item key="ComputeOverallQualityScores" value="True"/><item key="CreateDatasetInfoFile" value="True"/><item key="LCMS2DPlotMZResolution" value="0.4"/><item key="LCMS2DPlotMaxPointsToPlot" value="500000"/><item key="LCMS2DPlotMinPointsPerSpectrum" value="2"/><item key="LCMS2DPlotMinIntensity" value="0"/><item key="LCMS2DOverviewPlotDivisor" value="10"/></section></sections>','trim|max_length[2147483647]');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO form_field_choosers VALUES(1,'is_purgeable','picker.replace','yesNoAsOneZeroPickList','','',',','');
INSERT INTO form_field_choosers VALUES(2,'raw_data_type','picker.replace','rawDataTypePickList','','',',','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'instrument_class','invoke_entity','value','instrument_class/show/','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'instrument_class','instrumentClass','varchar','input','32','AddUpdateInstrumentClass');
INSERT INTO sproc_args VALUES(2,'is_purgeable','isPurgeable','int','input','1','AddUpdateInstrumentClass');
INSERT INTO sproc_args VALUES(3,'raw_data_type','rawDataType','varchar','input','32','AddUpdateInstrumentClass');
INSERT INTO sproc_args VALUES(6,'params','params','text','input','2147483647','AddUpdateInstrumentClass');
INSERT INTO sproc_args VALUES(7,'comment','comment','varchar','input','255','AddUpdateInstrumentClass');
INSERT INTO sproc_args VALUES(8,'<local>','mode','varchar','input','12','AddUpdateInstrumentClass');
INSERT INTO sproc_args VALUES(9,'<local>','message','varchar','output','512','AddUpdateInstrumentClass');
CREATE TABLE form_field_options ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "parameter" text );
INSERT INTO form_field_options VALUES(1,'params','auto_format','xml');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_class','Class','10','','instrument_class','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_raw_data_type','Raw Data Type','10','','raw_data_type','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_comment','Comment','10','','comment','ContainsText','text','80','','');
COMMIT;
