PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','T_Instrument_Group');
INSERT INTO general_params VALUES('list_report_data_table','v_instrument_group_list_report');
INSERT INTO general_params VALUES('detail_report_data_table','v_instrument_group_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','instrument_group');
INSERT INTO general_params VALUES('entry_page_data_table','v_instrument_group_entry');
INSERT INTO general_params VALUES('entry_page_data_id_col','instrument_group');
INSERT INTO general_params VALUES('entry_sproc','add_update_instrument_group');
INSERT INTO general_params VALUES('post_submission_detail_id','instrument_group');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'instrument_group','invoke_entity','value','instrument_group/show/','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_instrument_group','Instrument_Group','20!','','instrument_group','ContainsText','text','64','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_allowed_dataset_types','Allowed_Dataset_Types','20!','','allowed_dataset_types','ContainsText','text','4000','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_active','Active','20','','active','Equals','text','20','','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'instrument_group','instrumentGroup','varchar','input','64','add_update_instrument_group');
INSERT INTO sproc_args VALUES(2,'usage','usage','varchar','input','64','add_update_instrument_group');
INSERT INTO sproc_args VALUES(3,'comment','comment','varchar','input','512','add_update_instrument_group');
INSERT INTO sproc_args VALUES(4,'active','active','tinyint','input','','add_update_instrument_group');
INSERT INTO sproc_args VALUES(5,'sample_prep_visible','samplePrepVisible','tinyint','input','','add_update_instrument_group');
INSERT INTO sproc_args VALUES(6,'requested_run_visible','requestedRunVisible','tinyint','input','','add_update_instrument_group');
INSERT INTO sproc_args VALUES(7,'allocation_tag','allocationTag','varchar','intput','24','add_update_instrument_group');
INSERT INTO sproc_args VALUES(8,'default_dataset_type_name','defaultDatasetTypeName','varchar','input','50','add_update_instrument_group');
INSERT INTO sproc_args VALUES(9,'<local>','mode','varchar','input','12','add_update_instrument_group');
INSERT INTO sproc_args VALUES(10,'<local>','message','varchar','output','512','add_update_instrument_group');
INSERT INTO sproc_args VALUES(11,'<local>','callingUser','varchar','input','128','add_update_instrument_group');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO form_fields VALUES(1,'instrument_group','Instrument Group','text-if-new','50','64','','','','trim|max_length[64]');
INSERT INTO form_fields VALUES(2,'usage','Usage','text','64','64','','','','trim|max_length[64]');
INSERT INTO form_fields VALUES(3,'comment','Comment','area','64','512','2','60','','trim|max_length[512]');
INSERT INTO form_fields VALUES(4,'active','Active','text','12','12','','','','trim|max_length[12]');
INSERT INTO form_fields VALUES(5,'sample_prep_visible','Sample Prep Visible','text','12','12','','','','trim|max_length[12]');
INSERT INTO form_fields VALUES(6,'requested_run_visible','Requested Run Visible','text','12','12','','','','trim|max_length[12]');
INSERT INTO form_fields VALUES(7,'allocation_tag','Allocation Tag','text','12','24','','','','trim|max_length[24]');
INSERT INTO form_fields VALUES(8,'default_dataset_type_name','Default Dataset Type','text','20','64','','','','trim|max_length[64]');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO detail_report_hotlinks VALUES(1,'allowed_dataset_types','detail-report','instrument_group','instrument_allowed_dataset_type/report/~@','labelCol','dl_dataset_type','');
INSERT INTO detail_report_hotlinks VALUES(2,'instruments','detail-report','instrument_group','instrument/report/-/-/-/~@','labelCol','dl_instrument_list','');
INSERT INTO detail_report_hotlinks VALUES(3,'+instruments','tabular_link_list','instruments','instrumentid/show/','valueCol','dl_instrument_id','');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO form_field_choosers VALUES(1,'default_dataset_type_name','picker.replace','datasetTypePickList','','',',','');
INSERT INTO form_field_choosers VALUES(2,'active','picker.replace','yesNoAsOneZeroPickList','','',',','');
INSERT INTO form_field_choosers VALUES(3,'sample_prep_visible','picker.replace','yesNoAsOneZeroPickList','','',',','');
INSERT INTO form_field_choosers VALUES(4,'requested_run_visible','picker.replace','yesNoAsOneZeroPickList','','',',','');
COMMIT;
