PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('list_report_data_table','V_Instrument_Allocation_List_Report');
INSERT INTO "general_params" VALUES('base_table','T_Instrument_Allocation');
INSERT INTO "general_params" VALUES('list_report_cmds','instrument_allocation_cmds');
INSERT INTO "general_params" VALUES('operations_sproc','UpdateInstrumentUsageAllocationsXML');
INSERT INTO "general_params" VALUES('list_report_cmds_url','instrument_allocation/operation');
INSERT INTO "general_params" VALUES('detail_report_data_table','V_Instrument_Allocation_Detail_Report');
INSERT INTO "general_params" VALUES('entry_page_data_table','v_instrument_allocation_detail_entry');
INSERT INTO "general_params" VALUES('detail_report_data_id_col','FY_Proposal');
INSERT INTO "general_params" VALUES('entry_page_data_id_col','fy_proposal');
INSERT INTO "general_params" VALUES('entry_sproc','UpdateInstrumentUsageAllocations');
INSERT INTO "general_params" VALUES('post_submission_detail_id','fy_proposal');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO "list_report_primary_filter" VALUES(1,'pf_fiscal_year','Fiscal Year','20','','Fiscal_Year','Equals','text','20','','');
INSERT INTO "list_report_primary_filter" VALUES(4,'pf_proposal_id','Proposal ID','20','','Proposal_ID','ContainsText','text','20','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO "list_report_hotlinks" VALUES(1,'Proposal_ID','invoke_entity','#FY_Proposal','instrument_allocation/show/','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO "sproc_args" VALUES(1,'parameterList','parameterList','text','input','2147483647','UpdateInstrumentUsageAllocationsXML');
INSERT INTO "sproc_args" VALUES(2,'<local>','message','varchar','output','512','UpdateInstrumentUsageAllocationsXML');
INSERT INTO "sproc_args" VALUES(3,'<local>','callingUser','varchar','input','128','UpdateInstrumentUsageAllocationsXML');
INSERT INTO "sproc_args" VALUES(4,'infoOnly','infoOnly','tinyint','input','','UpdateInstrumentUsageAllocationsXML');
INSERT INTO "sproc_args" VALUES(5,'fy_proposal','FYProposal','varchar','input','64','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(6,'fiscal_year','FiscalYear','varchar','input','24','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(7,'proposal_id','ProposalID','varchar','input','128','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(8,'ft','FT','varchar','input','24','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(9,'ft_comment','FTComment','varchar','input','256','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(10,'ims','IMS','varchar','input','24','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(11,'ims_comment','IMSComment','varchar','input','256','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(12,'orb','ORB','varchar','input','24','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(13,'orb_comment','ORBComment','varchar','input','256','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(14,'exa','EXA','varchar','input','24','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(15,'exa_comment','EXAComment','varchar','input','256','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(16,'ltq','LTQ','varchar','input','24','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(17,'ltq_comment','LTQComment','varchar','input','256','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(18,'gc','GC','varchar','input','24','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(19,'gc_comment','GCComment','varchar','input','256','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(20,'qqq','QQQ','varchar','input','24','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(21,'qqq_comment','QQQComment','varchar','input','256','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(22,'<local>','mode','varchar','input','12','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(23,'<local>','message','varchar','output','512','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(24,'<local>','callingUser','varchar','input','128','UpdateInstrumentUsageAllocations');
INSERT INTO "sproc_args" VALUES(25,'infoOnly','infoOnly','tinyint','input','','UpdateInstrumentUsageAllocations');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO "form_fields" VALUES(1,'fy_proposal','FY_Proposal','non-edit','64','','','','0','trim');
INSERT INTO "form_fields" VALUES(2,'fiscal_year','Fiscal Year','text','24','','','','','trim');
INSERT INTO "form_fields" VALUES(3,'proposal_id','Proposal ID','text','64','64','','','','trim');
INSERT INTO "form_fields" VALUES(4,'ft','FT Hours','text','24','','','','','trim');
INSERT INTO "form_fields" VALUES(5,'ft_comment','FT Comment','text','64','256','','','','trim');
INSERT INTO "form_fields" VALUES(6,'ims','IMS Hours','text','24','','','','','trim');
INSERT INTO "form_fields" VALUES(7,'ims_comment','IMS Comment','text','64','256','','','','trim');
INSERT INTO "form_fields" VALUES(8,'orb','Orbitrap Hours','text','24','','','','','trim');
INSERT INTO "form_fields" VALUES(9,'orb_comment','Orbi Comment','text','64','256','','','','trim');
INSERT INTO "form_fields" VALUES(10,'exa','Exactive Hours','text','24','','','','','trim');
INSERT INTO "form_fields" VALUES(11,'exa_comment','Exactive Comment','text','64','256','','','','trim');
INSERT INTO "form_fields" VALUES(12,'ltq','LTQ Hours','text','24','','','','','trim');
INSERT INTO "form_fields" VALUES(13,'ltq_comment','LTQ Comment','text','64','256','','','','trim');
INSERT INTO "form_fields" VALUES(14,'gc','GC Hours','text','24','','','','','trim');
INSERT INTO "form_fields" VALUES(15,'gc_comment','GC Comment','text','64','256','','','','trim');
INSERT INTO "form_fields" VALUES(16,'qqq','QQQ','text','24','','','','','trim');
INSERT INTO "form_fields" VALUES(17,'qqq_comment','QQQ Comment','text','64','256','','','','trim');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO "detail_report_hotlinks" VALUES(1,'Fiscal Year','detail-report','Fiscal Year','instrument_allocation/report/','labelCol','dl_Fiscal_Year',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(2,'Proposal_ID','detail-report','Proposal_ID','eus_proposals/show/','labelCol','dl_Proposal',NULL);
COMMIT;
