PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_internal_standards_composition_report');
INSERT INTO general_params VALUES('list_report_data_sort_dir','ASC');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_name','Internal Std Name','20!','','component','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_description','Description','20!','','component_description','ContainsText','text','1024','','');
CREATE TABLE list_report_hotlinks (  id INTEGER PRIMARY KEY, name text,  LinkType text, WhichArg text,  Target text, Options text);
INSERT INTO list_report_hotlinks VALUES(1,'name','no_display','value','','');
COMMIT;
