PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_lc_cart_request_loading_list_report');
INSERT INTO general_params VALUES('alternate_title_report','LC Cart Request Assignment');
INSERT INTO general_params VALUES('list_report_cmds','lc_cart_request_loading_cmds');
INSERT INTO general_params VALUES('operations_sproc','update_lc_cart_request_assignments');
INSERT INTO general_params VALUES('list_report_cmds_url','lc_cart_request_loading/operation');
INSERT INTO general_params VALUES('list_report_data_cols','request AS Sel, *');
INSERT INTO general_params VALUES('list_report_data_sort_col','request');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_batchid','Batch ID','20','','batch_id','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_name','Name','20','','name','ContainsText','text','64','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_cart','Cart','20','','cart','ContainsText','text','32','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_instrument','Instrument','20','','instrument','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_cart_config','Cart Config','20','','cart_config','ContainsText','text','32','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(4,'batch_id','invoke_entity','batch_id','requested_run_batch/show','');
INSERT INTO list_report_hotlinks VALUES(5,'cart','inplace_edit','request','','{"width":"10"}');
INSERT INTO list_report_hotlinks VALUES(6,'cart_config','inplace_edit','request','','');
INSERT INTO list_report_hotlinks VALUES(7,'col','inplace_edit','request','','{"width":"5"}');
INSERT INTO list_report_hotlinks VALUES(8,'request','invoke_entity','request','requested_run/show','');
INSERT INTO list_report_hotlinks VALUES(9,'sel','CHECKBOX','value','','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'cartAssignmentList','cartAssignmentList','text','input','2147483647','update_lc_cart_request_assignments');
INSERT INTO sproc_args VALUES(2,'<local>','mode','varchar','input','32','update_lc_cart_request_assignments');
INSERT INTO sproc_args VALUES(3,'<local>','message','varchar','output','512','update_lc_cart_request_assignments');
COMMIT;
