PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('list_report_data_table','V_LC_Cart_Settings_History_List_Report');
INSERT INTO "general_params" VALUES('list_report_data_sort_dir','DESC');
INSERT INTO "general_params" VALUES('detail_report_data_table','V_LC_Cart_Settings_History_Detail_Report');
INSERT INTO "general_params" VALUES('detail_report_data_id_col','ID');
INSERT INTO "general_params" VALUES('entry_sproc','AddUpdateLCCartSettingsHistory');
INSERT INTO "general_params" VALUES('entry_page_data_table','V_LC_Cart_Settings_History_Entry');
INSERT INTO "general_params" VALUES('entry_page_data_id_col','ID');
INSERT INTO "general_params" VALUES('post_submission_detail_id','ID');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO "form_fields" VALUES(1,'ID','ID','non-edit','','','','','','trim|max_length[10]');
INSERT INTO "form_fields" VALUES(2,'CartName','Cart Name','text','60','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(3,'DateOfChange','Date Of Change','text','16','16','','','','trim|max_length[16]');
INSERT INTO "form_fields" VALUES(4,'ValveToColumnExtension','Valve To Column Extension','text','60','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(5,'ValveToColumnExtensionDimensions','Valve To Column Extension Dimensions','text','60','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(6,'OperatingPressure','Operating Pressure','text','60','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(7,'InterfaceConfiguration','Interface Configuration','text','60','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(8,'MixerVolume','Mixer Volume','text','60','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(9,'SampleLoopVolume','Sample Loop Volume','text','60','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(10,'SampleLoadingTime','Sample Loading Time','text','60','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(11,'SplitFlowRate','Split Flow Rate','text','60','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(12,'SplitColumnDimensions','Split Column Dimensions','text','60','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(13,'PurgeFlowRate','Purge Flow Rate','text','60','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(14,'PurgeColumnDimensions','Purge Column Dimensions','text','60','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(15,'PurgeVolume','Purge Volume','text','60','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(16,'AcquisitionTime','Acquisition Time','text','60','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(17,'SolventA','Solvent A','text','60','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(18,'SolventB','Solvent B','text','60','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(19,'Comment','Comment','area','','','3','60','','trim|max_length[512]');
CREATE TABLE form_field_options ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "parameter" text );
INSERT INTO "form_field_options" VALUES(1,'DateOfChange','default_function','CurrentDate');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO "form_field_choosers" VALUES(1,'CartName','picker.replace','lcCartPickList','','',',','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO "list_report_primary_filter" VALUES(1,'pf_cart','Cart','20','','Cart','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(2,'pf_comment','Comment','60','','Comment','ContainsText','text','128','','');
CREATE TABLE primary_filter_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text );
INSERT INTO "primary_filter_choosers" VALUES(1,'pf_cart','picker.replace','lcCartPickList','','',',');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO "list_report_hotlinks" VALUES(1,'ID','invoke_entity','value','lc_cart_settings_history/show/','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO "sproc_args" VALUES(1,'ID','ID','int','input','','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(2,'CartName','CartName','varchar','input','128','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(3,'ValveToColumnExtension','ValveToColumnExtension','varchar','input','128','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(4,'OperatingPressure','OperatingPressure','varchar','input','128','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(5,'InterfaceConfiguration','InterfaceConfiguration','varchar','input','128','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(6,'ValveToColumnExtensionDimensions','ValveToColumnExtensionDimensions','varchar','input','128','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(7,'MixerVolume','MixerVolume','varchar','input','128','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(8,'SampleLoopVolume','SampleLoopVolume','varchar','input','128','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(9,'SampleLoadingTime','SampleLoadingTime','varchar','input','128','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(10,'SplitFlowRate','SplitFlowRate','varchar','input','128','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(11,'SplitColumnDimensions','SplitColumnDimensions','varchar','input','128','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(12,'PurgeFlowRate','PurgeFlowRate','varchar','input','128','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(13,'PurgeColumnDimensions','PurgeColumnDimensions','varchar','input','128','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(14,'PurgeVolume','PurgeVolume','varchar','input','128','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(15,'AcquisitionTime','AcquisitionTime','varchar','input','128','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(16,'SolventA','SolventA','varchar','input','128','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(17,'SolventB','SolventB','varchar','input','128','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(18,'Comment','Comment','varchar','input','512','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(19,'DateOfChange','DateOfChange','varchar','input','24','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(20,'<local>','mode','varchar','input','12','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(21,'<local>','message','varchar','output','512','AddUpdateLCCartSettingsHistory');
INSERT INTO "sproc_args" VALUES(22,'<local>','callingUser','varchar','input','128','AddUpdateLCCartSettingsHistory');
COMMIT;
