PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('my_db_group','broker');
INSERT INTO general_params VALUES('entry_page_data_id_col','Job');
INSERT INTO general_params VALUES('entry_sproc','AddMACJob');
INSERT INTO general_params VALUES('entry_submission_cmds','mac_jobs_cmds');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'job','job','int','output','','AddMACJob');
INSERT INTO sproc_args VALUES(2,'data_package_id','DataPackageID','int','input','','AddMACJob');
INSERT INTO sproc_args VALUES(3,'job_param','jobParam','varchar','input','8000','AddMACJob');
INSERT INTO sproc_args VALUES(4,'comment','comment','varchar','input','512','AddMACJob');
INSERT INTO sproc_args VALUES(5,'owner_prn','ownerPRN','varchar','input','64','AddMACJob');
INSERT INTO sproc_args VALUES(6,'script_name','scriptName','varchar','input','64','AddMACJob');
INSERT INTO sproc_args VALUES(7,'<local>','mode','varchar','input','12','AddMACJob');
INSERT INTO sproc_args VALUES(8,'<local>','message','varchar','output','512','AddMACJob');
INSERT INTO sproc_args VALUES(9,'<local>','callingUser','varchar','input','128','AddMACJob');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO form_fields VALUES(1,'job','Job','non-edit','','','','','0','trim|max_length[12]');
INSERT INTO form_fields VALUES(2,'data_package_id','Data Package ID','text','12','12','','','','trim|max_length[12]');
INSERT INTO form_fields VALUES(6,'comment','Comment','area','','','4','120','','trim|max_length[512]');
INSERT INTO form_fields VALUES(7,'owner_prn','Owner PRN','text','50','64','','','','trim|max_length[64]');
INSERT INTO form_fields VALUES(9,'script_name','Script Name','hidden','','','','','','trim|max_length[64]');
INSERT INTO form_fields VALUES(10,'job_param','Job Param','hidden','','','','','','trim|max_length[8000]');
CREATE TABLE form_field_options ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "parameter" text );
INSERT INTO form_field_options VALUES(2,'owner_prn','default_function','GetUser()');
CREATE TABLE utility_queries ( id integer PRIMARY KEY, name text, label text, db text, "table" text, columns text, sorting text, filters text, hotlinks text );
INSERT INTO utility_queries VALUES(2,'parameter_definitions','','broker','V_Pipeline_Script_MAC_With_Fields','Name, Fields as params','','{"Name":"MTx"}','');
INSERT INTO utility_queries VALUES(3,'parameter_scripts','','broker','V_Pipeline_Script_MAC_With_Fields','Name, Description','','','');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO form_field_choosers VALUES(1,'owner_prn','picker.replace','userPRNPickList','','',',','');
INSERT INTO form_field_choosers VALUES(2,'data_package_id','list-report.helper','','helper_data_package','',',','');
COMMIT;
