PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','T_Mass_Correction_Factors');
INSERT INTO general_params VALUES('list_report_data_table','v_mass_correction_factors');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_id','ID','','','mass_correction_id','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_name','Name','','','mass_correction_tag','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_description','Description','','','description','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_mono_mass_min','Min Mass','','','monoisotopic_mass','GreaterThanOrEqualTo','text','','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_mono_mass_max','Max Mass','','','monoisotopic_mass','LessThanOrEqualTo','text','','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_original_source_name','Source Name','35!','','original_source_name','ContainsText','text','','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'mass_correction_id','invoke_entity','value','param_file_mass_mods/report/-/','');
INSERT INTO list_report_hotlinks VALUES(2,'original_source_name','invoke_entity','value','unimod/report/~','');
COMMIT;
