PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','V_Material_Location_List_Report');
INSERT INTO general_params VALUES('list_report_data_sort_col','Location');
INSERT INTO general_params VALUES('detail_report_data_table','V_Material_Location_Detail_Report');
INSERT INTO general_params VALUES('detail_report_data_id_col','Location');
INSERT INTO general_params VALUES('entry_sproc','UpdateMaterialLocation');
INSERT INTO general_params VALUES('entry_page_data_table','v_material_location_entry');
INSERT INTO general_params VALUES('entry_page_data_id_col','location');
INSERT INTO general_params VALUES('post_submission_detail_id','location');
INSERT INTO general_params VALUES('entry_block_new','True');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_location','Location','15!','','Location','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_freezer','Freezer','15!','','Freezer','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_shelf','Shelf','5!','','Shelf','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_rack','Rack','5!','','Rack','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_row','Row','5!','','Row','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_col','Col','5!','','Col','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_status','Status','6','','Status','StartsWithText','text','24','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'Containers','invoke_entity','Location','material_container/report/-/~@','');
INSERT INTO list_report_hotlinks VALUES(2,'Freezer','invoke_entity','value','material_location/report/-/~@/-/-/-/-/Active','');
INSERT INTO list_report_hotlinks VALUES(3,'Location','invoke_entity','value','material_location/show/','');
INSERT INTO list_report_hotlinks VALUES(4,'Freezer_Tag','no_display','value','','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text, "options" text );
INSERT INTO detail_report_hotlinks VALUES(1,'Location','detail-report','Location','material_container/report/-/~','labelCol','dl_location','');
INSERT INTO detail_report_hotlinks VALUES(2,'Freezer','detail-report','Freezer','freezers/report/~','labelCol','dl_freezer','');
INSERT INTO detail_report_hotlinks VALUES(3,'Containers','detail-report','Location','material_items/report/-/~','labelCol','dl_containers','');
INSERT INTO detail_report_hotlinks VALUES(4,'Status','detail-report','Location','material_log/report/-/-/-/~','labelCol','dl_log_location','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'location','locationTag','varchar','input','64','UpdateMaterialLocation');
INSERT INTO sproc_args VALUES(2,'comment','comment','varchar','input','512','UpdateMaterialLocation');
INSERT INTO sproc_args VALUES(3,'status','status','varchar','input','32','UpdateMaterialLocation');
INSERT INTO sproc_args VALUES(4,'<local>','message','varchar','output','512','UpdateMaterialLocation');
INSERT INTO sproc_args VALUES(5,'<local>','callingUser','varchar','input','128','UpdateMaterialLocation');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO form_fields VALUES(1,'id','ID','non-edit','40','80','','','','trim');
INSERT INTO form_fields VALUES(2,'location','Location','non-edit','40','80','','','','trim');
INSERT INTO form_fields VALUES(3,'comment','Comment','area','','','4','50','','trim|max_length[500]');
INSERT INTO form_fields VALUES(4,'status','Status','text','40','40','','','','trim|max_length[32]|alpha_dash');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO form_field_choosers VALUES(1,'status','picker.replace','activeInactivePickList','','',',','');
COMMIT;
