PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_material_locations_available_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_col','location');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_location','Location','25!','','location','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_freezer','Freezer','25!','','freezer','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_shelf','Shelf','3!','','shelf','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_rack','Rack','3!','','rack','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_row','Row','3!','','row','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_col','Col','3!','','col','ContainsText','text','80','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'containers','invoke_entity','location','material_container/report/-/','');
INSERT INTO list_report_hotlinks VALUES(2,'action','invoke_entity','location','material_container/create/init/-/-/','');
INSERT INTO list_report_hotlinks VALUES(3,'location','invoke_entity','value','material_location/show/','');
COMMIT;
