PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_material_log_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_col','id');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_type','Type','32','','type','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_item','Item','32','','item','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_initial','Initial','32','','initial','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_final','Final','32','','final','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_user','User','32','','user','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_date','Most Recent Weeks','32','','date','MostRecentWeeks','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(2,'final','select_case','item_type','','{"Biomaterial":"material_container","Experiment":"material_container","RefCompound":"material_container","Container":"material_location"}');
INSERT INTO list_report_hotlinks VALUES(3,'initial','select_case','item_type','','{"Biomaterial":"material_container","Experiment":"material_container","RefCompound":"material_container","Container":"material_location"}');
INSERT INTO list_report_hotlinks VALUES(4,'item','select_case','item_type','','{"Biomaterial":"biomaterial","Experiment":"experiment","RefCompound":"reference_compound/report","Container":"material_container"}');
COMMIT;
