PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_material_items_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_dir','ASC');
INSERT INTO general_params VALUES('detail_report_data_table','v_material_items_list_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','id');
INSERT INTO general_params VALUES('list_report_data_sort_col','container, item');
INSERT INTO general_params VALUES('detail_report_data_id_type','integer');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_container','Container','6','','container','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_location','Location','25!','','location','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_item','Item','6','','item','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_item_type','Item Type','6','','item_type','ContainsText','text','80','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_item_id','Item ID','6','','id','Equals','text','32','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_container_status','Container Status','6','','container_status','StartsWithText','text','32','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_prep_request_id','Prep Request','6','','prep_request','Equals','text','80','','');
INSERT INTO list_report_primary_filter VALUES(8,'pf_campaign','Campaign','25!','','campaign','ContainsText','text','80','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'item','select_case','item_type','','{"Biomaterial":"biomaterial","Experiment":"experiment","RefCompound":"reference_compound/report"}');
INSERT INTO list_report_hotlinks VALUES(2,'container','invoke_entity','value','material_container/show/','');
INSERT INTO list_report_hotlinks VALUES(3,'location','invoke_entity','value','material_location/report/~@','');
INSERT INTO list_report_hotlinks VALUES(4,'prep_request','invoke_entity','value','sample_prep_request/show/','');
INSERT INTO list_report_hotlinks VALUES(5,'campaign','invoke_entity','value','campaign/show/','');
INSERT INTO list_report_hotlinks VALUES(6,'id','invoke_entity','value','material_items/show/','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text, "options" text );
INSERT INTO detail_report_hotlinks VALUES(1,'container','detail-report','container','material_container/show/','labelCol','','');
INSERT INTO detail_report_hotlinks VALUES(2,'location','detail-report','location','material_location/report/~@','labelCol','','');
INSERT INTO detail_report_hotlinks VALUES(3,'campaign','detail-report','campaign','campaign/show/','labelCol','','');
INSERT INTO detail_report_hotlinks VALUES(4,'id','detail-report','id','material_items/report/-/-/-/-/@','labelCol','','');
COMMIT;
