PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','T_MaxQuant_Mod_Residues');
INSERT INTO general_params VALUES('list_report_data_table','v_max_quant_mods_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_col','id');
INSERT INTO general_params VALUES('list_report_data_sort_dir','ASC');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'mod_id','invoke_entity','value','param_file_mass_mods/report/-/@','');
INSERT INTO list_report_hotlinks VALUES(2,'mass_correction_tag','invoke_entity','value','mass_correction_factors/report/-/~','');
INSERT INTO list_report_hotlinks VALUES(3,'residue_symbol','invoke_entity','value','residue/report/@/-','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'ID','ID','3!','','id','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(2,'Mod_Title','Mod Title','20!','','mod_title','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(3,'Mod_Position','Position','','','mod_position','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(4,'Residue_Symbol','Residue','2!','','residue_symbol','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(5,'Mod_ID','Mod_ID','','','mod_id','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(6,'Mass_Correction_Tag','Mass_Correction_Tag','','','mass_correction_tag','ContainsText','text','','','');
COMMIT;
