PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','T_MaxQuant_Mod_Residues');
INSERT INTO general_params VALUES('list_report_data_table','V_MaxQuant_Mods_List_Report');
INSERT INTO general_params VALUES('list_report_data_sort_col','ID');
INSERT INTO general_params VALUES('list_report_data_sort_dir','ASC');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'Mod_ID','invoke_entity','value','param_file_mass_mods/report/-/@','');
INSERT INTO list_report_hotlinks VALUES(2,'Mass_Correction_Tag','invoke_entity','value','mass_correction_factors/report/-/~','');
INSERT INTO list_report_hotlinks VALUES(3,'Residue_Symbol','invoke_entity','value','residue/report/@/-','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'ID','ID','3!','','ID','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(2,'Mod_Title','Mod Title','20!','','Mod_Title','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(3,'Mod_Position','Position','','','Mod_Position','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(4,'Residue_Symbol','Residue','2!','','Residue_Symbol','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(5,'Mod_ID','Mod_ID','','','Mod_ID','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(6,'Mass_Correction_Tag','Mass_Correction_Tag','','','Mass_Correction_Tag','ContainsText','text','','','');
COMMIT;
