PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','V_Param_Value');
INSERT INTO general_params VALUES('my_db_group','manager_control');
INSERT INTO general_params VALUES('list_report_data_table','v_param_value');
INSERT INTO general_params VALUES('list_report_data_cols','mgr_name AS [Mgr_Name], param_name AS [Param_Name], entry_id AS [Entry_ID], type_id AS [Type_ID], value AS [Value], mgr_id AS [Mgr_ID], comment AS [Comment], last_affected AS [Last_Affected], entered_by AS [Entered_By], mgr_type_id AS [Mgr_Type_ID]');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_m_name','Mgr_Name','20','','mgr_name','ContainsText','text','50','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_paramname','Param_Name','30!','','param_name','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_value','Value','20','','value','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_comment','Comment','20','','comment','ContainsText','text','255','','');
INSERT INTO list_report_primary_filter VALUES(8,'pf_last_affected','Last_Affected','20','','last_affected','LaterThan','text','20','','');
INSERT INTO list_report_primary_filter VALUES(9,'pf_entered_by','Entered_By','20','','entered_by','ContainsText','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'mgr_name','invoke_entity','value','pipeline_processor_step_tools/show','');
COMMIT;
