PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_mrm_list_attachment_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('entry_sproc','AddUpdateAttachments');
INSERT INTO general_params VALUES('entry_page_data_table','v_mrm_list_attachment_entry');
INSERT INTO general_params VALUES('entry_page_data_id_col','id');
INSERT INTO general_params VALUES('list_report_data_cols','*, ''Download'' AS download');
INSERT INTO general_params VALUES('detail_report_data_table','v_mrm_list_attachment_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','id');
INSERT INTO general_params VALUES('detail_report_data_id_type','integer');
INSERT INTO general_params VALUES('post_submission_detail_id','id');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO form_fields VALUES(1,'attachment_name','Name','text','80','128','','','','trim|max_length[128]');
INSERT INTO form_fields VALUES(2,'attachment_description','Description','area','','','4','60','','trim|max_length[1024]');
INSERT INTO form_fields VALUES(3,'owner_prn','Owner','text','24','24','','','','trim|max_length[24]');
INSERT INTO form_fields VALUES(4,'active','Active','text','8','8','','','Y','trim|max_length[8]');
INSERT INTO form_fields VALUES(5,'id','ID','non-edit','','','','','0','trim');
INSERT INTO form_fields VALUES(6,'attachment_type','Type','hidden','','','','','MRM Transition List','trim');
INSERT INTO form_fields VALUES(7,'file_name','FileName','text','80','128','','','','trim');
INSERT INTO form_fields VALUES(8,'contents','File Contents','area','','','20','90','','trim|max_length[100000]');
CREATE TABLE form_field_options ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "parameter" text );
INSERT INTO form_field_options VALUES(1,'owner_prn','default_function','GetUser()');
INSERT INTO form_field_options VALUES(2,'contents','auto_format','None');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_id','ID','6','','id','Equals','text','12','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_name','Name','32','','name','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_description','Description','32','','description','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_owner','Owner','32','','owner','ContainsText','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'download','invoke_entity','id','mrm_list_attachment/download','');
INSERT INTO list_report_hotlinks VALUES(2,'id','invoke_entity','value','mrm_list_attachment/show/','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'id','id','int','output','','AddUpdateAttachments');
INSERT INTO sproc_args VALUES(2,'attachment_type','AttachmentType','varchar','input','24','AddUpdateAttachments');
INSERT INTO sproc_args VALUES(3,'attachment_name','AttachmentName','varchar','input','128','AddUpdateAttachments');
INSERT INTO sproc_args VALUES(4,'attachment_description','AttachmentDescription','varchar','input','1024','AddUpdateAttachments');
INSERT INTO sproc_args VALUES(5,'owner_prn','OwnerPRN','varchar','input','24','AddUpdateAttachments');
INSERT INTO sproc_args VALUES(6,'active','Active','varchar','input','8','AddUpdateAttachments');
INSERT INTO sproc_args VALUES(7,'contents','Contents','text','input','2147483647','AddUpdateAttachments');
INSERT INTO sproc_args VALUES(8,'file_name','FileName','varchar','input','128','AddUpdateAttachments');
INSERT INTO sproc_args VALUES(9,'<local>','mode','varchar','input','12','AddUpdateAttachments');
INSERT INTO sproc_args VALUES(10,'<local>','message','varchar','output','512','AddUpdateAttachments');
INSERT INTO sproc_args VALUES(11,'<local>','callingUser','varchar','input','128','AddUpdateAttachments');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO detail_report_hotlinks VALUES(1,'contents','markup','contents','','valueCol','dl_contents','');
COMMIT;
