PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_mts_pt_dbs');
INSERT INTO general_params VALUES('list_report_data_sort_col','peptide_db_id');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_peptide_db_name','DB_Name','20','','peptide_db_name','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_description','Description','20','','description','ContainsText','text','2048','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_state','State','20','','state','ContainsText','text','50','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_organism','Organism','20','','organism','ContainsText','text','64','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_server','Server','20','','server_name','ContainsText','text','64','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'peptide_db_name','invoke_entity','peptide_db_name','mts_pt_db_jobs/show','');
INSERT INTO list_report_hotlinks VALUES(2,'organism','invoke_entity','organism','organism/report/~','');
INSERT INTO list_report_hotlinks VALUES(3,'msms_jobs','invoke_entity','peptide_db_name','mts_pt_db_jobs/report/-/-/peptide_hit/~','');
INSERT INTO list_report_hotlinks VALUES(4,'sic_jobs','invoke_entity','peptide_db_name','mts_pt_db_jobs/report/-/-/sic/~','');
COMMIT;
