PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('list_report_data_table','V_MTS_PT_DB_Jobs');
INSERT INTO "general_params" VALUES('detail_report_data_table','V_MTS_PT_DBs_Detail_Report');
INSERT INTO "general_params" VALUES('detail_report_data_id_col','Peptide_DB_Name');
INSERT INTO "general_params" VALUES('list_report_data_sort_col','#sort_key');
INSERT INTO "general_params" VALUES('list_report_data_sort_dir','DESC');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO "list_report_primary_filter" VALUES(1,'pf_job','Job','20','','Job','Equals','text','20','','');
INSERT INTO "list_report_primary_filter" VALUES(2,'pf_dataset','Dataset','20','','Dataset','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(3,'pf_resulttype','ResultType','20','','ResultType','ContainsText','text','64','','');
INSERT INTO "list_report_primary_filter" VALUES(4,'pf_peptide_db_name','Peptide_DB_Name','20','','Peptide_DB_Name','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(5,'pf_campaign','Campaign','20','','Campaign','ContainsText','text','64','','');
INSERT INTO "list_report_primary_filter" VALUES(6,'pf_process_state','Process_State','20','','Process_State','ContainsText','text','512','','');
INSERT INTO "list_report_primary_filter" VALUES(7,'pf_instrument','Instrument','20','','Instrument','ContainsText','text','24','','');
INSERT INTO "list_report_primary_filter" VALUES(8,'pf_server_name','Server_Name','20','','Server_Name','ContainsText','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO "list_report_hotlinks" VALUES(1,'Dataset','invoke_entity','Dataset','dataset/show','');
INSERT INTO "list_report_hotlinks" VALUES(2,'Job','invoke_entity','Job','analysis_job/show','');
INSERT INTO "list_report_hotlinks" VALUES(3,'Peptide_DB_Name','invoke_entity','Peptide_DB_Name','mts_pt_db_jobs/show','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO "detail_report_hotlinks" VALUES(1,'MSMS_Jobs','detail-report','Peptide_DB_Name','mts_pt_db_jobs/report/-/-/Peptide_Hit/~','labelCol','Peptide_DB',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(2,'Organism','detail-report','Organism','organism/report/~','labelCol','Organism',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(3,'SIC_Jobs','detail-report','Peptide_DB_Name','mts_pt_db_jobs/report/-/-/SIC/~','labelCol','Peptide_DB_SIC',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(4,'Mass_Tag_DBs','link_list','Mass_Tag_DBs','mts_mt_db_jobs/show','valueCol','Mass_Tag_DB',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(5,'Server_Name','detail-report','Server_Name','mts_pt_dbs/report/-/-/-/-/~','labelCol','Server_Name','');
COMMIT;
