PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_mts_mt_db_jobs');
INSERT INTO general_params VALUES('detail_report_data_table','v_mts_mt_dbs_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','mt_db_name');
INSERT INTO general_params VALUES('list_report_data_sort_col','sort_key');
INSERT INTO general_params VALUES('list_report_data_sort_dir','desc');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_job','Job','20','','job','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_dataset','Dataset','20','','dataset','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_resulttype','Result Type','20','','result_type','ContainsText','text','64','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_mt_db_name','MT DB_Name','30!','','mt_db_name','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_campaign','Campaign','20','','campaign','ContainsText','text','64','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_process_state','State','20','','process_state','ContainsText','text','512','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_instrument','Instrument','20','','instrument','ContainsText','text','24','','');
INSERT INTO list_report_primary_filter VALUES(8,'pf_server_name','Server','20','','server_name','ContainsText','text','64','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'dataset','invoke_entity','dataset','dataset/show','');
INSERT INTO list_report_hotlinks VALUES(2,'job','invoke_entity','job','analysis_job/show','');
INSERT INTO list_report_hotlinks VALUES(3,'mt_db_name','invoke_entity','mt_db_name','mts_mt_db_jobs/show','');
INSERT INTO list_report_hotlinks VALUES(4,'sort_key','no_display','value','','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO detail_report_hotlinks VALUES(1,'msms_jobs','detail-report','mt_db_name','mts_mt_db_jobs/report/-/-/peptide_hit/~','labelCol','MT_DB',NULL);
INSERT INTO detail_report_hotlinks VALUES(2,'ms_jobs','detail-report','mt_db_name','mts_mt_db_jobs/report/-/-/StartsWith__hmma/~','labelCol','MT_DB_HMMA','');
INSERT INTO detail_report_hotlinks VALUES(3,'campaign','detail-report','campaign','campaign/show','valueCol','Campaign',NULL);
INSERT INTO detail_report_hotlinks VALUES(4,'organism','detail-report','organism','organism/report/~','labelCol','Organism',NULL);
INSERT INTO detail_report_hotlinks VALUES(5,'pm_task_count','detail-report','mt_db_name','mts_pm_results/report/-/-/-/~','labelCol','PM_Tasks',NULL);
INSERT INTO detail_report_hotlinks VALUES(6,'peptide_db','detail-report','peptide_db','mts_pt_db_jobs/show','valueCol','PeptideDB',NULL);
INSERT INTO detail_report_hotlinks VALUES(7,'server_name','detail-report','server_name','mts_mt_dbs/report/-/-/-/-/-/~','labelCol','Server','');
COMMIT;
