PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_ncbi_taxonomy_alt_name_list_report');
INSERT INTO general_params VALUES('my_db_group','ontology');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_tax_id','Tax_ID','','','tax_id','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_scientific_name','Name','','','scientific_name','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_synonym_type','Type','','','synonym_type','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_synonym','Synonym','','','synonym','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_division','Division','','','division','ContainsText','text','','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'tax_id','invoke_entity','value','ncbi_taxonomy/report/','');
INSERT INTO list_report_hotlinks VALUES(2,'parent_tax_id','invoke_entity','value','ncbi_taxonomy/report/','');
COMMIT;
