PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_ncbi_taxonomy_list_report');
INSERT INTO general_params VALUES('detail_report_data_table','v_ncbi_taxonomy_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','tax_id');
INSERT INTO general_params VALUES('detail_report_data_id_type','integer');
INSERT INTO general_params VALUES('my_db_group','ontology');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'tax_id','invoke_entity','value','ncbi_taxonomy/show/','');
INSERT INTO list_report_hotlinks VALUES(2,'parent_tax_id','invoke_entity','value','ncbi_taxonomy/report/','');
INSERT INTO list_report_hotlinks VALUES(3,'synonyms','invoke_entity','tax_id','ncbi_taxonomy_altname/report','');
INSERT INTO list_report_hotlinks VALUES(4,'children','invoke_entity','tax_id','ncbi_taxonomy/report/-/-/','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO detail_report_hotlinks VALUES(1,'tax_id','detail-report','tax_id','newt/show','labelCol','','');
INSERT INTO detail_report_hotlinks VALUES(2,'parent_tax_id','detail-report','parent_tax_id','ncbi_taxonomy/show','labelCol','','');
INSERT INTO detail_report_hotlinks VALUES(3,'synonyms','detail-report','tax_id','ncbi_taxonomy_altname/report/','labelCol','','');
INSERT INTO detail_report_hotlinks VALUES(4,'children','detail-report','tax_id','ncbi_taxonomy/report/-/-/','labelCol','','');
INSERT INTO detail_report_hotlinks VALUES(5,'taxonomy_list','tabular_list','taxonomy_list','','valueCol','','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_tax_id','Tax ID','20','','tax_id','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_name','Name','30!','','name','ContainsTextTPO','text','','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_parent_tax_id','Parent Tax ID','20','','parent_tax_id','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_parent_name','Parent Name','30!','','parent_name','ContainsTextTPO','text','','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_rank','Rank','20','','rank','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_division','Division','20','','division','ContainsText','text','','','');
COMMIT;
