PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('list_report_data_table','V_Pipeline_Step_Tools_List_Report');
INSERT INTO "general_params" VALUES('list_report_data_sort_dir','DESC');
INSERT INTO "general_params" VALUES('detail_report_data_table','V_Pipeline_Step_Tools_Detail_Report');
INSERT INTO "general_params" VALUES('detail_report_data_id_col','Name');
INSERT INTO "general_params" VALUES('entry_sproc','AddUpdateStepTools');
INSERT INTO "general_params" VALUES('entry_page_data_table','V_Pipeline_Step_Tools_Entry');
INSERT INTO "general_params" VALUES('entry_page_data_id_col','Name');
INSERT INTO "general_params" VALUES('my_db_group','broker');
INSERT INTO "general_params" VALUES('post_submission_detail_id','Name');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO "form_fields" VALUES(1,'Name','Name','text-if-new','60','64','','','','trim|max_length[64]');
INSERT INTO "form_fields" VALUES(2,'Type','Type','text','60','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(3,'Description','Description','area','','','3','60','','trim|max_length[512]');
INSERT INTO "form_fields" VALUES(4,'SharedResultVersion','Shared Result Version','text','2','2','','','','trim|max_length[2]');
INSERT INTO "form_fields" VALUES(5,'FilterVersion','Filter Version','text','2','2','','','','trim|max_length[2]');
INSERT INTO "form_fields" VALUES(6,'CPULoad','CPU Load','text','2','2','','','','trim|max_length[2]');
INSERT INTO "form_fields" VALUES(7,'MemoryUsageMB','Memory Usage MB','text','24','24','','','','trim|Max_Length[24]');
INSERT INTO "form_fields" VALUES(8,'ParameterTemplate','Parameter Template','area','','','15','70','','trim|max_length[2147483647]');
INSERT INTO "form_fields" VALUES(9,'ParamFileStoragePath','ParamFileStoragePath','text','60','128','','','','rim|max_length[256]');
CREATE TABLE form_field_options ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "parameter" text );
INSERT INTO "form_field_options" VALUES(1,'ParameterTemplate','auto_format','xml');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO "list_report_primary_filter" VALUES(1,'pf_name','Name','6','','Name','ContainsText','text','80','','');
INSERT INTO "list_report_primary_filter" VALUES(2,'pf_type','Type','6','','Type','ContainsText','text','80','','');
INSERT INTO "list_report_primary_filter" VALUES(3,'pf_description','Description','6','','Description','ContainsText','text','80','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO "list_report_hotlinks" VALUES(1,'Name','invoke_entity','value','pipeline_step_tools/show/','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO "sproc_args" VALUES(1,'Name','Name','varchar','input','64','AddUpdateStepTools');
INSERT INTO "sproc_args" VALUES(2,'Type','Type','varchar','input','128','AddUpdateStepTools');
INSERT INTO "sproc_args" VALUES(3,'Description','Description','varchar','input','512','AddUpdateStepTools');
INSERT INTO "sproc_args" VALUES(4,'SharedResultVersion','SharedResultVersion','smallint','input','','AddUpdateStepTools');
INSERT INTO "sproc_args" VALUES(5,'FilterVersion','FilterVersion','smallint','input','','AddUpdateStepTools');
INSERT INTO "sproc_args" VALUES(6,'CPULoad','CPULoad','smallint','input','','AddUpdateStepTools');
INSERT INTO "sproc_args" VALUES(7,'MemoryUsageMB','MemoryUsageMB','int','input','','AddUpdateStepTools');
INSERT INTO "sproc_args" VALUES(8,'ParameterTemplate','ParameterTemplate','text','input','2147483647','AddUpdateStepTools');
INSERT INTO "sproc_args" VALUES(9,'ParamFileStoragePath','ParamFileStoragePath','varchar','input','256','AddUpdateStepTools');
INSERT INTO "sproc_args" VALUES(10,'<local>','mode','varchar','input','12','AddUpdateStepTools');
INSERT INTO "sproc_args" VALUES(11,'<local>','message','varchar','output','512','AddUpdateStepTools');
INSERT INTO "sproc_args" VALUES(12,'<local>','callingUser','varchar','input','128','AddUpdateStepTools');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text, "options" text );
INSERT INTO "detail_report_hotlinks" VALUES(1,'Name','detail-report','Name','pipeline_processor_step_tools/report/-/@','valueCol','dl_name','');
COMMIT;
