PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('list_report_data_table','V_Pipeline_Jobs_List_Report');
INSERT INTO "general_params" VALUES('list_report_data_sort_dir','DESC');
INSERT INTO "general_params" VALUES('detail_report_data_table','V_Pipeline_Jobs_Detail_Report');
INSERT INTO "general_params" VALUES('detail_report_data_id_col','Job');
INSERT INTO "general_params" VALUES('detail_report_data_id_type','integer');
INSERT INTO "general_params" VALUES('my_db_group','broker');
INSERT INTO "general_params" VALUES('entry_page_data_table','V_Pipeline_Jobs_Entry');
INSERT INTO "general_params" VALUES('entry_page_data_id_col','Job');
INSERT INTO "general_params" VALUES('entry_sproc','AddUpdateLocalJobInBroker');
INSERT INTO "general_params" VALUES('entry_submission_cmds','pipeline_jobs_cmds');
INSERT INTO "general_params" VALUES('detail_report_cmds','pipeline_jobs_cmds');
INSERT INTO "general_params" VALUES('post_submission_detail_id','Job');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO "list_report_primary_filter" VALUES(1,'pf_job','Job','6','','Job','Equals','text','80','','');
INSERT INTO "list_report_primary_filter" VALUES(2,'pf_job_state_b','Job_State_B','6','','Job_State_B','ContainsText','text','80','','');
INSERT INTO "list_report_primary_filter" VALUES(3,'pf_dataset','Dataset','40!','','Dataset','ContainsText','text','80','','');
INSERT INTO "list_report_primary_filter" VALUES(4,'pf_script','Script','15!','','Script','ContainsText','text','80','','');
INSERT INTO "list_report_primary_filter" VALUES(5,'pf_DataPkgID','DataPkgID','6','','DataPkgID','Equals','text','80','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO "list_report_hotlinks" VALUES(1,'Job','invoke_entity','value','pipeline_jobs/show/','');
INSERT INTO "list_report_hotlinks" VALUES(2,'Steps','invoke_entity','Job','pipeline_job_steps/report','');
INSERT INTO "list_report_hotlinks" VALUES(3,'DataPkgID','invoke_entity','value','data_package/show/','');
INSERT INTO "list_report_hotlinks" VALUES(4,'Owner','invoke_entity','value','user/show','');
INSERT INTO "list_report_hotlinks" VALUES(5,'Comment','min_col_width','value','120','');
INSERT INTO "list_report_hotlinks" VALUES(6,'Runtime_Minutes','format_commas','value','','{"Decimals":"1"}');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO "detail_report_hotlinks" VALUES(1,'Job','detail-report','Job','analysis_job/show','labelCol','job',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(2,'Dataset','detail-report','Dataset','dataset/show','labelCol','dataset',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(3,'Steps','detail-report','Job','pipeline_job_steps/report','labelCol','Steps',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(4,'Parameters','xml_params','Parameters','','valueCol','param_id',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(5,'Transfer_Folder_Path','href-folder','Transfer_Folder_Path','','valueCol','dh_TransferFolder',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(6,'Script','detail-report','Script','pipeline_script/show','valueCol','ID',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(7,'Owner','detail-report','Owner','user/show','labelCol','owner',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(8,'Data_Package_ID','detail-report','Data_Package_ID','data_package/show','labelCol','dh_DataPkgID',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(9,'Settings_File','detail-report','Settings_File','settings_files/report/-/','labelCol','dl_SettingsFile','');
INSERT INTO "detail_report_hotlinks" VALUES(10,'Parameter_File','detail-report','Parameter_File','param_file/report/-/','labelCol','dl_ParameterFile','');
INSERT INTO "detail_report_hotlinks" VALUES(11,'Runtime_Minutes','format_commas','Runtime_Minutes','','valueCol','dl_runtime_minutes','{"Decimals":"1"}');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO "sproc_args" VALUES(1,'job','job','int','output','','AddUpdateLocalJobInBroker');
INSERT INTO "sproc_args" VALUES(2,'scriptName','scriptName','varchar','input','64','AddUpdateLocalJobInBroker');
INSERT INTO "sproc_args" VALUES(3,'datasetNum','datasetNum','varchar','input','128','AddUpdateLocalJobInBroker');
INSERT INTO "sproc_args" VALUES(4,'priority','priority','int','input','','AddUpdateLocalJobInBroker');
INSERT INTO "sproc_args" VALUES(5,'jobParam','jobParam','varchar','input','8000','AddUpdateLocalJobInBroker');
INSERT INTO "sproc_args" VALUES(6,'comment','comment','varchar','input','512','AddUpdateLocalJobInBroker');
INSERT INTO "sproc_args" VALUES(7,'ownerPRN','ownerPRN','varchar','input','64','AddUpdateLocalJobInBroker');
INSERT INTO "sproc_args" VALUES(8,'DataPackageID','DataPackageID','int','input','','AddUpdateLocalJobInBroker');
INSERT INTO "sproc_args" VALUES(9,'resultsFolderName','resultsFolderName','varchar','output','128','AddUpdateLocalJobInBroker');
INSERT INTO "sproc_args" VALUES(10,'<local>','mode','varchar','input','12','AddUpdateLocalJobInBroker');
INSERT INTO "sproc_args" VALUES(11,'<local>','message','varchar','output','512','AddUpdateLocalJobInBroker');
INSERT INTO "sproc_args" VALUES(12,'<local>','callingUser','varchar','input','128','AddUpdateLocalJobInBroker');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO "form_fields" VALUES(1,'job','Job','non-edit','','','','','0','trim|max_length[12]');
INSERT INTO "form_fields" VALUES(2,'scriptName','Script Name','text','50','64','','','','trim|max_length[64]');
INSERT INTO "form_fields" VALUES(3,'datasetNum','Dataset Num','text','50','128','','','Aggregation','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(4,'priority','Priority','text','12','12','','','3','trim|max_length[12]');
INSERT INTO "form_fields" VALUES(5,'jobParam','Job Param','hidden','','','','','','trim|max_length[8000]');
INSERT INTO "form_fields" VALUES(6,'comment','Comment','area','','','4','120','','trim|max_length[512]');
INSERT INTO "form_fields" VALUES(7,'ownerPRN','Owner','text','','','','','','trim|max_length[64]');
INSERT INTO "form_fields" VALUES(8,'DataPackageID','Data Package ID','text','12','12','','','','trim|max_length[12]');
INSERT INTO "form_fields" VALUES(9,'resultsFolderName','Results Folder Name','non-edit','50','128','','','','trim|max_length[128]');
CREATE TABLE form_field_options ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "parameter" text );
INSERT INTO "form_field_options" VALUES(1,'jobParam','auto_format','xml');
CREATE TABLE entry_commands ( id INTEGER PRIMARY KEY,  "name" text, "type" text, "label" text, "tooltip" text, "target" text );
INSERT INTO "entry_commands" VALUES(1,'reset','cmd','Reset Failed Steps or Rerun Job','','');
CREATE TABLE utility_queries ( id integer PRIMARY KEY, name text, label text, db text, "table" text, columns text, sorting text, filters text, hotlinks text );
INSERT INTO "utility_queries" VALUES(1,'parameter_values','','broker','T_Job_Parameters','CONVERT(varchar(MAX), Parameters)  as params','','{"Job":"EQn"}','');
INSERT INTO "utility_queries" VALUES(2,'parameter_definitions','','broker','T_Scripts','CONVERT(varchar(MAX), Parameters)  as params','','{"Script":"MTx"}','');
INSERT INTO "utility_queries" VALUES(3,'parameter_scripts','','broker','V_Pipeline_Script_With_Parameters','*','','','');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO "form_field_choosers" VALUES(1,'ownerPRN','picker.replace','userPRNPickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(2,'DataPackageID','list-report.helper','','helper_data_package/report','',',','');
COMMIT;
