PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','t_pnnl_projects');
INSERT INTO general_params VALUES('list_report_data_table','v_pnnl_projects_list_report');
INSERT INTO general_params VALUES('detail_report_data_table','v_pnnl_projects_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','project_number');
INSERT INTO general_params VALUES('detail_report_data_id_type','text');
INSERT INTO general_params VALUES('list_report_data_sort_col','project_num');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'project_number','invoke_entity','value','pnnl_projects/show','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_project_num','Project Number','6!','','project_num','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_project_title','Title','30!','','project_title','ContainsTextTPO','text','','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_resp_username','Resp Person Username','6!','','resp_username','StartsWithText','text','','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_resp_hanford_id','Resp Person HID','8!','','resp_hid','StartsWithText','text','','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_resp_name','Resp Person Name','15!','','responsible_person_name','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_project_number','Project Number Starts With','6!','','project_number','StartsWithText','text','','','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text, "options" text );
INSERT INTO detail_report_hotlinks VALUES(1,'responsible_person_hanford_id','detail-report','responsible_person_hanford_id','pnnl_projects/report/-/-/-/','valueCol','dl_resp_hid','');
INSERT INTO detail_report_hotlinks VALUES(2,'responsible_person_username','detail-report','responsible_person_username','pnnl_projects/report/-/-/@/-','valueCol','dl_resp_username','');
INSERT INTO detail_report_hotlinks VALUES(3,'responsible_person_name','detail-report','responsible_person_name','user/report/-/@','valueCol','dl_resp_person_name','');
COMMIT;
