PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','T_Predefined_Analysis_Scheduling_Queue');
INSERT INTO general_params VALUES('list_report_data_table','v_predefined_analysis_scheduling_queue_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_col','item');
INSERT INTO general_params VALUES('list_report_data_sort_dir','Desc');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_dataset','Dataset','30!','','dataset','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_id','Dataset ID','20','','id','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_state','State','20','','state','ContainsText','text','32','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_user','User','5!','','user','StartsWithText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_entered','Most Recent Weeks','3!','','entered','MostRecentWeeks','text','20','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(2,'jobs_created','invoke_entity','dataset','analysis_job/report/-/-/-/~','');
INSERT INTO list_report_hotlinks VALUES(3,'dataset','invoke_entity','value','dataset/show','');
INSERT INTO list_report_hotlinks VALUES(4,'message','min_col_width','value','60','');
COMMIT;
