PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','T_Predefined_Analysis_Scheduling_Queue');
INSERT INTO general_params VALUES('list_report_data_table','V_Predefined_Analysis_Scheduling_Queue_List_Report');
INSERT INTO general_params VALUES('list_report_data_sort_col','Item');
INSERT INTO general_params VALUES('list_report_data_sort_dir','Desc');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_dataset','Dataset','30!','','Dataset','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_id','Dataset ID','20','','ID','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_state','State','20','','State','ContainsText','text','32','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_user','User','5!','','User','StartsWithText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_entered','Most Recent Weeks','3!','','Entered','MostRecentWeeks','text','20','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(2,'Jobs_Created','invoke_entity','Dataset','analysis_job/report/-/-/-/~','');
INSERT INTO list_report_hotlinks VALUES(3,'Dataset','invoke_entity','value','dataset/show','');
INSERT INTO list_report_hotlinks VALUES(4,'Message','min_col_width','value','60','');
COMMIT;
