PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('entry_page_data_id_col','ID');
INSERT INTO "general_params" VALUES('entry_sproc','MakePrepLCCaptureJob');
INSERT INTO "general_params" VALUES('my_db_group','capture');
INSERT INTO "general_params" VALUES('entry_page_data_table','V_DMS_PrepLC_Job_Parameters');
INSERT INTO "general_params" VALUES('entry_page_data_id_col','ID');
INSERT INTO "general_params" VALUES('alternate_title_edit','Create Capture Job for Prep LC Run');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO "sproc_args" VALUES(1,'ID','ID','int','input','','MakePrepLCCaptureJob');
INSERT INTO "sproc_args" VALUES(2,'Instrument','Instrument','varchar','input','128','MakePrepLCCaptureJob');
INSERT INTO "sproc_args" VALUES(3,'SourceFolderName','SourceFolderName','varchar','input','128','MakePrepLCCaptureJob');
INSERT INTO "sproc_args" VALUES(4,'Comment','Comment','varchar','input','512','MakePrepLCCaptureJob');
INSERT INTO "sproc_args" VALUES(5,'Job','Job','int','output','','MakePrepLCCaptureJob');
INSERT INTO "sproc_args" VALUES(6,'<local>','mode','varchar','input','12','MakePrepLCCaptureJob');
INSERT INTO "sproc_args" VALUES(7,'<local>','message','varchar','output','512','MakePrepLCCaptureJob');
INSERT INTO "sproc_args" VALUES(8,'<local>','callingUser','varchar','input','128','MakePrepLCCaptureJob');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO "form_fields" VALUES(1,'ID','Prep LC Run','non-edit','','','','','','trim|NoBlank');
INSERT INTO "form_fields" VALUES(2,'Instrument','Instrument','non-edit','50','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(3,'SourceFolderName','Source Folder Name','text','100','128','','','','trim|max_length[128]|NoBlank');
INSERT INTO "form_fields" VALUES(4,'Comment','Comment','area','','','4','70','','trim|max_length[512]');
INSERT INTO "form_fields" VALUES(5,'Job','Capture Job','non-edit','12','12','','','','trim|max_length[12]');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO "form_field_choosers" VALUES(1,'SourceFolderName','list-report.helper','','helper_inst_source/view','Instrument',',','');
CREATE TABLE entry_commands ( id INTEGER PRIMARY KEY,  "name" text, "type" text, "label" text, "tooltip" text, "target" text );
INSERT INTO "entry_commands" VALUES(1,'update','override','Create Job','','update');
COMMIT;
