PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('list_report_data_table','V_Prep_LC_Column_List_Report');
INSERT INTO "general_params" VALUES('detail_report_data_table','V_Prep_LC_Column_Detail_Report');
INSERT INTO "general_params" VALUES('detail_report_data_id_col','Column Name');
INSERT INTO "general_params" VALUES('entry_page_data_table','V_Prep_LC_Column_Entry');
INSERT INTO "general_params" VALUES('entry_page_data_id_col','ColumnName');
INSERT INTO "general_params" VALUES('entry_sproc','AddUpdatePrepLCColumn');
INSERT INTO "general_params" VALUES('post_submission_detail_id','ColumnName');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO "form_fields" VALUES(1,'ColumnName','Column Name','text-if-new','50','128','','','','trim|max_length[128]|alpha_dash|min_length[8]');
INSERT INTO "form_fields" VALUES(2,'MfgName','Mfg Name','text','50','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(3,'MfgModel','Mfg Model','text','50','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(4,'MfgSerialNumber','Mfg Serial Number','text','50','64','','','','trim|max_length[64]');
INSERT INTO "form_fields" VALUES(5,'PackingMfg','Packing Mfg','text','50','64','','','','trim|max_length[64]');
INSERT INTO "form_fields" VALUES(6,'PackingType','Packing Type','text','50','64','','','','trim|max_length[64]');
INSERT INTO "form_fields" VALUES(7,'Particlesize','Particlesize','text','50','64','','','','trim|max_length[64]');
INSERT INTO "form_fields" VALUES(8,'Particletype','Particletype','text','50','64','','','','trim|max_length[64]');
INSERT INTO "form_fields" VALUES(9,'ColumnInnerDia','Column Inner Dia','text','50','64','','','','trim|max_length[64]');
INSERT INTO "form_fields" VALUES(10,'ColumnOuterDia','Column Outer Dia','text','50','64','','','','trim|max_length[64]');
INSERT INTO "form_fields" VALUES(11,'Length','Length','text','50','64','','','','trim|max_length[64]');
INSERT INTO "form_fields" VALUES(12,'State','State','text','32','32','','','New','trim|max_length[32]');
INSERT INTO "form_fields" VALUES(13,'OperatorPRN','Operator PRN','text','50','50','','','','trim|max_length[50]');
INSERT INTO "form_fields" VALUES(14,'Comment','Comment','area','','','4','70','','trim|max_length[244]');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO "form_field_choosers" VALUES(1,'State','picker.replace','LCColumnStatePickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(2,'OperatorPRN','picker.replace','userPRNPickList','','',',','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO "list_report_primary_filter" VALUES(1,'pf_column_name','Column Name','20','','Column Name','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(2,'pf_mfg_name','Mfg Name','20','','Mfg Name','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(3,'pf_mfg_model','Mfg Model','20','','Mfg Model','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(4,'pf_comment','Comment','20','','Comment','ContainsText','text','244','','');
INSERT INTO "list_report_primary_filter" VALUES(5,'pf_state','State','20','','State','ContainsText','text','32','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO "list_report_hotlinks" VALUES(1,'Column Name','invoke_entity','value','prep_lc_column/show/','');
INSERT INTO "list_report_hotlinks" VALUES(2,'Runs','invoke_entity','Column Name','prep_lc_run/report/-/-/-/~','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO "sproc_args" VALUES(1,'ColumnName','ColumnName','varchar','input','128','AddUpdatePrepLCColumn');
INSERT INTO "sproc_args" VALUES(2,'MfgName','MfgName','varchar','input','128','AddUpdatePrepLCColumn');
INSERT INTO "sproc_args" VALUES(3,'MfgModel','MfgModel','varchar','input','128','AddUpdatePrepLCColumn');
INSERT INTO "sproc_args" VALUES(4,'MfgSerialNumber','MfgSerialNumber','varchar','input','64','AddUpdatePrepLCColumn');
INSERT INTO "sproc_args" VALUES(5,'PackingMfg','PackingMfg','varchar','input','64','AddUpdatePrepLCColumn');
INSERT INTO "sproc_args" VALUES(6,'PackingType','PackingType','varchar','input','64','AddUpdatePrepLCColumn');
INSERT INTO "sproc_args" VALUES(7,'Particlesize','Particlesize','varchar','input','64','AddUpdatePrepLCColumn');
INSERT INTO "sproc_args" VALUES(8,'Particletype','Particletype','varchar','input','64','AddUpdatePrepLCColumn');
INSERT INTO "sproc_args" VALUES(9,'ColumnInnerDia','ColumnInnerDia','varchar','input','64','AddUpdatePrepLCColumn');
INSERT INTO "sproc_args" VALUES(10,'ColumnOuterDia','ColumnOuterDia','varchar','input','64','AddUpdatePrepLCColumn');
INSERT INTO "sproc_args" VALUES(11,'Length','Length','varchar','input','64','AddUpdatePrepLCColumn');
INSERT INTO "sproc_args" VALUES(12,'State','State','varchar','input','32','AddUpdatePrepLCColumn');
INSERT INTO "sproc_args" VALUES(13,'OperatorPRN','OperatorPRN','varchar','input','50','AddUpdatePrepLCColumn');
INSERT INTO "sproc_args" VALUES(14,'Comment','Comment','varchar','input','244','AddUpdatePrepLCColumn');
INSERT INTO "sproc_args" VALUES(15,'<local>','mode','varchar','input','12','AddUpdatePrepLCColumn');
INSERT INTO "sproc_args" VALUES(16,'<local>','message','varchar','output','512','AddUpdatePrepLCColumn');
INSERT INTO "sproc_args" VALUES(17,'<local>','callingUser','varchar','input','128','AddUpdatePrepLCColumn');
CREATE TABLE form_field_options ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "parameter" text );
INSERT INTO "form_field_options" VALUES(1,'OperatorPRN','default_function','GetUser()');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO "detail_report_hotlinks" VALUES(1,'Runs','detail-report','Column Name','prep_lc_run/report/-/-/-/~','labelCol','dl_column_name','');
COMMIT;
