PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_protein_collection_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_dir','desc');
INSERT INTO general_params VALUES('detail_report_data_table','v_protein_collection_list_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','id');
INSERT INTO general_params VALUES('detail_report_data_id_type','integer');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'organism_name','invoke_entity','value','organism/report/~','');
INSERT INTO list_report_hotlinks VALUES(2,'usage_last_12_months','invoke_entity','name','analysis_job/report/-/-/-/-/-/-/@/-/52','');
INSERT INTO list_report_hotlinks VALUES(3,'usage_all_years','invoke_entity','name','analysis_job/report/-/-/-/-/-/-/@','');
INSERT INTO list_report_hotlinks VALUES(4,'id','invoke_entity','value','/protein_collection/show/','');
INSERT INTO list_report_hotlinks VALUES(5,'entries','invoke_entity','id','protein_collection_members/report/@','');
INSERT INTO list_report_hotlinks VALUES(6,'+entries','format_commas','value','','{"Decimals":"0"}');
INSERT INTO list_report_hotlinks VALUES(7,'residues','format_commas','value','','{"Decimals":"0"}');
INSERT INTO list_report_hotlinks VALUES(8,'description','min_col_width','value','60','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_Name','Name','40!','','name','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_Organism','Organism','15!','','organism_name','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_Usage','Most recent weeks','2!','','most_recent_usage','MostRecentWeeks','text','','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_Min_Entries','Min entries','5!','','entries','GreaterThanOrEqualTo','text','','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_Max_Entries','Max entries','5!','','entries','LessThanOrEqualTo','text','','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_Description','Description','','','description','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_Source','Source','20!','','source','ContainsText','text','','','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO detail_report_hotlinks VALUES(1,'organism_name','detail-report','organism_name','organism/report/~','labelCol','dl_organism',NULL);
INSERT INTO detail_report_hotlinks VALUES(2,'usage_last_12_months','detail-report','name','analysis_job/report/-/-/-/-/-/-/@/-/52','labelCol','dl_usage_12_months','');
INSERT INTO detail_report_hotlinks VALUES(3,'usage_all_years','detail-report','name','analysis_job/report/-/-/-/-/-/-/@/-/-','labelCol','dl_usage_all_years','');
INSERT INTO detail_report_hotlinks VALUES(4,'entries','detail-report','id','protein_collection_members/report/@/-/-/-','labelCol','dl_entries','');
INSERT INTO detail_report_hotlinks VALUES(5,'+entries','format_commas','entries','','valueCol','dl_entries_formatter','{"Decimals":"0"}');
INSERT INTO detail_report_hotlinks VALUES(6,'residues','format_commas','residues','','valueCol','dl_residues_formatter','{"Decimals":"0"}');
INSERT INTO detail_report_hotlinks VALUES(7,'name','detail-report','name','protein_collection/report/~','valueCol','dl_name',NULL);
INSERT INTO detail_report_hotlinks VALUES(8,'id','detail-report','id','protein_collection_members/report/@/-/-/-','valueCol','dl_entries_2','');
COMMIT;
