PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_qc_metrics_list_report');
INSERT INTO general_params VALUES('list_report_cmds','export_graph_cmds');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_dataset','Dataset','40!','','dataset','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_file_size_mb','File Size MB','20','','file_size_mb','ContainsText','text','20','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_amts_10pct_fdr','AMTs 10pct FDR','20','','amts_10pct_fdr','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_task_database','Task_Database','20','','task_database','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_param_file','Param File','40!','','param_file','ContainsText','text','255','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_settings_file','Settings_File','15!','','settings_file','ContainsText','text','255','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_ini_file','Ini_File_Name','20','','ini_file_name','ContainsText','text','255','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'results_url','masked_link','value','','{"Label":"Results"}');
INSERT INTO list_report_hotlinks VALUES(2,'qc_link','image_link','value','index.html','{"width":"400"}');
COMMIT;
