PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','T_Reference_Compound');
INSERT INTO general_params VALUES('list_report_data_table','v_reference_compound_list_report');
INSERT INTO general_params VALUES('detail_report_data_table','v_reference_compound_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','compound_id');
INSERT INTO general_params VALUES('detail_report_data_id_type','integer');
INSERT INTO general_params VALUES('entry_page_data_table','v_reference_compound_entry');
INSERT INTO general_params VALUES('entry_page_data_id_col','compound_id');
INSERT INTO general_params VALUES('entry_sproc','AddUpdateReferenceCompound');
INSERT INTO general_params VALUES('list_report_data_sort_col','id');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('post_submission_detail_id','compound_id');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_Name','Name','35!','','name','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_PubChemID','PubChem ID','','','pub_chem_cid','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_Supplier','Supplier','','','supplier','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_Description','Description','','','description','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_ID_Name','ID_Name','','','id_name','StartsWithText','text','','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'id','invoke_entity','value','reference_compound/show','');
INSERT INTO list_report_hotlinks VALUES(2,'description','min_col_width','value','60','');
INSERT INTO list_report_hotlinks VALUES(4,'container','invoke_entity','value','material_items/report/~','');
INSERT INTO list_report_hotlinks VALUES(6,'organism','invoke_entity','value','organism/report/~','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text, "options" text );
INSERT INTO detail_report_hotlinks VALUES(1,'campaign','detail-report','campaign','campaign/show','labelCol','campaign','');
INSERT INTO detail_report_hotlinks VALUES(2,'container','detail-report','container','material_items/report/~','labelCol','dl_container','');
INSERT INTO detail_report_hotlinks VALUES(3,'+container','detail-report','container','material_move_items/report/~','valueCol','dl_container_move','');
INSERT INTO detail_report_hotlinks VALUES(4,'location','detail-report','location','material_items/report/-/','labelCol','dl_location','');
INSERT INTO detail_report_hotlinks VALUES(5,'+location','detail-report','location','material_move_items/report/-/','valueCol','dl_location_move','');
INSERT INTO detail_report_hotlinks VALUES(6,'organism','detail-report','organism','organism/report/~','labelCol','','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'compound_id','compoundID','int','input','12','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(2,'compound_name','compoundName','varchar','input','64','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(3,'description','description','varchar','input','500','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(4,'compound_type_name','compoundTypeName','varchar','input','64','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(5,'gene_name','geneName','varchar','input','128','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(7,'modifications','modifications','varchar','input','500','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(8,'organism_name','organismName','varchar','input','128','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(9,'pub_chem_cid','pubChemID','varchar','input','12','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(10,'campaign','campaignName','varchar','input','64','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(11,'container','containerName','varchar','input','128','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(12,'wellplate_name','wellplateName','varchar','input','64','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(13,'well_number','wellNumber','varchar','input','64','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(14,'contact_username','contactPRN','varchar','input','64','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(15,'supplier','supplier','varchar','input','64','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(16,'product_id','productId','varchar','input','128','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(17,'purchase_date','purchaseDate','varchar','input','30','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(18,'purity','purity','varchar','input','64','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(19,'purchase_quantity','purchaseQuantity','varchar','input','128','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(20,'mass','mass','varchar','input','30','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(21,'active','active','varchar','input','3','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(22,'<local>','mode','varchar','input','12','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(23,'<local>','message','varchar','output','512','AddUpdateReferenceCompound');
INSERT INTO sproc_args VALUES(24,'<local>','callingUser','varchar','input','128','AddUpdateReferenceCompound');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO form_fields VALUES(1,'compound_id','Compound_ID','non-edit','','','','','','trim');
INSERT INTO form_fields VALUES(2,'compound_name','Compound Name','text','60','80','','','','trim|required|max_length[128]|name_space|min_length[6]');
INSERT INTO form_fields VALUES(3,'description','Description','area','','','4','50','','trim|max_length[512]');
INSERT INTO form_fields VALUES(4,'compound_type_name','Compound Type','text','60','80','','','','trim|required|max_length[64]');
INSERT INTO form_fields VALUES(5,'gene_name','Gene or Protein','text','60','80','','','','trim|max_length[128]');
INSERT INTO form_fields VALUES(7,'modifications','Modifications','area','','','2','50','','trim|max_length[500]');
INSERT INTO form_fields VALUES(8,'organism_name','Organism','text','60','80','','','','trim|required|max_length[128]');
INSERT INTO form_fields VALUES(9,'pub_chem_cid','PubChem CID','text','20','80','','','','trim|numeric');
INSERT INTO form_fields VALUES(10,'contact_username','Contact (usually PNNL Staff)','text','60','128','','','','trim|required|max_length[128]');
INSERT INTO form_fields VALUES(11,'campaign','Campaign','text','60','80','','','','trim|required|max_length[64]');
INSERT INTO form_fields VALUES(12,'container','Container','text','60','128','','','','trim|required|max_length[128]');
INSERT INTO form_fields VALUES(13,'wellplate_name','Wellplate','text','60','80','','','','trim|max_length[64]');
INSERT INTO form_fields VALUES(14,'well_number','Well Number','text','60','80','','','','trim|max_length[64]');
INSERT INTO form_fields VALUES(15,'supplier','Supplier','text','60','80','','','','trim|required|max_length[64]');
INSERT INTO form_fields VALUES(16,'product_id','Product ID (Catalog #)','text','30','128','','','','trim|max_length[128]');
INSERT INTO form_fields VALUES(17,'purchase_date','Purchase Date','text','30','30','','','','trim|max_length[30]');
INSERT INTO form_fields VALUES(18,'purity','Purity','text','30','64','','','','trim|max_length[64]');
INSERT INTO form_fields VALUES(19,'purchase_quantity','Purchase Quantity','text','30','128','','','','trim|max_length[64]');
INSERT INTO form_fields VALUES(20,'mass','Mass','text','30','30','','','','trim|max_length[30]');
INSERT INTO form_fields VALUES(21,'active','Active','text','30','30','','','Yes','trim|max_length[3]');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO form_field_choosers VALUES(1,'contact_username','picker.replace','userPRNPickList','','',',','');
INSERT INTO form_field_choosers VALUES(2,'campaign','list-report.helper','','helper_campaign/report/Active/','campaign',',','');
INSERT INTO form_field_choosers VALUES(3,'container','list-report.helper','','helper_material_container/report','',',','');
INSERT INTO form_field_choosers VALUES(4,'purchase_date','picker.prevDate','','','',',','');
INSERT INTO form_field_choosers VALUES(5,'active','picker.replace','yesNoPickList','','',',','');
INSERT INTO form_field_choosers VALUES(6,'compound_type_name','picker.replace','compoundTypePickList','','',',','');
INSERT INTO form_field_choosers VALUES(7,'organism_name','list-report.helper','','helper_organism/report','',',','');
COMMIT;
