PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_reporter_ion_observation_rate_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'job','invoke_entity','value','analysis_job/show','');
INSERT INTO list_report_hotlinks VALUES(2,'dataset','invoke_entity','value','dataset/show','');
INSERT INTO list_report_hotlinks VALUES(3,'instrument','invoke_entity','value','instrument_operation_history/report','');
INSERT INTO list_report_hotlinks VALUES(4,'observation_rate_link','image_link','value','index.html','{"width":"400"}');
INSERT INTO list_report_hotlinks VALUES(5,'intensity_stats_link','image_link','value','index.html','{"width":"400"}');
INSERT INTO list_report_hotlinks VALUES(6,'channel1','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(7,'channel2','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(8,'channel3','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(9,'channel4','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(10,'channel5','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(11,'channel6','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(12,'channel7','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(13,'channel8','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(14,'channel9','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(15,'channel10','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(16,'channel11','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(17,'channel12','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(18,'channel13','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(19,'channel14','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(20,'channel15','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(21,'channel16','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(22,'channel1_intensity','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(23,'channel2_intensity','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(24,'channel3_intensity','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(25,'channel4_intensity','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(26,'channel5_intensity','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(27,'channel6_intensity','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(28,'channel7_intensity','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(29,'channel8_intensity','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(30,'channel9_intensity','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(31,'channel10_intensity','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(32,'channel11_intensity','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(33,'channel12_intensity','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(34,'channel13_intensity','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(35,'channel14_intensity','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(36,'channel15_intensity','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(37,'channel16_intensity','format_commas','value','','{"Decimals":"2"}');
INSERT INTO list_report_hotlinks VALUES(38,'param_file','invoke_entity','value','param_file/report/-/@/-','');
INSERT INTO list_report_hotlinks VALUES(39,'reporter_ion','invoke_entity','value','sample_label_reporter_ions/report/~','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_job','Job','6!','','job','Equals','text','24','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_dataset','Dataset','40!','','dataset','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_datasetId','Dataset_ID','6!','','dataset_id','Equals','text','24','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_instrument','Instrument','32','','instrument','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_reporterIon','Reporter_Ion','','','reporter_ion','StartsWithText','text','24','','');
COMMIT;
