PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('entry_sproc','AddRequestedRunFractions');
INSERT INTO "general_params" VALUES('entry_page_data_table','v_requested_run_fraction_entry');
INSERT INTO "general_params" VALUES('entry_page_data_id_col','source_request_id');
INSERT INTO "general_params" VALUES('post_submission_link','{"link":"requested_run/report/StartsWith__", "label":"Show new requested runs"}');
INSERT INTO "general_params" VALUES('post_submission_detail_id','source_request_name');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO "form_fields" VALUES(1,'source_request_id','Source Request','non-edit','','','','','0','trim');
INSERT INTO "form_fields" VALUES(2,'source_request_name','Source Request Name','non-edit','','','','','','trim');
INSERT INTO "form_fields" VALUES(3,'experiment','Experiment Name','non-edit','','','','','','trim');
INSERT INTO "form_fields" VALUES(4,'instrument_group','Instrument Group','non-edit','','','','','','trim');
INSERT INTO "form_fields" VALUES(5,'run_type','Run Type','non-edit','','','','','','trim');
INSERT INTO "form_fields" VALUES(6,'source_separation_group','Source Separation Group','non-edit','','','','','','trim');
INSERT INTO "form_fields" VALUES(7,'separation_group','Separation Group','text','25','80','','','','trim|required|max_length[64]');
INSERT INTO "form_fields" VALUES(8,'requestor','Requestor (Username)','text','35','80','','','','trim|required|max_length[80]');
INSERT INTO "form_fields" VALUES(9,'instrument_settings','Instrument Settings','area','','','6','60','','trim|max_length[512]');
INSERT INTO "form_fields" VALUES(10,'staging_location','Staging Location','text','40','64','','','','trim|max_length[64]');
INSERT INTO "form_fields" VALUES(11,'wellplate','Wellplate','text','40','80','','','(lookup)','trim|max_length[64]');
INSERT INTO "form_fields" VALUES(12,'well','Well','text','40','80','','','(lookup)','trim|max_length[24]');
INSERT INTO "form_fields" VALUES(13,'vialing_concentration','Vialing Concentration','text','25','80','','','','trim|max_length[32]');
INSERT INTO "form_fields" VALUES(14,'vialing_volume','Vialing Volume','text','25','80','','','','trim|max_length[32]');
INSERT INTO "form_fields" VALUES(15,'comment','Comment','area','','','6','80','','trim|max_length[1024]');
INSERT INTO "form_fields" VALUES(16,'work_package','Work Package','text','15','50','','','(lookup)','trim|max_length[50]|required');
INSERT INTO "form_fields" VALUES(17,'eus_usage_type','EMSL Usage Type','text','15','50','','','(lookup)','trim|required|max_length[50]|not_contain[(unknown)]');
INSERT INTO "form_fields" VALUES(18,'eus_proposal_id','EMSL Proposal ID','text','10','10','','','(lookup)','trim|max_length[10]');
INSERT INTO "form_fields" VALUES(19,'eus_user','EMSL Proposal User','text','25','1024','','','(lookup)','trim|max_length[1024]');
INSERT INTO "form_fields" VALUES(20,'mrm_attachment','MRM Transition List Attachment','text','60','128','','','','trim|max_length[128]');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO "form_field_choosers" VALUES(1,'separation_group','picker.replace','separationGroupNoFractionsPickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(2,'requestor','picker.replace','userPRNPickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(3,'staging_location','list-report.helper','','helper_material_location','',',','');
INSERT INTO "form_field_choosers" VALUES(4,'wellplate','picker.replace','wellplatePickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(5,'work_package','list-report.helper','','helper_charge_code/report','',',','');
INSERT INTO "form_field_choosers" VALUES(6,'eus_usage_type','picker.replace','eusUsageTypePickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(7,'eus_proposal_id','list-report.helper','','helper_eus_proposal/report','',',','Select Proposal...');
INSERT INTO "form_field_choosers" VALUES(8,'eus_proposal_id','list-report.helper','','helper_eus_proposal_ex/report','',',','Select Proposal (by dataset)...');
INSERT INTO "form_field_choosers" VALUES(9,'eus_user','list-report.helper','','helper_eus_user/report','eus_proposal_id',',','Select User...');
INSERT INTO "form_field_choosers" VALUES(10,'mrm_attachment','list-report.helper','','helper_mrm_attachment/report','',',','');
INSERT INTO "form_field_choosers" VALUES(11,'comment','link.list','multiDatasetRequestCommentTmpl','','',',','Use Template:');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO "list_report_hotlinks" VALUES(1,'Request','invoke_entity','value','requested_run/show/','');
INSERT INTO "list_report_hotlinks" VALUES(2,'Campaign','invoke_entity','value','campaign/show','');
INSERT INTO "list_report_hotlinks" VALUES(3,'Experiment','invoke_entity','value','experiment/show','');
INSERT INTO "list_report_hotlinks" VALUES(4,'Dataset','invoke_entity','value','dataset/show','');
INSERT INTO "list_report_hotlinks" VALUES(5,'Days In Queue','color_label','#DaysInQueue','','{"30":"clr_30","60":"clr_60","90":"clr_90","120":"clr_120"}');
INSERT INTO "list_report_hotlinks" VALUES(6,'Batch','invoke_entity','value','requested_run_batch/show','');
INSERT INTO "list_report_hotlinks" VALUES(7,'Work Package','invoke_entity','value','charge_code/show','');
INSERT INTO "list_report_hotlinks" VALUES(8,'WP State','color_label','#WPActivationState','','{"0":"clr_30","1":"clr_45","2":"clr_60","3":"clr_90","4":"clr_120","5":"clr_120","10":"clr_120"}');
INSERT INTO "list_report_hotlinks" VALUES(9,'Proposal','invoke_entity','value','eus_proposals/show','');
INSERT INTO "list_report_hotlinks" VALUES(10,'Comment','markup','Comment','60','');
INSERT INTO "list_report_hotlinks" VALUES(11,'Proposal State','color_label','value','','{"Active":"clr_30", "Permanently Active":"clr_60", "Closed":"clr_90", "Inactive":"clr_90"}');
INSERT INTO "list_report_hotlinks" VALUES(12,'Queue State','invoke_entity','Campaign','requested_run_admin/report/-/-/-/-/~@/-/-/-','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text, "options" text );
INSERT INTO "detail_report_hotlinks" VALUES(1,'Experiment','detail-report','Experiment','experiment/show','labelCol','experiment','');
INSERT INTO "detail_report_hotlinks" VALUES(2,'Campaign','detail-report','Campaign','campaign/show','labelCol','campaign','');
INSERT INTO "detail_report_hotlinks" VALUES(3,'Batch','detail-report','Batch','requested_run_batch/show','labelCol','batch','');
INSERT INTO "detail_report_hotlinks" VALUES(4,'Block','detail-report','Batch','requested_run_batch_blocking/param','valueCol','block','');
INSERT INTO "detail_report_hotlinks" VALUES(5,'Dataset','detail-report','Dataset','dataset/show','valueCol','dataset','');
INSERT INTO "detail_report_hotlinks" VALUES(6,'Factors','detail-report','Request','custom_factors/report/-','labelCol','dl_show_factors','');
INSERT INTO "detail_report_hotlinks" VALUES(7,'+Factors','detail-report','Request','requested_run_factors/param/@/Requested_Run_ID','valueCol','dl_edit_factors','');
INSERT INTO "detail_report_hotlinks" VALUES(8,'Instrument Group','detail-report','Instrument Group','instrument_group/show/','valueCol','dl_instrument_group','');
INSERT INTO "detail_report_hotlinks" VALUES(9,'Instrument Used','detail-report','Instrument Used','instrument/show/','valueCol','dl_instrument','');
INSERT INTO "detail_report_hotlinks" VALUES(10,'EUS Proposal','detail-report','EUS Proposal','eus_proposals/show','valueCol','dl_eus_proposal','');
INSERT INTO "detail_report_hotlinks" VALUES(11,'Work Package','detail-report','Work Package','charge_code/show','labelCol','dl_Work_Package','');
INSERT INTO "detail_report_hotlinks" VALUES(12,'Work Package State','color_label','#WPActivationState','','valueCol','dl_Work_Package_State','{"3":"clr_90","4":"clr_120", "5":"clr_120","10":"clr_120"}');
INSERT INTO "detail_report_hotlinks" VALUES(13,'Requestor','detail-report','Requestor','user/report/-/~','labelCol','dl_Requestor','{"RemoveRegEx":" [(].*[)]"}');
INSERT INTO "detail_report_hotlinks" VALUES(14,'Separation Group','detail-report','Separation Group','separation_group/show','labelCol','dl_separation_group','');
INSERT INTO "detail_report_hotlinks" VALUES(15,'Staging Location','detail-report','Staging Location','material_location/report/~@','valueCol','dl_staging_location','');
INSERT INTO "detail_report_hotlinks" VALUES(16,'Comment','markup','Comment','','valueCol','dl_comment','');
INSERT INTO "detail_report_hotlinks" VALUES(17,'EUS Proposal State','color_label','EUS Proposal State','','valueCol','dl_eus_proposal_state','{"Active":"clr_30", "Permanently Active":"clr_60", "Closed":"clr_90", "Inactive":"clr_90"}

');
INSERT INTO "detail_report_hotlinks" VALUES(18,'Queue State','detail-report','Campaign','requested_run_admin/report/-/-/-/-/~@/-/-/-','labelCol','dl_requested_run_admin','');
INSERT INTO "detail_report_hotlinks" VALUES(19,'Days In Queue','detail-report','Instrument Group','run_planning/report/~@/-/-/-/-/-/-/-','labelCol','dl_run_planning','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO "sproc_args" VALUES(1,'source_request_id','sourceRequestID','int','input','','AddRequestedRunFractions');
INSERT INTO "sproc_args" VALUES(2,'separation_group','separationGroup','varchar','input','64','AddRequestedRunFractions');
INSERT INTO "sproc_args" VALUES(3,'requestor','requestorPRN','varchar','input','80','AddRequestedRunFractions');
INSERT INTO "sproc_args" VALUES(4,'instrument_settings','instrumentSettings','varchar','input','512','AddRequestedRunFractions');
INSERT INTO "sproc_args" VALUES(5,'staging_location','stagingLocation','varchar','input','64','AddRequestedRunFractions');
INSERT INTO "sproc_args" VALUES(6,'wellplate','wellplateName','varchar','input','64','AddRequestedRunFractions');
INSERT INTO "sproc_args" VALUES(7,'well','wellNumber','varchar','input','24','AddRequestedRunFractions');
INSERT INTO "sproc_args" VALUES(8,'vialing_concentration','vialingConc','varchar','input','32','AddRequestedRunFractions');
INSERT INTO "sproc_args" VALUES(9,'vialing_volume','vialingVol','varchar','input','32','AddRequestedRunFractions');
INSERT INTO "sproc_args" VALUES(10,'comment','comment','varchar','input','1024','AddRequestedRunFractions');
INSERT INTO "sproc_args" VALUES(11,'work_package','workPackage','varchar','input','50','AddRequestedRunFractions');
INSERT INTO "sproc_args" VALUES(12,'eus_usage_type','eusUsageType','varchar','input','50','AddRequestedRunFractions');
INSERT INTO "sproc_args" VALUES(13,'eus_proposal_id','eusProposalID','varchar','input','10','AddRequestedRunFractions');
INSERT INTO "sproc_args" VALUES(14,'eus_user','eusUserID','varchar','input','512','AddRequestedRunFractions');
INSERT INTO "sproc_args" VALUES(15,'mrm_attachment','mrmAttachment','varchar','input','128','AddRequestedRunFractions');
INSERT INTO "sproc_args" VALUES(16,'<local>','mode','varchar','input','12','AddRequestedRunFractions');
INSERT INTO "sproc_args" VALUES(17,'<local>','message','varchar','output','1024','AddRequestedRunFractions');
INSERT INTO "sproc_args" VALUES(18,'<local>','callingUser','varchar','input','128','AddRequestedRunFractions');
CREATE TABLE external_sources ( id INTEGER PRIMARY KEY,  "source_page" text, "field" text, "type" text, "value" text );
INSERT INTO "external_sources" VALUES(1,'requested_run','source_request_id','ColName','Request');
INSERT INTO "external_sources" VALUES(2,'requested_run','source_request_name','ColName','Name');
INSERT INTO "external_sources" VALUES(3,'requested_run','experiment','ColName','Experiment');
INSERT INTO "external_sources" VALUES(4,'requested_run','instrument_group','ColName','Instrument Group');
INSERT INTO "external_sources" VALUES(5,'requested_run','run_type','ColName','Type');
INSERT INTO "external_sources" VALUES(6,'requested_run','source_separation_group','ColName','Separation Group');
INSERT INTO "external_sources" VALUES(7,'requested_run','requestor','ColName','Requestor');
INSERT INTO "external_sources" VALUES(8,'requested_run','instrument_settings','ColName','Instrument Settings');
INSERT INTO "external_sources" VALUES(9,'requested_run','staging_location','ColName','Staging Location');
INSERT INTO "external_sources" VALUES(10,'requested_run','wellplate','ColName','Well Plate');
INSERT INTO "external_sources" VALUES(11,'requested_run','well','ColName','Well');
INSERT INTO "external_sources" VALUES(12,'requested_run','vialing_concentration','ColName','Vialing Concentration');
INSERT INTO "external_sources" VALUES(13,'requested_run','vialing_volume','ColName','Vialing Volume');
INSERT INTO "external_sources" VALUES(14,'requested_run','comment','ColName','Comment');
INSERT INTO "external_sources" VALUES(15,'requested_run','work_package','ColName','Work Package');
INSERT INTO "external_sources" VALUES(16,'requested_run','eus_usage_type','ColName','EUS Usage Type');
INSERT INTO "external_sources" VALUES(17,'requested_run','eus_proposal_id','ColName','EUS Proposal');
INSERT INTO "external_sources" VALUES(18,'requested_run','eus_user','ColName','EUS User');
INSERT INTO "external_sources" VALUES(19,'requested_run','mrm_attachment','ColName','MRM Transistion List');
CREATE TABLE entry_commands ( id INTEGER PRIMARY KEY,  "name" text, "type" text, "label" text, "tooltip" text, "target" text );
INSERT INTO "entry_commands" VALUES(1,'preview','cmd','Preview','Validate options and show the requested runs that would be created','');
COMMIT;
