PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_requested_run_batch_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('detail_report_data_table','v_requested_run_batch_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','id');
INSERT INTO general_params VALUES('detail_report_data_id_type','integer');
INSERT INTO general_params VALUES('entry_sproc','AddUpdateRequestedRunBatch');
INSERT INTO general_params VALUES('entry_page_data_table','v_requested_run_batch_entry');
INSERT INTO general_params VALUES('entry_page_data_id_col','id');
INSERT INTO general_params VALUES('operations_sproc','DoRequestedRunBatchOperation');
INSERT INTO general_params VALUES('post_submission_detail_id','id');
INSERT INTO general_params VALUES('detail_report_cmds','file_attachment_cmds');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO form_fields VALUES(1,'id','ID','non-edit','','','','','','trim|max_length[6]');
INSERT INTO form_fields VALUES(2,'name','Name','text','50','50','','','','trim|required|max_length[50]');
INSERT INTO form_fields VALUES(3,'description','Description','area','','','2','60','','trim|max_length[256]');
INSERT INTO form_fields VALUES(4,'requested_run_list','Requests','area','','','4','60','','trim');
INSERT INTO form_fields VALUES(5,'owner_username','Owner','text','24','24','','','','trim|required|max_length[24]');
INSERT INTO form_fields VALUES(6,'requested_batch_priority','Requested Batch Priority','text','24','24','','','Normal','trim|required|max_length[24]');
INSERT INTO form_fields VALUES(7,'requested_completion_date','Requested Completion Date','text','32','32','','','','trim|required|max_length[32]|valid_date');
INSERT INTO form_fields VALUES(8,'justification_high_priority','Justification High Priority','area','','','4','60','','trim|max_length[512]');
INSERT INTO form_fields VALUES(9,'requested_instrument','Instrument Group','text','24','64','','','','trim|required|max_length[64]');
INSERT INTO form_fields VALUES(10,'comment','Comment','area','','','4','60','','trim|max_length[512]');
INSERT INTO form_fields VALUES(11,'batch_group','Batch Group','text','24','24','','','','trim|numeric');
INSERT INTO form_fields VALUES(12,'batch_group_order','Batch Group Order','text','24','24','','','','trim|numeric');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO form_field_choosers VALUES(1,'requested_run_list','list-report.helper','','helper_requested_run/report','',',','');
INSERT INTO form_field_choosers VALUES(2,'owner_username','picker.replace','userUsernamePickList','','',',','');
INSERT INTO form_field_choosers VALUES(3,'requested_batch_priority','picker.replace','batchPriorityPickList','','',',','');
INSERT INTO form_field_choosers VALUES(4,'requested_instrument','picker.replace','instrumentGroupPickList','','',',','');
INSERT INTO form_field_choosers VALUES(5,'requested_completion_date','picker.prevDate','','','',',','');
INSERT INTO form_field_choosers VALUES(6,'batch_group','picker.replace','requested_run_batch_group_list','','',',','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_name','Name','32','','name','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_instrument','Inst. Group','32','','inst_group','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_description','Description','32','','description','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_owner','Owner','32','','owner','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_days_in_queue','Days In Queue','20','','days_in_queue','GreaterThanOrEqualTo','text','20','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_comment','Comment','32','','comment','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(8,'pf_req_priority','Req. Priority','32','','req_priority','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(9,'pf_requests','Requests','12','','requests','GreaterThanOrEqualTo','text','128','','');
INSERT INTO list_report_primary_filter VALUES(10,'pf_ID','Batch ID','12','','id','Equals','text','32','','');
INSERT INTO list_report_primary_filter VALUES(11,'pf_SeparationType','Separation Type','32','','separation_type','ContainsText','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'id','invoke_entity','value','requested_run_batch/show/','');
INSERT INTO list_report_hotlinks VALUES(2,'requests','invoke_entity','id','requested_run/report/-/-/active','');
INSERT INTO list_report_hotlinks VALUES(3,'runs','invoke_entity','id','requested_run/report/-/-/completed/','');
INSERT INTO list_report_hotlinks VALUES(4,'days_in_queue','color_label','days_in_queue_bin','','{"30":"clr_30","60":"clr_60","90":"clr_90","120":"clr_120"}');
INSERT INTO list_report_hotlinks VALUES(6,'first_active_request','invoke_entity','first_active_request','requested_run/show/','');
INSERT INTO list_report_hotlinks VALUES(7,'last_active_request','invoke_entity','last_active_request','requested_run/show/','');
INSERT INTO list_report_hotlinks VALUES(8,'comment','min_col_width','value','40','');
INSERT INTO list_report_hotlinks VALUES(9,'blocked','invoke_entity','id','requested_run_batch_blocking/param/@','');
INSERT INTO list_report_hotlinks VALUES(10,'days_in_queue_bin','no_display','value','','');
INSERT INTO list_report_hotlinks VALUES(11,'batch_group','invoke_entity','value','requested_run_batch_group/show/','');
CREATE TABLE detail_report_commands ( id INTEGER PRIMARY KEY,  "name" text, "Type" text, "Command" text, "Target" text, "Tooltip" text, "Prompt" text );
INSERT INTO detail_report_commands VALUES(1,'Lock batch','cmd_op','LockBatch','requested_run_batch','Lock batch to prevent changes to run order or membership','Are you sure that you want to lock this batch?');
INSERT INTO detail_report_commands VALUES(2,'Unlock batch','cmd_op','UnlockBatch','requested_run_batch','Unlock batch to permit changes to run order or membership','Are you sure that you want to unlock this batch?');
INSERT INTO detail_report_commands VALUES(3,'Delete batch','cmd_op','delete','requested_run_batch','Delete this requested run batch request.','Are you sure that you want to delete this batch?');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO detail_report_hotlinks VALUES(1,'requests','detail-report','id','requested_run/report/-/-/-','labelCol','dl_requests','');
INSERT INTO detail_report_hotlinks VALUES(2,'id','detail-report','id','requested_run_batch_blocking/param','labelCol','dl_batch_blocking','');
INSERT INTO detail_report_hotlinks VALUES(3,'+id','detail-report','id','requested_run_batch/report/-/-/-/-/-/-/-/-/@','valueCol','dl_batch_list_report','');
INSERT INTO detail_report_hotlinks VALUES(4,'factors','detail-report','id','custom_factors/report','labelCol','dl_show_factors',NULL);
INSERT INTO detail_report_hotlinks VALUES(5,'+factors','detail-report','id','requested_run_factors/param/@/batch_id','valueCol','dl_edit_factors',NULL);
INSERT INTO detail_report_hotlinks VALUES(6,'instrument_group','detail-report','instrument_group','instrument_group/show/','labelCol','dl_instrument_group',NULL);
INSERT INTO detail_report_hotlinks VALUES(7,'instrument_used','detail-report','instrument_used','instrument/show/','labelCol','dl_instrument','');
INSERT INTO detail_report_hotlinks VALUES(8,'last_ordered','detail-report','id','requested_run_batch_blocking/param/@','labelCol','dl_batch_run_order','');
INSERT INTO detail_report_hotlinks VALUES(9,'batch_group','detail-report','batch_group','requested_run_batch_group/show/','valueCol','dl_batch_group_edit','');
INSERT INTO detail_report_hotlinks VALUES(10,'+batch_group','detail-report','batch_group','requested_run_batch_group/report/','labelCol','dl_batch_group_report','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'id','id','int','output','','AddUpdateRequestedRunBatch');
INSERT INTO sproc_args VALUES(2,'name','name','varchar','input','50','AddUpdateRequestedRunBatch');
INSERT INTO sproc_args VALUES(3,'description','description','varchar','input','256','AddUpdateRequestedRunBatch');
INSERT INTO sproc_args VALUES(4,'requested_run_list','requestedRunList','text','input','2147483647','AddUpdateRequestedRunBatch');
INSERT INTO sproc_args VALUES(5,'owner_username','ownerPRN','varchar','input','24','AddUpdateRequestedRunBatch');
INSERT INTO sproc_args VALUES(6,'requested_batch_priority','requestedBatchPriority','varchar','input','24','AddUpdateRequestedRunBatch');
INSERT INTO sproc_args VALUES(7,'requested_completion_date','requestedCompletionDate','varchar','input','32','AddUpdateRequestedRunBatch');
INSERT INTO sproc_args VALUES(8,'justification_high_priority','justificationHighPriority','varchar','input','512','AddUpdateRequestedRunBatch');
INSERT INTO sproc_args VALUES(9,'requested_instrument','requestedInstrument','varchar','input','64','AddUpdateRequestedRunBatch');
INSERT INTO sproc_args VALUES(10,'comment','comment','varchar','input','512','AddUpdateRequestedRunBatch');
INSERT INTO sproc_args VALUES(11,'batch_group','batchGroupID','int','input','24','AddUpdateRequestedRunBatch');
INSERT INTO sproc_args VALUES(12,'batch_group_order','batchGroupOrder','int','input','12','AddUpdateRequestedRunBatch');
INSERT INTO sproc_args VALUES(13,'<local>','mode','varchar','input','12','AddUpdateRequestedRunBatch');
INSERT INTO sproc_args VALUES(14,'<local>','message','varchar','output','512','AddUpdateRequestedRunBatch');
INSERT INTO sproc_args VALUES(15,'id','batchID','int','input','','DoRequestedRunBatchOperation');
INSERT INTO sproc_args VALUES(16,'<local>','mode','varchar','input','12','DoRequestedRunBatchOperation');
INSERT INTO sproc_args VALUES(17,'<local>','message','varchar','output','512','DoRequestedRunBatchOperation');
COMMIT;
