PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('entry_sproc','AddRequestedRuns');
INSERT INTO general_params VALUES('entry_page_data_table','v_requested_run_entry');
INSERT INTO general_params VALUES('entry_page_data_id_col','request');
INSERT INTO general_params VALUES('post_submission_link_tag','requested_run');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO form_fields VALUES(1,'experiment_group_id','Experiment Group ID','text','12','12','','','','trim|required|max_length[12]');
INSERT INTO form_fields VALUES(2,'request_name_suffix','Request Name Suffix','text','32','32','','','','trim|max_length[32]');
INSERT INTO form_fields VALUES(3,'instrument_group','Instrument Group','text','25','80','','','(lookup)','trim|required|max_length[64]');
INSERT INTO form_fields VALUES(4,'type','Run Type','text','25','80','','','(lookup)','trim|required|max_length[50]');
INSERT INTO form_fields VALUES(5,'separation_group','Separation Group','text','25','64','','','(lookup)','trim|required|max_length[64]');
INSERT INTO form_fields VALUES(6,'requester','Requester (Username)','text','25','50','','','','trim|required|max_length[50]');
INSERT INTO form_fields VALUES(7,'instrument_settings','Instrument Settings','area','','','6','60','','trim|max_length[512]');
INSERT INTO form_fields VALUES(8,'staging_location','Staging Location','text','40','64','','','','trim|max_length[64]');
INSERT INTO form_fields VALUES(9,'vialing_conc','Vialing Concentration','text','25','80','','','','trim|max_length[32]');
INSERT INTO form_fields VALUES(10,'vialing_vol','Vialing Volume','text','25','80','','','','trim|max_length[32]');
INSERT INTO form_fields VALUES(11,'comment','Comment','area','','','4','60','','trim|max_length[1024]');
INSERT INTO form_fields VALUES(12,'work_package','Work Package','text','15','50','','','(lookup)','trim|max_length[50]|required');
INSERT INTO form_fields VALUES(15,'eus_usage_type','EMSL Usage Type','text','15','50','','','(lookup)','trim|required|max_length[50]');
INSERT INTO form_fields VALUES(16,'eus_proposal_id','EMSL Proposal ID','text','10','10','','','(lookup)','trim|max_length[10]');
INSERT INTO form_fields VALUES(17,'eus_users','EMSL Users List','area','','','4','60','(lookup)','trim|max_length[1024]');
INSERT INTO form_fields VALUES(18,'mrm_attachment','MRM Transition List Attachment','text','60','128','','','','trim|max_length[128]');
INSERT INTO form_fields VALUES(19,'internal_standard','Dataset Internal Standard','hidden','','','','','none','trim|max_length[50]|required');
INSERT INTO form_fields VALUES(20,'experiment_list','','hidden','','','','','','trim|max_length[3500]');
INSERT INTO form_fields VALUES(21,'batch_name','Batch Name','text','30!','50','','','','trim|max_length[50]');
INSERT INTO form_fields VALUES(22,'batch_description','Batch Description','text','30!','','2','60','','trim|max_length[255]');
INSERT INTO form_fields VALUES(23,'batch_completion_date','Batch Completion Date','text','25','32','','','','trim|max_length[32]|valid_date');
INSERT INTO form_fields VALUES(24,'batch_priority','Requested Batch Priority','text','24','','','','Normal','trim|required|max_length[24]');
INSERT INTO form_fields VALUES(25,'batch_priority_justification','Justification High Priority','area','','','4','60','','trim|max_length[512]');
INSERT INTO form_fields VALUES(26,'batch_comment','Comment','area','','','4','60','','trim|max_length[512]');
CREATE TABLE form_field_options ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "parameter" text );
INSERT INTO form_field_options VALUES(1,'requester','default_function','GetUser()');
INSERT INTO form_field_options VALUES(2,'batch_name','section','Batch Information (optional)');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO form_field_choosers VALUES(1,'experiment_group_id','list-report.helper','','helper_experiment_group/report','experiment_group_id',',','');
INSERT INTO form_field_choosers VALUES(2,'instrument_group','picker.replace','instrumentGroupPickList','','',',','');
INSERT INTO form_field_choosers VALUES(3,'type','list-report.helper','','data/lr/ad_hoc_query/helper_inst_group_dstype/report','instrument_group|required',',','');
INSERT INTO form_field_choosers VALUES(4,'separation_group','picker.replace','separationGroupPickList','','',',','');
INSERT INTO form_field_choosers VALUES(5,'requester','picker.replace','userUsernamePickList','','',',','');
INSERT INTO form_field_choosers VALUES(7,'eus_usage_type','picker.replace','eusUsageTypePickList','','',',','');
INSERT INTO form_field_choosers VALUES(8,'eus_users','list-report.helper','','helper_eus_user_ckbx/report','eus_proposal_id',',','');
INSERT INTO form_field_choosers VALUES(9,'mrm_attachment','list-report.helper','','helper_mrm_attachment/report','',',','');
INSERT INTO form_field_choosers VALUES(10,'eus_proposal_id','list-report.helper','','helper_eus_proposal/report','',',','Select Proposal...');
INSERT INTO form_field_choosers VALUES(11,'eus_proposal_id','list-report.helper','','helper_eus_proposal_ex/report','',',','Select Proposal (by dataset)...');
INSERT INTO form_field_choosers VALUES(12,'work_package','list-report.helper','','helper_charge_code/report','',',','');
INSERT INTO form_field_choosers VALUES(13,'staging_location','list-report.helper','','helper_material_location','',',','');
INSERT INTO form_field_choosers VALUES(14,'batch_completion_date','picker.prevDate','','','',',','');
INSERT INTO form_field_choosers VALUES(15,'batch_priority','picker.replace','batchPriorityPickList','','',',','');
INSERT INTO form_field_choosers VALUES(16,'batch_name','list-report.helper','','helper_experiment_group_name/report','experiment_group_id',',','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'experiment_group_id','experimentGroupID','varchar','input','12','AddRequestedRuns');
INSERT INTO sproc_args VALUES(2,'experiment_list','experimentList','varchar','input','3500','AddRequestedRuns');
INSERT INTO sproc_args VALUES(3,'request_name_suffix','requestNameSuffix','varchar','input','32','AddRequestedRuns');
INSERT INTO sproc_args VALUES(4,'requester','operPRN','varchar','input','64','AddRequestedRuns');
INSERT INTO sproc_args VALUES(5,'instrument_group','instrumentGroup','varchar','input','64','AddRequestedRuns');
INSERT INTO sproc_args VALUES(6,'work_package','workPackage','varchar','input','50','AddRequestedRuns');
INSERT INTO sproc_args VALUES(7,'type','msType','varchar','input','20','AddRequestedRuns');
INSERT INTO sproc_args VALUES(8,'instrument_settings','instrumentSettings','varchar','input','512','AddRequestedRuns');
INSERT INTO sproc_args VALUES(11,'eus_proposal_id','eusProposalID','varchar','input','10','AddRequestedRuns');
INSERT INTO sproc_args VALUES(12,'eus_usage_type','eusUsageType','varchar','input','50','AddRequestedRuns');
INSERT INTO sproc_args VALUES(13,'eus_users','eusUsersList','varchar','input','1024','AddRequestedRuns');
INSERT INTO sproc_args VALUES(14,'internal_standard','internalStandard','varchar','input','50','AddRequestedRuns');
INSERT INTO sproc_args VALUES(15,'comment','comment','varchar','input','1024','AddRequestedRuns');
INSERT INTO sproc_args VALUES(16,'<local>','mode','varchar','input','12','AddRequestedRuns');
INSERT INTO sproc_args VALUES(17,'<local>','message','varchar','output','512','AddRequestedRuns');
INSERT INTO sproc_args VALUES(18,'separation_group','separationGroup','varchar','input','64','AddRequestedRuns');
INSERT INTO sproc_args VALUES(19,'mrm_attachment','mrmAttachment','varchar','input','128','AddRequestedRuns');
INSERT INTO sproc_args VALUES(20,'vialing_conc','VialingConc','varchar','input','32','AddRequestedRuns');
INSERT INTO sproc_args VALUES(21,'vialing_vol','VialingVol','varchar','input','32','AddRequestedRuns');
INSERT INTO sproc_args VALUES(22,'staging_location','stagingLocation','varchar','input','64','AddRequestedRuns');
INSERT INTO sproc_args VALUES(23,'<local>','callingUser','varchar','input','128','AddRequestedRuns');
INSERT INTO sproc_args VALUES(24,'batch_name','batchName','varchar','input','50','AddRequestedRuns');
INSERT INTO sproc_args VALUES(25,'batch_description','batchDescription','varchar','input','256','AddRequestedRuns');
INSERT INTO sproc_args VALUES(26,'batch_completion_date','batchCompletionDate','varchar','input','32','AddRequestedRuns');
INSERT INTO sproc_args VALUES(27,'batch_priority','batchPriority','varchar','input','24','AddRequestedRuns');
INSERT INTO sproc_args VALUES(28,'batch_priority_justification','batchPriorityJustification','varchar','input','512','AddRequestedRuns');
INSERT INTO sproc_args VALUES(29,'batch_comment','batchComment','varchar','input','512','AddRequestedRuns');
CREATE TABLE entry_commands ( id INTEGER PRIMARY KEY,  "name" text, "type" text, "label" text, "tooltip" text, "target" text );
INSERT INTO entry_commands VALUES(1,'PreviewAdd','cmd','Preview Add','Determine if current values are valid, but do not change database.','');
CREATE TABLE external_sources ( id INTEGER PRIMARY KEY,  "source_page" text, "field" text, "type" text, "value" text );
INSERT INTO external_sources VALUES(1,'requested_run','instrument_group','ColName','instrument_group');
INSERT INTO external_sources VALUES(2,'requested_run','type','ColName','run_type');
INSERT INTO external_sources VALUES(3,'requested_run','separation_group','ColName','separation_group');
INSERT INTO external_sources VALUES(4,'requested_run','requester','ColName.action.ExtractUsername','requester');
INSERT INTO external_sources VALUES(5,'requested_run','instrument_settings','ColName','instrument_settings');
INSERT INTO external_sources VALUES(6,'requested_run','staging_location','ColName','staging_location');
INSERT INTO external_sources VALUES(7,'requested_run','vialing_conc','ColName','vialing_concentration');
INSERT INTO external_sources VALUES(8,'requested_run','vialing_vol','ColName','vialing_volume');
INSERT INTO external_sources VALUES(9,'requested_run','work_package','ColName','work_package');
INSERT INTO external_sources VALUES(10,'requested_run','eus_usage_type','ColName','eus_usage_type');
INSERT INTO external_sources VALUES(11,'requested_run','eus_proposal_id','ColName','eus_proposal');
INSERT INTO external_sources VALUES(12,'requested_run','eus_users','ColName.action.ExtractEUSId','eus_user');
INSERT INTO external_sources VALUES(13,'requested_run','mrm_attachment','ColName','mrm_transition_list');
COMMIT;
