PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_requested_run_batch_location_history_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'batch_id','invoke_entity','value','requested_run_batch/show','');
INSERT INTO list_report_hotlinks VALUES(2,'freezer','invoke_entity','value','material_location/report/-/~@/-/-/-/-/active','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_batch_id','Batch ID','12','','batch_id','Equals','text','32','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_batch_name','Name','30!','','batch_name','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_owner','Owner','32','','batch_owner','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_freezer','Freezer','15!','','freezer','ContainsText','text','80','','');
COMMIT;
