PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_requested_run_batch_group_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('detail_report_data_table','v_requested_run_batch_group_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','id');
INSERT INTO general_params VALUES('detail_report_data_id_type','integer');
INSERT INTO general_params VALUES('entry_page_data_table','v_requested_run_batch_group_entry');
INSERT INTO general_params VALUES('entry_page_data_id_col','id');
INSERT INTO general_params VALUES('entry_sproc','add_update_requested_run_batch_group');
INSERT INTO general_params VALUES('post_submission_detail_id','id');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'id','invoke_entity','value','requested_run_batch_group/show/','');
INSERT INTO list_report_hotlinks VALUES(2,'batches','link_list','value','requested_run_batch/show/','');
INSERT INTO list_report_hotlinks VALUES(3,'first_request','invoke_entity','value','requested_run/show/','');
INSERT INTO list_report_hotlinks VALUES(4,'last_request','invoke_entity','value','requested_run/show/','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_id','ID','','','id','Equals','text','32','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_name','Name','25!','','name','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_batch','Batch','','','batches','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_first_request','First Request','','','first_request','Equals','text','32','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_last_request','Last Request','','','last_request','Equals','text','32','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_instrument_group','Inst Group','','','instrument_group','ContainsText','text','64','','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text, "options" text );
INSERT INTO detail_report_hotlinks VALUES(1,'batches','link_list','batches','requested_run_batch/show/','valueCol','dl_batches','');
INSERT INTO detail_report_hotlinks VALUES(2,'requests','link_list','requests','requested_run/show/','valueCol','dl_requests','');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO form_fields VALUES(1,'id','Batch Group ID','non-edit','','','','','','trim');
INSERT INTO form_fields VALUES(2,'name','Batch Group Name','text','50','50','','','','trim|max_length[50]');
INSERT INTO form_fields VALUES(3,'description','Description','area','','','2','60','','trim|max_length[256]');
INSERT INTO form_fields VALUES(4,'requested_run_batch_list','Batch IDs','area','','','4','60','','trim');
INSERT INTO form_fields VALUES(5,'owner_username','Owner','text','50','64','','','','trim|required|max_length[64]');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'id','id','int','output','','add_update_requested_run_batch_group');
INSERT INTO sproc_args VALUES(2,'name','name','varchar','input','50','add_update_requested_run_batch_group');
INSERT INTO sproc_args VALUES(3,'description','description','varchar','input','256','add_update_requested_run_batch_group');
INSERT INTO sproc_args VALUES(4,'requested_run_batch_list','requestedRunBatchList','varchar','input','2147483647','add_update_requested_run_batch_group');
INSERT INTO sproc_args VALUES(5,'owner_username','ownerUsername','varchar','input','64','add_update_requested_run_batch_group');
INSERT INTO sproc_args VALUES(6,'<local>','mode','varchar','input','12','add_update_requested_run_batch_group');
INSERT INTO sproc_args VALUES(7,'<local>','message','varchar','output','512','add_update_requested_run_batch_group');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO form_field_choosers VALUES(1,'requested_run_batch_list','list-report.helper','','helper_requested_run_batch_ckbx/report','',',','');
INSERT INTO form_field_choosers VALUES(2,'owner_username','picker.replace','userUsernamePickList','','',',','');
COMMIT;
