PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','T_Run_Tracking');
INSERT INTO general_params VALUES('list_report_data_table','v_run_tracking_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_col','time_start');
INSERT INTO general_params VALUES('list_report_data_sort_dir','Desc');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_instrument','Instrument','20','','instrument','ContainsText','text','24','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_year','Year','20','','year','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_month','Month','20','','month','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_day','Day','20','','day','Equals','text','20','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_dataset','Dataset','40','','dataset','ContainsTextTPO','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(2,'interval','invoke_entity','id','run_interval/edit','{"GreaterOrEqual":"180"}');
INSERT INTO list_report_hotlinks VALUES(3,'dataset','select_case','dataset_type','','{"Regular":"dataset","Tracking":"tracking_dataset"}');
INSERT INTO list_report_hotlinks VALUES(4,'dataset_type','no_display','value','','');
CREATE TABLE primary_filter_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text );
INSERT INTO primary_filter_choosers VALUES(1,'pf_instrument','picker.replace','instrumentNamePickList','','',',');
COMMIT;
