PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','T_Sample_Labelling_Reporter_Ions');
INSERT INTO general_params VALUES('list_report_data_table','v_sample_label_reporter_ions_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_col','label, channel');
INSERT INTO general_params VALUES('list_report_data_sort_dir','Asc');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_Label','Label','15!','','label','ContainsText','text','64','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_Channel','Channel','10!','','channel','Equals','text','22','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_Tag_Name','Tag','15!','','tag_name','ContainsText','text','64','','');
COMMIT;
