PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','T_Sample_Submission');
INSERT INTO general_params VALUES('list_report_data_table','v_sample_submission_list_report');
INSERT INTO general_params VALUES('detail_report_data_table','v_sample_submission_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','id');
INSERT INTO general_params VALUES('entry_page_data_table','v_sample_submission_entry');
INSERT INTO general_params VALUES('entry_page_data_id_col','id');
INSERT INTO general_params VALUES('entry_sproc','add_update_sample_submission');
INSERT INTO general_params VALUES('post_submission_detail_id','id');
INSERT INTO general_params VALUES('operations_sproc','do_sample_submission_operation');
INSERT INTO general_params VALUES('list_report_data_sort_col','id');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('detail_report_cmds','file_attachment_cmds');
INSERT INTO general_params VALUES('detail_report_data_id_type','integer');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'id','invoke_entity','value','sample_submission/show/','');
INSERT INTO list_report_hotlinks VALUES(2,'campaign','invoke_entity','campaign','campaign/show','');
INSERT INTO list_report_hotlinks VALUES(3,'container_list','link_list','value','material_container/show','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'id','id','int','output','','add_update_sample_submission');
INSERT INTO sproc_args VALUES(2,'campaign','Campaign','varchar','input','64','add_update_sample_submission');
INSERT INTO sproc_args VALUES(3,'received_by','ReceivedBy','varchar','input','64','add_update_sample_submission');
INSERT INTO sproc_args VALUES(4,'container_list','ContainerList','varchar','output','1024','add_update_sample_submission');
INSERT INTO sproc_args VALUES(5,'new_container_comment','NewContainerComment','varchar','input','1024','add_update_sample_submission');
INSERT INTO sproc_args VALUES(6,'description','Description','varchar','input','4096','add_update_sample_submission');
INSERT INTO sproc_args VALUES(7,'<local>','mode','varchar','input','12','add_update_sample_submission');
INSERT INTO sproc_args VALUES(8,'<local>','message','varchar','output','512','add_update_sample_submission');
INSERT INTO sproc_args VALUES(9,'<local>','callingUser','varchar','input','128','add_update_sample_submission');
INSERT INTO sproc_args VALUES(10,'id','id','int','input','','do_sample_submission_operation');
INSERT INTO sproc_args VALUES(11,'<local>','mode','varchar','input','12','do_sample_submission_operation');
INSERT INTO sproc_args VALUES(12,'<local>','message','varchar','output','512','do_sample_submission_operation');
INSERT INTO sproc_args VALUES(13,'<local>','callingUser','varchar','input','128','do_sample_submission_operation');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO form_fields VALUES(1,'id','ID','non-edit','','','','','0','trim');
INSERT INTO form_fields VALUES(2,'campaign','Campaign','text','90','64','','','','trim|max_length[64]');
INSERT INTO form_fields VALUES(3,'received_by','Received By','text','50','64','','','','trim|max_length[64]');
INSERT INTO form_fields VALUES(4,'container_list','Container List','area','','','2','70','','trim|max_length[1024]');
INSERT INTO form_fields VALUES(5,'new_container_comment','New Container Comment','area','','','2','70','','trim|max_length[1024]');
INSERT INTO form_fields VALUES(6,'description','Description','area','','','10','70','','trim|max_length[4096]');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO form_field_choosers VALUES(1,'container_list','list-report.helper','','helper_material_container_ckbx/report','',',','Choose current container...');
INSERT INTO form_field_choosers VALUES(2,'container_list','list-report.helper','','helper_material_location_available_ckbx/report','',',','Make new container...');
INSERT INTO form_field_choosers VALUES(3,'received_by','picker.replace','userUsernamePickList','','',',','');
INSERT INTO form_field_choosers VALUES(4,'campaign','list-report.helper','','helper_campaign/report/Active/','',',','campaign');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO detail_report_hotlinks VALUES(1,'container_list','link_list','container_list','material_container/show','valueCol','dl_container_list',NULL);
INSERT INTO detail_report_hotlinks VALUES(3,'campaign','detail-report','campaign','campaign/show','valueCol','dl_campaign',NULL);
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_campaign','Campaign','20','','campaign','ContainsText','text','64','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_received_by','Received_By','20','','received_by','ContainsText','text','103','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_description','Description','20','','description','ContainsText','text','4096','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_container_list','Container_List','20','','container_list','ContainsText','text','1024','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_id','ID','20','','id','Equals','text','20','','');
CREATE TABLE form_field_options ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "parameter" text );
INSERT INTO form_field_options VALUES(1,'new_container_comment','hide','update');
CREATE TABLE detail_report_commands ( id INTEGER PRIMARY KEY,  "name" text, "Type" text, "Command" text, "Target" text, "Tooltip" text, "Prompt" text );
INSERT INTO detail_report_commands VALUES(1,'Create Biomaterial','copy_from','','biomaterial','Go to biomaterial entry page and copy information from this sample submission.','');
COMMIT;
