PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_sample_prep_request_assignment');
INSERT INTO general_params VALUES('list_report_data_sort_col','id');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('list_report_cmds','sample_prep_request_assignment_cmds');
INSERT INTO general_params VALUES('list_report_cmds_url','/sample_prep_request_assignment/operation');
INSERT INTO general_params VALUES('operations_sproc','UpdateSampleRequestAssignments');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_name','Name','32','','name','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_state','State','32','','state_id','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_requester','Requester','32','','requester','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_comment','Comment','32','','comment','ContainsText','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'sel','CHECKBOX','id','','');
INSERT INTO list_report_hotlinks VALUES(3,'days_in_queue','color_label','days_in_queue_bin','','{"30":"clr_30","60":"clr_60","90":"clr_90","120":"clr_120"}');
INSERT INTO list_report_hotlinks VALUES(4,'id','invoke_entity','id','sample_prep_request/show/','');
INSERT INTO list_report_hotlinks VALUES(5,'prep_method','min_col_width','value','60','');
INSERT INTO list_report_hotlinks VALUES(6,'comment','min_col_width','value','75','');
INSERT INTO list_report_hotlinks VALUES(7,'reason','min_col_width','value','75','');
INSERT INTO list_report_hotlinks VALUES(8,'days_in_queue_bin','no_display','value','','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'<local>','mode','varchar','input','32','UpdateSampleRequestAssignments');
INSERT INTO sproc_args VALUES(2,'newValue','newValue','varchar','input','512','UpdateSampleRequestAssignments');
INSERT INTO sproc_args VALUES(3,'reqIDList','reqIDList','varchar','input','2048','UpdateSampleRequestAssignments');
COMMIT;
