PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_service_center_use_list_report');
INSERT INTO general_params VALUES('detail_report_data_table','v_service_center_use_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','id');
INSERT INTO general_params VALUES('detail_report_data_id_type','integer');
INSERT INTO general_params VALUES('entry_page_data_table','v_service_center_use_entry');
INSERT INTO general_params VALUES('entry_page_data_id_col','id');
INSERT INTO general_params VALUES('entry_sproc','update_service_use');
INSERT INTO general_params VALUES('list_report_data_sort_col','report_id, dataset_id');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('post_submission_detail_id','id');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'entry_id','invoke_entity','value','service_center_use/show/','');
INSERT INTO list_report_hotlinks VALUES(2,'dataset_id','invoke_entity','value','datasetid/show/','');
INSERT INTO list_report_hotlinks VALUES(3,'service_type_id','invoke_entity','value','service_center_use_type/report/','');
INSERT INTO list_report_hotlinks VALUES(4,'report_id','invoke_entity','no_value','service_center_use_report/report/-/-/-','');
INSERT INTO list_report_hotlinks VALUES(5,'charge_code','invoke_entity','value','charge_code/show/','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_report_id','Report ID','6!','','report_id','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_entry_id','Entry ID','8!','','entry_id','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_dataset_id','Dataset ID','8!','','dataset_id','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_instrument','Instrument','20!','','instrument','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_charge_code','Charge Code','','','charge_code','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_service_type_id','Service Type ID','6!','','service_type_id','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_service_type','Service Type','20!','','service_type','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(8,'pf_comment','Comment','30!','','comment','ContainsText','text','','','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text, "options" text );
INSERT INTO detail_report_hotlinks VALUES(1,'report_id','detail-report','report_id','service_center_use/report','valueCol','','');
INSERT INTO detail_report_hotlinks VALUES(2,'+report_id','detail-report','report_id','service_center_use_report/report','labelCol','','');
INSERT INTO detail_report_hotlinks VALUES(3,'dataset_id','detail-report','dataset_id','datasetid/show/','labelCol','','');
INSERT INTO detail_report_hotlinks VALUES(4,'request_id','detail-report','request_id','requested_run/show/','labelCol','','');
INSERT INTO detail_report_hotlinks VALUES(5,'charge_code','detail-report','charge_code','charge_code/show/','labelCol','','');
INSERT INTO detail_report_hotlinks VALUES(6,'service_type_id','detail-report','service_type_id','service_center_use_type/report/','labelCol','','');
INSERT INTO detail_report_hotlinks VALUES(7,'requestor_employee_id','detail-report','requestor_employee_id','user/show/','labelCol','','');
INSERT INTO detail_report_hotlinks VALUES(8,'instrument','detail-report','instrument','instrument/show/','labelCol','','');
INSERT INTO detail_report_hotlinks VALUES(9,'dataset_rating','detail-report','','dataset_rating/report/-/-/-','labelCol','','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'id','entryID','int','input','','update_service_use');
INSERT INTO sproc_args VALUES(2,'charge_code','chargeCode','varchar','input','64','update_service_use');
INSERT INTO sproc_args VALUES(3,'service_type_id','serviceTypeID','int','input','','update_service_use');
INSERT INTO sproc_args VALUES(4,'comment','comment','varchar','input','512','update_service_use');
INSERT INTO sproc_args VALUES(5,'<local>','mode','varchar','input','128','update_service_use');
INSERT INTO sproc_args VALUES(6,'<local>','message','varchar','output','512','update_service_use');
INSERT INTO sproc_args VALUES(7,'<local>','callingUser','varchar','input','128','update_service_use');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO form_fields VALUES(1,'id','Entry ID','non-edit','12','24','','','','trim');
INSERT INTO form_fields VALUES(2,'dataset_id','Dataset ID','non-edit','12','24','','','','trim');
INSERT INTO form_fields VALUES(3,'charge_code','Charge Code','text','15','50','','','','trim|required|max_length[64]');
INSERT INTO form_fields VALUES(4,'service_type_id','Service Type ID','text','12','24','','','','trim|required');
INSERT INTO form_fields VALUES(5,'comment','Comment','area','','','4','70','','trim|max_length[512]');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO form_field_choosers VALUES(1,'charge_code','list-report.helper','','helper_charge_code/report','',',','');
INSERT INTO form_field_choosers VALUES(2,'service_type_id','picker.replace','serviceTypePickList','','',',','');
COMMIT;
