PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_service_center_use_admin_report');
INSERT INTO general_params VALUES('list_report_data_sort_col','entry_id');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('list_report_data_cols','entry_id AS Sel, dataset_id, instrument, charge_code, service_type_id, service_type, transaction_date, transaction_units, is_held, comment, dataset_rating, report_id, report_state_id, dataset_svc_center_state');
INSERT INTO general_params VALUES('list_report_cmds','service_center_use_admin_cmds');
INSERT INTO general_params VALUES('list_report_cmds_url','service_center_use_admin_cmds/operation');
INSERT INTO general_params VALUES('operations_sproc','update_service_use_entries');
INSERT INTO general_params VALUES('update_comment_sproc','update_service_use_comment');
INSERT INTO general_params VALUES('update_wp_sproc','update_service_use_wp');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'textTofind','textTofind','varchar','input','2000','update_service_use_comment');
INSERT INTO sproc_args VALUES(2,'replacementText','replacementText','varchar','input','2000','update_service_use_comment');
INSERT INTO sproc_args VALUES(3,'entryIdList','entryIdList','varchar','input','2147483647','update_service_use_comment');
INSERT INTO sproc_args VALUES(4,'<local>','message','varchar','output','512','update_service_use_comment');
INSERT INTO sproc_args VALUES(5,'<local>','callingUser','varchar','input','128','update_service_use_comment');
INSERT INTO sproc_args VALUES(6,'oldWorkPackage','oldWorkPackage','varchar','input','50','update_service_use_wp');
INSERT INTO sproc_args VALUES(7,'newWorkPackage','newWorkPackage','varchar','input','50','update_service_use_wp');
INSERT INTO sproc_args VALUES(8,'entryIdList','entryIdList','varchar','input','2147483647','update_service_use_wp');
INSERT INTO sproc_args VALUES(9,'<local>','message','varchar','output','512','update_service_use_wp');
INSERT INTO sproc_args VALUES(10,'<local>','callingUser','varchar','input','128','update_service_use_wp');
INSERT INTO sproc_args VALUES(11,'<local>','mode','varchar','input','32','update_service_use_entries');
INSERT INTO sproc_args VALUES(12,'param','newValue','varchar','input','512','update_service_use_entries');
INSERT INTO sproc_args VALUES(13,'id','entryIDList','varchar','input','2147483647','update_service_use_entries');
INSERT INTO sproc_args VALUES(14,'<local>','message','varchar','output','512','update_service_use_entries');
INSERT INTO sproc_args VALUES(15,'<local>','callingUser','varchar','input','128','update_service_use_entries');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'sel','CHECKBOX','value','','');
INSERT INTO list_report_hotlinks VALUES(2,'dataset_id','invoke_entity','value','datasetid/show','');
INSERT INTO list_report_hotlinks VALUES(3,'+dataset_id','color_label','report_state_id','','{"3":"clr_80", "4":"clr_120"}');
INSERT INTO list_report_hotlinks VALUES(4,'instrument','invoke_entity','value','instrument/show','');
INSERT INTO list_report_hotlinks VALUES(5,'charge_code','invoke_entity','value','charge_code/show','');
INSERT INTO list_report_hotlinks VALUES(6,'service_type_id','invoke_entity','value','service_center_use_type/report/@/-/-','');
INSERT INTO list_report_hotlinks VALUES(7,'report_id','invoke_entity','value','service_center_use_report/report/@/-/-','');
INSERT INTO list_report_hotlinks VALUES(8,'+report_id','color_label','report_state_id','','{"1":"clr_30", "2":"clr_30", "3":"clr_80", "4":"clr_120"}');
INSERT INTO list_report_hotlinks VALUES(9,'report_state_id','no_display','value','','');
INSERT INTO list_report_hotlinks VALUES(10,'dataset_svc_center_state','color_label','value','','{"Need to refund to service center":"violet_background", "Refunded to service center":"violet_background"}');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_report_id','Report ID','6!','','report_id','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_dataset_id','Dataset ID','8!','','dataset_id','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_instrument','Instrument','20!','','instrument','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_charge_code','Charge Code','','','charge_code','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_service_type_id','Service Type ID','6!','','service_type_id','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_service_type','Service Type','20!','','service_type','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_comment','Comment','40!','','comment','ContainsText','text','','','');
COMMIT;
