PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_service_center_use_admin_report');
INSERT INTO general_params VALUES('list_report_data_sort_col','entry_id');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('list_report_data_cols','entry_id AS Sel, dataset_id, instrument, charge_code, service_type_id, service_type, transaction_date, transaction_units, is_held, comment, dataset_rating, report_id');
INSERT INTO general_params VALUES('list_report_cmds','service_center_use_admin_cmds');
INSERT INTO general_params VALUES('list_report_cmds_url','service_center_use_admin_cmds/operation');
INSERT INTO general_params VALUES('operations_sproc','update_service_use_entries');
INSERT INTO general_params VALUES('update_comment_sproc','update_service_use_comment');
INSERT INTO general_params VALUES('update_wp_sproc','update_service_use_wp');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'TextTofind','textTofind','varchar','input','2000','update_comment_sproc');
INSERT INTO sproc_args VALUES(2,'ReplacementText','replacementText','varchar','input','2000','update_comment_sproc');
INSERT INTO sproc_args VALUES(3,'EntryIdList','entryIdList','varchar','input','2147483647','update_comment_sproc');
INSERT INTO sproc_args VALUES(4,'<local>','message','varchar','output','512','update_comment_sproc');
INSERT INTO sproc_args VALUES(5,'<local>','callingUser','varchar','input','128','update_comment_sproc');
INSERT INTO sproc_args VALUES(6,'OldWorkPackage','oldWorkPackage','varchar','input','50','update_wp_sproc');
INSERT INTO sproc_args VALUES(7,'NewWorkPackage','newWorkPackage','varchar','input','50','update_wp_sproc');
INSERT INTO sproc_args VALUES(8,'EntryIdList','entryIdList','varchar','input','2147483647','update_wp_sproc');
INSERT INTO sproc_args VALUES(9,'<local>','message','varchar','output','512','update_wp_sproc');
INSERT INTO sproc_args VALUES(10,'<local>','callingUser','varchar','input','128','update_wp_sproc');
INSERT INTO sproc_args VALUES(11,'<local>','mode','varchar','input','32','update_service_use_entries');
INSERT INTO sproc_args VALUES(12,'param','newValue','varchar','input','512','update_service_use_entries');
INSERT INTO sproc_args VALUES(13,'id','entryIDList','varchar','input','2147483647','update_service_use_entries');
INSERT INTO sproc_args VALUES(14,'<local>','message','varchar','output','512','update_service_use_entries');
INSERT INTO sproc_args VALUES(15,'<local>','callingUser','varchar','input','128','update_service_use_entries');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'sel','CHECKBOX','value','','');
INSERT INTO list_report_hotlinks VALUES(2,'dataset_id','invoke_entity','value','datasetid/show','');
INSERT INTO list_report_hotlinks VALUES(3,'instrument','invoke_entity','value','instrument/show','');
INSERT INTO list_report_hotlinks VALUES(4,'charge_code','invoke_entity','value','charge_code/show','');
INSERT INTO list_report_hotlinks VALUES(5,'service_type_id','invoke_entity','value','service_center_use_type/report/@/-/-','');
INSERT INTO list_report_hotlinks VALUES(6,'report_id','invoke_entity','value','service_center_use_report/report/@/-/-','');
COMMIT;
