PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_dataset_qc_metrics');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('list_report_data_sort_col','dataset_id');
INSERT INTO general_params VALUES('detail_report_data_table','v_dataset_qc_metrics_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','dataset_id');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'instrument','literal_link','value','https://prismsupport.pnl.gov/smaqc/index.php/smaqc/instrument/','');
INSERT INTO list_report_hotlinks VALUES(2,'dataset','invoke_entity','value','dataset/show/','');
INSERT INTO list_report_hotlinks VALUES(3,'dataset_id','invoke_entity','value','smaqc/show/','');
INSERT INTO list_report_hotlinks VALUES(4,'amts_10pct_fdr','column_tooltip','value','Number of LC-MS features','');
INSERT INTO list_report_hotlinks VALUES(5,'c_1a','column_tooltip','value','Fraction of peptides identified more than 4 minutes earlier than the chromatographic peak apex','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(6,'c_1b','column_tooltip','value','Fraction of peptides identified more than 4 minutes later than the chromatographic peak apex','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(7,'c_2a','column_tooltip','value','Time period over which 50% of peptides are identified','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(8,'c_2b','column_tooltip','value','Rate of peptide identification during C-2A (peptides/minute)','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(9,'c_3a','column_tooltip','value','Median peak width for all peptides (seconds)','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(10,'c_3b','column_tooltip','value','Median peak width during middle 50% of separation (seconds)','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(11,'c_4a','column_tooltip','value','Median peak width during first 10% of separation (seconds)','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(12,'c_4b','column_tooltip','value','Median peak width during last 10% of separation (seconds)','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(13,'c_4c','column_tooltip','value','Median peak width during middle 10% of separation (seconds)','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(14,'ds_1a','column_tooltip','value','Count of peptides with one spectrum / count of peptides with two spectra','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(15,'ds_1b','column_tooltip','value','Count of peptides with two spectra / count of peptides with three spectra','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(16,'ds_2a','column_tooltip','value','Number of MS1 scans taken over middle 50% of separation','');
INSERT INTO list_report_hotlinks VALUES(17,'ds_2b','column_tooltip','value','Number of MS2 scans taken over middle 50% of separation','');
INSERT INTO list_report_hotlinks VALUES(18,'ds_3a','column_tooltip','value','Median of MS1 max / MS1 sampled abundance','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(19,'ds_3b','column_tooltip','value','Median of MS1 max / MS1 sampled abundance; limit to bottom 50% of peptides by abundance','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(20,'is_1a','column_tooltip','value','Occurrences of MS1 jumping >10x','');
INSERT INTO list_report_hotlinks VALUES(21,'is_1b','column_tooltip','value','Occurrences of MS1 falling >10x','');
INSERT INTO list_report_hotlinks VALUES(22,'is_2','column_tooltip','value','Median precursor m/z for all peptides','{"Decimals":"1"}');
INSERT INTO list_report_hotlinks VALUES(23,'is_3a','column_tooltip','value','Count of 1+ peptides / count of 2+ peptides','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(24,'is_3b','column_tooltip','value','Count of 3+ peptides / count of 2+ peptides','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(25,'is_3c','column_tooltip','value','Count of 4+ peptides / count of 2+ peptides','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(26,'keratin_2a','column_tooltip','value','Number of keratin peptides (full or partial trypsin); total spectra count','');
INSERT INTO list_report_hotlinks VALUES(27,'keratin_2c','column_tooltip','value','Number of keratin peptides (full or partial trypsin); unique peptide count','');
INSERT INTO list_report_hotlinks VALUES(28,'mass_error_ppm','column_tooltip','value','Either a duplicate of MS1_5C, or the value reported by DTA_Refinery before refinement','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(29,'mass_error_ppm_refined','column_tooltip','value','Computed by DTA_Refinery after refinement','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(30,'mass_error_ppm_viper','column_tooltip','value','Median of the precursor mass error (ppm)','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(31,'ms1_1','column_tooltip','value','Median MS1 ion injection time','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(32,'ms1_2a','column_tooltip','value','Median S/N value for MS1 spectra from run start through middle 50% of separation','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(33,'ms1_2b','column_tooltip','value','Median TIC value for identified peptides from run start through middle 50% of separation','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(34,'ms1_3a','column_tooltip','value','Dynamic range estimate using 95th percentile peptide peak apex intensity / 5th percentile','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(35,'ms1_3b','column_tooltip','value','Median peak apex intensity for all peptides','{"Decimals":"0"}');
INSERT INTO list_report_hotlinks VALUES(36,'ms1_5a','column_tooltip','value','Median of precursor mass error (Th)','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(37,'ms1_5b','column_tooltip','value','Median of absolute value of precursor mass error (Th)','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(38,'ms1_5c','column_tooltip','value','Median of precursor mass error (ppm)','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(39,'ms1_5d','column_tooltip','value','Interquartile distance in ppm-based precursor mass error','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(40,'ms1_count','column_tooltip','value','Number of MS spectra collected','');
INSERT INTO list_report_hotlinks VALUES(41,'ms1_density_q1','column_tooltip','value','25%ile of MS scan peak counts','');
INSERT INTO list_report_hotlinks VALUES(42,'ms1_density_q2','column_tooltip','value','50%ile of MS scan peak counts','');
INSERT INTO list_report_hotlinks VALUES(43,'ms1_density_q3','column_tooltip','value','75%ile of MS scan peak counts','');
INSERT INTO list_report_hotlinks VALUES(44,'ms1_freq_max','column_tooltip','value','Fastest frequency for MS collection in any minute (Hz)','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(45,'ms1_tic_change_q2','column_tooltip','value','The log ratio for 50%ile of TIC changes over 25%ile of TIC changes','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(46,'ms1_tic_change_q3','column_tooltip','value','The log ratio for 75%ile of TIC changes over 50%ile of TIC changes','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(47,'ms1_tic_change_q4','column_tooltip','value','The log ratio for largest TIC change over 75%ile of TIC changes','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(48,'ms1_tic_q2','column_tooltip','value','The log ratio for 50%ile of TIC over 25%ile of TIC','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(49,'ms1_tic_q3','column_tooltip','value','The log ratio for 75%ile of TIC over 50%ile of TIC','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(50,'ms1_tic_q4','column_tooltip','value','The log ratio for largest TIC over 75%ile TIC','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(51,'ms2_1','column_tooltip','value','Median MS2 ion injection time (milliseconds)','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(52,'ms2_2','column_tooltip','value','Median S/N value for identified MS2 spectra','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(53,'ms2_3','column_tooltip','value','Median number of peaks in all MS2 spectra','');
INSERT INTO list_report_hotlinks VALUES(54,'ms2_4a','column_tooltip','value','Fraction of all MS2 spectra identified; low abundance quartile (determined using MS1 intensity of identified peptides)','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(55,'ms2_4b','column_tooltip','value','Fraction of all MS2 spectra identified; second quartile (determined using MS1 intensity of identified peptides)','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(56,'ms2_4c','column_tooltip','value','Fraction of all MS2 spectra identified; third quartile (determined using MS1 intensity of identified peptides)','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(57,'ms2_4d','column_tooltip','value','Fraction of all MS2 spectra identified; high abundance quartile (determined using MS1 intensity of identified peptides)','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(58,'ms2_count','column_tooltip','value','Number of MS/MS spectra collected','');
INSERT INTO list_report_hotlinks VALUES(59,'ms2_density_q1','column_tooltip','value','25%ile of MS/MS scan peak counts','');
INSERT INTO list_report_hotlinks VALUES(60,'ms2_density_q2','column_tooltip','value','50%ile of MS/MS scan peak counts','');
INSERT INTO list_report_hotlinks VALUES(61,'ms2_density_q3','column_tooltip','value','75%ile of MS/MS scan peak counts','');
INSERT INTO list_report_hotlinks VALUES(62,'ms2_freq_max','column_tooltip','value','Fastest frequency for MS/MS collection in any minute (Hz)','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(63,'ms2_prec_z_1','column_tooltip','value','Fraction of MS/MS precursors that are singly charged','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(64,'ms2_prec_z_2','column_tooltip','value','Fraction of MS/MS precursors that are doubly charged','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(65,'ms2_prec_z_3','column_tooltip','value','Fraction of MS/MS precursors that are triply charged','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(66,'ms2_prec_z_4','column_tooltip','value','Fraction of MS/MS precursors that are quadruply charged','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(67,'ms2_prec_z_5','column_tooltip','value','Fraction of MS/MS precursors that are quintuply charged','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(68,'ms2_prec_z_likely_1','column_tooltip','value','Fraction of MS/MS precursors lack known charge but look like 1+','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(69,'ms2_prec_z_likely_multi','column_tooltip','value','Fraction of MS/MS precursors lack known charge but look like 2+ or higher','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(70,'ms2_prec_z_more','column_tooltip','value','Fraction of MS/MS precursors that are charged higher than +5','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(71,'p_1a','column_tooltip','value','Median peptide ID score (-Log10(MSGF_SpecProb) or X!Tandem hyperscore)','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(72,'p_1b','column_tooltip','value','Median peptide ID score ( Log10(MSGF_SpecProb) or X!Tandem Peptide_Expectation_Value_Log(e))','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(73,'p_2a','column_tooltip','value','Number of tryptic peptides; total spectra count','');
INSERT INTO list_report_hotlinks VALUES(74,'p_2b','column_tooltip','value','Number of tryptic peptides; unique peptide & charge count','');
INSERT INTO list_report_hotlinks VALUES(75,'p_2c','column_tooltip','value','Number of tryptic peptides; unique peptide count','');
INSERT INTO list_report_hotlinks VALUES(76,'p_3','column_tooltip','value','Ratio of unique semi-tryptic / unique fully tryptic peptides','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(77,'p_4a','column_tooltip','value','Ratio of unique fully tryptic peptides / total unique peptides','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(78,'p_4b','column_tooltip','value','Ratio of total missed cleavages (among unique peptides) / total unique peptides','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(79,'phos_2a','column_tooltip','value','Number of tryptic phosphopeptides; total spectra count','');
INSERT INTO list_report_hotlinks VALUES(80,'phos_2c','column_tooltip','value','Number of tryptic phosphopeptides; unique peptide count','');
INSERT INTO list_report_hotlinks VALUES(81,'qcdm','column_tooltip','value','Overall confidence using model developed by Brett Amidan','');
INSERT INTO list_report_hotlinks VALUES(82,'rt_duration','column_tooltip','value','Highest scan time observed minus the lowest scan time observed, in seconds','{"Decimals":"0"}');
INSERT INTO list_report_hotlinks VALUES(83,'rt_ms_q1','column_tooltip','value','The interval for the first 25% of all MS events divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(84,'rt_ms_q2','column_tooltip','value','The interval for the second 25% of all MS events divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(85,'rt_ms_q3','column_tooltip','value','The interval for the third 25% of all MS events divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(86,'rt_ms_q4','column_tooltip','value','The interval for the fourth 25% of all MS events divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(87,'rt_msms_q1','column_tooltip','value','The interval for the first 25% of all MS/MS events divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(88,'rt_msms_q2','column_tooltip','value','The interval for the second 25% of all MS/MS events divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(89,'rt_msms_q3','column_tooltip','value','The interval for the third 25% of all MS/MS events divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(90,'rt_msms_q4','column_tooltip','value','The interval for the fourth 25% of all MS/MS events divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(91,'rt_tic_q1','column_tooltip','value','The interval when the first 25% of TIC accumulates divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(92,'rt_tic_q2','column_tooltip','value','The interval when the second 25% of TIC accumulates divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(93,'rt_tic_q3','column_tooltip','value','The interval when the third 25% of TIC accumulates divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(94,'rt_tic_q4','column_tooltip','value','The interval when the fourth 25% of TIC accumulates divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(95,'xic_fwhm_q1','column_tooltip','value','25%ile of peak widths for the wide XICs','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(96,'xic_fwhm_q2','column_tooltip','value','50%ile of peak widths for the wide XICs','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(97,'xic_fwhm_q3','column_tooltip','value','75%ile of peak widths for the wide XICs','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(98,'xic_height_q2','column_tooltip','value','The log ratio for 50%ile of wide XIC heights over 25%ile of heights.','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(99,'xic_height_q3','column_tooltip','value','The log ratio for 75%ile of wide XIC heights over 50%ile of heights.','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(100,'xic_height_q4','column_tooltip','value','The log ratio for maximum of wide XIC heights over 75%ile of heights.','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(101,'xic_wide_frac','column_tooltip','value','Fraction of precursor ions accounting for the top half of all peak width','{"Decimals":"3"}');
INSERT INTO list_report_hotlinks VALUES(102,'qcart','column_tooltip','value','Overall confidence using model developed by Allison Thompson and Ryan Butner','');
INSERT INTO list_report_hotlinks VALUES(103,'trypsin_2a','column_tooltip','value','Number of peptides from trypsin; total spectra count','');
INSERT INTO list_report_hotlinks VALUES(104,'trypsin_2c','column_tooltip','value','Number of peptides from trypsin; unique peptide count','');
INSERT INTO list_report_hotlinks VALUES(105,'ms2_rep_ion_all','column_tooltip','value','Number of peptides (PSMs) where all reporter ions were seen','');
INSERT INTO list_report_hotlinks VALUES(106,'ms2_rep_ion_1missing','column_tooltip','value','Number of peptides (PSMs) where all but 1 of the reporter ions were seen','');
INSERT INTO list_report_hotlinks VALUES(107,'ms2_rep_ion_2missing','column_tooltip','value','Number of peptides (PSMs) where all but 2 of the reporter ions were seen','');
INSERT INTO list_report_hotlinks VALUES(108,'ms2_rep_ion_3missing','column_tooltip','value','Number of peptides (PSMs) where all but 3 of the reporter ions were seen','');
INSERT INTO list_report_hotlinks VALUES(109,'quameter_job','invoke_entity','value','capture_jobs/show','');
INSERT INTO list_report_hotlinks VALUES(110,'smaqc_job','invoke_entity','value','analysis_job/show','');
INSERT INTO list_report_hotlinks VALUES(111,'psm_source_job','invoke_entity','value','analysis_job/show','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO detail_report_hotlinks VALUES(1,'smaqc_job','detail-report','smaqc_job','analysis_job/show','labelCol','job',NULL);
INSERT INTO detail_report_hotlinks VALUES(2,'dataset','detail-report','dataset','dataset/show','labelCol','dataset',NULL);
INSERT INTO detail_report_hotlinks VALUES(5,'dataset_folder_path','href-folder','dataset_folder_path','','labelCol','dataset_folder_path',NULL);
INSERT INTO detail_report_hotlinks VALUES(6,'qc_metric_stats','literal_link','qc_metric_stats','','valueCol','smaqc_data',NULL);
INSERT INTO detail_report_hotlinks VALUES(13,'xic_wide_frac','glossary_entry','xic_wide_frac','smaqc_metrics/show/','labelCol','smaqc_xic_widefrac','{"Label":"Fraction of precursor ions accounting for the top half of all peak width"}');
INSERT INTO detail_report_hotlinks VALUES(14,'xic_fwhm_q1','glossary_entry','xic_fwhm_q1','smaqc_metrics/show/','labelCol','smaqc_xic_fwhm_q1','{"Label":"25%ile of peak widths for the wide XICs"}');
INSERT INTO detail_report_hotlinks VALUES(15,'amts_10pct_fdr','glossary_entry','amts_10pct_fdr','smaqc_metrics/show/','labelCol','smaqc_AMTs_10pct_FDR','{"Label":"Number of LC-MS features"}');
INSERT INTO detail_report_hotlinks VALUES(16,'c_1a','glossary_entry','c_1a','smaqc_metrics/show/','labelCol','smaqc_C_1A','{"Label":"Fraction of peptides identified more than 4 minutes earlier than the chromatographic peak apex"}');
INSERT INTO detail_report_hotlinks VALUES(17,'c_1b','glossary_entry','c_1b','smaqc_metrics/show/','labelCol','smaqc_C_1B','{"Label":"Fraction of peptides identified more than 4 minutes later than the chromatographic peak apex"}');
INSERT INTO detail_report_hotlinks VALUES(18,'c_2a','glossary_entry','c_2a','smaqc_metrics/show/','labelCol','smaqc_C_2A','{"Label":"Time period over which 50% of peptides are identified"}');
INSERT INTO detail_report_hotlinks VALUES(19,'c_2b','glossary_entry','c_2b','smaqc_metrics/show/','labelCol','smaqc_C_2B','{"Label":"Rate of peptide identification during C-2A"}');
INSERT INTO detail_report_hotlinks VALUES(20,'c_3a','glossary_entry','c_3a','smaqc_metrics/show/','labelCol','smaqc_C_3A','{"Label":"Median peak width for all peptides"}');
INSERT INTO detail_report_hotlinks VALUES(21,'c_3b','glossary_entry','c_3b','smaqc_metrics/show/','labelCol','smaqc_C_3B','{"Label":"Median peak width during middle 50% of separation"}');
INSERT INTO detail_report_hotlinks VALUES(22,'c_4a','glossary_entry','c_4a','smaqc_metrics/show/','labelCol','smaqc_C_4A','{"Label":"Median peak width during first 10% of separation"}');
INSERT INTO detail_report_hotlinks VALUES(23,'c_4b','glossary_entry','c_4b','smaqc_metrics/show/','labelCol','smaqc_C_4B','{"Label":"Median peak width during last 10% of separation"}');
INSERT INTO detail_report_hotlinks VALUES(24,'c_4c','glossary_entry','c_4c','smaqc_metrics/show/','labelCol','smaqc_C_4C','{"Label":"Median peak width during middle 10% of separation"}');
INSERT INTO detail_report_hotlinks VALUES(25,'ds_1a','glossary_entry','ds_1a','smaqc_metrics/show/','labelCol','smaqc_DS_1A','{"Label":"Count of peptides with one spectrum / count of peptides with two spectra"}');
INSERT INTO detail_report_hotlinks VALUES(26,'ds_1b','glossary_entry','ds_1b','smaqc_metrics/show/','labelCol','smaqc_DS_1B','{"Label":"Count of peptides with two spectra / count of peptides with three spectra"}');
INSERT INTO detail_report_hotlinks VALUES(27,'ds_2a','glossary_entry','ds_2a','smaqc_metrics/show/','labelCol','smaqc_DS_2A','{"Label":"Number of MS1 scans taken over middle 50% of separation"}');
INSERT INTO detail_report_hotlinks VALUES(28,'ds_2b','glossary_entry','ds_2b','smaqc_metrics/show/','labelCol','smaqc_DS_2B','{"Label":"Number of MS2 scans taken over middle 50% of separation"}');
INSERT INTO detail_report_hotlinks VALUES(29,'ds_3a','glossary_entry','ds_3a','smaqc_metrics/show/','labelCol','smaqc_DS_3A','{"Label":"Median of MS1 max / MS1 sampled abundance"}');
INSERT INTO detail_report_hotlinks VALUES(30,'ds_3b','glossary_entry','ds_3b','smaqc_metrics/show/','labelCol','smaqc_DS_3B','{"Label":"Median of MS1 max / MS1 sampled abundance; limit to bottom 50% of peptides by abundance"}');
INSERT INTO detail_report_hotlinks VALUES(31,'is_1a','glossary_entry','is_1a','smaqc_metrics/show/','labelCol','smaqc_IS_1A','{"Label":"Occurrences of MS1 jumping >10x"}');
INSERT INTO detail_report_hotlinks VALUES(32,'is_1b','glossary_entry','is_1b','smaqc_metrics/show/','labelCol','smaqc_IS_1B','{"Label":"Occurrences of MS1 falling >10x"}');
INSERT INTO detail_report_hotlinks VALUES(33,'is_2','glossary_entry','is_2','smaqc_metrics/show/','labelCol','smaqc_IS_2','{"Label":"Median precursor m/z for all peptides"}');
INSERT INTO detail_report_hotlinks VALUES(34,'is_3a','glossary_entry','is_3a','smaqc_metrics/show/','labelCol','smaqc_IS_3A','{"Label":"Count of 1+ peptides / count of 2+ peptides"}');
INSERT INTO detail_report_hotlinks VALUES(35,'is_3b','glossary_entry','is_3b','smaqc_metrics/show/','labelCol','smaqc_IS_3B','{"Label":"Count of 3+ peptides / count of 2+ peptides"}');
INSERT INTO detail_report_hotlinks VALUES(36,'is_3c','glossary_entry','is_3c','smaqc_metrics/show/','labelCol','smaqc_IS_3C','{"Label":"Count of 4+ peptides / count of 2+ peptides"}');
INSERT INTO detail_report_hotlinks VALUES(37,'keratin_2a','glossary_entry','keratin_2a','smaqc_metrics/show/','labelCol','smaqc_Keratin_2A','{"Label":"Number of keratin peptides (full or partial trypsin); total spectra count"}');
INSERT INTO detail_report_hotlinks VALUES(38,'keratin_2c','glossary_entry','keratin_2c','smaqc_metrics/show/','labelCol','smaqc_Keratin_2C','{"Label":"Number of keratin peptides (full or partial trypsin); unique peptide count"}');
INSERT INTO detail_report_hotlinks VALUES(39,'mass_error_ppm','glossary_entry','mass_error_ppm','smaqc_metrics/show/','labelCol','smaqc_MassErrorPPM','{"Label":"Either a duplicate of MS1_5C, or the value reported by DTA_Refinery before refinement"}');
INSERT INTO detail_report_hotlinks VALUES(40,'mass_error_ppm_refined','glossary_entry','mass_error_ppm_refined','smaqc_metrics/show/','labelCol','smaqc_MassErrorPPM_Refined','{"Label":"Computed by DTA_Refinery after refinement"}');
INSERT INTO detail_report_hotlinks VALUES(41,'mass_error_ppm_viper','glossary_entry','mass_error_ppm_viper','smaqc_metrics/show/','labelCol','smaqc_MassErrorPPM_VIPER','{"Label":"Median of the precursor mass error (ppm)"}');
INSERT INTO detail_report_hotlinks VALUES(42,'ms1_1','glossary_entry','ms1_1','smaqc_metrics/show/','labelCol','smaqc_MS1_1','{"Label":"Median MS1 ion injection time"}');
INSERT INTO detail_report_hotlinks VALUES(43,'ms1_2a','glossary_entry','ms1_2a','smaqc_metrics/show/','labelCol','smaqc_MS1_2A','{"Label":"Median S/N value for MS1 spectra from run start through middle 50% of separation"}');
INSERT INTO detail_report_hotlinks VALUES(44,'ms1_2b','glossary_entry','ms1_2b','smaqc_metrics/show/','labelCol','smaqc_MS1_2B','{"Label":"Median TIC value for identified peptides from run start through middle 50% of separation"}');
INSERT INTO detail_report_hotlinks VALUES(45,'ms1_3a','glossary_entry','ms1_3a','smaqc_metrics/show/','labelCol','smaqc_MS1_3A','{"Label":"Dynamic range estimate using 95th percentile peptide peak apex intensity / 5th percentile"}');
INSERT INTO detail_report_hotlinks VALUES(46,'ms1_3b','glossary_entry','ms1_3b','smaqc_metrics/show/','labelCol','smaqc_MS1_3B','{"Label":"Median peak apex intensity for all peptides"}');
INSERT INTO detail_report_hotlinks VALUES(47,'ms1_5a','glossary_entry','ms1_5a','smaqc_metrics/show/','labelCol','smaqc_MS1_5A','{"Label":"Median of precursor mass error (Th)"}');
INSERT INTO detail_report_hotlinks VALUES(48,'ms1_5b','glossary_entry','ms1_5b','smaqc_metrics/show/','labelCol','smaqc_MS1_5B','{"Label":"Median of absolute value of precursor mass error (Th)"}');
INSERT INTO detail_report_hotlinks VALUES(49,'ms1_5c','glossary_entry','ms1_5c','smaqc_metrics/show/','labelCol','smaqc_MS1_5C','{"Label":"Median of precursor mass error (ppm)"}');
INSERT INTO detail_report_hotlinks VALUES(50,'ms1_5d','glossary_entry','ms1_5d','smaqc_metrics/show/','labelCol','smaqc_MS1_5D','{"Label":"Interquartile distance in ppm-based precursor mass error"}');
INSERT INTO detail_report_hotlinks VALUES(51,'ms1_count','glossary_entry','ms1_count','smaqc_metrics/show/','labelCol','smaqc_MS1_Count','{"Label":"Number of MS spectra collected"}');
INSERT INTO detail_report_hotlinks VALUES(52,'ms1_density_q1','glossary_entry','ms1_density_q1','smaqc_metrics/show/','labelCol','smaqc_MS1_Density_Q1','{"Label":"25%ile of MS scan peak counts"}');
INSERT INTO detail_report_hotlinks VALUES(53,'ms1_density_q2','glossary_entry','ms1_density_q2','smaqc_metrics/show/','labelCol','smaqc_MS1_Density_Q2','{"Label":"50%ile of MS scan peak counts"}');
INSERT INTO detail_report_hotlinks VALUES(54,'ms1_density_q3','glossary_entry','ms1_density_q3','smaqc_metrics/show/','labelCol','smaqc_MS1_Density_Q3','{"Label":"75%ile of MS scan peak counts"}');
INSERT INTO detail_report_hotlinks VALUES(55,'ms1_freq_max','glossary_entry','ms1_freq_max','smaqc_metrics/show/','labelCol','smaqc_MS1_Freq_Max','{"Label":"Fastest frequency for MS collection in any minute"}');
INSERT INTO detail_report_hotlinks VALUES(56,'ms1_tic_change_q2','glossary_entry','ms1_tic_change_q2','smaqc_metrics/show/','labelCol','smaqc_MS1_TIC_Change_Q2','{"Label":"The log ratio for 50%ile of TIC changes over 25%ile of TIC changes"}');
INSERT INTO detail_report_hotlinks VALUES(57,'ms1_tic_change_q3','glossary_entry','ms1_tic_change_q3','smaqc_metrics/show/','labelCol','smaqc_MS1_TIC_Change_Q3','{"Label":"The log ratio for 75%ile of TIC changes over 50%ile of TIC changes"}');
INSERT INTO detail_report_hotlinks VALUES(58,'ms1_tic_change_q4','glossary_entry','ms1_tic_change_q4','smaqc_metrics/show/','labelCol','smaqc_MS1_TIC_Change_Q4','{"Label":"The log ratio for largest TIC change over 75%ile of TIC changes"}');
INSERT INTO detail_report_hotlinks VALUES(59,'ms1_tic_q2','glossary_entry','ms1_tic_q2','smaqc_metrics/show/','labelCol','smaqc_MS1_TIC_Q2','{"Label":"The log ratio for 50%ile of TIC over 25%ile of TIC"}');
INSERT INTO detail_report_hotlinks VALUES(60,'ms1_tic_q3','glossary_entry','ms1_tic_q3','smaqc_metrics/show/','labelCol','smaqc_MS1_TIC_Q3','{"Label":"The log ratio for 75%ile of TIC over 50%ile of TIC"}');
INSERT INTO detail_report_hotlinks VALUES(61,'ms1_tic_q4','glossary_entry','ms1_tic_q4','smaqc_metrics/show/','labelCol','smaqc_MS1_TIC_Q4','{"Label":"The log ratio for largest TIC over 75%ile TIC"}');
INSERT INTO detail_report_hotlinks VALUES(62,'ms2_1','glossary_entry','ms2_1','smaqc_metrics/show/','labelCol','smaqc_MS2_1','{"Label":"Median MS2 ion injection time"}');
INSERT INTO detail_report_hotlinks VALUES(63,'ms2_2','glossary_entry','ms2_2','smaqc_metrics/show/','labelCol','smaqc_MS2_2','{"Label":"Median S/N value for identified MS2 spectra"}');
INSERT INTO detail_report_hotlinks VALUES(64,'ms2_3','glossary_entry','ms2_3','smaqc_metrics/show/','labelCol','smaqc_MS2_3','{"Label":"Median number of peaks in all MS2 spectra"}');
INSERT INTO detail_report_hotlinks VALUES(65,'ms2_4a','glossary_entry','ms2_4a','smaqc_metrics/show/','labelCol','smaqc_MS2_4A','{"Label":"Fraction of all MS2 spectra identified; low abundance quartile (determined using MS1 intensity of identified peptides)"}');
INSERT INTO detail_report_hotlinks VALUES(66,'ms2_4b','glossary_entry','ms2_4b','smaqc_metrics/show/','labelCol','smaqc_MS2_4B','{"Label":"Fraction of all MS2 spectra identified; second quartile (determined using MS1 intensity of identified peptides)"}');
INSERT INTO detail_report_hotlinks VALUES(67,'ms2_4c','glossary_entry','ms2_4c','smaqc_metrics/show/','labelCol','smaqc_MS2_4C','{"Label":"Fraction of all MS2 spectra identified; third quartile (determined using MS1 intensity of identified peptides)"}');
INSERT INTO detail_report_hotlinks VALUES(68,'ms2_4d','glossary_entry','ms2_4d','smaqc_metrics/show/','labelCol','smaqc_MS2_4D','{"Label":"Fraction of all MS2 spectra identified; high abundance quartile (determined using MS1 intensity of identified peptides)"}');
INSERT INTO detail_report_hotlinks VALUES(69,'ms2_count','glossary_entry','ms2_count','smaqc_metrics/show/','labelCol','smaqc_MS2_Count','{"Label":"Number of MS/MS spectra collected"}');
INSERT INTO detail_report_hotlinks VALUES(70,'ms2_density_q1','glossary_entry','ms2_density_q1','smaqc_metrics/show/','labelCol','smaqc_MS2_Density_Q1','{"Label":"25%ile of MS/MS scan peak counts"}');
INSERT INTO detail_report_hotlinks VALUES(71,'ms2_density_q2','glossary_entry','ms2_density_q2','smaqc_metrics/show/','labelCol','smaqc_MS2_Density_Q2','{"Label":"50%ile of MS/MS scan peak counts"}');
INSERT INTO detail_report_hotlinks VALUES(72,'ms2_density_q3','glossary_entry','ms2_density_q3','smaqc_metrics/show/','labelCol','smaqc_MS2_Density_Q3','{"Label":"75%ile of MS/MS scan peak counts"}');
INSERT INTO detail_report_hotlinks VALUES(73,'ms2_freq_max','glossary_entry','ms2_freq_max','smaqc_metrics/show/','labelCol','smaqc_MS2_Freq_Max','{"Label":"Fastest frequency for MS/MS collection in any minute"}');
INSERT INTO detail_report_hotlinks VALUES(74,'ms2_prec_z_1','glossary_entry','ms2_prec_z_1','smaqc_metrics/show/','labelCol','smaqc_MS2_PrecZ_1','{"Label":"Fraction of MS/MS precursors that are singly charged"}');
INSERT INTO detail_report_hotlinks VALUES(75,'ms2_prec_z_2','glossary_entry','ms2_prec_z_2','smaqc_metrics/show/','labelCol','smaqc_MS2_PrecZ_2','{"Label":"Fraction of MS/MS precursors that are doubly charged"}');
INSERT INTO detail_report_hotlinks VALUES(76,'ms2_prec_z_3','glossary_entry','ms2_prec_z_3','smaqc_metrics/show/','labelCol','smaqc_MS2_PrecZ_3','{"Label":"Fraction of MS/MS precursors that are triply charged"}');
INSERT INTO detail_report_hotlinks VALUES(77,'ms2_prec_z_4','glossary_entry','ms2_prec_z_4','smaqc_metrics/show/','labelCol','smaqc_MS2_PrecZ_4','{"Label":"Fraction of MS/MS precursors that are quadruply charged"}');
INSERT INTO detail_report_hotlinks VALUES(78,'ms2_prec_z_5','glossary_entry','ms2_prec_z_5','smaqc_metrics/show/','labelCol','smaqc_MS2_PrecZ_5','{"Label":"Fraction of MS/MS precursors that are quintuply charged"}');
INSERT INTO detail_report_hotlinks VALUES(79,'ms2_prec_z_likely_1','glossary_entry','ms2_prec_z_likely_1','smaqc_metrics/show/','labelCol','smaqc_MS2_PrecZ_likely_1','{"Label":"Fraction of MS/MS precursors lack known charge but look like 1+"}');
INSERT INTO detail_report_hotlinks VALUES(80,'ms2_prec_z_likely_multi','glossary_entry','ms2_prec_z_likely_multi','smaqc_metrics/show/','labelCol','smaqc_MS2_PrecZ_likely_multi','{"Label":"Fraction of MS/MS precursors lack known charge but look like 2+ or higher"}');
INSERT INTO detail_report_hotlinks VALUES(81,'ms2_prec_z_more','glossary_entry','ms2_prec_z_more','smaqc_metrics/show/','labelCol','smaqc_MS2_PrecZ_more','{"Label":"Fraction of MS/MS precursors that are charged higher than +5"}');
INSERT INTO detail_report_hotlinks VALUES(82,'p_1a','glossary_entry','p_1a','smaqc_metrics/show/','labelCol','smaqc_P_1A','{"Label":"Median peptide ID score (-Log10(MSGF_SpecProb) or X!Tandem hyperscore)"}');
INSERT INTO detail_report_hotlinks VALUES(83,'p_1b','glossary_entry','p_1b','smaqc_metrics/show/','labelCol','smaqc_P_1B','{"Label":"Median peptide ID score ( Log10(MSGF_SpecProb) or X!Tandem Peptide_Expectation_Value_Log(e))"}');
INSERT INTO detail_report_hotlinks VALUES(84,'p_2a','glossary_entry','p_2a','smaqc_metrics/show/','labelCol','smaqc_P_2A','{"Label":"Number of tryptic peptides; total spectra count"}');
INSERT INTO detail_report_hotlinks VALUES(85,'p_2b','glossary_entry','p_2b','smaqc_metrics/show/','labelCol','smaqc_P_2B','{"Label":"Number of tryptic peptides; unique peptide & charge count"}');
INSERT INTO detail_report_hotlinks VALUES(86,'p_2c','glossary_entry','p_2c','smaqc_metrics/show/','labelCol','smaqc_P_2C','{"Label":"Number of tryptic peptides; unique peptide count"}');
INSERT INTO detail_report_hotlinks VALUES(87,'p_3','glossary_entry','p_3','smaqc_metrics/show/','labelCol','smaqc_P_3','{"Label":"Ratio of unique semi-tryptic / unique fully tryptic peptides"}');
INSERT INTO detail_report_hotlinks VALUES(88,'p_4a','glossary_entry','p_4a','smaqc_metrics/show/','labelCol','smaqc_P_4A','{"Label":"Ratio of unique fully tryptic peptides / total unique peptides"}');
INSERT INTO detail_report_hotlinks VALUES(89,'p_4b','glossary_entry','p_4b','smaqc_metrics/show/','labelCol','smaqc_P_4B','{"Label":"Ratio of total missed cleavages (among unique peptides) / total unique peptides"}');
INSERT INTO detail_report_hotlinks VALUES(90,'phos_2a','glossary_entry','phos_2a','smaqc_metrics/show/','labelCol','smaqc_Phos_2A','{"Label":"Number of tryptic phosphopeptides; total spectra count"}');
INSERT INTO detail_report_hotlinks VALUES(91,'phos_2c','glossary_entry','phos_2c','smaqc_metrics/show/','labelCol','smaqc_Phos_2C','{"Label":"Number of tryptic phosphopeptides; unique peptide count"}');
INSERT INTO detail_report_hotlinks VALUES(92,'qcdm','glossary_entry','qcdm','smaqc_metrics/show/','labelCol','smaqc_QCDM','{"Label":"Overall confidence using model developed by Brett Amidan"}');
INSERT INTO detail_report_hotlinks VALUES(93,'rt_duration','glossary_entry','rt_duration','smaqc_metrics/show/','labelCol','smaqc_RT_Duration','{"Label":"Highest scan time observed minus the lowest scan time observed"}');
INSERT INTO detail_report_hotlinks VALUES(94,'rt_ms_q1','glossary_entry','rt_ms_q1','smaqc_metrics/show/','labelCol','smaqc_RT_MS_Q1','{"Label":"The interval for the first 25% of all MS events divided by RT-Duration"}');
INSERT INTO detail_report_hotlinks VALUES(95,'rt_ms_q2','glossary_entry','rt_ms_q2','smaqc_metrics/show/','labelCol','smaqc_RT_MS_Q2','{"Label":"The interval for the second 25% of all MS events divided by RT-Duration"}');
INSERT INTO detail_report_hotlinks VALUES(96,'rt_ms_q3','glossary_entry','rt_ms_q3','smaqc_metrics/show/','labelCol','smaqc_RT_MS_Q3','{"Label":"The interval for the third 25% of all MS events divided by RT-Duration"}');
INSERT INTO detail_report_hotlinks VALUES(97,'rt_ms_q4','glossary_entry','rt_ms_q4','smaqc_metrics/show/','labelCol','smaqc_RT_MS_Q4','{"Label":"The interval for the fourth 25% of all MS events divided by RT-Duration"}');
INSERT INTO detail_report_hotlinks VALUES(98,'rt_msms_q1','glossary_entry','rt_msms_q1','smaqc_metrics/show/','labelCol','smaqc_RT_MSMS_Q1','{"Label":"The interval for the first 25% of all MS/MS events divided by RT-Duration"}');
INSERT INTO detail_report_hotlinks VALUES(99,'rt_msms_q2','glossary_entry','rt_msms_q2','smaqc_metrics/show/','labelCol','smaqc_RT_MSMS_Q2','{"Label":"The interval for the second 25% of all MS/MS events divided by RT-Duration"}');
INSERT INTO detail_report_hotlinks VALUES(100,'rt_msms_q3','glossary_entry','rt_msms_q3','smaqc_metrics/show/','labelCol','smaqc_RT_MSMS_Q3','{"Label":"The interval for the third 25% of all MS/MS events divided by RT-Duration"}');
INSERT INTO detail_report_hotlinks VALUES(101,'rt_msms_q4','glossary_entry','rt_msms_q4','smaqc_metrics/show/','labelCol','smaqc_RT_MSMS_Q4','{"Label":"The interval for the fourth 25% of all MS/MS events divided by RT-Duration"}');
INSERT INTO detail_report_hotlinks VALUES(102,'rt_tic_q1','glossary_entry','rt_tic_q1','smaqc_metrics/show/','labelCol','smaqc_RT_TIC_Q1','{"Label":"The interval when the first 25% of TIC accumulates divided by RT-Duration"}');
INSERT INTO detail_report_hotlinks VALUES(103,'rt_tic_q2','glossary_entry','rt_tic_q2','smaqc_metrics/show/','labelCol','smaqc_RT_TIC_Q2','{"Label":"The interval when the second 25% of TIC accumulates divided by RT-Duration"}');
INSERT INTO detail_report_hotlinks VALUES(104,'rt_tic_q3','glossary_entry','rt_tic_q3','smaqc_metrics/show/','labelCol','smaqc_RT_TIC_Q3','{"Label":"The interval when the third 25% of TIC accumulates divided by RT-Duration"}');
INSERT INTO detail_report_hotlinks VALUES(105,'rt_tic_q4','glossary_entry','rt_tic_q4','smaqc_metrics/show/','labelCol','smaqc_RT_TIC_Q4','{"Label":"The interval when the fourth 25% of TIC accumulates divided by RT-Duration"}');
INSERT INTO detail_report_hotlinks VALUES(106,'xic_fwhm_q2','glossary_entry','xic_fwhm_q2','smaqc_metrics/show/','labelCol','smaqc_XIC_FWHM_Q2','{"Label":"50%ile of peak widths for the wide XICs"}');
INSERT INTO detail_report_hotlinks VALUES(107,'xic_fwhm_q3','glossary_entry','xic_fwhm_q3','smaqc_metrics/show/','labelCol','smaqc_XIC_FWHM_Q3','{"Label":"75%ile of peak widths for the wide XICs"}');
INSERT INTO detail_report_hotlinks VALUES(108,'xic_height_q2','glossary_entry','xic_height_q2','smaqc_metrics/show/','labelCol','smaqc_XIC_Height_Q2','{"Label":"The log ratio for 50%ile of wide XIC heights over 25%ile of heights."}');
INSERT INTO detail_report_hotlinks VALUES(109,'xic_height_q3','glossary_entry','xic_height_q3','smaqc_metrics/show/','labelCol','smaqc_XIC_Height_Q3','{"Label":"The log ratio for 75%ile of wide XIC heights over 50%ile of heights."}');
INSERT INTO detail_report_hotlinks VALUES(110,'xic_height_q4','glossary_entry','xic_height_q4','smaqc_metrics/show/','labelCol','smaqc_XIC_Height_Q4','{"Label":"The log ratio for maximum of wide XIC heights over 75%ile of heights."}');
INSERT INTO detail_report_hotlinks VALUES(111,'trypsin_2a','glossary_entry','trypsin_2a','smaqc_metrics/show/','labelCol','smaqc_Trypsin_2A','{"Label":"Number of peptides from trypsin; total spectra count"}');
INSERT INTO detail_report_hotlinks VALUES(112,'trypsin_2c','glossary_entry','trypsin_2c','smaqc_metrics/show/','labelCol','smaqc_Trypsin_2C','{"Label":"Number of peptides from trypsin; unique peptide count"}');
INSERT INTO detail_report_hotlinks VALUES(113,'ms2_rep_ion_all','glossary_entry','ms2_rep_ion_all','smaqc_metrics/show/','labelCol','smaqc_MS2_RepIon_All','{"Label":"Number of peptides (PSMs) where all reporter ions were seen"}');
INSERT INTO detail_report_hotlinks VALUES(114,'ms2_rep_ion_1missing','glossary_entry','ms2_rep_ion_1missing','smaqc_metrics/show/','labelCol','smaqc_MS2_RepIon_1Missing','{"Label":"Number of peptides (PSMs) where all but 1 of the reporter ions were seen"}');
INSERT INTO detail_report_hotlinks VALUES(115,'ms2_rep_ion_2missing','glossary_entry','ms2_rep_ion_2missing','smaqc_metrics/show/','labelCol','smaqc_MS2_RepIon_2Missing','{"Label":"Number of peptides (PSMs) where all but 2 of the reporter ions were seen"}');
INSERT INTO detail_report_hotlinks VALUES(116,'ms2_rep_ion_3missing','glossary_entry','ms2_rep_ion_3missing','smaqc_metrics/show/','labelCol','smaqc_MS2_RepIon_3Missing','{"Label":"Number of peptides (PSMs) where all but 3 of the reporter ions were seen"}');
INSERT INTO detail_report_hotlinks VALUES(117,'+c_1a','item_list','c_1a','','valueCol','data_c_1a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(118,'+c_1b','item_list','c_1b','','valueCol','data_c_1b','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(119,'+c_2a','item_list','c_2a','','valueCol','data_c_2a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(120,'+c_2b','item_list','c_2b','','valueCol','data_c_2b','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(121,'+c_3a','item_list','c_3a','','valueCol','data_c_3a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(122,'+c_3b','item_list','c_3b','','valueCol','data_c_3b','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(123,'+c_4a','item_list','c_4a','','valueCol','data_c_4a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(124,'+c_4b','item_list','c_4b','','valueCol','data_c_4b','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(125,'+c_4c','item_list','c_4c','','valueCol','data_c_4c','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(126,'+ds_1a','item_list','ds_1a','','valueCol','data_ds_1a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(127,'+ds_1b','item_list','ds_1b','','valueCol','data_ds_1b','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(128,'+ds_2a','item_list','ds_2a','','valueCol','data_ds_2a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(129,'+ds_2b','item_list','ds_2b','','valueCol','data_ds_2b','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(130,'+ds_3a','item_list','ds_3a','','valueCol','data_ds_3a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(131,'+ds_3b','item_list','ds_3b','','valueCol','data_ds_3b','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(132,'+is_1a','item_list','is_1a','','valueCol','data_is_1a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(133,'+is_1b','item_list','is_1b','','valueCol','data_is_1b','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(134,'+is_2','item_list','is_2','','valueCol','data_is_2','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(135,'+is_3a','item_list','is_3a','','valueCol','data_is_3a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(136,'+is_3b','item_list','is_3b','','valueCol','data_is_3b','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(137,'+is_3c','item_list','is_3c','','valueCol','data_is_3c','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(138,'+keratin_2a','item_list','keratin_2a','','valueCol','data_keratin_2a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(139,'+keratin_2c','item_list','keratin_2c','','valueCol','data_keratin_2c','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(140,'+mass_error_ppm','item_list','mass_error_ppm','','valueCol','data_masserrorppm','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(141,'+mass_error_ppm_refined','item_list','mass_error_ppm_refined','','valueCol','data_masserrorppm_refined','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(142,'+mass_error_ppm_viper','item_list','mass_error_ppm_viper','','valueCol','data_masserrorppm_viper','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(143,'+ms1_1','item_list','ms1_1','','valueCol','data_ms1_1','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(144,'+ms1_2a','item_list','ms1_2a','','valueCol','data_ms1_2a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(145,'+ms1_2b','item_list','ms1_2b','','valueCol','data_ms1_2b','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(146,'+ms1_3a','item_list','ms1_3a','','valueCol','data_ms1_3a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(147,'+ms1_3b','item_list','ms1_3b','','valueCol','data_ms1_3b','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(148,'+ms1_5a','item_list','ms1_5a','','valueCol','data_ms1_5a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(149,'+ms1_5b','item_list','ms1_5b','','valueCol','data_ms1_5b','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(150,'+ms1_5c','item_list','ms1_5c','','valueCol','data_ms1_5c','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(151,'+ms1_5d','item_list','ms1_5d','','valueCol','data_ms1_5d','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(152,'+ms1_count','item_list','ms1_count','','valueCol','data_ms1_count','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(153,'+ms1_density_q1','item_list','ms1_density_q1','','valueCol','data_ms1_density_q1','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(154,'+ms1_density_q2','item_list','ms1_density_q2','','valueCol','data_ms1_density_q2','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(155,'+ms1_density_q3','item_list','ms1_density_q3','','valueCol','data_ms1_density_q3','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(156,'+ms1_freq_max','item_list','ms1_freq_max','','valueCol','data_ms1_freq_max','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(157,'+ms1_tic_change_q2','item_list','ms1_tic_change_q2','','valueCol','data_ms1_tic_change_q2','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(158,'+ms1_tic_change_q3','item_list','ms1_tic_change_q3','','valueCol','data_ms1_tic_change_q3','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(159,'+ms1_tic_change_q4','item_list','ms1_tic_change_q4','','valueCol','data_ms1_tic_change_q4','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(160,'+ms1_tic_q2','item_list','ms1_tic_q2','','valueCol','data_ms1_tic_q2','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(161,'+ms1_tic_q3','item_list','ms1_tic_q3','','valueCol','data_ms1_tic_q3','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(162,'+ms1_tic_q4','item_list','ms1_tic_q4','','valueCol','data_ms1_tic_q4','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(163,'+ms2_1','item_list','ms2_1','','valueCol','data_ms2_1','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(164,'+ms2_2','item_list','ms2_2','','valueCol','data_ms2_2','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(165,'+ms2_3','item_list','ms2_3','','valueCol','data_ms2_3','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(166,'+ms2_4a','item_list','ms2_4a','','valueCol','data_ms2_4a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(167,'+ms2_4b','item_list','ms2_4b','','valueCol','data_ms2_4b','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(168,'+ms2_4c','item_list','ms2_4c','','valueCol','data_ms2_4c','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(169,'+ms2_4d','item_list','ms2_4d','','valueCol','data_ms2_4d','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(170,'+ms2_count','item_list','ms2_count','','valueCol','data_ms2_count','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(171,'+ms2_density_q1','item_list','ms2_density_q1','','valueCol','data_ms2_density_q1','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(172,'+ms2_density_q2','item_list','ms2_density_q2','','valueCol','data_ms2_density_q2','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(173,'+ms2_density_q3','item_list','ms2_density_q3','','valueCol','data_ms2_density_q3','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(174,'+ms2_freq_max','item_list','ms2_freq_max','','valueCol','data_ms2_freq_max','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(175,'+ms2_prec_z_1','item_list','ms2_prec_z_1','','valueCol','data_ms2_precz_1','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(176,'+ms2_prec_z_2','item_list','ms2_prec_z_2','','valueCol','data_ms2_precz_2','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(177,'+ms2_prec_z_3','item_list','ms2_prec_z_3','','valueCol','data_ms2_precz_3','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(178,'+ms2_prec_z_4','item_list','ms2_prec_z_4','','valueCol','data_ms2_precz_4','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(179,'+ms2_prec_z_5','item_list','ms2_prec_z_5','','valueCol','data_ms2_precz_5','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(180,'+ms2_prec_z_likely_1','item_list','ms2_prec_z_likely_1','','valueCol','data_ms2_precz_likely_1','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(181,'+ms2_prec_z_likely_multi','item_list','ms2_prec_z_likely_multi','','valueCol','data_ms2_precz_likely_multi','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(182,'+ms2_prec_z_more','item_list','ms2_prec_z_more','','valueCol','data_ms2_precz_more','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(183,'+ms2_rep_ion_1missing','item_list','ms2_rep_ion_1missing','','valueCol','data_ms2_repion_1missing','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(184,'+ms2_rep_ion_2missing','item_list','ms2_rep_ion_2missing','','valueCol','data_ms2_repion_2missing','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(185,'+ms2_rep_ion_3missing','item_list','ms2_rep_ion_3missing','','valueCol','data_ms2_repion_3missing','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(186,'+ms2_rep_ion_all','item_list','ms2_rep_ion_all','','valueCol','data_ms2_repion_all','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(187,'+p_1a','item_list','p_1a','','valueCol','data_p_1a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(188,'+p_1b','item_list','p_1b','','valueCol','data_p_1b','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(189,'+p_2a','item_list','p_2a','','valueCol','data_p_2a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(190,'+p_2b','item_list','p_2b','','valueCol','data_p_2b','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(191,'+p_2c','item_list','p_2c','','valueCol','data_p_2c','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(192,'+p_3','item_list','p_3','','valueCol','data_p_3','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(193,'+p_4a','item_list','p_4a','','valueCol','data_p_4a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(194,'+p_4b','item_list','p_4b','','valueCol','data_p_4b','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(195,'+phos_2a','item_list','phos_2a','','valueCol','data_phos_2a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(196,'+phos_2c','item_list','phos_2c','','valueCol','data_phos_2c','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(197,'+rt_duration','item_list','rt_duration','','valueCol','data_rt_duration','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(198,'+rt_ms_q1','item_list','rt_ms_q1','','valueCol','data_rt_ms_q1','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(199,'+rt_ms_q2','item_list','rt_ms_q2','','valueCol','data_rt_ms_q2','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(200,'+rt_ms_q3','item_list','rt_ms_q3','','valueCol','data_rt_ms_q3','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(201,'+rt_ms_q4','item_list','rt_ms_q4','','valueCol','data_rt_ms_q4','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(202,'+rt_msms_q1','item_list','rt_msms_q1','','valueCol','data_rt_msms_q1','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(203,'+rt_msms_q2','item_list','rt_msms_q2','','valueCol','data_rt_msms_q2','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(204,'+rt_msms_q3','item_list','rt_msms_q3','','valueCol','data_rt_msms_q3','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(205,'+rt_msms_q4','item_list','rt_msms_q4','','valueCol','data_rt_msms_q4','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(206,'+rt_tic_q1','item_list','rt_tic_q1','','valueCol','data_rt_tic_q1','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(207,'+rt_tic_q2','item_list','rt_tic_q2','','valueCol','data_rt_tic_q2','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(208,'+rt_tic_q3','item_list','rt_tic_q3','','valueCol','data_rt_tic_q3','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(209,'+rt_tic_q4','item_list','rt_tic_q4','','valueCol','data_rt_tic_q4','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(210,'+trypsin_2a','item_list','trypsin_2a','','valueCol','data_trypsin_2a','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(211,'+trypsin_2c','item_list','trypsin_2c','','valueCol','data_trypsin_2c','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(212,'+xic_fwhm_q1','item_list','xic_fwhm_q1','','valueCol','data_xic_fwhm_q1','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(213,'+xic_fwhm_q2','item_list','xic_fwhm_q2','','valueCol','data_xic_fwhm_q2','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(214,'+xic_fwhm_q3','item_list','xic_fwhm_q3','','valueCol','data_xic_fwhm_q3','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(215,'+xic_height_q2','item_list','xic_height_q2','','valueCol','data_xic_height_q2','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(216,'+xic_height_q3','item_list','xic_height_q3','','valueCol','data_xic_height_q3','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(217,'+xic_height_q4','item_list','xic_height_q4','','valueCol','data_xic_height_q4','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(218,'+xic_wide_frac','item_list','xic_wide_frac','','valueCol','data_xic_widefrac','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(219,'+qcdm','item_list','qcdm','','valueCol','data_qcdm','{"Widths":"20%,80%"}');
INSERT INTO detail_report_hotlinks VALUES(220,'+qcart','item_list','qcart','','valueCol','data_qcart','{"Widths":"20%,80%"}');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_Instrument_Group','Inst. Group','24','','instrument_group','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_Instrument','Instrument','24','','instrument','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_dataset','Dataset','35!','','dataset','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_most_recent_weeks','Most Recent Weeks','2!','','acq_time_start','MostRecentWeeks','text','20','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_created_after','Created After','8','','acq_time_start','LaterThan','text','20','','');
COMMIT;
