PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_dataset_qc_metric_definitions');
INSERT INTO general_params VALUES('list_report_data_sort_dir','ASC');
INSERT INTO general_params VALUES('list_report_data_sort_col','metric');
INSERT INTO general_params VALUES('detail_report_data_table','v_dataset_qc_metric_definitions');
INSERT INTO general_params VALUES('detail_report_data_id_col','metric');
INSERT INTO general_params VALUES('detail_report_data_cols','metric, short_description, source, category, metric_group, metric_value, units, optimal, purpose, description');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_Metric','Metric','24','','metric','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_Source','Source','24','','source','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_Category','Category','24','','category','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_Description','Description','24','','description','ContainsText','text','','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'metric','invoke_entity','value','smaqc_metrics/show/','');
COMMIT;
