PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('list_report_data_table','V_Dataset_QC_Metrics');
INSERT INTO "general_params" VALUES('list_report_data_sort_dir','DESC');
INSERT INTO "general_params" VALUES('list_report_data_sort_col','Dataset_ID');
INSERT INTO "general_params" VALUES('detail_report_data_table','V_Dataset_QC_Metrics_Detail_Report');
INSERT INTO "general_params" VALUES('detail_report_data_id_col','Dataset_ID');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO "list_report_hotlinks" VALUES(1,'Instrument','literal_link','value','https://prismsupport.pnl.gov/smaqc/index.php/smaqc/instrument/','');
INSERT INTO "list_report_hotlinks" VALUES(2,'Dataset','invoke_entity','value','dataset/show/','');
INSERT INTO "list_report_hotlinks" VALUES(3,'Dataset_ID','invoke_entity','value','smaqc/show/','');
INSERT INTO "list_report_hotlinks" VALUES(4,'AMTs_10pct_FDR','column_tooltip','value','Number of LC-MS features','');
INSERT INTO "list_report_hotlinks" VALUES(5,'C_1A','column_tooltip','value','Fraction of peptides identified more than 4 minutes earlier than the chromatographic peak apex','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(6,'C_1B','column_tooltip','value','Fraction of peptides identified more than 4 minutes later than the chromatographic peak apex','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(7,'C_2A','column_tooltip','value','Time period over which 50% of peptides are identified','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(8,'C_2B','column_tooltip','value','Rate of peptide identification during C-2A (peptides/minute)','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(9,'C_3A','column_tooltip','value','Median peak width for all peptides (seconds)','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(10,'C_3B','column_tooltip','value','Median peak width during middle 50% of separation (seconds)','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(11,'C_4A','column_tooltip','value','Median peak width during first 10% of separation (seconds)','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(12,'C_4B','column_tooltip','value','Median peak width during last 10% of separation (seconds)','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(13,'C_4C','column_tooltip','value','Median peak width during middle 10% of separation (seconds)','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(14,'DS_1A','column_tooltip','value','Count of peptides with one spectrum / count of peptides with two spectra','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(15,'DS_1B','column_tooltip','value','Count of peptides with two spectra / count of peptides with three spectra','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(16,'DS_2A','column_tooltip','value','Number of MS1 scans taken over middle 50% of separation','');
INSERT INTO "list_report_hotlinks" VALUES(17,'DS_2B','column_tooltip','value','Number of MS2 scans taken over middle 50% of separation','');
INSERT INTO "list_report_hotlinks" VALUES(18,'DS_3A','column_tooltip','value','Median of MS1 max / MS1 sampled abundance','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(19,'DS_3B','column_tooltip','value','Median of MS1 max / MS1 sampled abundance; limit to bottom 50% of peptides by abundance','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(20,'IS_1A','column_tooltip','value','Occurrences of MS1 jumping >10x','');
INSERT INTO "list_report_hotlinks" VALUES(21,'IS_1B','column_tooltip','value','Occurrences of MS1 falling >10x','');
INSERT INTO "list_report_hotlinks" VALUES(22,'IS_2','column_tooltip','value','Median precursor m/z for all peptides','{"Decimals":"1"}');
INSERT INTO "list_report_hotlinks" VALUES(23,'IS_3A','column_tooltip','value','Count of 1+ peptides / count of 2+ peptides','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(24,'IS_3B','column_tooltip','value','Count of 3+ peptides / count of 2+ peptides','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(25,'IS_3C','column_tooltip','value','Count of 4+ peptides / count of 2+ peptides','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(26,'Keratin_2A','column_tooltip','value','Number of keratin peptides (full or partial trypsin); total spectra count','');
INSERT INTO "list_report_hotlinks" VALUES(27,'Keratin_2C','column_tooltip','value','Number of keratin peptides (full or partial trypsin); unique peptide count','');
INSERT INTO "list_report_hotlinks" VALUES(28,'MassErrorPPM','column_tooltip','value','Either a duplicate of MS1_5C, or the value reported by DTA_Refinery before refinement','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(29,'MassErrorPPM_Refined','column_tooltip','value','Computed by DTA_Refinery after refinement','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(30,'MassErrorPPM_VIPER','column_tooltip','value','Median of the precursor mass error (ppm)','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(31,'MS1_1','column_tooltip','value','Median MS1 ion injection time','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(32,'MS1_2A','column_tooltip','value','Median S/N value for MS1 spectra from run start through middle 50% of separation','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(33,'MS1_2B','column_tooltip','value','Median TIC value for identified peptides from run start through middle 50% of separation','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(34,'MS1_3A','column_tooltip','value','Dynamic range estimate using 95th percentile peptide peak apex intensity / 5th percentile','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(35,'MS1_3B','column_tooltip','value','Median peak apex intensity for all peptides','{"Decimals":"0"}');
INSERT INTO "list_report_hotlinks" VALUES(36,'MS1_5A','column_tooltip','value','Median of precursor mass error (Th)','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(37,'MS1_5B','column_tooltip','value','Median of absolute value of precursor mass error (Th)','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(38,'MS1_5C','column_tooltip','value','Median of precursor mass error (ppm)','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(39,'MS1_5D','column_tooltip','value','Interquartile distance in ppm-based precursor mass error','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(40,'MS1_Count','column_tooltip','value','Number of MS spectra collected','');
INSERT INTO "list_report_hotlinks" VALUES(41,'MS1_Density_Q1','column_tooltip','value','25%ile of MS scan peak counts','');
INSERT INTO "list_report_hotlinks" VALUES(42,'MS1_Density_Q2','column_tooltip','value','50%ile of MS scan peak counts','');
INSERT INTO "list_report_hotlinks" VALUES(43,'MS1_Density_Q3','column_tooltip','value','75%ile of MS scan peak counts','');
INSERT INTO "list_report_hotlinks" VALUES(44,'MS1_Freq_Max','column_tooltip','value','Fastest frequency for MS collection in any minute (Hz)','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(45,'MS1_TIC_Change_Q2','column_tooltip','value','The log ratio for 50%ile of TIC changes over 25%ile of TIC changes','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(46,'MS1_TIC_Change_Q3','column_tooltip','value','The log ratio for 75%ile of TIC changes over 50%ile of TIC changes','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(47,'MS1_TIC_Change_Q4','column_tooltip','value','The log ratio for largest TIC change over 75%ile of TIC changes','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(48,'MS1_TIC_Q2','column_tooltip','value','The log ratio for 50%ile of TIC over 25%ile of TIC','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(49,'MS1_TIC_Q3','column_tooltip','value','The log ratio for 75%ile of TIC over 50%ile of TIC','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(50,'MS1_TIC_Q4','column_tooltip','value','The log ratio for largest TIC over 75%ile TIC','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(51,'MS2_1','column_tooltip','value','Median MS2 ion injection time (milliseconds)','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(52,'MS2_2','column_tooltip','value','Median S/N value for identified MS2 spectra','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(53,'MS2_3','column_tooltip','value','Median number of peaks in all MS2 spectra','');
INSERT INTO "list_report_hotlinks" VALUES(54,'MS2_4A','column_tooltip','value','Fraction of all MS2 spectra identified; low abundance quartile (determined using MS1 intensity of identified peptides)','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(55,'MS2_4B','column_tooltip','value','Fraction of all MS2 spectra identified; second quartile (determined using MS1 intensity of identified peptides)','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(56,'MS2_4C','column_tooltip','value','Fraction of all MS2 spectra identified; third quartile (determined using MS1 intensity of identified peptides)','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(57,'MS2_4D','column_tooltip','value','Fraction of all MS2 spectra identified; high abundance quartile (determined using MS1 intensity of identified peptides)','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(58,'MS2_Count','column_tooltip','value','Number of MS/MS spectra collected','');
INSERT INTO "list_report_hotlinks" VALUES(59,'MS2_Density_Q1','column_tooltip','value','25%ile of MS/MS scan peak counts','');
INSERT INTO "list_report_hotlinks" VALUES(60,'MS2_Density_Q2','column_tooltip','value','50%ile of MS/MS scan peak counts','');
INSERT INTO "list_report_hotlinks" VALUES(61,'MS2_Density_Q3','column_tooltip','value','75%ile of MS/MS scan peak counts','');
INSERT INTO "list_report_hotlinks" VALUES(62,'MS2_Freq_Max','column_tooltip','value','Fastest frequency for MS/MS collection in any minute (Hz)','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(63,'MS2_PrecZ_1','column_tooltip','value','Fraction of MS/MS precursors that are singly charged','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(64,'MS2_PrecZ_2','column_tooltip','value','Fraction of MS/MS precursors that are doubly charged','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(65,'MS2_PrecZ_3','column_tooltip','value','Fraction of MS/MS precursors that are triply charged','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(66,'MS2_PrecZ_4','column_tooltip','value','Fraction of MS/MS precursors that are quadruply charged','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(67,'MS2_PrecZ_5','column_tooltip','value','Fraction of MS/MS precursors that are quintuply charged','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(68,'MS2_PrecZ_likely_1','column_tooltip','value','Fraction of MS/MS precursors lack known charge but look like 1+','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(69,'MS2_PrecZ_likely_multi','column_tooltip','value','Fraction of MS/MS precursors lack known charge but look like 2+ or higher','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(70,'MS2_PrecZ_more','column_tooltip','value','Fraction of MS/MS precursors that are charged higher than +5','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(71,'P_1A','column_tooltip','value','Median peptide ID score (-Log10(MSGF_SpecProb) or X!Tandem hyperscore)','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(72,'P_1B','column_tooltip','value','Median peptide ID score ( Log10(MSGF_SpecProb) or X!Tandem Peptide_Expectation_Value_Log(e))','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(73,'P_2A','column_tooltip','value','Number of tryptic peptides; total spectra count','');
INSERT INTO "list_report_hotlinks" VALUES(74,'P_2B','column_tooltip','value','Number of tryptic peptides; unique peptide & charge count','');
INSERT INTO "list_report_hotlinks" VALUES(75,'P_2C','column_tooltip','value','Number of tryptic peptides; unique peptide count','');
INSERT INTO "list_report_hotlinks" VALUES(76,'P_3','column_tooltip','value','Ratio of unique semi-tryptic / unique fully tryptic peptides','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(77,'P_4A','column_tooltip','value','Ratio of unique fully tryptic peptides / total unique peptides','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(78,'P_4B','column_tooltip','value','Ratio of total missed cleavages (among unique peptides) / total unique peptides','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(79,'Phos_2A','column_tooltip','value','Number of tryptic phosphopeptides; total spectra count','');
INSERT INTO "list_report_hotlinks" VALUES(80,'Phos_2C','column_tooltip','value','Number of tryptic phosphopeptides; unique peptide count','');
INSERT INTO "list_report_hotlinks" VALUES(81,'QCDM','column_tooltip','value','Overall confidence using model developed by Brett Amidan','');
INSERT INTO "list_report_hotlinks" VALUES(82,'RT_Duration','column_tooltip','value','Highest scan time observed minus the lowest scan time observed, in seconds','{"Decimals":"0"}');
INSERT INTO "list_report_hotlinks" VALUES(83,'RT_MS_Q1','column_tooltip','value','The interval for the first 25% of all MS events divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(84,'RT_MS_Q2','column_tooltip','value','The interval for the second 25% of all MS events divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(85,'RT_MS_Q3','column_tooltip','value','The interval for the third 25% of all MS events divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(86,'RT_MS_Q4','column_tooltip','value','The interval for the fourth 25% of all MS events divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(87,'RT_MSMS_Q1','column_tooltip','value','The interval for the first 25% of all MS/MS events divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(88,'RT_MSMS_Q2','column_tooltip','value','The interval for the second 25% of all MS/MS events divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(89,'RT_MSMS_Q3','column_tooltip','value','The interval for the third 25% of all MS/MS events divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(90,'RT_MSMS_Q4','column_tooltip','value','The interval for the fourth 25% of all MS/MS events divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(91,'RT_TIC_Q1','column_tooltip','value','The interval when the first 25% of TIC accumulates divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(92,'RT_TIC_Q2','column_tooltip','value','The interval when the second 25% of TIC accumulates divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(93,'RT_TIC_Q3','column_tooltip','value','The interval when the third 25% of TIC accumulates divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(94,'RT_TIC_Q4','column_tooltip','value','The interval when the fourth 25% of TIC accumulates divided by RT-Duration','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(95,'XIC_FWHM_Q1','column_tooltip','value','25%ile of peak widths for the wide XICs','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(96,'XIC_FWHM_Q2','column_tooltip','value','50%ile of peak widths for the wide XICs','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(97,'XIC_FWHM_Q3','column_tooltip','value','75%ile of peak widths for the wide XICs','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(98,'XIC_Height_Q2','column_tooltip','value','The log ratio for 50%ile of wide XIC heights over 25%ile of heights.','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(99,'XIC_Height_Q3','column_tooltip','value','The log ratio for 75%ile of wide XIC heights over 50%ile of heights.','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(100,'XIC_Height_Q4','column_tooltip','value','The log ratio for maximum of wide XIC heights over 75%ile of heights.','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(101,'XIC_WideFrac','column_tooltip','value','Fraction of precursor ions accounting for the top half of all peak width','{"Decimals":"3"}');
INSERT INTO "list_report_hotlinks" VALUES(102,'QCART','column_tooltip','value','Overall confidence using model developed by Allison Thompson and Ryan Butner','');
INSERT INTO "list_report_hotlinks" VALUES(103,'Trypsin_2A','column_tooltip','value','Number of peptides from trypsin; total spectra count','');
INSERT INTO "list_report_hotlinks" VALUES(104,'Trypsin_2C','column_tooltip','value','Number of peptides from trypsin; unique peptide count','');
INSERT INTO "list_report_hotlinks" VALUES(105,'MS2_RepIon_All','column_tooltip','value','Number of peptides (PSMs) where all reporter ions were seen','');
INSERT INTO "list_report_hotlinks" VALUES(106,'MS2_RepIon_1Missing','column_tooltip','value','Number of peptides (PSMs) where all but 1 of the reporter ions were seen','');
INSERT INTO "list_report_hotlinks" VALUES(107,'MS2_RepIon_2Missing','column_tooltip','value','Number of peptides (PSMs) where all but 2 of the reporter ions were seen','');
INSERT INTO "list_report_hotlinks" VALUES(108,'MS2_RepIon_3Missing','column_tooltip','value','Number of peptides (PSMs) where all but 3 of the reporter ions were seen','');
INSERT INTO "list_report_hotlinks" VALUES(109,'Quameter_Job','invoke_entity','value','capture_jobs/show','');
INSERT INTO "list_report_hotlinks" VALUES(110,'SMAQC_Job','invoke_entity','value','analysis_job/show','');
INSERT INTO "list_report_hotlinks" VALUES(111,'PSM_Source_Job','invoke_entity','value','analysis_job/show','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO "detail_report_hotlinks" VALUES(1,'SMAQC_Job','detail-report','SMAQC_Job','analysis_job/show','labelCol','job',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(2,'Dataset','detail-report','Dataset','dataset/show','labelCol','dataset',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(5,'Dataset Folder Path','href-folder','Dataset Folder Path','','labelCol','dataset_folder_path',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(6,'QC Metric Stats','literal_link','QC Metric Stats','','valueCol','smaqc_data',NULL);
INSERT INTO "detail_report_hotlinks" VALUES(13,'XIC_WideFrac','glossary_entry','XIC_WideFrac','smaqc_metrics/show/','labelCol','smaqc_xic_widefrac','{"Label":"Fraction of precursor ions accounting for the top half of all peak width"}');
INSERT INTO "detail_report_hotlinks" VALUES(14,'XIC_FWHM_Q1','glossary_entry','XIC_FWHM_Q1','smaqc_metrics/show/','labelCol','smaqc_xic_fwhm_q1','{"Label":"25%ile of peak widths for the wide XICs"}');
INSERT INTO "detail_report_hotlinks" VALUES(15,'AMTs_10pct_FDR','glossary_entry','AMTs_10pct_FDR','smaqc_metrics/show/','labelCol','smaqc_AMTs_10pct_FDR','{"Label":"Number of LC-MS features"}');
INSERT INTO "detail_report_hotlinks" VALUES(16,'C_1A','glossary_entry','C_1A','smaqc_metrics/show/','labelCol','smaqc_C_1A','{"Label":"Fraction of peptides identified more than 4 minutes earlier than the chromatographic peak apex"}');
INSERT INTO "detail_report_hotlinks" VALUES(17,'C_1B','glossary_entry','C_1B','smaqc_metrics/show/','labelCol','smaqc_C_1B','{"Label":"Fraction of peptides identified more than 4 minutes later than the chromatographic peak apex"}');
INSERT INTO "detail_report_hotlinks" VALUES(18,'C_2A','glossary_entry','C_2A','smaqc_metrics/show/','labelCol','smaqc_C_2A','{"Label":"Time period over which 50% of peptides are identified"}');
INSERT INTO "detail_report_hotlinks" VALUES(19,'C_2B','glossary_entry','C_2B','smaqc_metrics/show/','labelCol','smaqc_C_2B','{"Label":"Rate of peptide identification during C-2A"}');
INSERT INTO "detail_report_hotlinks" VALUES(20,'C_3A','glossary_entry','C_3A','smaqc_metrics/show/','labelCol','smaqc_C_3A','{"Label":"Median peak width for all peptides"}');
INSERT INTO "detail_report_hotlinks" VALUES(21,'C_3B','glossary_entry','C_3B','smaqc_metrics/show/','labelCol','smaqc_C_3B','{"Label":"Median peak width during middle 50% of separation"}');
INSERT INTO "detail_report_hotlinks" VALUES(22,'C_4A','glossary_entry','C_4A','smaqc_metrics/show/','labelCol','smaqc_C_4A','{"Label":"Median peak width during first 10% of separation"}');
INSERT INTO "detail_report_hotlinks" VALUES(23,'C_4B','glossary_entry','C_4B','smaqc_metrics/show/','labelCol','smaqc_C_4B','{"Label":"Median peak width during last 10% of separation"}');
INSERT INTO "detail_report_hotlinks" VALUES(24,'C_4C','glossary_entry','C_4C','smaqc_metrics/show/','labelCol','smaqc_C_4C','{"Label":"Median peak width during middle 10% of separation"}');
INSERT INTO "detail_report_hotlinks" VALUES(25,'DS_1A','glossary_entry','DS_1A','smaqc_metrics/show/','labelCol','smaqc_DS_1A','{"Label":"Count of peptides with one spectrum / count of peptides with two spectra"}');
INSERT INTO "detail_report_hotlinks" VALUES(26,'DS_1B','glossary_entry','DS_1B','smaqc_metrics/show/','labelCol','smaqc_DS_1B','{"Label":"Count of peptides with two spectra / count of peptides with three spectra"}');
INSERT INTO "detail_report_hotlinks" VALUES(27,'DS_2A','glossary_entry','DS_2A','smaqc_metrics/show/','labelCol','smaqc_DS_2A','{"Label":"Number of MS1 scans taken over middle 50% of separation"}');
INSERT INTO "detail_report_hotlinks" VALUES(28,'DS_2B','glossary_entry','DS_2B','smaqc_metrics/show/','labelCol','smaqc_DS_2B','{"Label":"Number of MS2 scans taken over middle 50% of separation"}');
INSERT INTO "detail_report_hotlinks" VALUES(29,'DS_3A','glossary_entry','DS_3A','smaqc_metrics/show/','labelCol','smaqc_DS_3A','{"Label":"Median of MS1 max / MS1 sampled abundance"}');
INSERT INTO "detail_report_hotlinks" VALUES(30,'DS_3B','glossary_entry','DS_3B','smaqc_metrics/show/','labelCol','smaqc_DS_3B','{"Label":"Median of MS1 max / MS1 sampled abundance; limit to bottom 50% of peptides by abundance"}');
INSERT INTO "detail_report_hotlinks" VALUES(31,'IS_1A','glossary_entry','IS_1A','smaqc_metrics/show/','labelCol','smaqc_IS_1A','{"Label":"Occurrences of MS1 jumping >10x"}');
INSERT INTO "detail_report_hotlinks" VALUES(32,'IS_1B','glossary_entry','IS_1B','smaqc_metrics/show/','labelCol','smaqc_IS_1B','{"Label":"Occurrences of MS1 falling >10x"}');
INSERT INTO "detail_report_hotlinks" VALUES(33,'IS_2','glossary_entry','IS_2','smaqc_metrics/show/','labelCol','smaqc_IS_2','{"Label":"Median precursor m/z for all peptides"}');
INSERT INTO "detail_report_hotlinks" VALUES(34,'IS_3A','glossary_entry','IS_3A','smaqc_metrics/show/','labelCol','smaqc_IS_3A','{"Label":"Count of 1+ peptides / count of 2+ peptides"}');
INSERT INTO "detail_report_hotlinks" VALUES(35,'IS_3B','glossary_entry','IS_3B','smaqc_metrics/show/','labelCol','smaqc_IS_3B','{"Label":"Count of 3+ peptides / count of 2+ peptides"}');
INSERT INTO "detail_report_hotlinks" VALUES(36,'IS_3C','glossary_entry','IS_3C','smaqc_metrics/show/','labelCol','smaqc_IS_3C','{"Label":"Count of 4+ peptides / count of 2+ peptides"}');
INSERT INTO "detail_report_hotlinks" VALUES(37,'Keratin_2A','glossary_entry','Keratin_2A','smaqc_metrics/show/','labelCol','smaqc_Keratin_2A','{"Label":"Number of keratin peptides (full or partial trypsin); total spectra count"}');
INSERT INTO "detail_report_hotlinks" VALUES(38,'Keratin_2C','glossary_entry','Keratin_2C','smaqc_metrics/show/','labelCol','smaqc_Keratin_2C','{"Label":"Number of keratin peptides (full or partial trypsin); unique peptide count"}');
INSERT INTO "detail_report_hotlinks" VALUES(39,'MassErrorPPM','glossary_entry','MassErrorPPM','smaqc_metrics/show/','labelCol','smaqc_MassErrorPPM','{"Label":"Either a duplicate of MS1_5C, or the value reported by DTA_Refinery before refinement"}');
INSERT INTO "detail_report_hotlinks" VALUES(40,'MassErrorPPM_Refined','glossary_entry','MassErrorPPM_Refined','smaqc_metrics/show/','labelCol','smaqc_MassErrorPPM_Refined','{"Label":"Computed by DTA_Refinery after refinement"}');
INSERT INTO "detail_report_hotlinks" VALUES(41,'MassErrorPPM_VIPER','glossary_entry','MassErrorPPM_VIPER','smaqc_metrics/show/','labelCol','smaqc_MassErrorPPM_VIPER','{"Label":"Median of the precursor mass error (ppm)"}');
INSERT INTO "detail_report_hotlinks" VALUES(42,'MS1_1','glossary_entry','MS1_1','smaqc_metrics/show/','labelCol','smaqc_MS1_1','{"Label":"Median MS1 ion injection time"}');
INSERT INTO "detail_report_hotlinks" VALUES(43,'MS1_2A','glossary_entry','MS1_2A','smaqc_metrics/show/','labelCol','smaqc_MS1_2A','{"Label":"Median S/N value for MS1 spectra from run start through middle 50% of separation"}');
INSERT INTO "detail_report_hotlinks" VALUES(44,'MS1_2B','glossary_entry','MS1_2B','smaqc_metrics/show/','labelCol','smaqc_MS1_2B','{"Label":"Median TIC value for identified peptides from run start through middle 50% of separation"}');
INSERT INTO "detail_report_hotlinks" VALUES(45,'MS1_3A','glossary_entry','MS1_3A','smaqc_metrics/show/','labelCol','smaqc_MS1_3A','{"Label":"Dynamic range estimate using 95th percentile peptide peak apex intensity / 5th percentile"}');
INSERT INTO "detail_report_hotlinks" VALUES(46,'MS1_3B','glossary_entry','MS1_3B','smaqc_metrics/show/','labelCol','smaqc_MS1_3B','{"Label":"Median peak apex intensity for all peptides"}');
INSERT INTO "detail_report_hotlinks" VALUES(47,'MS1_5A','glossary_entry','MS1_5A','smaqc_metrics/show/','labelCol','smaqc_MS1_5A','{"Label":"Median of precursor mass error (Th)"}');
INSERT INTO "detail_report_hotlinks" VALUES(48,'MS1_5B','glossary_entry','MS1_5B','smaqc_metrics/show/','labelCol','smaqc_MS1_5B','{"Label":"Median of absolute value of precursor mass error (Th)"}');
INSERT INTO "detail_report_hotlinks" VALUES(49,'MS1_5C','glossary_entry','MS1_5C','smaqc_metrics/show/','labelCol','smaqc_MS1_5C','{"Label":"Median of precursor mass error (ppm)"}');
INSERT INTO "detail_report_hotlinks" VALUES(50,'MS1_5D','glossary_entry','MS1_5D','smaqc_metrics/show/','labelCol','smaqc_MS1_5D','{"Label":"Interquartile distance in ppm-based precursor mass error"}');
INSERT INTO "detail_report_hotlinks" VALUES(51,'MS1_Count','glossary_entry','MS1_Count','smaqc_metrics/show/','labelCol','smaqc_MS1_Count','{"Label":"Number of MS spectra collected"}');
INSERT INTO "detail_report_hotlinks" VALUES(52,'MS1_Density_Q1','glossary_entry','MS1_Density_Q1','smaqc_metrics/show/','labelCol','smaqc_MS1_Density_Q1','{"Label":"25%ile of MS scan peak counts"}');
INSERT INTO "detail_report_hotlinks" VALUES(53,'MS1_Density_Q2','glossary_entry','MS1_Density_Q2','smaqc_metrics/show/','labelCol','smaqc_MS1_Density_Q2','{"Label":"50%ile of MS scan peak counts"}');
INSERT INTO "detail_report_hotlinks" VALUES(54,'MS1_Density_Q3','glossary_entry','MS1_Density_Q3','smaqc_metrics/show/','labelCol','smaqc_MS1_Density_Q3','{"Label":"75%ile of MS scan peak counts"}');
INSERT INTO "detail_report_hotlinks" VALUES(55,'MS1_Freq_Max','glossary_entry','MS1_Freq_Max','smaqc_metrics/show/','labelCol','smaqc_MS1_Freq_Max','{"Label":"Fastest frequency for MS collection in any minute"}');
INSERT INTO "detail_report_hotlinks" VALUES(56,'MS1_TIC_Change_Q2','glossary_entry','MS1_TIC_Change_Q2','smaqc_metrics/show/','labelCol','smaqc_MS1_TIC_Change_Q2','{"Label":"The log ratio for 50%ile of TIC changes over 25%ile of TIC changes"}');
INSERT INTO "detail_report_hotlinks" VALUES(57,'MS1_TIC_Change_Q3','glossary_entry','MS1_TIC_Change_Q3','smaqc_metrics/show/','labelCol','smaqc_MS1_TIC_Change_Q3','{"Label":"The log ratio for 75%ile of TIC changes over 50%ile of TIC changes"}');
INSERT INTO "detail_report_hotlinks" VALUES(58,'MS1_TIC_Change_Q4','glossary_entry','MS1_TIC_Change_Q4','smaqc_metrics/show/','labelCol','smaqc_MS1_TIC_Change_Q4','{"Label":"The log ratio for largest TIC change over 75%ile of TIC changes"}');
INSERT INTO "detail_report_hotlinks" VALUES(59,'MS1_TIC_Q2','glossary_entry','MS1_TIC_Q2','smaqc_metrics/show/','labelCol','smaqc_MS1_TIC_Q2','{"Label":"The log ratio for 50%ile of TIC over 25%ile of TIC"}');
INSERT INTO "detail_report_hotlinks" VALUES(60,'MS1_TIC_Q3','glossary_entry','MS1_TIC_Q3','smaqc_metrics/show/','labelCol','smaqc_MS1_TIC_Q3','{"Label":"The log ratio for 75%ile of TIC over 50%ile of TIC"}');
INSERT INTO "detail_report_hotlinks" VALUES(61,'MS1_TIC_Q4','glossary_entry','MS1_TIC_Q4','smaqc_metrics/show/','labelCol','smaqc_MS1_TIC_Q4','{"Label":"The log ratio for largest TIC over 75%ile TIC"}');
INSERT INTO "detail_report_hotlinks" VALUES(62,'MS2_1','glossary_entry','MS2_1','smaqc_metrics/show/','labelCol','smaqc_MS2_1','{"Label":"Median MS2 ion injection time"}');
INSERT INTO "detail_report_hotlinks" VALUES(63,'MS2_2','glossary_entry','MS2_2','smaqc_metrics/show/','labelCol','smaqc_MS2_2','{"Label":"Median S/N value for identified MS2 spectra"}');
INSERT INTO "detail_report_hotlinks" VALUES(64,'MS2_3','glossary_entry','MS2_3','smaqc_metrics/show/','labelCol','smaqc_MS2_3','{"Label":"Median number of peaks in all MS2 spectra"}');
INSERT INTO "detail_report_hotlinks" VALUES(65,'MS2_4A','glossary_entry','MS2_4A','smaqc_metrics/show/','labelCol','smaqc_MS2_4A','{"Label":"Fraction of all MS2 spectra identified; low abundance quartile (determined using MS1 intensity of identified peptides)"}');
INSERT INTO "detail_report_hotlinks" VALUES(66,'MS2_4B','glossary_entry','MS2_4B','smaqc_metrics/show/','labelCol','smaqc_MS2_4B','{"Label":"Fraction of all MS2 spectra identified; second quartile (determined using MS1 intensity of identified peptides)"}');
INSERT INTO "detail_report_hotlinks" VALUES(67,'MS2_4C','glossary_entry','MS2_4C','smaqc_metrics/show/','labelCol','smaqc_MS2_4C','{"Label":"Fraction of all MS2 spectra identified; third quartile (determined using MS1 intensity of identified peptides)"}');
INSERT INTO "detail_report_hotlinks" VALUES(68,'MS2_4D','glossary_entry','MS2_4D','smaqc_metrics/show/','labelCol','smaqc_MS2_4D','{"Label":"Fraction of all MS2 spectra identified; high abundance quartile (determined using MS1 intensity of identified peptides)"}');
INSERT INTO "detail_report_hotlinks" VALUES(69,'MS2_Count','glossary_entry','MS2_Count','smaqc_metrics/show/','labelCol','smaqc_MS2_Count','{"Label":"Number of MS/MS spectra collected"}');
INSERT INTO "detail_report_hotlinks" VALUES(70,'MS2_Density_Q1','glossary_entry','MS2_Density_Q1','smaqc_metrics/show/','labelCol','smaqc_MS2_Density_Q1','{"Label":"25%ile of MS/MS scan peak counts"}');
INSERT INTO "detail_report_hotlinks" VALUES(71,'MS2_Density_Q2','glossary_entry','MS2_Density_Q2','smaqc_metrics/show/','labelCol','smaqc_MS2_Density_Q2','{"Label":"50%ile of MS/MS scan peak counts"}');
INSERT INTO "detail_report_hotlinks" VALUES(72,'MS2_Density_Q3','glossary_entry','MS2_Density_Q3','smaqc_metrics/show/','labelCol','smaqc_MS2_Density_Q3','{"Label":"75%ile of MS/MS scan peak counts"}');
INSERT INTO "detail_report_hotlinks" VALUES(73,'MS2_Freq_Max','glossary_entry','MS2_Freq_Max','smaqc_metrics/show/','labelCol','smaqc_MS2_Freq_Max','{"Label":"Fastest frequency for MS/MS collection in any minute"}');
INSERT INTO "detail_report_hotlinks" VALUES(74,'MS2_PrecZ_1','glossary_entry','MS2_PrecZ_1','smaqc_metrics/show/','labelCol','smaqc_MS2_PrecZ_1','{"Label":"Fraction of MS/MS precursors that are singly charged"}');
INSERT INTO "detail_report_hotlinks" VALUES(75,'MS2_PrecZ_2','glossary_entry','MS2_PrecZ_2','smaqc_metrics/show/','labelCol','smaqc_MS2_PrecZ_2','{"Label":"Fraction of MS/MS precursors that are doubly charged"}');
INSERT INTO "detail_report_hotlinks" VALUES(76,'MS2_PrecZ_3','glossary_entry','MS2_PrecZ_3','smaqc_metrics/show/','labelCol','smaqc_MS2_PrecZ_3','{"Label":"Fraction of MS/MS precursors that are triply charged"}');
INSERT INTO "detail_report_hotlinks" VALUES(77,'MS2_PrecZ_4','glossary_entry','MS2_PrecZ_4','smaqc_metrics/show/','labelCol','smaqc_MS2_PrecZ_4','{"Label":"Fraction of MS/MS precursors that are quadruply charged"}');
INSERT INTO "detail_report_hotlinks" VALUES(78,'MS2_PrecZ_5','glossary_entry','MS2_PrecZ_5','smaqc_metrics/show/','labelCol','smaqc_MS2_PrecZ_5','{"Label":"Fraction of MS/MS precursors that are quintuply charged"}');
INSERT INTO "detail_report_hotlinks" VALUES(79,'MS2_PrecZ_likely_1','glossary_entry','MS2_PrecZ_likely_1','smaqc_metrics/show/','labelCol','smaqc_MS2_PrecZ_likely_1','{"Label":"Fraction of MS/MS precursors lack known charge but look like 1+"}');
INSERT INTO "detail_report_hotlinks" VALUES(80,'MS2_PrecZ_likely_multi','glossary_entry','MS2_PrecZ_likely_multi','smaqc_metrics/show/','labelCol','smaqc_MS2_PrecZ_likely_multi','{"Label":"Fraction of MS/MS precursors lack known charge but look like 2+ or higher"}');
INSERT INTO "detail_report_hotlinks" VALUES(81,'MS2_PrecZ_more','glossary_entry','MS2_PrecZ_more','smaqc_metrics/show/','labelCol','smaqc_MS2_PrecZ_more','{"Label":"Fraction of MS/MS precursors that are charged higher than +5"}');
INSERT INTO "detail_report_hotlinks" VALUES(82,'P_1A','glossary_entry','P_1A','smaqc_metrics/show/','labelCol','smaqc_P_1A','{"Label":"Median peptide ID score (-Log10(MSGF_SpecProb) or X!Tandem hyperscore)"}');
INSERT INTO "detail_report_hotlinks" VALUES(83,'P_1B','glossary_entry','P_1B','smaqc_metrics/show/','labelCol','smaqc_P_1B','{"Label":"Median peptide ID score ( Log10(MSGF_SpecProb) or X!Tandem Peptide_Expectation_Value_Log(e))"}');
INSERT INTO "detail_report_hotlinks" VALUES(84,'P_2A','glossary_entry','P_2A','smaqc_metrics/show/','labelCol','smaqc_P_2A','{"Label":"Number of tryptic peptides; total spectra count"}');
INSERT INTO "detail_report_hotlinks" VALUES(85,'P_2B','glossary_entry','P_2B','smaqc_metrics/show/','labelCol','smaqc_P_2B','{"Label":"Number of tryptic peptides; unique peptide & charge count"}');
INSERT INTO "detail_report_hotlinks" VALUES(86,'P_2C','glossary_entry','P_2C','smaqc_metrics/show/','labelCol','smaqc_P_2C','{"Label":"Number of tryptic peptides; unique peptide count"}');
INSERT INTO "detail_report_hotlinks" VALUES(87,'P_3','glossary_entry','P_3','smaqc_metrics/show/','labelCol','smaqc_P_3','{"Label":"Ratio of unique semi-tryptic / unique fully tryptic peptides"}');
INSERT INTO "detail_report_hotlinks" VALUES(88,'P_4A','glossary_entry','P_4A','smaqc_metrics/show/','labelCol','smaqc_P_4A','{"Label":"Ratio of unique fully tryptic peptides / total unique peptides"}');
INSERT INTO "detail_report_hotlinks" VALUES(89,'P_4B','glossary_entry','P_4B','smaqc_metrics/show/','labelCol','smaqc_P_4B','{"Label":"Ratio of total missed cleavages (among unique peptides) / total unique peptides"}');
INSERT INTO "detail_report_hotlinks" VALUES(90,'Phos_2A','glossary_entry','Phos_2A','smaqc_metrics/show/','labelCol','smaqc_Phos_2A','{"Label":"Number of tryptic phosphopeptides; total spectra count"}');
INSERT INTO "detail_report_hotlinks" VALUES(91,'Phos_2C','glossary_entry','Phos_2C','smaqc_metrics/show/','labelCol','smaqc_Phos_2C','{"Label":"Number of tryptic phosphopeptides; unique peptide count"}');
INSERT INTO "detail_report_hotlinks" VALUES(92,'QCDM','glossary_entry','QCDM','smaqc_metrics/show/','labelCol','smaqc_QCDM','{"Label":"Overall confidence using model developed by Brett Amidan"}');
INSERT INTO "detail_report_hotlinks" VALUES(93,'RT_Duration','glossary_entry','RT_Duration','smaqc_metrics/show/','labelCol','smaqc_RT_Duration','{"Label":"Highest scan time observed minus the lowest scan time observed"}');
INSERT INTO "detail_report_hotlinks" VALUES(94,'RT_MS_Q1','glossary_entry','RT_MS_Q1','smaqc_metrics/show/','labelCol','smaqc_RT_MS_Q1','{"Label":"The interval for the first 25% of all MS events divided by RT-Duration"}');
INSERT INTO "detail_report_hotlinks" VALUES(95,'RT_MS_Q2','glossary_entry','RT_MS_Q2','smaqc_metrics/show/','labelCol','smaqc_RT_MS_Q2','{"Label":"The interval for the second 25% of all MS events divided by RT-Duration"}');
INSERT INTO "detail_report_hotlinks" VALUES(96,'RT_MS_Q3','glossary_entry','RT_MS_Q3','smaqc_metrics/show/','labelCol','smaqc_RT_MS_Q3','{"Label":"The interval for the third 25% of all MS events divided by RT-Duration"}');
INSERT INTO "detail_report_hotlinks" VALUES(97,'RT_MS_Q4','glossary_entry','RT_MS_Q4','smaqc_metrics/show/','labelCol','smaqc_RT_MS_Q4','{"Label":"The interval for the fourth 25% of all MS events divided by RT-Duration"}');
INSERT INTO "detail_report_hotlinks" VALUES(98,'RT_MSMS_Q1','glossary_entry','RT_MSMS_Q1','smaqc_metrics/show/','labelCol','smaqc_RT_MSMS_Q1','{"Label":"The interval for the first 25% of all MS/MS events divided by RT-Duration"}');
INSERT INTO "detail_report_hotlinks" VALUES(99,'RT_MSMS_Q2','glossary_entry','RT_MSMS_Q2','smaqc_metrics/show/','labelCol','smaqc_RT_MSMS_Q2','{"Label":"The interval for the second 25% of all MS/MS events divided by RT-Duration"}');
INSERT INTO "detail_report_hotlinks" VALUES(100,'RT_MSMS_Q3','glossary_entry','RT_MSMS_Q3','smaqc_metrics/show/','labelCol','smaqc_RT_MSMS_Q3','{"Label":"The interval for the third 25% of all MS/MS events divided by RT-Duration"}');
INSERT INTO "detail_report_hotlinks" VALUES(101,'RT_MSMS_Q4','glossary_entry','RT_MSMS_Q4','smaqc_metrics/show/','labelCol','smaqc_RT_MSMS_Q4','{"Label":"The interval for the fourth 25% of all MS/MS events divided by RT-Duration"}');
INSERT INTO "detail_report_hotlinks" VALUES(102,'RT_TIC_Q1','glossary_entry','RT_TIC_Q1','smaqc_metrics/show/','labelCol','smaqc_RT_TIC_Q1','{"Label":"The interval when the first 25% of TIC accumulates divided by RT-Duration"}');
INSERT INTO "detail_report_hotlinks" VALUES(103,'RT_TIC_Q2','glossary_entry','RT_TIC_Q2','smaqc_metrics/show/','labelCol','smaqc_RT_TIC_Q2','{"Label":"The interval when the second 25% of TIC accumulates divided by RT-Duration"}');
INSERT INTO "detail_report_hotlinks" VALUES(104,'RT_TIC_Q3','glossary_entry','RT_TIC_Q3','smaqc_metrics/show/','labelCol','smaqc_RT_TIC_Q3','{"Label":"The interval when the third 25% of TIC accumulates divided by RT-Duration"}');
INSERT INTO "detail_report_hotlinks" VALUES(105,'RT_TIC_Q4','glossary_entry','RT_TIC_Q4','smaqc_metrics/show/','labelCol','smaqc_RT_TIC_Q4','{"Label":"The interval when the fourth 25% of TIC accumulates divided by RT-Duration"}');
INSERT INTO "detail_report_hotlinks" VALUES(106,'XIC_FWHM_Q2','glossary_entry','XIC_FWHM_Q2','smaqc_metrics/show/','labelCol','smaqc_XIC_FWHM_Q2','{"Label":"50%ile of peak widths for the wide XICs"}');
INSERT INTO "detail_report_hotlinks" VALUES(107,'XIC_FWHM_Q3','glossary_entry','XIC_FWHM_Q3','smaqc_metrics/show/','labelCol','smaqc_XIC_FWHM_Q3','{"Label":"75%ile of peak widths for the wide XICs"}');
INSERT INTO "detail_report_hotlinks" VALUES(108,'XIC_Height_Q2','glossary_entry','XIC_Height_Q2','smaqc_metrics/show/','labelCol','smaqc_XIC_Height_Q2','{"Label":"The log ratio for 50%ile of wide XIC heights over 25%ile of heights."}');
INSERT INTO "detail_report_hotlinks" VALUES(109,'XIC_Height_Q3','glossary_entry','XIC_Height_Q3','smaqc_metrics/show/','labelCol','smaqc_XIC_Height_Q3','{"Label":"The log ratio for 75%ile of wide XIC heights over 50%ile of heights."}');
INSERT INTO "detail_report_hotlinks" VALUES(110,'XIC_Height_Q4','glossary_entry','XIC_Height_Q4','smaqc_metrics/show/','labelCol','smaqc_XIC_Height_Q4','{"Label":"The log ratio for maximum of wide XIC heights over 75%ile of heights."}');
INSERT INTO "detail_report_hotlinks" VALUES(111,'Trypsin_2A','glossary_entry','Trypsin_2A','smaqc_metrics/show/','labelCol','smaqc_Trypsin_2A','{"Label":"Number of peptides from trypsin; total spectra count"}');
INSERT INTO "detail_report_hotlinks" VALUES(112,'Trypsin_2C','glossary_entry','Trypsin_2C','smaqc_metrics/show/','labelCol','smaqc_Trypsin_2C','{"Label":"Number of peptides from trypsin; unique peptide count"}');
INSERT INTO "detail_report_hotlinks" VALUES(113,'MS2_RepIon_All','glossary_entry','MS2_RepIon_All','smaqc_metrics/show/','labelCol','smaqc_MS2_RepIon_All','{"Label":"Number of peptides (PSMs) where all reporter ions were seen"}');
INSERT INTO "detail_report_hotlinks" VALUES(114,'MS2_RepIon_1Missing','glossary_entry','MS2_RepIon_1Missing','smaqc_metrics/show/','labelCol','smaqc_MS2_RepIon_1Missing','{"Label":"Number of peptides (PSMs) where all but 1 of the reporter ions were seen"}');
INSERT INTO "detail_report_hotlinks" VALUES(115,'MS2_RepIon_2Missing','glossary_entry','MS2_RepIon_2Missing','smaqc_metrics/show/','labelCol','smaqc_MS2_RepIon_2Missing','{"Label":"Number of peptides (PSMs) where all but 2 of the reporter ions were seen"}');
INSERT INTO "detail_report_hotlinks" VALUES(116,'MS2_RepIon_3Missing','glossary_entry','MS2_RepIon_3Missing','smaqc_metrics/show/','labelCol','smaqc_MS2_RepIon_3Missing','{"Label":"Number of peptides (PSMs) where all but 3 of the reporter ions were seen"}');
INSERT INTO "detail_report_hotlinks" VALUES(117,'+C_1A','item_list','C_1A','','valueCol','data_c_1a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(118,'+C_1B','item_list','C_1B','','valueCol','data_c_1b','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(119,'+C_2A','item_list','C_2A','','valueCol','data_c_2a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(120,'+C_2B','item_list','C_2B','','valueCol','data_c_2b','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(121,'+C_3A','item_list','C_3A','','valueCol','data_c_3a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(122,'+C_3B','item_list','C_3B','','valueCol','data_c_3b','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(123,'+C_4A','item_list','C_4A','','valueCol','data_c_4a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(124,'+C_4B','item_list','C_4B','','valueCol','data_c_4b','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(125,'+C_4C','item_list','C_4C','','valueCol','data_c_4c','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(126,'+DS_1A','item_list','DS_1A','','valueCol','data_ds_1a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(127,'+DS_1B','item_list','DS_1B','','valueCol','data_ds_1b','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(128,'+DS_2A','item_list','DS_2A','','valueCol','data_ds_2a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(129,'+DS_2B','item_list','DS_2B','','valueCol','data_ds_2b','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(130,'+DS_3A','item_list','DS_3A','','valueCol','data_ds_3a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(131,'+DS_3B','item_list','DS_3B','','valueCol','data_ds_3b','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(132,'+IS_1A','item_list','IS_1A','','valueCol','data_is_1a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(133,'+IS_1B','item_list','IS_1B','','valueCol','data_is_1b','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(134,'+IS_2','item_list','IS_2','','valueCol','data_is_2','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(135,'+IS_3A','item_list','IS_3A','','valueCol','data_is_3a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(136,'+IS_3B','item_list','IS_3B','','valueCol','data_is_3b','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(137,'+IS_3C','item_list','IS_3C','','valueCol','data_is_3c','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(138,'+Keratin_2A','item_list','Keratin_2A','','valueCol','data_keratin_2a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(139,'+Keratin_2C','item_list','Keratin_2C','','valueCol','data_keratin_2c','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(140,'+MassErrorPPM','item_list','MassErrorPPM','','valueCol','data_masserrorppm','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(141,'+MassErrorPPM_Refined','item_list','MassErrorPPM_Refined','','valueCol','data_masserrorppm_refined','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(142,'+MassErrorPPM_VIPER','item_list','MassErrorPPM_VIPER','','valueCol','data_masserrorppm_viper','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(143,'+MS1_1','item_list','MS1_1','','valueCol','data_ms1_1','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(144,'+MS1_2A','item_list','MS1_2A','','valueCol','data_ms1_2a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(145,'+MS1_2B','item_list','MS1_2B','','valueCol','data_ms1_2b','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(146,'+MS1_3A','item_list','MS1_3A','','valueCol','data_ms1_3a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(147,'+MS1_3B','item_list','MS1_3B','','valueCol','data_ms1_3b','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(148,'+MS1_5A','item_list','MS1_5A','','valueCol','data_ms1_5a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(149,'+MS1_5B','item_list','MS1_5B','','valueCol','data_ms1_5b','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(150,'+MS1_5C','item_list','MS1_5C','','valueCol','data_ms1_5c','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(151,'+MS1_5D','item_list','MS1_5D','','valueCol','data_ms1_5d','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(152,'+MS1_Count','item_list','MS1_Count','','valueCol','data_ms1_count','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(153,'+MS1_Density_Q1','item_list','MS1_Density_Q1','','valueCol','data_ms1_density_q1','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(154,'+MS1_Density_Q2','item_list','MS1_Density_Q2','','valueCol','data_ms1_density_q2','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(155,'+MS1_Density_Q3','item_list','MS1_Density_Q3','','valueCol','data_ms1_density_q3','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(156,'+MS1_Freq_Max','item_list','MS1_Freq_Max','','valueCol','data_ms1_freq_max','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(157,'+MS1_TIC_Change_Q2','item_list','MS1_TIC_Change_Q2','','valueCol','data_ms1_tic_change_q2','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(158,'+MS1_TIC_Change_Q3','item_list','MS1_TIC_Change_Q3','','valueCol','data_ms1_tic_change_q3','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(159,'+MS1_TIC_Change_Q4','item_list','MS1_TIC_Change_Q4','','valueCol','data_ms1_tic_change_q4','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(160,'+MS1_TIC_Q2','item_list','MS1_TIC_Q2','','valueCol','data_ms1_tic_q2','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(161,'+MS1_TIC_Q3','item_list','MS1_TIC_Q3','','valueCol','data_ms1_tic_q3','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(162,'+MS1_TIC_Q4','item_list','MS1_TIC_Q4','','valueCol','data_ms1_tic_q4','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(163,'+MS2_1','item_list','MS2_1','','valueCol','data_ms2_1','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(164,'+MS2_2','item_list','MS2_2','','valueCol','data_ms2_2','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(165,'+MS2_3','item_list','MS2_3','','valueCol','data_ms2_3','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(166,'+MS2_4A','item_list','MS2_4A','','valueCol','data_ms2_4a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(167,'+MS2_4B','item_list','MS2_4B','','valueCol','data_ms2_4b','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(168,'+MS2_4C','item_list','MS2_4C','','valueCol','data_ms2_4c','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(169,'+MS2_4D','item_list','MS2_4D','','valueCol','data_ms2_4d','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(170,'+MS2_Count','item_list','MS2_Count','','valueCol','data_ms2_count','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(171,'+MS2_Density_Q1','item_list','MS2_Density_Q1','','valueCol','data_ms2_density_q1','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(172,'+MS2_Density_Q2','item_list','MS2_Density_Q2','','valueCol','data_ms2_density_q2','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(173,'+MS2_Density_Q3','item_list','MS2_Density_Q3','','valueCol','data_ms2_density_q3','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(174,'+MS2_Freq_Max','item_list','MS2_Freq_Max','','valueCol','data_ms2_freq_max','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(175,'+MS2_PrecZ_1','item_list','MS2_PrecZ_1','','valueCol','data_ms2_precz_1','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(176,'+MS2_PrecZ_2','item_list','MS2_PrecZ_2','','valueCol','data_ms2_precz_2','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(177,'+MS2_PrecZ_3','item_list','MS2_PrecZ_3','','valueCol','data_ms2_precz_3','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(178,'+MS2_PrecZ_4','item_list','MS2_PrecZ_4','','valueCol','data_ms2_precz_4','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(179,'+MS2_PrecZ_5','item_list','MS2_PrecZ_5','','valueCol','data_ms2_precz_5','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(180,'+MS2_PrecZ_likely_1','item_list','MS2_PrecZ_likely_1','','valueCol','data_ms2_precz_likely_1','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(181,'+MS2_PrecZ_likely_multi','item_list','MS2_PrecZ_likely_multi','','valueCol','data_ms2_precz_likely_multi','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(182,'+MS2_PrecZ_more','item_list','MS2_PrecZ_more','','valueCol','data_ms2_precz_more','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(183,'+MS2_RepIon_1Missing','item_list','MS2_RepIon_1Missing','','valueCol','data_ms2_repion_1missing','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(184,'+MS2_RepIon_2Missing','item_list','MS2_RepIon_2Missing','','valueCol','data_ms2_repion_2missing','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(185,'+MS2_RepIon_3Missing','item_list','MS2_RepIon_3Missing','','valueCol','data_ms2_repion_3missing','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(186,'+MS2_RepIon_All','item_list','MS2_RepIon_All','','valueCol','data_ms2_repion_all','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(187,'+P_1A','item_list','P_1A','','valueCol','data_p_1a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(188,'+P_1B','item_list','P_1B','','valueCol','data_p_1b','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(189,'+P_2A','item_list','P_2A','','valueCol','data_p_2a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(190,'+P_2B','item_list','P_2B','','valueCol','data_p_2b','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(191,'+P_2C','item_list','P_2C','','valueCol','data_p_2c','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(192,'+P_3','item_list','P_3','','valueCol','data_p_3','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(193,'+P_4A','item_list','P_4A','','valueCol','data_p_4a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(194,'+P_4B','item_list','P_4B','','valueCol','data_p_4b','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(195,'+Phos_2A','item_list','Phos_2A','','valueCol','data_phos_2a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(196,'+Phos_2C','item_list','Phos_2C','','valueCol','data_phos_2c','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(197,'+RT_Duration','item_list','RT_Duration','','valueCol','data_rt_duration','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(198,'+RT_MS_Q1','item_list','RT_MS_Q1','','valueCol','data_rt_ms_q1','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(199,'+RT_MS_Q2','item_list','RT_MS_Q2','','valueCol','data_rt_ms_q2','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(200,'+RT_MS_Q3','item_list','RT_MS_Q3','','valueCol','data_rt_ms_q3','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(201,'+RT_MS_Q4','item_list','RT_MS_Q4','','valueCol','data_rt_ms_q4','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(202,'+RT_MSMS_Q1','item_list','RT_MSMS_Q1','','valueCol','data_rt_msms_q1','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(203,'+RT_MSMS_Q2','item_list','RT_MSMS_Q2','','valueCol','data_rt_msms_q2','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(204,'+RT_MSMS_Q3','item_list','RT_MSMS_Q3','','valueCol','data_rt_msms_q3','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(205,'+RT_MSMS_Q4','item_list','RT_MSMS_Q4','','valueCol','data_rt_msms_q4','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(206,'+RT_TIC_Q1','item_list','RT_TIC_Q1','','valueCol','data_rt_tic_q1','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(207,'+RT_TIC_Q2','item_list','RT_TIC_Q2','','valueCol','data_rt_tic_q2','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(208,'+RT_TIC_Q3','item_list','RT_TIC_Q3','','valueCol','data_rt_tic_q3','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(209,'+RT_TIC_Q4','item_list','RT_TIC_Q4','','valueCol','data_rt_tic_q4','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(210,'+Trypsin_2A','item_list','Trypsin_2A','','valueCol','data_trypsin_2a','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(211,'+Trypsin_2C','item_list','Trypsin_2C','','valueCol','data_trypsin_2c','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(212,'+XIC_FWHM_Q1','item_list','XIC_FWHM_Q1','','valueCol','data_xic_fwhm_q1','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(213,'+XIC_FWHM_Q2','item_list','XIC_FWHM_Q2','','valueCol','data_xic_fwhm_q2','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(214,'+XIC_FWHM_Q3','item_list','XIC_FWHM_Q3','','valueCol','data_xic_fwhm_q3','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(215,'+XIC_Height_Q2','item_list','XIC_Height_Q2','','valueCol','data_xic_height_q2','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(216,'+XIC_Height_Q3','item_list','XIC_Height_Q3','','valueCol','data_xic_height_q3','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(217,'+XIC_Height_Q4','item_list','XIC_Height_Q4','','valueCol','data_xic_height_q4','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(218,'+XIC_WideFrac','item_list','XIC_WideFrac','','valueCol','data_xic_widefrac','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(219,'+QCDM','item_list','QCDM','','valueCol','data_qcdm','{"Widths":"20%,80%"}');
INSERT INTO "detail_report_hotlinks" VALUES(220,'+QCART','item_list','QCART','','valueCol','data_qcart','{"Widths":"20%,80%"}');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO "list_report_primary_filter" VALUES(1,'pf_Instrument_Group','Inst. Group','24','','Instrument Group','ContainsText','text','','','');
INSERT INTO "list_report_primary_filter" VALUES(2,'pf_Instrument','Instrument','24','','Instrument','ContainsText','text','','','');
INSERT INTO "list_report_primary_filter" VALUES(3,'pf_dataset','Dataset','35!','','Dataset','ContainsText','text','','','');
INSERT INTO "list_report_primary_filter" VALUES(4,'pf_most_recent_weeks','Most Recent Weeks','2!','','Acq_Time_Start','MostRecentWeeks','text','20','','');
INSERT INTO "list_report_primary_filter" VALUES(5,'pf_created_after','Created After','8','','Acq_Time_Start','LaterThan','text','20','','');
COMMIT;
