PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','T_Spectral_Library');
INSERT INTO general_params VALUES('list_report_data_table','v_spectral_library_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_col','library_id');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_library_id','Library ID','','','library_id','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_library_name','Library Name','40!','','library_name','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_library_state','Library State','','','library_state','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_protein_collection_list','Protein Collection','50!','','protein_collection_list','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_dynamic_mods','Dynamic Mods','','','dynamic_mods','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_max_dynamic_mods','Max Dynamic Mods','3!','','max_dynamic_mods','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_static_mods','Static Mods','','','static_mods','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(8,'pf_fragment_ion_mz_min','Fragment Min m/z','4!','','fragment_ion_mz_min','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(9,'pf_fragment_ion_mz_max','Fragment Max m/z','4!','','fragment_ion_mz_max','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(10,'pf_missed_cleavages','Missed Cleavages','3!','','missed_cleavages','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(11,'pf_peptide_length_min','Peptide Length Min','3!','','peptide_length_min','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(12,'pf_peptide_length_max','Peptide Length Max','3!','','peptide_length_max','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(13,'pf_precursor_mz_min','Precursor Min m/z','4!','','precursor_mz_min','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(14,'pf_precursor_mz_max','Precursor Max m/z','4!','','precursor_mz_max','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(15,'pf_precursor_charge_min','Precursor Charge Min','3!','','precursor_charge_min','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(16,'pf_precursor_charge_max','Precursor Charge Max','3!','','precursor_charge_max','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(17,'pf_program_version','Program Version','','','program_version','ContainsText','text','','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'source_job','invoke_entity','value','analysis_job/show','');
INSERT INTO list_report_hotlinks VALUES(2,'protein_collection_list','link_list','value','protein_collection/report','');
COMMIT;
