PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_storage_list_report');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('detail_report_data_table','v_storage_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','id');
INSERT INTO general_params VALUES('detail_report_data_id_type','integer');
INSERT INTO general_params VALUES('entry_sproc','add_update_storage');
INSERT INTO general_params VALUES('entry_page_data_table','v_storage_entry');
INSERT INTO general_params VALUES('entry_page_data_id_col','storage_path_id');
INSERT INTO general_params VALUES('post_submission_detail_id','storage_path_id');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO form_fields VALUES(1,'storage_path_id','ID','non-edit','','','','','','trim');
INSERT INTO form_fields VALUES(2,'storage_path','Path','text','40','255','','','','trim|required|max_length[255]');
INSERT INTO form_fields VALUES(3,'vol_name_client','Volume (client)','text','40','128','','','','trim|max_length[128]');
INSERT INTO form_fields VALUES(4,'vol_name_server','Volume (server)','text','40','128','','','','trim|required|max_length[128]');
INSERT INTO form_fields VALUES(5,'storage_path_function','Function','text','40','80','','','','trim|required|max_length[50]');
INSERT INTO form_fields VALUES(6,'instrument','Instrument','text','40','80','','','','trim|required|max_length[64]');
INSERT INTO form_fields VALUES(7,'description','Description','area','','','4','50','','trim|max_length[255]');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO form_field_choosers VALUES(1,'storage_path_function','picker.replace','storageFunctionPickList','','',',','');
INSERT INTO form_field_choosers VALUES(2,'instrument','picker.replace','instrumentNamePickList','','',',','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'id','invoke_entity','value','storage/show/','');
INSERT INTO list_report_hotlinks VALUES(2,'instrument','invoke_entity','value','instrument/show/','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'storage_path','path','varchar','input','255','add_update_storage');
INSERT INTO sproc_args VALUES(2,'vol_name_client','volNameClient','varchar','input','128','add_update_storage');
INSERT INTO sproc_args VALUES(3,'vol_name_server','volNameServer','varchar','input','128','add_update_storage');
INSERT INTO sproc_args VALUES(4,'storage_path_function','storFunction','varchar','input','50','add_update_storage');
INSERT INTO sproc_args VALUES(5,'instrument','instrumentName','varchar','input','64','add_update_storage');
INSERT INTO sproc_args VALUES(6,'description','description','varchar','input','255','add_update_storage');
INSERT INTO sproc_args VALUES(7,'storage_path_id','id','varchar','output','32','add_update_storage');
INSERT INTO sproc_args VALUES(8,'<local>','mode','varchar','input','12','add_update_storage');
INSERT INTO sproc_args VALUES(9,'<local>','message','varchar','output','512','add_update_storage');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_vol_client','Vol Client','20','','vol_client','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_instrument','Instrument','20','','instrument','ContainsText','text','50','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_storage_path_function','Function','20','','storage_path_function','ContainsText','text','50','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_description','Description','20','','description','ContainsText','text','255','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_storage_path','Path','20','','storage_path','ContainsText','text','255','','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO detail_report_hotlinks VALUES(1,'instrument','detail-report','instrument','instrument/show/','labelCol','dl_Instrument','');
COMMIT;
