PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_bto_tissue_report');
INSERT INTO general_params VALUES('list_report_data_sort_col','usage');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('my_db_group','ontology');
INSERT INTO general_params VALUES('detail_report_data_table','v_bto_tissue_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','identifier');
INSERT INTO general_params VALUES('detail_report_data_id_type','string');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'identifier','invoke_entity','value','tissue/show','');
INSERT INTO list_report_hotlinks VALUES(2,'tissue','invoke_entity','value','tissue/report/~@','');
INSERT INTO list_report_hotlinks VALUES(3,'parent_tissue','invoke_entity','value','tissue/report/-/-/~@','');
INSERT INTO list_report_hotlinks VALUES(4,'grandparent_tissue','invoke_entity','value','tissue/report/-/-/-/~@','');
INSERT INTO list_report_hotlinks VALUES(5,'children','invoke_entity','tissue','tissue/report/-/-/~@','');
INSERT INTO list_report_hotlinks VALUES(6,'parent_id','invoke_entity','value','tissue/show','');
INSERT INTO list_report_hotlinks VALUES(7,'grandparent_id','invoke_entity','value','tissue/show','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_Tissue','Tissue','30!','','tissue','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_identifier','Identifier','20','','identifier','ContainsText','text','24','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_parent','Parent','30!','','parent_tissue','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_grandparent','Grandparent','30!','','grandparent_tissue','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_synonyms','Synonym','30!','','synonyms','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_is_leaf','Leaf node','20','','is_leaf','Equals','text','8','','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text, "options" text );
INSERT INTO detail_report_hotlinks VALUES(1,'tissue','detail-report','tissue','tissue/report/','valueCol','','');
INSERT INTO detail_report_hotlinks VALUES(2,'parent_tissue','detail-report','parent_tissue','tissue/report/','valueCol','','');
INSERT INTO detail_report_hotlinks VALUES(3,'grandparent_tissue','detail-report','grandparent_tissue','tissue/report/','valueCol','','');
INSERT INTO detail_report_hotlinks VALUES(4,'parent_id','detail-report','parent_id','tissue/show/','valueCol','','');
INSERT INTO detail_report_hotlinks VALUES(5,'grandparent_id','detail-report','grandparent_id','tissue/show/','valueCol','','');
INSERT INTO detail_report_hotlinks VALUES(6,'children','detail-report','tissue','tissue/report/-/-/','valueCol','','');
COMMIT;
