PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('list_report_data_sort_dir','ASC');
INSERT INTO "general_params" VALUES('list_report_data_sort_col','Tissue');
INSERT INTO "general_params" VALUES('list_report_sproc','ReportTissueUsageStats');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO "sproc_args" VALUES(1,'Start_Date','startDate','varchar','input','24','ReportTissueUsageStats');
INSERT INTO "sproc_args" VALUES(2,'End_Date','endDate','varchar','input','24','ReportTissueUsageStats');
INSERT INTO "sproc_args" VALUES(3,'Organism_ID_Filter_List','organismIDFilterList','varchar','input','2000','ReportTissueUsageStats');
INSERT INTO "sproc_args" VALUES(4,'Campaign_ID_Filter_List','campaignIDFilterList','varchar','input','2000','ReportTissueUsageStats');
INSERT INTO "sproc_args" VALUES(5,'Instrument_Filter_List','instrumentFilterList','varchar','input','2000','ReportTissueUsageStats');
INSERT INTO "sproc_args" VALUES(6,'<local>','message','varchar','output','256','ReportTissueUsageStats');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO "form_fields" VALUES(1,'Start_Date','Starting Date','text','24','80','','','','trim');
INSERT INTO "form_fields" VALUES(2,'End_Date','Ending Date','text','24','80','','','','trim');
INSERT INTO "form_fields" VALUES(3,'Campaign_ID_Filter_List','Campaign ID List','text','24','2000','','','','trim');
INSERT INTO "form_fields" VALUES(4,'Organism_ID_Filter_List','Organism Filter List','text','24','2000','','','','trim');
INSERT INTO "form_fields" VALUES(5,'Instrument_Filter_List','Instrument Filter List','text','24','2000','','','','trim');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO "list_report_hotlinks" VALUES(1,'Experiments','invoke_entity','Tissue','experiment/report/-/-/-/-/@','');
CREATE TABLE form_field_options ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "parameter" text );
INSERT INTO "form_field_options" VALUES(1,'Start_Date','default_function','PreviousNWeeks:10');
INSERT INTO "form_field_options" VALUES(2,'End_Date','default_function','CurrentDate');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO "form_field_choosers" VALUES(1,'Instrument_Filter_List','picker.append','instrumentNamePickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(2,'Campaign_ID_Filter_List','picker.append','campaignIDPickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(3,'Organism_ID_Filter_List','picker.append','organismIDPickList','','',',','');
COMMIT;
