PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','v_unimod_list_report');
INSERT INTO general_params VALUES('detail_report_data_table','v_unimod_detail_report');
INSERT INTO general_params VALUES('detail_report_data_id_col','unimod_id');
INSERT INTO general_params VALUES('my_db_group','ontology');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(2,'pf_name','Name','20','','name','ContainsText','text','512','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_DMS_Name','DMS_Name','20','','dms_name','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_full_name','Full_Name','20','','full_name','ContainsText','text','1020','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_monomass_min','Min_Mass','20','','monomass','GreaterThanOrEqualTo','text','20','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_monomass_max','Max_Mass','20','','monomass','LessThanOrEqualTo','text','20','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_composition','Composition','40','','composition','ContainsText','text','512','','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO detail_report_hotlinks VALUES(1,'name','detail-report','name','unimod/report/','valueCol','dl_Name',NULL);
INSERT INTO detail_report_hotlinks VALUES(2,'monoisotopic_mass','detail-report','monoisotopic_mass','unimod/report/-/-/-/-/@/@','valueCol','dl_monomass',NULL);
INSERT INTO detail_report_hotlinks VALUES(3,'url','literal_link','url','url/show','valueCol','dl_url',NULL);
INSERT INTO detail_report_hotlinks VALUES(4,'dms_name','detail-report','dms_name','mass_correction_factors/report/-/~','valueCol','dl_dms_name','');
INSERT INTO detail_report_hotlinks VALUES(5,'mass_correction_id','detail-report','mass_correction_id','param_file_mass_mods/report/-/@','valueCol','dl_mass_correction_id','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'id','invoke_entity','value','unimod/show/','');
INSERT INTO list_report_hotlinks VALUES(2,'dms_name','invoke_entity','value','mass_correction_factors/report/-/~','');
COMMIT;
