PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('list_report_data_sort_dir','DESC');
INSERT INTO "general_params" VALUES('entry_sproc','UpdateAnalysisJobs');
INSERT INTO "general_params" VALUES('entry_page_data_table','T_Analysis_Job');
INSERT INTO "general_params" VALUES('entry_page_data_id_col','AJ_JobID');
INSERT INTO "general_params" VALUES('alternate_title_create','Update Multiple Analysis Jobs');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO "form_fields" VALUES(1,'JobList','Job List','area','','','4','60','','trim|required|max_length[6000]');
INSERT INTO "form_fields" VALUES(2,'state','State','text','32','32','','','','trim|max_length[32]');
INSERT INTO "form_fields" VALUES(3,'priority','Priority','text','12','12','','','','trim|max_length[12]');
INSERT INTO "form_fields" VALUES(4,'comment','Append To Comment','area','','','2','60','','trim|max_length[255]');
INSERT INTO "form_fields" VALUES(5,'findText','Find In Comment','area','','','2','60','','trim|max_length[255]');
INSERT INTO "form_fields" VALUES(6,'replaceText','Replace In Comment','area','','','2','60','','trim|max_length[255]');
INSERT INTO "form_fields" VALUES(7,'assignedProcessor','Assigned Processor','text','60','64','','','','trim|max_length[64]');
INSERT INTO "form_fields" VALUES(8,'associatedProcessorGroup','Associated Processor Group','text','60','64','','','','trim|max_length[64]');
INSERT INTO "form_fields" VALUES(9,'propagationMode','Export Mode','text','24','24','','','','trim|max_length[24]');
INSERT INTO "form_fields" VALUES(10,'AJ_ParmFile','Parameter File','text','60','255','','','','trim|max_length[255]');
INSERT INTO "form_fields" VALUES(11,'AJ_SettingsFile','Settings File','text','60','80','','','','trim|default_value[LCQDefSettings.txt]|max_length[80]');
INSERT INTO "form_fields" VALUES(12,'AJ_Organism','Organism','text','30','128','','','','trim|max_length[128]');
INSERT INTO "form_fields" VALUES(13,'protCollNameList','Protein Collection List','area','','','3','60','na','trim|max_length[2000]');
INSERT INTO "form_fields" VALUES(14,'protCollOptionsList','Protein Options List','area','','','2','60','seq_direction=forward','trim|max_length[256]');
CREATE TABLE form_field_options ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "parameter" text );
INSERT INTO "form_field_options" VALUES(1,'JobList','enable','none');
INSERT INTO "form_field_options" VALUES(2,'state','enable','ckbx');
INSERT INTO "form_field_options" VALUES(3,'priority','enable','ckbx');
INSERT INTO "form_field_options" VALUES(4,'comment','enable','ckbx');
INSERT INTO "form_field_options" VALUES(5,'findText','enable','ckbx');
INSERT INTO "form_field_options" VALUES(6,'replaceText','enable','ckbx');
INSERT INTO "form_field_options" VALUES(7,'assignedProcessor','enable','ckbx');
INSERT INTO "form_field_options" VALUES(8,'associatedProcessorGroup','enable','ckbx');
INSERT INTO "form_field_options" VALUES(9,'propagationMode','enable','ckbx');
INSERT INTO "form_field_options" VALUES(10,'AJ_ParmFile','enable','ckbx');
INSERT INTO "form_field_options" VALUES(11,'AJ_SettingsFile','enable','ckbx');
INSERT INTO "form_field_options" VALUES(12,'AJ_Organism','enable','ckbx');
INSERT INTO "form_field_options" VALUES(13,'protCollNameList','enable','ckbx');
INSERT INTO "form_field_options" VALUES(14,'protCollOptionsList','enable','ckbx');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO "form_field_choosers" VALUES(1,'JobList','list-report.helper','','helper_analysis_job_ckbx/report','',',','');
INSERT INTO "form_field_choosers" VALUES(2,'state','picker.replace','analysisJobStatePickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(3,'priority','picker.replace','analysisJobPriPickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(4,'assignedProcessor','picker.replace','assignedProcessorPickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(5,'associatedProcessorGroup','list-report.helper','','helper_analysis_processor_group/report','',',','');
INSERT INTO "form_field_choosers" VALUES(6,'propagationMode','picker.replace','jobPropagationModePickList','','',',','');
INSERT INTO "form_field_choosers" VALUES(7,'AJ_ParmFile','list-report.helper','','helper_aj_param_file/report','',',','');
INSERT INTO "form_field_choosers" VALUES(8,'AJ_SettingsFile','list-report.helper','','helper_aj_settings_file/report','',',','');
INSERT INTO "form_field_choosers" VALUES(9,'AJ_Organism','list-report.helper','','helper_organism/report','',',','');
INSERT INTO "form_field_choosers" VALUES(10,'protCollNameList','list-report.helper','','helper_protein_collection/report','AJ_Organism',',','');
INSERT INTO "form_field_choosers" VALUES(11,'protCollOptionsList','picker.replace','protOptSeqDirPickList','','',',','');
CREATE TABLE entry_commands ( id INTEGER PRIMARY KEY,  "name" text, "type" text, "label" text, "tooltip" text, "target" text );
INSERT INTO "entry_commands" VALUES(1,'update','override','Update','','add');
INSERT INTO "entry_commands" VALUES(2,'preview','cmd','Validate changes','Validate without making any changes to database','');
INSERT INTO "entry_commands" VALUES(3,'Reset','cmd','Reset the selected jobs','Make changes in the selected jobs and also overide job state to "New" and clear run times','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO "sproc_args" VALUES(1,'JobList','JobList','varchar','input','6000','UpdateAnalysisJobs');
INSERT INTO "sproc_args" VALUES(2,'state','state','varchar','input','32','UpdateAnalysisJobs');
INSERT INTO "sproc_args" VALUES(3,'priority','priority','varchar','input','12','UpdateAnalysisJobs');
INSERT INTO "sproc_args" VALUES(4,'comment','comment','varchar','input','512','UpdateAnalysisJobs');
INSERT INTO "sproc_args" VALUES(5,'findText','findText','varchar','input','255','UpdateAnalysisJobs');
INSERT INTO "sproc_args" VALUES(6,'replaceText','replaceText','varchar','input','255','UpdateAnalysisJobs');
INSERT INTO "sproc_args" VALUES(7,'assignedProcessor','assignedProcessor','varchar','input','64','UpdateAnalysisJobs');
INSERT INTO "sproc_args" VALUES(8,'associatedProcessorGroup','associatedProcessorGroup','varchar','input','64','UpdateAnalysisJobs');
INSERT INTO "sproc_args" VALUES(9,'propagationMode','propagationMode','varchar','input','24','UpdateAnalysisJobs');
INSERT INTO "sproc_args" VALUES(10,'AJ_ParmFile','parmFileName','varchar','input','255','UpdateAnalysisJobs');
INSERT INTO "sproc_args" VALUES(11,'AJ_SettingsFile','settingsFileName','varchar','input','255','UpdateAnalysisJobs');
INSERT INTO "sproc_args" VALUES(12,'AJ_Organism','organismName','varchar','input','128','UpdateAnalysisJobs');
INSERT INTO "sproc_args" VALUES(13,'protCollNameList','protCollNameList','varchar','input','4000','UpdateAnalysisJobs');
INSERT INTO "sproc_args" VALUES(14,'protCollOptionsList','protCollOptionsList','varchar','input','256','UpdateAnalysisJobs');
INSERT INTO "sproc_args" VALUES(15,'<local>','mode','varchar','input','12','UpdateAnalysisJobs');
INSERT INTO "sproc_args" VALUES(16,'<local>','message','varchar','output','512','UpdateAnalysisJobs');
INSERT INTO "sproc_args" VALUES(17,'<local>','callingUser','varchar','input','128','UpdateAnalysisJobs');
COMMIT;
