PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('entry_sproc','UpdateAnalysisJobs');
INSERT INTO general_params VALUES('entry_page_data_table','t_analysis_job');
INSERT INTO general_params VALUES('entry_page_data_id_col','job_id');
INSERT INTO general_params VALUES('alternate_title_create','Update Multiple Analysis Jobs');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO form_fields VALUES(1,'job_list','Job List','area','','','4','60','','trim|required|max_length[6000]');
INSERT INTO form_fields VALUES(2,'state','State','text','32','32','','','','trim|max_length[32]');
INSERT INTO form_fields VALUES(3,'priority','Priority','text','12','12','','','','trim|max_length[12]');
INSERT INTO form_fields VALUES(4,'comment','Append To Comment','area','','','2','60','','trim|max_length[255]');
INSERT INTO form_fields VALUES(5,'find_text','Find In Comment','area','','','2','60','','trim|max_length[255]');
INSERT INTO form_fields VALUES(6,'replace_text','Replace In Comment','area','','','2','60','','trim|max_length[255]');
INSERT INTO form_fields VALUES(7,'assigned_processor','Assigned Processor','text','60','64','','','','trim|max_length[64]');
INSERT INTO form_fields VALUES(8,'associated_processor_group','Associated Processor Group','text','60','64','','','','trim|max_length[64]');
INSERT INTO form_fields VALUES(9,'propagation_mode','Export Mode','text','24','24','','','','trim|max_length[24]');
INSERT INTO form_fields VALUES(10,'param_file','Parameter File','text','60','255','','','','trim|max_length[255]');
INSERT INTO form_fields VALUES(11,'settings_file','Settings File','text','60','80','','','','trim|default_value[LCQDefSettings.txt]|max_length[80]');
INSERT INTO form_fields VALUES(12,'organism','Organism','text','30','128','','','','trim|max_length[128]');
INSERT INTO form_fields VALUES(13,'prot_coll_name_list','Protein Collection List','area','','','3','60','na','trim|max_length[2000]');
INSERT INTO form_fields VALUES(14,'prot_coll_options_list','Protein Options List','area','','','2','60','seq_direction=forward','trim|max_length[256]');
CREATE TABLE form_field_options ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "parameter" text );
INSERT INTO form_field_options VALUES(1,'job_list','enable','none');
INSERT INTO form_field_options VALUES(2,'state','enable','ckbx');
INSERT INTO form_field_options VALUES(3,'priority','enable','ckbx');
INSERT INTO form_field_options VALUES(4,'comment','enable','ckbx');
INSERT INTO form_field_options VALUES(5,'find_text','enable','ckbx');
INSERT INTO form_field_options VALUES(6,'replace_text','enable','ckbx');
INSERT INTO form_field_options VALUES(7,'assigned_processor','enable','ckbx');
INSERT INTO form_field_options VALUES(8,'associated_processor_group','enable','ckbx');
INSERT INTO form_field_options VALUES(9,'propagation_mode','enable','ckbx');
INSERT INTO form_field_options VALUES(10,'param_file','enable','ckbx');
INSERT INTO form_field_options VALUES(11,'settings_file','enable','ckbx');
INSERT INTO form_field_options VALUES(12,'organism','enable','ckbx');
INSERT INTO form_field_options VALUES(13,'prot_coll_name_list','enable','ckbx');
INSERT INTO form_field_options VALUES(14,'prot_coll_options_list','enable','ckbx');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO form_field_choosers VALUES(1,'job_list','list-report.helper','','helper_analysis_job_ckbx/report','',',','');
INSERT INTO form_field_choosers VALUES(2,'state','picker.replace','analysisJobStatePickList','','',',','');
INSERT INTO form_field_choosers VALUES(3,'priority','picker.replace','analysisJobPriPickList','','',',','');
INSERT INTO form_field_choosers VALUES(4,'assigned_processor','picker.replace','assignedProcessorPickList','','',',','');
INSERT INTO form_field_choosers VALUES(5,'associated_processor_group','list-report.helper','','helper_analysis_processor_group/report','',',','');
INSERT INTO form_field_choosers VALUES(6,'propagation_mode','picker.replace','jobPropagationModePickList','','',',','');
INSERT INTO form_field_choosers VALUES(7,'param_file','list-report.helper','','helper_aj_param_file/report','',',','');
INSERT INTO form_field_choosers VALUES(8,'settings_file','list-report.helper','','helper_aj_settings_file/report','',',','');
INSERT INTO form_field_choosers VALUES(9,'organism','list-report.helper','','helper_organism/report','',',','');
INSERT INTO form_field_choosers VALUES(10,'prot_coll_name_list','list-report.helper','','helper_protein_collection/report','organism',',','');
INSERT INTO form_field_choosers VALUES(11,'prot_coll_options_list','picker.replace','protOptSeqDirPickList','','',',','');
CREATE TABLE entry_commands ( id INTEGER PRIMARY KEY,  "name" text, "type" text, "label" text, "tooltip" text, "target" text );
INSERT INTO entry_commands VALUES(1,'update','override','Update','','add');
INSERT INTO entry_commands VALUES(2,'preview','cmd','Validate changes','Validate without making any changes to database','');
INSERT INTO entry_commands VALUES(3,'Reset','cmd','Reset the selected jobs','Make changes in the selected jobs and also overide job state to "New" and clear run times','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'job_list','JobList','varchar','input','6000','UpdateAnalysisJobs');
INSERT INTO sproc_args VALUES(2,'state','state','varchar','input','32','UpdateAnalysisJobs');
INSERT INTO sproc_args VALUES(3,'priority','priority','varchar','input','12','UpdateAnalysisJobs');
INSERT INTO sproc_args VALUES(4,'comment','comment','varchar','input','512','UpdateAnalysisJobs');
INSERT INTO sproc_args VALUES(5,'find_text','findText','varchar','input','255','UpdateAnalysisJobs');
INSERT INTO sproc_args VALUES(6,'replace_text','replaceText','varchar','input','255','UpdateAnalysisJobs');
INSERT INTO sproc_args VALUES(7,'assigned_processor','assignedProcessor','varchar','input','64','UpdateAnalysisJobs');
INSERT INTO sproc_args VALUES(8,'associated_processor_group','associatedProcessorGroup','varchar','input','64','UpdateAnalysisJobs');
INSERT INTO sproc_args VALUES(9,'propagation_mode','propagationMode','varchar','input','24','UpdateAnalysisJobs');
INSERT INTO sproc_args VALUES(10,'param_file','paramFileName','varchar','input','255','UpdateAnalysisJobs');
INSERT INTO sproc_args VALUES(11,'settings_file','settingsFileName','varchar','input','255','UpdateAnalysisJobs');
INSERT INTO sproc_args VALUES(12,'organism','organismName','varchar','input','128','UpdateAnalysisJobs');
INSERT INTO sproc_args VALUES(13,'prot_coll_name_list','protCollNameList','varchar','input','4000','UpdateAnalysisJobs');
INSERT INTO sproc_args VALUES(14,'prot_coll_options_list','protCollOptionsList','varchar','input','256','UpdateAnalysisJobs');
INSERT INTO sproc_args VALUES(15,'<local>','mode','varchar','input','12','UpdateAnalysisJobs');
INSERT INTO sproc_args VALUES(16,'<local>','message','varchar','output','512','UpdateAnalysisJobs');
INSERT INTO sproc_args VALUES(17,'<local>','callingUser','varchar','input','128','UpdateAnalysisJobs');
COMMIT;
