PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_sproc','get_monthly_instrument_usage_report');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'instrument','instrument','varchar','input','64','get_monthly_instrument_usage_report');
INSERT INTO sproc_args VALUES(2,'<local>','eusInstrumentId','int','input','12','get_monthly_instrument_usage_report');
INSERT INTO sproc_args VALUES(3,'year','year','varchar','input','12','get_monthly_instrument_usage_report');
INSERT INTO sproc_args VALUES(4,'month','month','varchar','input','12','get_monthly_instrument_usage_report');
INSERT INTO sproc_args VALUES(5,'output_format','outputFormat','varchar','input','12','get_monthly_instrument_usage_report');
INSERT INTO sproc_args VALUES(6,'<local>','message','varchar','output','512','get_monthly_instrument_usage_report');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO form_fields VALUES(1,'instrument','Instrument','text','50','64','','','','trim|max_length[64]');
INSERT INTO form_fields VALUES(2,'year','Year','text','12','12','','','','trim|max_length[12]');
INSERT INTO form_fields VALUES(3,'month','Month','text','12','12','','','','trim|max_length[12]');
INSERT INTO form_fields VALUES(4,'output_format','Output Format','text','12','12','','','details','trim|max_length[12]');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO form_field_choosers VALUES(1,'instrument','picker.replace','instrumentRunUsagePicklist','','',',','');
INSERT INTO form_field_choosers VALUES(2,'month','picker.replace','monthRunUsagePicklist','','',',','');
INSERT INTO form_field_choosers VALUES(3,'output_format','picker.replace','instrumentRunUsageFormatPicklist','','',',','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'Dataset_ID','invoke_entity','value','datasetid/show/','');
COMMIT;
