PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','V_Operations_User_List_Report');
INSERT INTO general_params VALUES('list_report_data_sort_col','Operation');
INSERT INTO general_params VALUES('list_report_data_sort_dir','ASC');
INSERT INTO general_params VALUES('detail_report_data_table','V_Operations_User_Detail_Report');
INSERT INTO general_params VALUES('detail_report_data_id_col','Operation');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_operation','Operation','20!','','Operation','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_username','User','','','Assigned Users','ContainsText','text','','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'Operation','invoke_entity','value','user_operation/show','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO detail_report_hotlinks VALUES(1,'Assigned Users','tabular_link_list','Assigned Users','user/report/','valueCol','',NULL);
COMMIT;
