PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('base_table','T_EUS_UsageType');
INSERT INTO "general_params" VALUES('list_report_data_table','V_EUS_Usage_Type_List_Report');
INSERT INTO "general_params" VALUES('list_report_data_sort_col','ID');
INSERT INTO "general_params" VALUES('list_report_data_sort_dir','ASC');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO "list_report_primary_filter" VALUES(1,'ID','ID','','','ID','Equals','int','','','');
INSERT INTO "list_report_primary_filter" VALUES(2,'Name','Name','','','Name','ContainsText','text','','','');
INSERT INTO "list_report_primary_filter" VALUES(3,'Enabled','Enabled','','','Enabled','Equals','int','','','');
INSERT INTO "list_report_primary_filter" VALUES(4,'Enabled_Campaign','Enabled Campaign','','','Enabled_Campaign','Equals','int','','','');
INSERT INTO "list_report_primary_filter" VALUES(5,'Enabled_Sample_Prep','Enabled Sample Prep','','','Enabled_Prep_Request','Equals','int','','','');
COMMIT;
