PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('list_report_data_table','V_Run_Factors_Export');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO "list_report_primary_filter" VALUES(1,'pf_factor','Factor','20','','Factor','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(2,'pf_value','Value','20','','Value','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(3,'pf_request','Request','20','','Request','Equals','text','20','','');
INSERT INTO "list_report_primary_filter" VALUES(4,'pf_batch','Batch','20','','Batch','Equals','text','20','','');
INSERT INTO "list_report_primary_filter" VALUES(5,'pf_datasetid','DatasetID','20','','DatasetID','Equals','text','20','','');
INSERT INTO "list_report_primary_filter" VALUES(6,'pf_dataset','Dataset','20','','Dataset','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(7,'pf_experiment','Experiment','20','','Experiment','ContainsText','text','50','','');
INSERT INTO "list_report_primary_filter" VALUES(8,'pf_campaign','Campaign','20','','Campaign','ContainsText','text','64','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO "list_report_hotlinks" VALUES(1,'Campaign','invoke_entity','value','campaign/show','');
INSERT INTO "list_report_hotlinks" VALUES(2,'Experiment','invoke_entity','value','experiment/show','');
INSERT INTO "list_report_hotlinks" VALUES(3,'Dataset','invoke_entity','value','dataset/show','');
INSERT INTO "list_report_hotlinks" VALUES(4,'Batch','invoke_entity','value','requested_run_batch/show','');
INSERT INTO "list_report_hotlinks" VALUES(5,'Request','invoke_entity','value','requested_run/show','');
COMMIT;
