PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','V_Analysis_Tool_Report');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_name','Name','60','','Name','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_resulttype','ResultType','60','','ResultType','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_allowed_inst_classes','Allowed Inst. Classes','60','','Allowed Inst. Classes','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_allowed_ds_types','Allowed DS Types','60','','Allowed DS Types','ContainsText','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'Allowed DS Types','min_col_width','value','90','');
INSERT INTO list_report_hotlinks VALUES(2,'Allowed Inst. Classes','min_col_width','value','70','');
INSERT INTO list_report_hotlinks VALUES(3,'Name','invoke_entity','value','analysis_job/report/-/-/~@/-/-/-/-/-/52/-','');
COMMIT;
