PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO "general_params" VALUES('list_report_data_table','V_Data_Package_Analysis_Jobs_List_Report');
INSERT INTO "general_params" VALUES('my_db_group','package');
INSERT INTO "general_params" VALUES('list_report_data_sort_col','ID, Job');
INSERT INTO "general_params" VALUES('list_report_data_sort_dir','asc');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO "list_report_primary_filter" VALUES(1,'pf_id','ID','','','ID','Equals','text','24','','');
INSERT INTO "list_report_primary_filter" VALUES(2,'pf_tool','Tool','','','Tool','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(3,'pf_job','Job','','','Job','Equals','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(4,'pf_dataset','Dataset','45!','','Dataset','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(5,'pf_parm_file','Parm File','25!','','Parm File','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(6,'pf_protein_collection_list','Protein Collection List','25!','','Protein Collection List','ContainsText','text','255','','');
INSERT INTO "list_report_primary_filter" VALUES(7,'pf_most_recent_weeks','Most Recent Weeks','','','Finished','MostRecentWeeks','text','32','','');
INSERT INTO "list_report_primary_filter" VALUES(8,'pf_settings_file','Settings File','15!','','Settings_File','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(9,'pf_job_comment','Job Comment','','','Comment','ContainsText','text','128','','');
INSERT INTO "list_report_primary_filter" VALUES(10,'pf_pkg_comment','Package Comment','','','Package_Comment','ContainsText','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO "list_report_hotlinks" VALUES(1,'Job','invoke_entity','value','analysis_job/show','');
INSERT INTO "list_report_hotlinks" VALUES(2,'ID','invoke_entity','value','data_package/show','');
INSERT INTO "list_report_hotlinks" VALUES(3,'Dataset_ID','invoke_entity','value','datasetid/show','');
INSERT INTO "list_report_hotlinks" VALUES(4,'Results URL','masked_link','value','','{"Label":"Browse"}');
COMMIT;
