PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE home_menu_sections (
    "id" INTEGER PRIMARY KEY NOT NULL,
    "section_name" TEXT,
    "section_header" TEXT,
    "section_number" TEXT,
    "section_comment" TEXT
);
INSERT INTO home_menu_sections VALUES(1,'General','General','1','The DMS is part of PRISM, the Proteomics Research Information Storage and Management System. DMS acquires data from mass spectrometers, collects laboratory information, and tracks and controls the intermediate data processing. ');
INSERT INTO home_menu_sections VALUES(2,'Campaign','Campaign','2','Campaign is the overarching umbrella for a particular research interest. Everything in DMS flows up to a campaign.');
INSERT INTO home_menu_sections VALUES(3,'Material Storage','Material Storage','3','Material Storage is used to keep track of Biomaterial and injectable samples (Experiments) in our freezers. All tracked biomaterial must be in a container and that container (box) must have its freezer location recorded in DMS.');
INSERT INTO home_menu_sections VALUES(4,'Biomaterial','Cell Culture/Biomaterial','4','Biomaterial/Cell Culture refers to the physical sample of biological material, often in its raw form. It is usually something sent to us by a user or collaborator.');
INSERT INTO home_menu_sections VALUES(5,'Sample Prep','Sample Preparation','5','Biomaterial is typically processed into injectable samples (Experiments) by one or more of the sample prep staff.  There is a request system for PIs and post-docs to use for scheduling sample preparation.');
INSERT INTO home_menu_sections VALUES(6,'Experiments','Experiments (Prepared Sample)','6','Experiments are injectable samples that are prepared from biomaterial. All experiments must be entered into DMS in order to be run on the instruments. You would enter a sample prep request to have your biomaterial processed into experiments.');
INSERT INTO home_menu_sections VALUES(7,'Requested Run','Requested Run','7','A Requested Run is a request that a specific experiment be run on an LCMS instrument to produce a Dataset.  An individual LCMS request must be entered for each instrument run, including replicates and blanks.');
INSERT INTO home_menu_sections VALUES(8,'Datasets','Datasets (LCMS Run)','8','Datasets represent a specific injectable sample (i.e. an aliquot of an Experiment) that is run on a particular instrument. An individual LCMS request must be entered for each instrument run, including replicates and blanks.');
INSERT INTO home_menu_sections VALUES(9,'Analysis Request','Analysis Job Request','9','An Analysis Job Request is a request that data analysis be performed on one or more Datasets.');
INSERT INTO home_menu_sections VALUES(10,'Data Analysis','Data Analysis','10','An analysis job is an automated process that analyzes the spectra for a single Dataset using a specific analysis tool (SEQUEST / X!Tandem/ ICR-2LS, etc.). You must enter an analysis job request to define the analysis job to be run.');
CREATE TABLE home_menu_items (
    "id" INTEGER PRIMARY KEY,
    "section_name" TEXT,
    "page" TEXT,
    "link" TEXT,
    "label" TEXT
);
INSERT INTO home_menu_items VALUES(1,'Biomaterial','biomaterial/report','Display','a list of existing biomaterial items');
INSERT INTO home_menu_items VALUES(2,'Biomaterial','biomaterial/create','Create','a new biomaterial item');
INSERT INTO home_menu_items VALUES(4,'Biomaterial','biomaterial/search','Search','for existing biomaterial items');
INSERT INTO home_menu_items VALUES(5,'Biomaterial','organism/report','Display','a list of existing organisms');
INSERT INTO home_menu_items VALUES(6,'Biomaterial','organism/create','Create','a new organism');
INSERT INTO home_menu_items VALUES(7,'Biomaterial','upload/main','Load','biomaterial from spreadsheet tsv file');
INSERT INTO home_menu_items VALUES(8,'Campaign','campaign/report','Display','a list of existing research campaigns');
INSERT INTO home_menu_items VALUES(9,'Campaign','campaign/create','Create','a new research campaign');
INSERT INTO home_menu_items VALUES(10,'Campaign','campaign/search','Search','for an existing campaign');
INSERT INTO home_menu_items VALUES(12,'Analysis Request','analysis_job_request/report/-/-/-/-','Display','a list of analysis job requests');
INSERT INTO home_menu_items VALUES(13,'Analysis Request','analysis_job_request_psm/create','Create','a new MS/MS search request');
INSERT INTO home_menu_items VALUES(14,'Analysis Request','analysis_job_request/create','Create','a new analysis job request');
INSERT INTO home_menu_items VALUES(15,'Analysis Request','upload/main','Load','analysis job requests from spreadsheet tsv file');
INSERT INTO home_menu_items VALUES(16,'Data Analysis','analysis_job/report','Display','a list of existing analysis jobs');
INSERT INTO home_menu_items VALUES(17,'Data Analysis','analysis_job/search','Search','for an existing analysis job');
INSERT INTO home_menu_items VALUES(18,'Data Analysis','analysis_job/report/-/-/StartsWith__Decon2LS','Display','a list of Decon2LS analysis jobs');
INSERT INTO home_menu_items VALUES(19,'Data Analysis','analysis_job/report/-/-/StartsWith__MASIC','Display','a list of MASIC analysis jobs');
INSERT INTO home_menu_items VALUES(20,'Data Analysis','analysis_job/report/-/-/StartsWith__MODa','Display','a list of MODa analysis jobs');
INSERT INTO home_menu_items VALUES(21,'Data Analysis','analysis_job/report/-/-/StartsWith__MSAlign','Display','a list of MSAlign analysis jobs');
INSERT INTO home_menu_items VALUES(22,'Data Analysis','analysis_job/report/-/-/StartsWith__MSGFPlus','Display','a list of MSGFPlus analysis jobs');
INSERT INTO home_menu_items VALUES(23,'Data Analysis','analysis_job/report/-/-/StartsWith__MSPathFinder','Display','a list of MSPathFinder analysis jobs');
INSERT INTO home_menu_items VALUES(24,'Data Analysis','analysis_job/report/-/-/StartsWith__MSXML_Gen','Display','a list of MSXML_Gen analysis jobs');
INSERT INTO home_menu_items VALUES(25,'Data Analysis','analysis_job/report/-/-/StartsWith__NOMSI','Display','a list of NOMSI analysis jobs');
INSERT INTO home_menu_items VALUES(26,'Data Analysis','analysis_job/report/-/-/StartsWith__Phospho_FDR_Aggregator','Display','a list of Phospho_FDR_Aggregator analysis jobs');
INSERT INTO home_menu_items VALUES(27,'Data Analysis','analysis_job/report/-/-/StartsWith__PRIDE_Converter','Display','a list of PRIDE_Converter analysis jobs');
INSERT INTO home_menu_items VALUES(28,'Data Analysis','analysis_job/report/-/-/StartsWith__SEQUEST','Display','a list of SEQUEST analysis jobs');
INSERT INTO home_menu_items VALUES(29,'Data Analysis','analysis_job/report/-/-/StartsWith__XTandem','Display','a list of X!Tandem analysis jobs');
INSERT INTO home_menu_items VALUES(30,'Data Analysis','get_paramfile_crosstab/param','Display','the paramfile crosstab report');
INSERT INTO home_menu_items VALUES(31,'Requested Run','requested_run/report','Display','a list of existing requested runs');
INSERT INTO home_menu_items VALUES(32,'Requested Run','requested_run/create','Create','a new requested run (for experiment)');
INSERT INTO home_menu_items VALUES(33,'Requested Run','requested_run_group/create','Create','new requested runs (for experiment group)');
INSERT INTO home_menu_items VALUES(34,'Requested Run','requested_run/search','Search','for existing requested runs');
INSERT INTO home_menu_items VALUES(35,'Requested Run','upload/main','Load','requested runs from spreadsheet tsv file');
INSERT INTO home_menu_items VALUES(36,'Datasets','dataset/report','Display','a list of existing datasets');
INSERT INTO home_menu_items VALUES(37,'Datasets','dataset/search','Search','for existing datasets');
INSERT INTO home_menu_items VALUES(38,'Datasets','dataset_disposition/search','Disposition','pending datasets');
INSERT INTO home_menu_items VALUES(39,'Datasets','dataset_redisposition/create','Redisposition','datasets that have been released');
INSERT INTO home_menu_items VALUES(40,'Datasets','run_planning/report','Display','the planning report');
INSERT INTO home_menu_items VALUES(41,'Datasets','production_instrument_stats/param','Display','production instrument statistics report');
INSERT INTO home_menu_items VALUES(42,'Experiments','experiment/report','Display','a list of existing experiments');
INSERT INTO home_menu_items VALUES(43,'Experiments','experiment/create','Create','a new experiment');
INSERT INTO home_menu_items VALUES(44,'Experiments','experiment/search','Search','for existing experiments');
INSERT INTO home_menu_items VALUES(45,'Experiments','experiment_group/report','Display','a list of existing experiment groups');
INSERT INTO home_menu_items VALUES(46,'Experiments','experiment_fraction/create','Create','a new experiment fraction group');
INSERT INTO home_menu_items VALUES(47,'Experiments','experiment_group/create','Create','a new group for existing experiments');
INSERT INTO home_menu_items VALUES(48,'Experiments','experiment_plex_members/create','Create','a new experiment plex mapping');
INSERT INTO home_menu_items VALUES(49,'Material Storage','material_container/report/-/-/-/-/Active','Display','list of active material containers');
INSERT INTO home_menu_items VALUES(50,'Material Storage','material_container/create','Create','a new storage container');
INSERT INTO home_menu_items VALUES(51,'Material Storage','material_items/report/-/-/-/-/-/Active','Display','list of active material items');
INSERT INTO home_menu_items VALUES(52,'Material Storage','material_location/report/-/-/-/-/-/-/Active','Display','a list of active material locations');
INSERT INTO home_menu_items VALUES(53,'Material Storage','material_move_container/report/-/-/-','Move','containers between locations');
INSERT INTO home_menu_items VALUES(54,'Material Storage','material_move_items/report/-/-/-','Move','material (Biomaterial, Experiments) between containers');
INSERT INTO home_menu_items VALUES(55,'Material Storage','material_log/report/-/-/-','Display','material movement and status log');
INSERT INTO home_menu_items VALUES(56,'Material Storage','wellplate/report/-/-/-','Display','a list of existing wellplates');
INSERT INTO home_menu_items VALUES(57,'Material Storage','wellplate/create','Create','a new wellplate');
INSERT INTO home_menu_items VALUES(58,'Sample Prep','sample_prep_request/report/-/-/-/-','Display','a list of all existing sample prep requests');
INSERT INTO home_menu_items VALUES(59,'Sample Prep','sample_prep_request/create','Create','a new sample prep request');
INSERT INTO home_menu_items VALUES(60,'Sample Prep','sample_prep_request/search','Search','for existing sample prep requests');
INSERT INTO home_menu_items VALUES(61,'Sample Prep','sample_prep_request_assignment/report','Assign','staff to requests (admin function)');
INSERT INTO home_menu_items VALUES(62,'Sample Prep','prep_lc_run/report','Display','a list of all prep LC runs');
INSERT INTO home_menu_items VALUES(63,'Sample Prep','prep_lc_run/create','Create','a new prep LC run');
INSERT INTO home_menu_items VALUES(64,'Sample Prep','prep_lc_column/report','Display','a list of all prep LC columns');
INSERT INTO home_menu_items VALUES(65,'Sample Prep','prep_lc_column/create','Create','a new prep LC column');
INSERT INTO home_menu_items VALUES(66,'Campaign','staff_roles/report','Display','a list of staff roles and assignments');
CREATE TABLE menu_def (
    "id" INTEGER PRIMARY KEY,
    "owner_menu" TEXT,
    "item_type" TEXT,
    "item_name" TEXT,
    "item_label" TEXT
);
INSERT INTO menu_def VALUES(1,'','submenu','Datasets','Datasets');
INSERT INTO menu_def VALUES(2,'Datasets','link','dataset/report','Report');
INSERT INTO menu_def VALUES(3,'Datasets','link','dataset/search','Search');
INSERT INTO menu_def VALUES(4,'Datasets','link','dataset/create','Entry');
INSERT INTO menu_def VALUES(5,'Datasets','link','dataset_disposition/search','Disposition');
INSERT INTO menu_def VALUES(6,'Datasets','link','dataset_disposition_lite','Disposition (No plots)');
INSERT INTO menu_def VALUES(7,'Datasets','link','main_log/report','Log');
INSERT INTO menu_def VALUES(8,'Datasets','submenu','Dataset QC Reports','QC Reports');
INSERT INTO menu_def VALUES(9,'Datasets','submenu','Dataset PSM Reports','PSM Reports');
INSERT INTO menu_def VALUES(10,'Datasets','submenu','Dataset Special Reports','Special Reports');
INSERT INTO menu_def VALUES(11,'Dataset QC Reports','link','dataset_qc/search','Dataset QC Report');
INSERT INTO menu_def VALUES(12,'Dataset QC Reports','link','dataset_qc_ions/report/','Dataset QC Ions');
INSERT INTO menu_def VALUES(13,'Dataset QC Reports','link','reporter_ion_observation_rate/search','Rep Ion Obs Rate Report');
INSERT INTO menu_def VALUES(14,'Dataset QC Reports','link','data_package_dataset_qc/search','Data Package Dataset QC');
INSERT INTO menu_def VALUES(15,'Dataset PSM Reports','link','dataset_psm/report/4/StartsWith__msgfplus','Dataset PSM Stats (MS-GF+)');
INSERT INTO menu_def VALUES(17,'Dataset PSM Reports','link','dataset_psm/report/4/StartsWith__DiaNN','Dataset PSM Stats (DiaNN)');
INSERT INTO menu_def VALUES(18,'Dataset PSM Reports','link','data_package_dataset_psm/report/-/4/StartsWith__msgfplus','Data Pkg Dataset PSM Stats');
INSERT INTO menu_def VALUES(19,'Dataset PSM Reports','link','data_package_analysis_job_psm/report/-/-/-/StartsWith__msgfplus','Data Pkg Job PSM Stats');
INSERT INTO menu_def VALUES(20,'Dataset PSM Reports','link','analysis_job_psm/report/','Job PSM Stats');
INSERT INTO menu_def VALUES(21,'Dataset Special Reports','link','ai_user_funded_datasets_list_report/report/-/-/-/-/12','User funded');
INSERT INTO menu_def VALUES(22,'Dataset Special Reports','link','dataset_funding/report/-/-/-/-/12','All funded');
INSERT INTO menu_def VALUES(23,'Dataset Special Reports','link','dataset_instrument/report','Instrument Usage');
INSERT INTO menu_def VALUES(25,'Dataset Special Reports','link','production_instrument_stats/param','Dataset Production Statistics');
INSERT INTO menu_def VALUES(26,'Datasets','separator','','');
INSERT INTO menu_def VALUES(27,'','submenu','Experiments','Experiments');
INSERT INTO menu_def VALUES(28,'Experiments','link','experiment/report','Report');
INSERT INTO menu_def VALUES(29,'Experiments','link','experiment/search','Search');
INSERT INTO menu_def VALUES(30,'Experiments','link','experiment/create','Entry');
INSERT INTO menu_def VALUES(31,'Experiments','submenu','Experiment Groups','Groups');
INSERT INTO menu_def VALUES(32,'Experiment Groups','link','experiment_group/report','Report');
INSERT INTO menu_def VALUES(33,'Experiment Groups','link','experiment_fraction/create','Make Fraction Group');
INSERT INTO menu_def VALUES(34,'Experiment Groups','link','experiment_group/create','Make General Group');
INSERT INTO menu_def VALUES(35,'Experiments','submenu','Experiment Factors','Factors');
INSERT INTO menu_def VALUES(36,'Experiment Factors','link','requested_run_factors/param','Define Factors');
INSERT INTO menu_def VALUES(37,'Experiment Factors','link','factors/grid','Define Factors (grid)');
INSERT INTO menu_def VALUES(38,'Experiment Factors','link','custom_factors/report/-','Browse Factors');
INSERT INTO menu_def VALUES(39,'Experiments','submenu','Experiment Labelling','Labelling');
INSERT INTO menu_def VALUES(40,'Experiment Labelling','link','experiment_plex_members/report/-/-/-','Plex Members');
INSERT INTO menu_def VALUES(41,'Experiment Labelling','link','experiment_plex_members_tsv/report/-/-/-','Plex Members TSV');
INSERT INTO menu_def VALUES(42,'Experiment Labelling','link','experiment_plex_members/create','Plex Members Entry');
INSERT INTO menu_def VALUES(43,'Experiment Labelling','link','sample_label_reporter_ions/report/-/-/-','Reporter Ions');
INSERT INTO menu_def VALUES(44,'Experiments','submenu','Experiment Organisms','Organisms');
INSERT INTO menu_def VALUES(45,'Experiment Organisms','link','organism/report','Report');
INSERT INTO menu_def VALUES(46,'Experiment Organisms','link','organism/create','Entry');
INSERT INTO menu_def VALUES(47,'Experiments','separator','','');
INSERT INTO menu_def VALUES(48,'','submenu','Biomaterial','Biomaterial');
INSERT INTO menu_def VALUES(49,'Biomaterial','link','biomaterial/report','Report');
INSERT INTO menu_def VALUES(50,'Biomaterial','link','biomaterial/search','Search');
INSERT INTO menu_def VALUES(51,'Biomaterial','link','biomaterial/create','Entry');
INSERT INTO menu_def VALUES(52,'','submenu','Campaigns','Campaigns');
INSERT INTO menu_def VALUES(53,'Campaigns','link','campaign/report','Report');
INSERT INTO menu_def VALUES(54,'Campaigns','link','campaign/search','Search');
INSERT INTO menu_def VALUES(55,'Campaigns','link','campaign/create','Entry');
INSERT INTO menu_def VALUES(56,'Campaigns','link','staff_roles/report','Staff Roles');
INSERT INTO menu_def VALUES(57,'Campaigns','link','campaign_dataset_stats/param','Campaign Dataset Stats');
INSERT INTO menu_def VALUES(58,'','separator ','','');
INSERT INTO menu_def VALUES(59,'','submenu','Sample Prep','Sample Prep');
INSERT INTO menu_def VALUES(60,'Sample Prep','submenu','Sample Prep Report','Report');
INSERT INTO menu_def VALUES(61,'Sample Prep Report','link','sample_prep_request/report/-/-/-/-','All');
INSERT INTO menu_def VALUES(62,'Sample Prep Report','link','sample_prep_request/report/~Pending Approval','Pending Approval');
INSERT INTO menu_def VALUES(63,'Sample Prep Report','link','sample_prep_request/report/~Open','Open');
INSERT INTO menu_def VALUES(64,'Sample Prep Report','link','sample_prep_request/report/~Prep in Progress','Prep in Progress');
INSERT INTO menu_def VALUES(65,'Sample Prep Report','link','sample_prep_request/report/~Prep Complete','Prep Complete');
INSERT INTO menu_def VALUES(66,'Sample Prep Report','link','sample_prep_request/report/~Closed','Closed');
INSERT INTO menu_def VALUES(67,'Sample Prep Report','link','sample_prep_request_active/report','Active');
INSERT INTO menu_def VALUES(68,'Sample Prep','link','sample_prep_request/create','Entry');
INSERT INTO menu_def VALUES(69,'Sample Prep','link','sample_prep_request_assignment/report/-/:Closed','Assignment');
INSERT INTO menu_def VALUES(70,'Sample Prep','link','sample_prep_request_planning/report/','Planning Report');
INSERT INTO menu_def VALUES(71,'Sample Prep','submenu','Sample Prep Report Active','Active (by staff)');
INSERT INTO menu_def VALUES(72,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Burnet','Burnet');
INSERT INTO menu_def VALUES(73,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Garcia','Garcia');
INSERT INTO menu_def VALUES(74,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Gritsenko','Gritsenko');
INSERT INTO menu_def VALUES(75,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Hutchinson','Hutchinson');
INSERT INTO menu_def VALUES(76,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Kwon','Kwon');
INSERT INTO menu_def VALUES(77,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Nicora','Nicora');
INSERT INTO menu_def VALUES(78,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Nieto','Nieto');
INSERT INTO menu_def VALUES(79,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Paurus','Paurus');
INSERT INTO menu_def VALUES(80,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Olson','Olson');
INSERT INTO menu_def VALUES(81,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Prozapas','Prozapas');
INSERT INTO menu_def VALUES(82,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Schepmoes','Schepmoes');
INSERT INTO menu_def VALUES(85,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Tate','Tate');
INSERT INTO menu_def VALUES(86,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Trejo','Trejo');
INSERT INTO menu_def VALUES(87,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Velickovic','Velickovic');
INSERT INTO menu_def VALUES(88,'Sample Prep Report Active','link','sample_prep_request_active/report/-/-/-/-/-/Williams','Williams');
INSERT INTO menu_def VALUES(90,'Sample Prep','submenu','OSM Packages','OSM Packages');
INSERT INTO menu_def VALUES(91,'OSM Packages','link','osm_package/report','Report');
INSERT INTO menu_def VALUES(92,'OSM Packages','link','osm_package/create','Entry');
INSERT INTO menu_def VALUES(106,'Sample Prep','submenu','Transcriptomics','Transcriptomics');
INSERT INTO menu_def VALUES(107,'Transcriptomics','link','rna_prep_request/report/-/-/-/-','Requests');
INSERT INTO menu_def VALUES(108,'Transcriptomics','link','rna_prep_request/create','Entry');
INSERT INTO menu_def VALUES(109,'Sample Prep','separator','','');
INSERT INTO menu_def VALUES(110,'','submenu','Prep LC','Prep LC');
INSERT INTO menu_def VALUES(111,'Prep LC','submenu','Prep LC Columns','Prep LC Columns');
INSERT INTO menu_def VALUES(112,'Prep LC Columns','link','prep_lc_column/report/-/-/-/-/NoMatch__Retired','Report');
INSERT INTO menu_def VALUES(113,'Prep LC Columns','link','prep_lc_column/create','Entry');
INSERT INTO menu_def VALUES(114,'Prep LC','submenu','Prep LC Runs','Prep LC Runs');
INSERT INTO menu_def VALUES(115,'Prep LC Runs','link','prep_lc_run/report','Report');
INSERT INTO menu_def VALUES(116,'Prep LC Runs','link','prep_lc_run/create','Entry');
INSERT INTO menu_def VALUES(117,'','separator',' ',' ');
INSERT INTO menu_def VALUES(118,'','submenu','Material Storage','Material Storage');
INSERT INTO menu_def VALUES(119,'Material Storage','link','material_location_available/report/-/-/-','Available Locations');
INSERT INTO menu_def VALUES(120,'Material Storage','link','material_location/report/-/-/-/-/-/-/Active','Active Locations');
INSERT INTO menu_def VALUES(121,'Material Storage','link','material_container/report/-/-/-/-/Active','Active Containers');
INSERT INTO menu_def VALUES(122,'Material Storage','link','material_items/report/-/-/-/-/-/Active','Active Items');
INSERT INTO menu_def VALUES(123,'Material Storage','link','freezers/report','Freezers');
INSERT INTO menu_def VALUES(124,'Material Storage','link','freezer/tree','Freezer Location Mgmt');
INSERT INTO menu_def VALUES(125,'Material Storage','link','material_container/create','New Container');
INSERT INTO menu_def VALUES(126,'Material Storage','link','material_log/report/-/-/-','Log');
INSERT INTO menu_def VALUES(127,'Material Storage','link','requested_run_batch_location_history/report','Batch Location History');
INSERT INTO menu_def VALUES(128,'','submenu','Reference Compounds','Reference Compounds');
INSERT INTO menu_def VALUES(129,'Reference Compounds','link','reference_compound/report','Report');
INSERT INTO menu_def VALUES(131,'Reference Compounds','link','reference_compound/create','Entry');
INSERT INTO menu_def VALUES(132,'','submenu','Sample Submission','Sample Submission');
INSERT INTO menu_def VALUES(133,'Sample Submission','link','sample_submission/report','Report');
INSERT INTO menu_def VALUES(134,'Sample Submission','link','sample_submission/create','Entry');
INSERT INTO menu_def VALUES(135,'','submenu','Wellplates','Wellplates');
INSERT INTO menu_def VALUES(136,'Wellplates','link','wellplate/report/-/-/-','Report');
INSERT INTO menu_def VALUES(137,'Wellplates','link','wellplate/create','Entry');
INSERT INTO menu_def VALUES(138,'','separator','','');
INSERT INTO menu_def VALUES(139,'','submenu','Data Analysis','Data Analysis');
INSERT INTO menu_def VALUES(140,'Data Analysis','submenu','Data Analysis Reports','Reports (last 12 months)');
INSERT INTO menu_def VALUES(141,'Data Analysis Reports','link','analysis_job/report/-/-/-/-/-/-/-/-/52','All');
INSERT INTO menu_def VALUES(143,'Data Analysis Reports','link','analysis_job/report/-/-/StartsWith__MSGFPlus/-/-/-/-/-/52','MS-GF+');
INSERT INTO menu_def VALUES(145,'Data Analysis Reports','link','analysis_job/report/-/-/StartsWith__Decon2LS/-/-/-/-/-/52','DeconTools');
INSERT INTO menu_def VALUES(150,'Data Analysis Reports','link','analysis_job/report/-/-/StartsWith__MASIC/-/-/-/-/-/52','MASIC');
INSERT INTO menu_def VALUES(151,'Data Analysis Reports','link','analysis_job/report/-/-/StartsWith__MSPathFinder/-/-/-/-/-/52','MSPathFinder');
INSERT INTO menu_def VALUES(152,'Data Analysis Reports','link','analysis_job/report/-/-/StartsWith__XTandem/-/-/-/-/-/52','X!Tandem');
INSERT INTO menu_def VALUES(153,'Data Analysis','link','analysis_job/search','Search');
INSERT INTO menu_def VALUES(154,'Data Analysis','submenu','Analysis Job Requests','Job Requests');
INSERT INTO menu_def VALUES(155,'Analysis Job Requests','link','analysis_job_request/report/-/-/-/-','All');
INSERT INTO menu_def VALUES(156,'Analysis Job Requests','link','analysis_job_request/report/New','New');
INSERT INTO menu_def VALUES(157,'Analysis Job Requests','link','analysis_job_request/report/Used','Used');
INSERT INTO menu_def VALUES(159,'Analysis Job Requests','separator','','');
INSERT INTO menu_def VALUES(161,'Analysis Job Requests','link','analysis_job_request_psm/create','MS/MS Job Request Wizard');
INSERT INTO menu_def VALUES(162,'Analysis Job Requests','link','analysis_job_request/create','Create generic request');
INSERT INTO menu_def VALUES(164,'Analysis Job Requests','link','pipeline_job_steps/report/-/-/-/StartsWith__running','Running Job Steps');
INSERT INTO menu_def VALUES(165,'Data Analysis','submenu','MAC Jobs','MAC Jobs');
INSERT INTO menu_def VALUES(166,'MAC Jobs','link','pipeline_jobs/report/-/-/~Aggregation','Report');
INSERT INTO menu_def VALUES(167,'MAC Jobs','link','pipeline_jobs_history/report/-/-/~Aggregation','Report (older jobs)');
INSERT INTO menu_def VALUES(169,'MAC Jobs','link','pipeline_jobs/create','Create generic MAC Job');
INSERT INTO menu_def VALUES(170,'Data Analysis','link','protein_collection/report','Protein Collections');
INSERT INTO menu_def VALUES(171,'Data Analysis','submenu','Analysis Job PSM Stats','PSM Stats');
INSERT INTO menu_def VALUES(172,'Analysis Job PSM Stats','link','dataset_psm/report/4/StartsWith__msgfplus','Dataset PSM Stats (MS-GF+)');
INSERT INTO menu_def VALUES(173,'Analysis Job PSM Stats','link','dataset_psm/report/4/StartsWith__DiaNN','Dataset PSM Stats (DiaNN)');
INSERT INTO menu_def VALUES(174,'Analysis Job PSM Stats','link','data_package_dataset_psm/report/-/4/StartsWith__msgfplus','Data Pkg Dataset PSM Stats');
INSERT INTO menu_def VALUES(175,'Analysis Job PSM Stats','link','data_package_analysis_job_psm/report/-/-/-/StartsWith__msgfplus','Data Pkg Job PSM Stats');
INSERT INTO menu_def VALUES(176,'Analysis Job PSM Stats','link','analysis_job_psm/report/','Job PSM Stats');
INSERT INTO menu_def VALUES(177,'Analysis Job PSM Stats','link','dataset_pm_and_psm/report/4/-/Exact','High Res Peak Matching Stats');
INSERT INTO menu_def VALUES(178,'Data Analysis','submenu','Data Analysis Requests','Data Analysis Requests');
INSERT INTO menu_def VALUES(179,'Data Analysis Requests','link','data_analysis_request/report/-/-/-/-/-/-/-/-/-/-/-','All');
INSERT INTO menu_def VALUES(180,'Data Analysis Requests','link','data_analysis_request/report/ExactMatch__New/-/-/-/-/-/-/-/-/-/-','New');
INSERT INTO menu_def VALUES(181,'Data Analysis Requests','link','data_analysis_request/report/-/-/Lipidomics/-/-/-/-/-/-/-','Lipidomics');
INSERT INTO menu_def VALUES(182,'Data Analysis Requests','link','data_analysis_request/report/-/-/Metabolomics/-/-/-/-/-/-/-','Metabolomics');
INSERT INTO menu_def VALUES(183,'Data Analysis Requests','link','data_analysis_request/report/-/-/Proteomics/-/-/-/-/-/-/-','Proteomics');
INSERT INTO menu_def VALUES(184,'Data Analysis Requests','link','data_analysis_request/create','Create new request');
INSERT INTO menu_def VALUES(185,'','submenu','Data Packages','Data Packages');
INSERT INTO menu_def VALUES(186,'Data Packages','submenu','Data Package Reports','Report');
INSERT INTO menu_def VALUES(188,'Data Package Reports','link','data_package/report','Data Packages');
INSERT INTO menu_def VALUES(189,'Data Package Reports','link','data_package_datasets/search','Data Package Datasets');
INSERT INTO menu_def VALUES(190,'Data Package Reports','link','data_package_jobs/search','Data Package Jobs');
INSERT INTO menu_def VALUES(191,'Data Package Reports','link','data_package_dataset_qc/search','Data Package Dataset QC');
INSERT INTO menu_def VALUES(192,'Data Packages','link','data_package/create','Entry');
INSERT INTO menu_def VALUES(193,'','separator','','');
INSERT INTO menu_def VALUES(194,'','submenu','MS Scheduling','MS Scheduling');
INSERT INTO menu_def VALUES(195,'MS Scheduling','submenu','Requested Run Reports','Reports');
INSERT INTO menu_def VALUES(197,'Requested Run Reports','link','requested_run/report/-/-/-/-','Requests - All');
INSERT INTO menu_def VALUES(198,'Requested Run Reports','link','requested_run/report/-/-/Active','Requests - Active');
INSERT INTO menu_def VALUES(199,'Requested Run Reports','link','requested_run/report/-/-/Inactive','Requests - Inactive');
INSERT INTO menu_def VALUES(200,'Requested Run Reports','link','requested_run/report/-/-/Completed','Requests - Completed');
INSERT INTO menu_def VALUES(201,'Requested Run Reports','link','run_planning/report','Planning Report');
INSERT INTO menu_def VALUES(202,'Requested Run Reports','link','requested_run_admin/report','Admin Report');
INSERT INTO menu_def VALUES(203,'Requested Run Reports','link','dataset_instrument_runtime/param','Instrument Runtimes');
INSERT INTO menu_def VALUES(204,'Requested Run Reports','url_link','https://protoapps.pnl.gov/datapkgs/Public/2022/4458_Instrument_Scheduling/','Instrument Scheduling');
INSERT INTO menu_def VALUES(205,'MS Scheduling','submenu','MS Scheduling Entry','Entry');
INSERT INTO menu_def VALUES(206,'MS Scheduling Entry','link','requested_run/create','Single Entry');
INSERT INTO menu_def VALUES(207,'MS Scheduling Entry','link','requested_run_group/create','From Experiment Group');
INSERT INTO menu_def VALUES(208,'','submenu','Task Queues','Task Queues');
INSERT INTO menu_def VALUES(209,'Task Queues','submenu','Ops Tasks','Ops Tasks');
INSERT INTO menu_def VALUES(210,'Ops Tasks','link','operations_tasks/report','Report');
INSERT INTO menu_def VALUES(211,'Ops Tasks','link','operations_tasks/report/-/-/-/:Completed','Active');
INSERT INTO menu_def VALUES(212,'Ops Tasks','link','operations_tasks/create','Create');
INSERT INTO menu_def VALUES(213,'Task Queues','submenu','Ops Tasks by Staff','Ops Tasks (by staff)');
INSERT INTO menu_def VALUES(214,'Ops Tasks by Staff','link','operations_tasks/report/-/-/StartsWith__Acosta/-/-','Acosta');
INSERT INTO menu_def VALUES(215,'Ops Tasks by Staff','link','operations_tasks/report/-/-/StartsWith__Culver/-/-','Culver');
INSERT INTO menu_def VALUES(216,'Ops Tasks by Staff','link','operations_tasks/report/-/-/StartsWith__Lawrence/-/-','Lawrence');
INSERT INTO menu_def VALUES(217,'Ops Tasks by Staff','link','operations_tasks/report/-/-/StartsWith__Lawver/-/-','Lawver');
INSERT INTO menu_def VALUES(218,'Ops Tasks by Staff','link','operations_tasks/report/-/-/StartsWith__Miller/-/-','Miller');
INSERT INTO menu_def VALUES(219,'Ops Tasks by Staff','link','operations_tasks/report/-/-/StartsWith__Prozapas/-/-','Prozapas');
INSERT INTO menu_def VALUES(220,'Ops Tasks by Staff','link','operations_tasks/report/-/-/StartsWith__Rosenstock/-/-','Rosenstock');
INSERT INTO menu_def VALUES(221,'Ops Tasks by Staff','link','operations_tasks/report/-/-/StartsWith__Wright/-/-','Wright');
INSERT INTO menu_def VALUES(222,'','submenu','Usage Tracking','Usage Tracking');
INSERT INTO menu_def VALUES(223,'Usage Tracking','link','run_tracking/cal','Inst. Usage Tracking');
INSERT INTO menu_def VALUES(224,'Usage Tracking','link','instrument_usage_report/grid','ERS Instrument Usage Grid');
INSERT INTO menu_def VALUES(225,'Usage Tracking','link','run_interval/report','Run Intervals');
INSERT INTO menu_def VALUES(226,'Usage Tracking','submenu','Tracking Datasets','Tracking Datasets');
INSERT INTO menu_def VALUES(227,'Tracking Datasets','link','tracking_dataset/report','Report');
INSERT INTO menu_def VALUES(228,'Tracking Datasets','link','tracking_dataset/create','Entry');
INSERT INTO menu_def VALUES(229,'MS Scheduling Entry','separator','','');
INSERT INTO menu_def VALUES(230,'MS Scheduling','submenu','MRM Transition List','MRM Transition List');
INSERT INTO menu_def VALUES(231,'MRM Transition List','link','mrm_list_attachment/report','Report');
INSERT INTO menu_def VALUES(232,'MRM Transition List','link','mrm_list_attachment/create','Upload');
INSERT INTO menu_def VALUES(233,'MRM Transition List','separator',' ',' ');
INSERT INTO menu_def VALUES(234,'MS Scheduling','submenu','MS Scheduling Batches','Run Batches');
INSERT INTO menu_def VALUES(235,'MS Scheduling Batches','link','requested_run_batch/report','Report');
INSERT INTO menu_def VALUES(236,'MS Scheduling Batches','link','requested_run_batch/report/-/-/-/-/-/-/-/1','Report Active Requests');
INSERT INTO menu_def VALUES(237,'MS Scheduling Batches','link','requested_run_batch/report/-/-/-/-/-/-/High/1','Report High Priority');
INSERT INTO menu_def VALUES(238,'MS Scheduling Batches','link','requested_run_batch/create','Entry');
INSERT INTO menu_def VALUES(239,'MS Scheduling Batches','link','requested_run_batch_group/report','Batch Groups');
INSERT INTO menu_def VALUES(240,'MS Scheduling Batches','link','batch_tracking/report/-/-/-/-','Tracking');
INSERT INTO menu_def VALUES(241,'MS Scheduling Batches','link','requested_run_batch_location_history/report','Location History');
INSERT INTO menu_def VALUES(242,'MS Scheduling Batches','separator','','');
INSERT INTO menu_def VALUES(243,'MS Scheduling','submenu','Requested Run Blocking','Run Blocking');
INSERT INTO menu_def VALUES(244,'Requested Run Blocking','separator','','');
INSERT INTO menu_def VALUES(245,'Requested Run Blocking','link','requested_run_batch_blocking/param','Define Blocking');
INSERT INTO menu_def VALUES(246,'Requested Run Blocking','link','requested_run_batch_blocking/grid','Define Blocking (grid)');
INSERT INTO menu_def VALUES(247,'MS Scheduling','submenu','Requested Run Factors','Run Factors');
INSERT INTO menu_def VALUES(249,'Requested Run Factors','link','requested_run_factors/param','Define Factors');
INSERT INTO menu_def VALUES(250,'Requested Run Factors','link','factors/grid','Define Factors (grid)');
INSERT INTO menu_def VALUES(251,'Requested Run Factors','link','custom_factors/report/-','Browse Factors');
INSERT INTO menu_def VALUES(252,'','separator',' ',' ');
INSERT INTO menu_def VALUES(253,'MS Scheduling','link','run_assignment_wellplate/report','Wellplates');
INSERT INTO menu_def VALUES(254,'','submenu','MS LC','MS LC');
INSERT INTO menu_def VALUES(255,'MS LC','submenu','LC Columns','LC Columns');
INSERT INTO menu_def VALUES(256,'LC Columns','link','lc_column/report','Report');
INSERT INTO menu_def VALUES(257,'LC Columns','link','lc_column/create','Entry');
INSERT INTO menu_def VALUES(258,'LC Columns','submenu','Special LC Columns Reports','Special Reports');
INSERT INTO menu_def VALUES(259,'Special LC Columns Reports','link','lc_column_dataset/report','Dataset Count');
INSERT INTO menu_def VALUES(260,'LC Columns','separator',' ',' ');
INSERT INTO menu_def VALUES(261,'MS LC','submenu','LC Carts','LC Carts');
INSERT INTO menu_def VALUES(262,'LC Carts','link','lc_cart/report','Report');
INSERT INTO menu_def VALUES(263,'LC Carts','link','lc_cart/create','Entry');
INSERT INTO menu_def VALUES(265,'LC Carts','link','lc_cart_request_loading/report','Configure loading (Req)');
INSERT INTO menu_def VALUES(266,'LC Carts','link','lc_cart_loading/report','Loading List');
INSERT INTO menu_def VALUES(267,'LC Carts','link','lc_cart_configuration/report','LC Cart Configurations');
INSERT INTO menu_def VALUES(268,'LC Carts','link','lc_cart_config_history/report','LC Cart Service Notes');
INSERT INTO menu_def VALUES(269,'LC Carts','separator','','');
INSERT INTO menu_def VALUES(270,'MS LC','submenu','Instrument Config','Instrument Config.');
INSERT INTO menu_def VALUES(271,'Instrument Config','link','instrument_config/report','Inst. List');
INSERT INTO menu_def VALUES(272,'Instrument Config','link','instrument_config_history/report','Config. History');
INSERT INTO menu_def VALUES(273,'Instrument Config','link','instrument_config_history/create','New Inst. Service Note');
INSERT INTO menu_def VALUES(274,'Instrument Config','separator','','');
INSERT INTO menu_def VALUES(275,'MS LC','link','run_op_logs/grid','Operation Log Grid');
INSERT INTO menu_def VALUES(276,'MS LC','link','instrument_operation_history/report','Inst. Operation Notes ');
INSERT INTO menu_def VALUES(277,'','separator',' ',' ');
INSERT INTO menu_def VALUES(278,'','submenu','MTS','MTS');
INSERT INTO menu_def VALUES(279,'MTS','submenu','Databases','Databases');
INSERT INTO menu_def VALUES(280,'Databases','link','mts_pt_dbs/report','Peptide DBs');
INSERT INTO menu_def VALUES(281,'Databases','link','mts_mt_dbs/report','AMT Tag DBs');
INSERT INTO menu_def VALUES(283,'MTS','submenu','MTS DB Jobs','Database Jobs');
INSERT INTO menu_def VALUES(284,'MTS DB Jobs','link','mts_pt_db_jobs/report','Peptide DB Jobs');
INSERT INTO menu_def VALUES(285,'MTS DB Jobs','link','mts_mt_db_jobs/report','AMT Tag DB Jobs');
INSERT INTO menu_def VALUES(286,'MTS','submenu','Peak Matching Results','Results');
INSERT INTO menu_def VALUES(287,'Peak Matching Results','link','mts_pm_results/report','Peak Matching');
INSERT INTO menu_def VALUES(288,'','separator',' ',' ');
INSERT INTO menu_def VALUES(289,'','submenu','Search','Search');
INSERT INTO menu_def VALUES(290,'Search','link','analysis_job/search','Analysis Jobs');
INSERT INTO menu_def VALUES(291,'Search','link','dataset/search','Datasets');
INSERT INTO menu_def VALUES(292,'Search','link','archive/search','Archive');
INSERT INTO menu_def VALUES(293,'Search','link','requested_run/search','Requested Runs');
INSERT INTO menu_def VALUES(295,'Search','link','experiment/search','Experiments');
INSERT INTO menu_def VALUES(296,'Search','link','sample_prep_request/search','Sample Prep Req.');
INSERT INTO menu_def VALUES(297,'Search','link','campaign/search','Campaigns');
INSERT INTO menu_def VALUES(298,'Search','separator','','');
INSERT INTO menu_def VALUES(299,'','submenu','Admin','Admin');
INSERT INTO menu_def VALUES(300,'Admin','submenu','Activity Reports','Activity Reports');
INSERT INTO menu_def VALUES(304,'Activity Reports','link','production_instrument_stats/param','Prod. Inst. Stats.');
INSERT INTO menu_def VALUES(305,'Activity Reports','link','dataset_instrument_runtime/param','Dataset Inst. Runtime');
INSERT INTO menu_def VALUES(306,'Activity Reports','link','campaign_dataset_stats/param','Campaign Dataset Stats');
INSERT INTO menu_def VALUES(307,'Activity Reports','link','project_usage/report/__ThisYear__/__ThisWeek__/user','Project Usage Stats');
INSERT INTO menu_def VALUES(308,'Activity Reports','link','tissue_stats/param/__TodayLastYear__/__Today__','Tissue Usage Statistics');
INSERT INTO menu_def VALUES(309,'Activity Reports','separator','','');
INSERT INTO menu_def VALUES(310,'Admin','submenu','Data Analysis Admin','Data Analysis');
INSERT INTO menu_def VALUES(311,'Data Analysis Admin','link','analysis_tools/report','Analysis Tools');
INSERT INTO menu_def VALUES(313,'Data Analysis Admin','link','get_paramfile_crosstab/param','Paramfile Crosstab');
INSERT INTO menu_def VALUES(314,'Data Analysis Admin','link','mass_correction_factors/report','Mass Correction Factors');
INSERT INTO menu_def VALUES(315,'Data Analysis Admin','link','param_file/report','Param File List Report');
INSERT INTO menu_def VALUES(316,'Data Analysis Admin','link','param_file_mass_mods/report','Param File Mass Mods');
INSERT INTO menu_def VALUES(317,'Data Analysis Admin','link','maxquant_mods/report','MaxQuant Mods');
INSERT INTO menu_def VALUES(318,'Data Analysis Admin','link','update_analysis_jobs/create','Multi-Job Update');
INSERT INTO menu_def VALUES(319,'Data Analysis Admin','link','analysis_batch/report','Batches');
INSERT INTO menu_def VALUES(320,'Data Analysis Admin','link','analysis_group/create','Job Entry');
INSERT INTO menu_def VALUES(321,'Data Analysis Admin','submenu','Processor Groups Admin','Processor Groups');
INSERT INTO menu_def VALUES(322,'Processor Groups Admin','link','analysis_job_processor_group/report','Report');
INSERT INTO menu_def VALUES(323,'Processor Groups Admin','link','analysis_job_processor_group/create','Entry');
INSERT INTO menu_def VALUES(324,'Data Analysis Admin','submenu','Processors Admin','Processors');
INSERT INTO menu_def VALUES(325,'Processors Admin','link','analysis_job_processors/report','Report');
INSERT INTO menu_def VALUES(326,'Processors Admin','link','analysis_job_processors/create','Entry');
INSERT INTO menu_def VALUES(327,'Data Analysis Admin','submenu','Predefines Admin','Predefines');
INSERT INTO menu_def VALUES(328,'Predefines Admin','submenu','Predefines Admin Report','Report');
INSERT INTO menu_def VALUES(329,'Predefines Admin Report','link','predefined_analysis/report/-','All');
INSERT INTO menu_def VALUES(330,'Predefines Admin Report','link','predefined_analysis/report/Agilent_Ion_Trap','Agilent_Ion_Trap');
INSERT INTO menu_def VALUES(331,'Predefines Admin Report','link','predefined_analysis/report/Agilent_TOF','Agilent_TOF');
INSERT INTO menu_def VALUES(332,'Predefines Admin Report','link','predefined_analysis/report/BRUKERFTMS','BRUKERFTMS');
INSERT INTO menu_def VALUES(333,'Predefines Admin Report','link','predefined_analysis/report/Finnigan_FTICR','Finnigan_FTICR');
INSERT INTO menu_def VALUES(334,'Predefines Admin Report','link','predefined_analysis/report/Finnigan_Ion_Trap','Finnigan_Ion_Trap');
INSERT INTO menu_def VALUES(335,'Predefines Admin Report','link','predefined_analysis/report/LTQ_FT','LTQ_FT');
INSERT INTO menu_def VALUES(336,'Predefines Admin Report','link','predefined_analysis/report/Micromass_QTOF','Micromass_QTOF');
INSERT INTO menu_def VALUES(337,'Predefines Admin Report','link','predefined_analysis/report/QStar_QTOF','QStar_QTOF');
INSERT INTO menu_def VALUES(338,'Predefines Admin Report','link','predefined_analysis_disabled/report','(Disabled)');
INSERT INTO menu_def VALUES(339,'Predefines Admin','separator','','');
INSERT INTO menu_def VALUES(340,'Predefines Admin','link','predefined_analysis/create','Entry');
INSERT INTO menu_def VALUES(341,'Predefines Admin','submenu','Predefines Admin Preview','Preview');
INSERT INTO menu_def VALUES(342,'Predefines Admin Preview','link','predefined_analysis_jobs_preview/param','Jobs');
INSERT INTO menu_def VALUES(343,'Predefines Admin Preview','link','predefined_analysis_preview_mds/param','Jobs (MDS)');
INSERT INTO menu_def VALUES(344,'Predefines Admin Preview','link','predefined_analysis_datasets/param','Datasets');
INSERT INTO menu_def VALUES(345,'Predefines Admin Preview','link','predefined_analysis_rules_preview/param','Rules');
INSERT INTO menu_def VALUES(346,'Predefines Admin Preview','separator',' ',' ');
INSERT INTO menu_def VALUES(347,'Predefines Admin','submenu','Predefines Admin Scheduling Rules','Scheduling Rules');
INSERT INTO menu_def VALUES(348,'Predefines Admin Scheduling Rules','link','predefined_analysis_scheduling_rules/report','Report');
INSERT INTO menu_def VALUES(349,'Predefines Admin Scheduling Rules','link','predefined_analysis_scheduling_rules/create','Entry');
INSERT INTO menu_def VALUES(350,'Predefines Admin Scheduling Rules','separator','','');
INSERT INTO menu_def VALUES(351,'Admin','submenu','Data Analysis Pipeline','Data Analysis Pipeline');
INSERT INTO menu_def VALUES(352,'Data Analysis Pipeline','link','settings_files/report','Settings Files');
INSERT INTO menu_def VALUES(353,'Data Analysis Pipeline','link','pipeline_script/report','Script');
INSERT INTO menu_def VALUES(354,'Data Analysis Pipeline','link','pipeline_jobs/report','Jobs');
INSERT INTO menu_def VALUES(355,'Data Analysis Pipeline','link','pipeline_job_steps/report','Job Steps');
INSERT INTO menu_def VALUES(356,'Data Analysis Pipeline','link','pipeline_jobs/create','Pipeline Job Entry');
INSERT INTO menu_def VALUES(357,'Data Analysis Pipeline','link','pipeline_local_processors/report','Local Processors');
INSERT INTO menu_def VALUES(358,'Data Analysis Pipeline','link','pipeline_step_tools/report','Step Tools');
INSERT INTO menu_def VALUES(359,'Data Analysis Pipeline','link','pipeline_processor_tool_crosstab/report','Processor Tool Crosstab');
INSERT INTO menu_def VALUES(360,'Data Analysis Pipeline','link','pipeline_processor_step_tools/report','Processor Step Tools');
INSERT INTO menu_def VALUES(361,'Admin','submenu','Capture Pipeline','Capture Pipeline');
INSERT INTO menu_def VALUES(362,'Capture Pipeline','link','capture_script/report','Script');
INSERT INTO menu_def VALUES(363,'Capture Pipeline','link','capture_jobs/report','Jobs');
INSERT INTO menu_def VALUES(364,'Capture Pipeline','link','capture_job_steps/report','Job Steps');
INSERT INTO menu_def VALUES(365,'Capture Pipeline','link','capture_local_processors/report','Local Processors');
INSERT INTO menu_def VALUES(366,'Capture Pipeline','link','capture_step_tools/report','Step Tools');
INSERT INTO menu_def VALUES(368,'Capture Pipeline','link','capture_processor_step_tools/report','Processor Step Tools');
INSERT INTO menu_def VALUES(369,'Admin','submenu','Capture Status Checks','Capture Status Checks');
INSERT INTO menu_def VALUES(370,'Admin','submenu','Dataset Admin','Dataset');
INSERT INTO menu_def VALUES(373,'Dataset Admin','link','dataset_redisposition/create','Redisposition Dataset');
INSERT INTO menu_def VALUES(374,'Dataset Admin','separator','','');
INSERT INTO menu_def VALUES(375,'Admin','submenu','Archive Admin','Archive');
INSERT INTO menu_def VALUES(376,'Archive Admin','link','archive/report','Datasets');
INSERT INTO menu_def VALUES(377,'Archive Admin','link','archive_assigned_storage/report','Assigned');
INSERT INTO menu_def VALUES(378,'Archive Admin','link','archive_path/report','Archive Path');
INSERT INTO menu_def VALUES(380,'Archive Admin','link','archive/search','Search');
INSERT INTO menu_def VALUES(381,'Archive Admin','separator','','');
INSERT INTO menu_def VALUES(382,'Admin','submenu','Daily Status Checks','Daily Status Checks');
INSERT INTO menu_def VALUES(383,'Daily Status Checks','link','dataset_daily_check/report','Dataset');
INSERT INTO menu_def VALUES(384,'Daily Status Checks','link','main_log/report/Warning','Log - Warnings');
INSERT INTO menu_def VALUES(385,'Daily Status Checks','link','archive_daily_check/report','Archive');
INSERT INTO menu_def VALUES(386,'Daily Status Checks','link','archive_daily_check_update/report','Archive Update');
INSERT INTO menu_def VALUES(387,'Daily Status Checks','link','analysis_daily_check/report','Analysis');
INSERT INTO menu_def VALUES(389,'Daily Status Checks','link','dms_activity/report','DMS Activity');
INSERT INTO menu_def VALUES(390,'Daily Status Checks','separator','','');
INSERT INTO menu_def VALUES(391,'Admin','submenu','Event Log','Event Log');
INSERT INTO menu_def VALUES(392,'Event Log','link','event_log_dataset/report','Dataset');
INSERT INTO menu_def VALUES(393,'Event Log','link','event_log_analysis_job/report','Analyses');
INSERT INTO menu_def VALUES(394,'Event Log','link','event_log_archive/report','Archive');
INSERT INTO menu_def VALUES(395,'Admin','submenu','Instruments Admin','Instruments');
INSERT INTO menu_def VALUES(396,'Instruments Admin','link','instrument/report','Report');
INSERT INTO menu_def VALUES(397,'Instruments Admin','link','new_instrument/create','New');
INSERT INTO menu_def VALUES(398,'Instruments Admin','link','run_op_logs/grid','Operation Log Grid');
INSERT INTO menu_def VALUES(399,'Instruments Admin','link','bionet/report','Bionet Hosts and IPs');
INSERT INTO menu_def VALUES(401,'Instruments Admin','link','instrument_class/report','Instrument Classes');
INSERT INTO menu_def VALUES(402,'Instruments Admin','link','instrument_group/report','Instrument Groups');
INSERT INTO menu_def VALUES(403,'Admin','submenu','Material Storage Admin','Material Storage');
INSERT INTO menu_def VALUES(404,'Material Storage Admin','link','material_location/report','Material Locations');
INSERT INTO menu_def VALUES(405,'Material Storage Admin','link','material_log/report','Material Log');
INSERT INTO menu_def VALUES(406,'Material Storage Admin','link','material_move_container/report/-/-/-','Move Containers');
INSERT INTO menu_def VALUES(407,'Material Storage Admin','link','material_move_items/report/-/-/-','Move Items');
INSERT INTO menu_def VALUES(408,'Admin','submenu','EMSL Admin','EMSL');
INSERT INTO menu_def VALUES(409,'EMSL Admin','submenu','EMSL Admin EUS Proposals','EUS Proposals');
INSERT INTO menu_def VALUES(410,'EMSL Admin EUS Proposals','link','eus_proposals/report/-','Report (all)');
INSERT INTO menu_def VALUES(411,'EMSL Admin EUS Proposals','link','eus_proposals/report/New','Report (new)');
INSERT INTO menu_def VALUES(412,'EMSL Admin EUS Proposals','link','eus_proposals/report/Active','Report (active)');
INSERT INTO menu_def VALUES(413,'EMSL Admin EUS Proposals','link','eus_proposals/create','Entry');
INSERT INTO menu_def VALUES(414,'EMSL Admin','submenu','EMSL Admin EUS Users','EUS Users');
INSERT INTO menu_def VALUES(415,'EMSL Admin EUS Users','link','eus_users/report','Report');
INSERT INTO menu_def VALUES(416,'EMSL Admin EUS Users','link','eus_users/create','Entry');
INSERT INTO menu_def VALUES(420,'EMSL Admin','submenu','EMSL Admin Instrument Usage','Instrument Usage');
INSERT INTO menu_def VALUES(422,'EMSL Admin Instrument Usage','link','instrument_actual/report/__ThisYear__','Actual Instrument Usage');
INSERT INTO menu_def VALUES(424,'EMSL Admin Instrument Usage','link','instrument_actual_monthly/report/__ThisYear__/__ThisMonth__','Monthly Instrument Usage');
INSERT INTO menu_def VALUES(425,'EMSL Admin Instrument Usage','link','instrument_usage_report/report/__ThisYear__/__LastMonth__','ERS Instrument Usage Report');
INSERT INTO menu_def VALUES(426,'EMSL Admin Instrument Usage','link','instrument_usage_report/grid','ERS Instrument Usage Grid');
INSERT INTO menu_def VALUES(427,'EMSL Admin Instrument Usage','link','run_tracking/cal','Inst. Usage Tracking');
INSERT INTO menu_def VALUES(428,'EMSL Admin Instrument Usage','link','run_interval/report','Run Intervals');
INSERT INTO menu_def VALUES(429,'EMSL Admin Instrument Usage','link','project_usage/report/__ThisYear__/__ThisWeek__/user','Weekly usage by project');
INSERT INTO menu_def VALUES(430,'Admin','submenu','Ontology','Ontology / Unimod');
INSERT INTO menu_def VALUES(431,'Ontology','link','ncbi_taxonomy/report','NCBI Taxonomy Names');
INSERT INTO menu_def VALUES(432,'Ontology','link','newt/report','Species (NEWT)');
INSERT INTO menu_def VALUES(433,'Ontology','link','tissue/report','Tissue (BTO)');
INSERT INTO menu_def VALUES(434,'Ontology','link','unimod/report/','Unimod Mods');
INSERT INTO menu_def VALUES(435,'Ontology','submenu','Ontology Lineage','Ontology Lineage');
INSERT INTO menu_def VALUES(436,'Ontology Lineage','link','ontology_cv/report/~CL/-/-/-','Cell Type (CL)');
INSERT INTO menu_def VALUES(437,'Ontology Lineage','link','ontology_cv/report/~DOID/-/-/-','Disease (DOID)');
INSERT INTO menu_def VALUES(438,'Ontology Lineage','link','ontology_cv/report/~PSI-MS/-/-/-','PSI-MS');
INSERT INTO menu_def VALUES(439,'Ontology','submenu','Ontology Definition','Ontology Definition');
INSERT INTO menu_def VALUES(440,'Ontology Definition','link','ontology/report/~CL/-/Blood/-','Cell Type (CL)');
INSERT INTO menu_def VALUES(441,'Ontology Definition','link','ontology/report/~DOID/-/diab/-','Disease (DOID)');
INSERT INTO menu_def VALUES(442,'Ontology Definition','link','ontology/report/~MS/-/Orbi/-','PSI-MS');
INSERT INTO menu_def VALUES(443,'Admin','submenu','Organisms Admin','Organisms');
INSERT INTO menu_def VALUES(444,'Organisms Admin','link','organism/report','Report');
INSERT INTO menu_def VALUES(445,'Organisms Admin','link','organism/create','Entry');
INSERT INTO menu_def VALUES(446,'Organisms Admin','link','ncbi_taxonomy/report','NCBI Taxonomy Names');
INSERT INTO menu_def VALUES(447,'Organisms Admin','link','protein_collection/report','Protein Collections');
INSERT INTO menu_def VALUES(448,'Organisms Admin','link','helper_organism_db/report','Individual FASTA files');
INSERT INTO menu_def VALUES(449,'Admin','submenu','File Storage','Storage');
INSERT INTO menu_def VALUES(450,'File Storage','link','storage/report','Report');
INSERT INTO menu_def VALUES(451,'File Storage','link','storage/create','Entry');
INSERT INTO menu_def VALUES(453,'Admin','submenu','User Admin','Users');
INSERT INTO menu_def VALUES(454,'User Admin','link','user/report','Report');
INSERT INTO menu_def VALUES(455,'User Admin','link','user/create','Entry');
INSERT INTO menu_def VALUES(456,'User Admin','link','user_operation/report','Operations');
INSERT INTO menu_def VALUES(457,'Admin','submenu','Internal Standards Admin','Internal Standards');
INSERT INTO menu_def VALUES(458,'Internal Standards Admin','link','internal_standards/report','Report');
INSERT INTO menu_def VALUES(459,'Admin','submenu','Manager Control','Manager Control');
INSERT INTO menu_def VALUES(460,'Manager Control','link','mc_params/report','Parameters');
INSERT INTO menu_def VALUES(461,'Manager Control','link','mc_enable_control_by_manager/report','Manager Control');
INSERT INTO menu_def VALUES(462,'Manager Control','link','mc_enable_control_by_manager_type/report','Manager Type Control');
INSERT INTO menu_def VALUES(466,'Admin','submenu','Aux Info Definition','Aux Info Definition');
INSERT INTO menu_def VALUES(467,'Aux Info Definition','link','aux_info_def/report/Biomaterial','Biomaterial');
INSERT INTO menu_def VALUES(468,'Aux Info Definition','link','aux_info_def/report/Experiment','Experiment');
INSERT INTO menu_def VALUES(469,'Aux Info Definition','link','aux_info_def/report/Dataset','Dataset');
INSERT INTO menu_def VALUES(470,'Aux Info Definition','link','aux_info_def/report/SamplePrepRequest','Sample Prep Request');
INSERT INTO menu_def VALUES(471,'Admin','submenu','Spreadsheet Loader','Spreadsheet Loader');
INSERT INTO menu_def VALUES(472,'Spreadsheet Loader','link','upload/main','Load Spreadsheet');
INSERT INTO menu_def VALUES(473,'Capture Status Checks','link','capture_daily_check/report/-','All');
INSERT INTO menu_def VALUES(474,'Capture Status Checks','link','capture_daily_check/report/DatasetCapture','Dataset Capture');
INSERT INTO menu_def VALUES(475,'Capture Status Checks','link','capture_daily_check/report/ArchiveUpdate','Archive Update');
INSERT INTO menu_def VALUES(476,'Capture Status Checks','link','capture_daily_check/report/DatasetArchive','Dataset Archive');
INSERT INTO menu_def VALUES(477,'Capture Status Checks','link','capture_daily_check/report/SourceFileRename','Source File Rename');
INSERT INTO menu_def VALUES(479,'Capture Pipeline','link','capture_log/report','Capture Log');
INSERT INTO menu_def VALUES(480,'Data Analysis Requests','submenu','Data Analysis Requests Active','Active (by staff)');
INSERT INTO menu_def VALUES(481,'Data Analysis Requests Active','link','data_analysis_request_active/report/-/-/-/-/-/-/-/StartsWith__Couvillion/-/-/-/-','Couvillion');
INSERT INTO menu_def VALUES(482,'Data Analysis Requests Active','link','data_analysis_request_active/report/-/-/-/-/-/-/-/StartsWith__Hixson/-/-/-/-','Hixson');
INSERT INTO menu_def VALUES(483,'Data Analysis Requests Active','link','data_analysis_request_active/report/-/-/-/-/-/-/-/StartsWith__Kim/-/-/-/-','Kim');
INSERT INTO menu_def VALUES(484,'Data Analysis Requests Active','link','data_analysis_request_active/report/-/-/-/-/-/-/-/StartsWith__Munoz/-/-/-/-','Munoz');
INSERT INTO menu_def VALUES(485,'Data Analysis Requests Active','link','data_analysis_request_active/report/-/-/-/-/-/-/-/StartsWith__Nakayasu/-/-/-/-','Nakayasu');
CREATE TABLE nav_def (
    "id" INTEGER PRIMARY KEY,
    "owner_menu" TEXT,
    "item_type" TEXT,
    "item_name" TEXT,
    "item_label" TEXT,
    "item_help" TEXT
);
INSERT INTO nav_def VALUES(1,'','header_context','side_panel_toggle','','');
INSERT INTO nav_def VALUES(2,'','header_context','home_link','','');
INSERT INTO nav_def VALUES(3,'','header_context','admin_page_link','','');
INSERT INTO nav_def VALUES(4,'','submenu','General','General','');
INSERT INTO nav_def VALUES(5,'General','separator','','Navigation','');
INSERT INTO nav_def VALUES(6,'General','link','gen/welcome','Home','');
INSERT INTO nav_def VALUES(7,'General','link','javascript:dmsNav.kill_frames()','Hide Side Menu','');
INSERT INTO nav_def VALUES(8,'General','link','javascript:dmsNav.open_frames()','Show Side Menu','');
INSERT INTO nav_def VALUES(9,'General','link','http://prismwiki.pnl.gov/wiki/PRISM_QuickStart_Guide','PRISM Wiki','');
INSERT INTO nav_def VALUES(10,'General','separator','','Preferences','');
INSERT INTO nav_def VALUES(11,'General','link','preferences','Preferences','');
INSERT INTO nav_def VALUES(12,'General','link_context','save_settings_link','Save Page Settings','Save current settings as defaults');
INSERT INTO nav_def VALUES(13,'General','link_context','clear_settings_link','Clear Page Settings','Clear any saved defaults');
INSERT INTO nav_def VALUES(14,'General','separator','','Notification','');
INSERT INTO nav_def VALUES(15,'General','link_context','user_notification_link','Notification','Show my current notifications');
INSERT INTO nav_def VALUES(16,'General','link_context','email_notification_link','EMail settings','Set email notification preferences');
INSERT INTO nav_def VALUES(17,'General','separator','','Campaigns','');
INSERT INTO nav_def VALUES(18,'General','link','campaign/report','Report','Display list of campaigns');
INSERT INTO nav_def VALUES(19,'General','link','campaign/search','Search','');
INSERT INTO nav_def VALUES(20,'General','link','campaign/create','Entry','Create a new campaign');
INSERT INTO nav_def VALUES(21,'General','link','staff_roles/report','Staff Roles','Display staff roles and responsibilities for campaigns');
INSERT INTO nav_def VALUES(22,'General','separator','','Data Packages','');
INSERT INTO nav_def VALUES(23,'General','link','data_package/report','Report','Display list of data packages');
INSERT INTO nav_def VALUES(24,'General','link','data_package/create','Entry','Create a new data package');
INSERT INTO nav_def VALUES(25,'General','separator','','File Attachments','');
INSERT INTO nav_def VALUES(26,'General','link','file_attachment/report','Report','Display list of file attachments');
INSERT INTO nav_def VALUES(27,'','submenu','Samples','Samples','');
INSERT INTO nav_def VALUES(28,'Samples','separator','','Material Storage','');
INSERT INTO nav_def VALUES(29,'Samples','link','material_location_available/report/-/-/-','Available Locations','Display list of material locations with space available');
INSERT INTO nav_def VALUES(30,'Samples','link','material_location/report/-/-/-/-/-/-/Active','Active Locations','Display list of material locations');
INSERT INTO nav_def VALUES(31,'Samples','link','material_container/report/-/-/-/-/Active','Active Containers','Display list of material containers');
INSERT INTO nav_def VALUES(32,'Samples','link','material_items/report/-/-/-/-/-/Active','Active Items','Display list of material items (experiments, biomaterial)');
INSERT INTO nav_def VALUES(33,'Samples','link','material_container/create','New Container','Create new container');
INSERT INTO nav_def VALUES(34,'Samples','link','material_log/report/-/-/-','Log','Display material tracking log');
INSERT INTO nav_def VALUES(35,'Samples','separator','','Sample Submission','');
INSERT INTO nav_def VALUES(36,'Samples','link','sample_submission/report','Report','Show list of sample submissions');
INSERT INTO nav_def VALUES(37,'Samples','link','sample_submission/create','Entry','Make new sample submission');
INSERT INTO nav_def VALUES(38,'Samples','separator','','Sample Prep Req','');
INSERT INTO nav_def VALUES(39,'Samples','link','sample_prep_request/report','Report','Display list of sample prep requests');
INSERT INTO nav_def VALUES(40,'Samples','link','sample_prep_request/create','Entry','Create a new sample prep request');
INSERT INTO nav_def VALUES(41,'Samples','link','sample_prep_request_assignment/report','Assignment','');
INSERT INTO nav_def VALUES(43,'Samples','separator','','Experiments','');
INSERT INTO nav_def VALUES(44,'Samples','link','experiment/report','Report','Display a list of experiments');
INSERT INTO nav_def VALUES(45,'Samples','link','experiment/search','Search','Search for experiments');
INSERT INTO nav_def VALUES(46,'Samples','link','experiment/create','Entry','Create a new experiment');
INSERT INTO nav_def VALUES(47,'Samples','separator','','Experiment Groups','');
INSERT INTO nav_def VALUES(48,'Samples','link','experiment_group/report','Report','Display a list of experiment fractionation groups');
INSERT INTO nav_def VALUES(49,'Samples','link','experiment_fraction/create','Entry - Fractions','Create a new experiment fractionation group');
INSERT INTO nav_def VALUES(50,'Samples','link','experiment_group/create','Entry - General','Create a new general experiment group');
INSERT INTO nav_def VALUES(51,'Samples','separator','','Biomaterial and Ref Comp','');
INSERT INTO nav_def VALUES(52,'Samples','link','biomaterial/report','Biomaterial Report','Display list of biomaterial items');
INSERT INTO nav_def VALUES(53,'Samples','link','biomaterial/create','Biomaterial Entry','Create a new biomaterial item');
INSERT INTO nav_def VALUES(54,'Samples','link','reference_compound/report','Reference Compounds','Show list of reference compounds');
INSERT INTO nav_def VALUES(55,'','submenu','Instrument Runs','Instrument Runs','');
INSERT INTO nav_def VALUES(56,'Instrument Runs','separator','','Requested Runs','');
INSERT INTO nav_def VALUES(57,'Instrument Runs','link','requested_run/report/-/-/Active','Report - Active','Display list of active requested runs');
INSERT INTO nav_def VALUES(59,'Instrument Runs','link','requested_run/report/-/-/Completed','Report - Completed','Display list of requesed runs that have been completed by datasets');
INSERT INTO nav_def VALUES(61,'Instrument Runs','link','requested_run/create','Single Entry','Create a new requested run for a single experiment');
INSERT INTO nav_def VALUES(62,'Instrument Runs','link','requested_run_group/create','Group Entry','Create a new requested run for an experiment fractionation group');
INSERT INTO nav_def VALUES(64,'Instrument Runs','separator','','Run Batches','');
INSERT INTO nav_def VALUES(65,'Instrument Runs','link','requested_run_batch/report','Report','Display list of requested run batches');
INSERT INTO nav_def VALUES(67,'Instrument Runs','link','requested_run_batch/create','Entry','Create a new requested run batch');
INSERT INTO nav_def VALUES(68,'Instrument Runs','link','batch_tracking/report/-/-/-/-','Tracking','Display requested run batch tracking report');
INSERT INTO nav_def VALUES(69,'Instrument Runs','link','requested_run_batch_location_history/report','Location History','Report on the last scanned locations for the batch box');
INSERT INTO nav_def VALUES(70,'Instrument Runs','separator','','Run Blocking','');
INSERT INTO nav_def VALUES(71,'Instrument Runs','link','requested_run_batch_blocking/param','Define Blocking','Define run blocking for a batch');
INSERT INTO nav_def VALUES(72,'Instrument Runs','link','requested_run_batch_blocking/grid','Define Blocking (grid)','Define run blocking for a batch');
INSERT INTO nav_def VALUES(73,'Instrument Runs','link','requested_run_factors/param','Define Factors','Define factors for requested runs');
INSERT INTO nav_def VALUES(74,'Instrument Runs','link','factors/grid','Define Factors (grid)','Define factors for requested runs');
INSERT INTO nav_def VALUES(75,'Instrument Runs','link','custom_factors/report/-','Browse Factors','View existing factors associated with requests');
INSERT INTO nav_def VALUES(76,'Instrument Runs','separator','','Wellplates','');
INSERT INTO nav_def VALUES(77,'Instrument Runs','link','wellplate/report','Report','Display list of wellplates');
INSERT INTO nav_def VALUES(78,'Instrument Runs','separator','','Datasets','');
INSERT INTO nav_def VALUES(80,'Instrument Runs','link','dataset/search','Search','Search for datasets');
INSERT INTO nav_def VALUES(81,'Instrument Runs','link','dataset_disposition/search','Disposition','Disposition datasets that are waiting for inspection');
INSERT INTO nav_def VALUES(82,'Instrument Runs','link','dataset_disposition_lite/report','Disposition (No plots)','Disposition datasets that are waiting for inspection');
INSERT INTO nav_def VALUES(83,'Instrument Runs','link','dataset/create','Entry','Create a new dataset');
INSERT INTO nav_def VALUES(84,'Instrument Runs','link','main_log/report','Log','Show log of dataset creation and capture');
INSERT INTO nav_def VALUES(85,'Instrument Runs','separator','','Usage Tracking','');
INSERT INTO nav_def VALUES(86,'Instrument Runs','link','run_tracking/cal','Inst. Usage Tracking','');
INSERT INTO nav_def VALUES(87,'','submenu','Data Analysis','Data Analysis','');
INSERT INTO nav_def VALUES(88,'Data Analysis','separator','','Analysis Job Requests','');
INSERT INTO nav_def VALUES(89,'Data Analysis','link','analysis_job_request/report/-/-/-','Report All','Display list of analysis job requests');
INSERT INTO nav_def VALUES(90,'Data Analysis','link','analysis_job_request/report/New','Report - New','Display list of analysis job requests that are in New state');
INSERT INTO nav_def VALUES(91,'Data Analysis','link','analysis_job_request/report/Used','Report - Used','Display list of analysis job requests that are in Used state');
INSERT INTO nav_def VALUES(92,'Data Analysis','link','analysis_job_request_psm/create','MS/MS Job Wizard','Create a new MS/MS analysis job request based on suggested defaults');
INSERT INTO nav_def VALUES(93,'Data Analysis','link','analysis_job_request/create','Generic Entry','Create a new analysis job request');
INSERT INTO nav_def VALUES(94,'Data Analysis','separator','','Analysis Jobs','');
INSERT INTO nav_def VALUES(95,'Data Analysis','link','analysis_job/search','Search','Search for analysis jobs');
INSERT INTO nav_def VALUES(96,'Data Analysis','separator','','Analysis Job Reports','');
INSERT INTO nav_def VALUES(99,'Data Analysis','link','analysis_job/report/-/-/StartsWith__MSGFPlus/-/-/-/-/-/52','MS-GF+','Display list of MS-GF+ analysis jobs (last 12 months)');
INSERT INTO nav_def VALUES(100,'Data Analysis','link','analysis_job/report/-/-/StartsWith__Decon2LS/-/-/-/-/-/52','DeconTools','Display list of DeconTools analysis jobs (last 12 months)');
INSERT INTO nav_def VALUES(101,'Data Analysis','link','analysis_job/report/-/-/StartsWith__MASIC/-/-/-/-/-/52','MASIC','Display list of MASIC analysis jobs (last 12 months)');
INSERT INTO nav_def VALUES(102,'Data Analysis','link','analysis_job/report/-/-/StartsWith__MSAlign/-/-/-/-/-/52','MSAlign','Display list of MSAlign analysis jobs (last 12 months)');
INSERT INTO nav_def VALUES(103,'Data Analysis','link','analysis_job/report/-/-/StartsWith__MSPathFinder/-/-/-/-/-/52','MSPathFinder','Display list of MSPathFinder analysis jobs (last 12 months)');
INSERT INTO nav_def VALUES(105,'Data Analysis','separator','','PSM Stats','');
INSERT INTO nav_def VALUES(106,'Data Analysis','link','analysis_job_psm/report/','Job PSM Stats','');
INSERT INTO nav_def VALUES(107,'Data Analysis','link','data_package_analysis_job_psm/report/-/-/-/StartsWith__msgfplus','Data Pkg Job PSM Stats','');
INSERT INTO nav_def VALUES(108,'Data Analysis','link','dataset_psm/report/4/StartsWith__msgfplus','Dataset PSM Stats','');
INSERT INTO nav_def VALUES(109,'Data Analysis','link','data_package_dataset_psm/report/-/4/StartsWith__msgfplus','Data Pkg Dataset PSM Stats','');
INSERT INTO nav_def VALUES(110,'','submenu','LC','LC','');
INSERT INTO nav_def VALUES(111,'LC','separator','','Columns','');
INSERT INTO nav_def VALUES(112,'LC','link','lc_column/report','Report','Display list of LC columns');
INSERT INTO nav_def VALUES(113,'LC','link','lc_column/create','Entry','Create a new LC column');
INSERT INTO nav_def VALUES(114,'LC','link','lc_column_dataset/report','Dataset Count','Display list of LC columns showing number of samples run');
INSERT INTO nav_def VALUES(115,'LC','link','separation_type/report','Separation Type','');
INSERT INTO nav_def VALUES(116,'LC','separator','','Carts','');
INSERT INTO nav_def VALUES(117,'LC','link','lc_cart/report','Report','Display list of LC carts');
INSERT INTO nav_def VALUES(118,'LC','link','lc_cart/create','Entry','Create new LC Cart');
INSERT INTO nav_def VALUES(121,'LC','link','lc_cart_request_loading/report','Configure loading (Req)','Prepare sample loading for LC Cart by requested runs');
INSERT INTO nav_def VALUES(122,'LC','link','lc_cart_loading/report','Loading List','Display requested run queue');
INSERT INTO nav_def VALUES(123,'LC','link','lc_cart_configuration/report','Cart Configurations','Display LC Cart configurations');
INSERT INTO nav_def VALUES(124,'LC','separator','','Cart Maintenance','');
INSERT INTO nav_def VALUES(126,'LC','link','lc_cart_config_history/report','Service Notes','Display LC cart service notes');
INSERT INTO nav_def VALUES(127,'LC','link','lc_cart_config_history/create','New Service Note','Add a new cart service note');
INSERT INTO nav_def VALUES(128,'LC','separator','','Instrument Config.','');
INSERT INTO nav_def VALUES(129,'LC','link','instrument_config/report','Inst. List','Display list of instruments');
INSERT INTO nav_def VALUES(130,'LC','link','instrument_config_history/report','Config. History','Display instrument config history');
INSERT INTO nav_def VALUES(131,'LC','link','instrument_config_history/Create','New Service Note','Create new instrument config note');
INSERT INTO nav_def VALUES(132,'LC','link','instrument_operation_history/report','Operation Notes','Display instrument operation notes');
INSERT INTO nav_def VALUES(133,'LC','link','instrument_operation_history/create','Add Operation Note..','Add new instrument operation notes');
INSERT INTO nav_def VALUES(134,'','submenu','Search','Search','');
INSERT INTO nav_def VALUES(135,'Search','separator','','Simple Search','');
INSERT INTO nav_def VALUES(136,'Search','link','analysis_job/search','Analysis Jobs','');
INSERT INTO nav_def VALUES(137,'Search','link','dataset/search','Datasets','');
INSERT INTO nav_def VALUES(138,'Search','link','archive/search','Archive','');
INSERT INTO nav_def VALUES(139,'Search','link','requested_run/search','Requested Runs','');
INSERT INTO nav_def VALUES(141,'Search','link','experiment/search','Experiments','');
INSERT INTO nav_def VALUES(142,'Search','link','sample_prep_request/search','Sample Prep Req.','');
INSERT INTO nav_def VALUES(143,'Search','link','campaign/search','Campaigns','');
INSERT INTO nav_def VALUES(144,'Search','link','custom_factors/search','Factors','');
INSERT INTO nav_def VALUES(145,'','submenu','MTS','MTS','');
INSERT INTO nav_def VALUES(146,'MTS','separator','','Databases','');
INSERT INTO nav_def VALUES(147,'MTS','link','mts_pt_dbs/report','Peptide DBs','Display list of peptide databases');
INSERT INTO nav_def VALUES(148,'MTS','link','mts_mt_dbs/report','AMT Tag DBs','Display list of AMT tag databases');
INSERT INTO nav_def VALUES(149,'MTS','separator','','Database Jobs','');
INSERT INTO nav_def VALUES(150,'MTS','link','mts_pt_db_jobs/report','Peptide DB Jobs','Display list of peptide databases by job');
INSERT INTO nav_def VALUES(151,'MTS','link','mts_mt_db_jobs/report','AMT Tag DB Jobs','Display list of AMT tag databases by job');
INSERT INTO nav_def VALUES(152,'MTS','separator','','Results','');
INSERT INTO nav_def VALUES(153,'MTS','link','mts_pm_results/report','Peak Matching','Display list of peak matching results');
INSERT INTO nav_def VALUES(154,'','submenu','Help',' Help','');
INSERT INTO nav_def VALUES(155,'Help','separator','','Help','');
INSERT INTO nav_def VALUES(156,'Help','link_context','help_basic_link','Help for page type','Show help page for this type of DMS page');
INSERT INTO nav_def VALUES(157,'Help','link_context','help_page_link','Help for specific page','Show help page for this DMS page');
INSERT INTO nav_def VALUES(158,'Help','separator','','Info','');
INSERT INTO nav_def VALUES(159,'Help','link_context','page_info_link','Page info','');
INSERT INTO nav_def VALUES(160,'Help','link_context','config_db_link','Page config','');
INSERT INTO nav_def VALUES(161,'','header_context','server_info','Page config','');
INSERT INTO nav_def VALUES(162,'Help','link_context','sql_link','SQL','Show SQL that returned data for this page');
INSERT INTO nav_def VALUES(163,'Help','link_context','url_link','URL','Show URL and filter information');
COMMIT;
