PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE home_menu_sections (
    "id" INTEGER PRIMARY KEY NOT NULL,
    "section_name" TEXT,
    "section_header" TEXT,
    "section_number" TEXT,
    "section_comment" TEXT
);
INSERT INTO home_menu_sections VALUES(1,'General','General','1','The DMS is part of PRISM, the Proteomics Research Information Storage and Management System. DMS acquires data from mass spectrometers, collects laboratory information, and tracks and controls the intermediate data processing. ');
INSERT INTO home_menu_sections VALUES(2,'Campaign','Campaign','2','Campaign is the overarching umbrella for a particular research interest. Everything in DMS flows up to a campaign.');
INSERT INTO home_menu_sections VALUES(4,'Biomaterial','Cell Culture/Biomaterial','4','Biomaterial/Cell Culture refers to the physical sample of biological material, often in its raw form. It is usually something sent to us by a user or collaborator.');
INSERT INTO home_menu_sections VALUES(6,'Experiments','Experiments (Prepared Sample)','6','Experiments are injectable samples that are prepared from biomaterial. All experiments must be entered into DMS in order to be run on the instruments. You would enter a sample prep request to have your biomaterial processed into experiments.');
INSERT INTO home_menu_sections VALUES(7,'Requested Run','Requested Run','7','A Requested Run is a request that a specific experiment be run on an LCMS instrument to produce a Dataset.  An individual LCMS request must be entered for each instrument run, including replicates and blanks.');
INSERT INTO home_menu_sections VALUES(8,'Datasets','Datasets (LCMS Run)','8','Datasets represent a specific injectable sample (i.e. an aliquot of an Experiment) that is run on a particular instrument. An individual LCMS request must be entered for each instrument run, including replicates and blanks.');
INSERT INTO home_menu_sections VALUES(9,'Analysis Request','Analysis Job Request','9','An Analysis Job Request is a request that data analysis be performed on one or more Datasets.');
INSERT INTO home_menu_sections VALUES(10,'Data Analysis','Data Analysis','10','An analysis job is an automated process that analyzes the spectra for a single Dataset using a specific analysis tool (SEQUEST / X!Tandem/ ICR-2LS, etc.). You must enter an analysis job request to define the analysis job to be run.');
CREATE TABLE home_menu_items (
    "id" INTEGER PRIMARY KEY,
    "section_name" TEXT,
    "page" TEXT,
    "link" TEXT,
    "label" TEXT
);
INSERT INTO home_menu_items VALUES(1,'Biomaterial','biomaterial/report','Display','a list of existing biomaterial items');
INSERT INTO home_menu_items VALUES(2,'Biomaterial','biomaterial/create','Create','a new biomaterial item');
INSERT INTO home_menu_items VALUES(4,'Biomaterial','biomaterial/search','Search','for existing biomaterial items');
INSERT INTO home_menu_items VALUES(5,'Biomaterial','organism/report','Display','a list of existing organisms');
INSERT INTO home_menu_items VALUES(6,'Biomaterial','organism/create','Create','a new organism');
INSERT INTO home_menu_items VALUES(7,'Biomaterial','upload/main','Load','biomaterial from spreadsheet tsv file');
INSERT INTO home_menu_items VALUES(8,'Campaign','campaign/report','Display','a list of existing research campaigns');
INSERT INTO home_menu_items VALUES(9,'Campaign','campaign/create','Create','a new research campaign');
INSERT INTO home_menu_items VALUES(10,'Campaign','campaign/search','Search','for an existing campaign');
INSERT INTO home_menu_items VALUES(12,'Analysis Request','analysis_job_request/report/-/-/-/-','Display','a list of analysis job requests');
INSERT INTO home_menu_items VALUES(13,'Analysis Request','analysis_job_request_psm/create','Create','a new MS/MS search request');
INSERT INTO home_menu_items VALUES(14,'Analysis Request','analysis_job_request/create','Create','a new analysis job request');
INSERT INTO home_menu_items VALUES(15,'Analysis Request','upload/main','Load','analysis job requests from spreadsheet tsv file');
INSERT INTO home_menu_items VALUES(16,'Data Analysis','analysis_job/report','Display','a list of existing analysis jobs');
INSERT INTO home_menu_items VALUES(17,'Data Analysis','analysis_job/search','Search','for an existing analysis job');
INSERT INTO home_menu_items VALUES(19,'Data Analysis','analysis_job/report/-/-/StartsWith__Decon2LS','Display','a list of Decon2LS analysis jobs');
INSERT INTO home_menu_items VALUES(22,'Data Analysis','analysis_job/report/-/-/StartsWith__MASIC','Display','a list of MASIC analysis jobs');
INSERT INTO home_menu_items VALUES(23,'Data Analysis','analysis_job/report/-/-/StartsWith__MSGFPlus','Display','a list of MS-GF+ analysis jobs');
INSERT INTO home_menu_items VALUES(28,'Data Analysis','analysis_job/report/-/-/StartsWith__XTandem','Display','a list of X!Tandem analysis jobs');
INSERT INTO home_menu_items VALUES(29,'Data Analysis','get_paramfile_crosstab/param','Display','the paramfile crosstab report');
INSERT INTO home_menu_items VALUES(30,'Requested Run','requested_run/report','Display','a list of existing requested runs');
INSERT INTO home_menu_items VALUES(31,'Requested Run','requested_run/create','Create','a new requested run (for experiment)');
INSERT INTO home_menu_items VALUES(32,'Requested Run','requested_run_group/create','Create','new requested runs (for experiment group)');
INSERT INTO home_menu_items VALUES(33,'Requested Run','requested_run/search','Search','for existing requested runs');
INSERT INTO home_menu_items VALUES(34,'Requested Run','upload/main','Load','requested runs from spreadsheet tsv file');
INSERT INTO home_menu_items VALUES(35,'Datasets','dataset/report','Display','a list of existing datasets');
INSERT INTO home_menu_items VALUES(36,'Datasets','dataset/search','Search','for existing datasets');
INSERT INTO home_menu_items VALUES(37,'Datasets','dataset_disposition/search','Disposition','pending datasets');
INSERT INTO home_menu_items VALUES(38,'Datasets','dataset_redisposition/create','Redisposition','datasets that have been released');
INSERT INTO home_menu_items VALUES(39,'Datasets','run_planning/report','Display','the planning report');
INSERT INTO home_menu_items VALUES(40,'Datasets','production_instrument_stats/param','Display','production instrument statistics report');
INSERT INTO home_menu_items VALUES(41,'Experiments','experiment/report','Display','a list of existing experiments');
INSERT INTO home_menu_items VALUES(42,'Experiments','experiment/create','Create','a new experiment');
INSERT INTO home_menu_items VALUES(43,'Experiments','experiment/search','Search','for existing experiments');
INSERT INTO home_menu_items VALUES(44,'Experiments','experiment_group/report','Display','a list of existing experiment groups');
INSERT INTO home_menu_items VALUES(45,'Experiments','experiment_fraction/create','Create','a new experiment fraction group');
INSERT INTO home_menu_items VALUES(46,'Experiments','experiment_group/create','Create','a new group for existing experiments');
INSERT INTO home_menu_items VALUES(64,'Campaign','staff_roles/report','Display','a list of staff roles and assignments');
CREATE TABLE menu_def (
    "id" INTEGER PRIMARY KEY,
    "owner_menu" TEXT,
    "item_type" TEXT,
    "item_name" TEXT,
    "item_label" TEXT
);
INSERT INTO menu_def VALUES(1,'','submenu','Datasets','Datasets');
INSERT INTO menu_def VALUES(2,'Datasets','link','dataset/report','Report');
INSERT INTO menu_def VALUES(3,'Datasets','link','dataset/search','Search');
INSERT INTO menu_def VALUES(4,'Datasets','link','dataset/create','Entry');
INSERT INTO menu_def VALUES(5,'Datasets','link','dataset_disposition/search','Disposition');
INSERT INTO menu_def VALUES(6,'Datasets','link','dataset_disposition_lite','Disposition (No plots)');
INSERT INTO menu_def VALUES(7,'Datasets','link','main_log/report','Log');
INSERT INTO menu_def VALUES(8,'Datasets','submenu','Special Reports','Special Reports');
INSERT INTO menu_def VALUES(9,'Special Reports','link','ai_user_funded_datasets_list_report/report/-/-/-/-/12','User funded');
INSERT INTO menu_def VALUES(10,'Special Reports','link','dataset_funding/report/-/-/-/-/12','All funded');
INSERT INTO menu_def VALUES(11,'Special Reports','link','dataset_instrument/report','Instrument Usage');
INSERT INTO menu_def VALUES(12,'Special Reports','link','find_datasets_by_instrument/param','Most Recent Datasets by Instrument');
INSERT INTO menu_def VALUES(14,'Special Reports','link','dataset_qc/search','Dataset QC report');
INSERT INTO menu_def VALUES(15,'Special Reports','link','dataset_pm_and_psm/report/4/-/Exact','High Res Peak Matching Stats');
INSERT INTO menu_def VALUES(16,'Special Reports','link','dataset_psm_and_pm/report/4/StartsWith__msgfplus','PSM and Peak Matching Stats');
INSERT INTO menu_def VALUES(17,'Special Reports','link','data_package_dataset_psm_and_pm/report/-/4/StartsWith__msgfplus','Data Pkg PSM Stats');
INSERT INTO menu_def VALUES(18,'Datasets','separator','','');
INSERT INTO menu_def VALUES(19,'','submenu','Experiments','Experiments');
INSERT INTO menu_def VALUES(20,'Experiments','link','experiment/report','Report');
INSERT INTO menu_def VALUES(21,'Experiments','link','experiment/search','Search');
INSERT INTO menu_def VALUES(22,'Experiments','link','experiment/create','Entry');
INSERT INTO menu_def VALUES(23,'Experiments','submenu','Experiment Groups','Groups');
INSERT INTO menu_def VALUES(24,'Experiment Groups','link','experiment_group/report','Report');
INSERT INTO menu_def VALUES(25,'Experiment Groups','link','experiment_fraction/create','Make Fraction Group');
INSERT INTO menu_def VALUES(26,'Experiment Groups','link','experiment_group/create','Make General Group');
INSERT INTO menu_def VALUES(27,'Experiments','submenu','Experiment Factors','Factors');
INSERT INTO menu_def VALUES(28,'Experiment Factors','link','requested_run_factors/param','Define Factors');
INSERT INTO menu_def VALUES(29,'Experiment Factors','link','custom_factors/report/-','Browse Factors');
INSERT INTO menu_def VALUES(30,'Experiments','separator','','');
INSERT INTO menu_def VALUES(31,'','submenu','Biomaterial','Biomaterial');
INSERT INTO menu_def VALUES(32,'Biomaterial','link','biomaterial/report','Report');
INSERT INTO menu_def VALUES(33,'Biomaterial','link','biomaterial/search','Search');
INSERT INTO menu_def VALUES(34,'Biomaterial','link','biomaterial/create','Entry');
INSERT INTO menu_def VALUES(35,'','submenu','Campaigns','Campaigns');
INSERT INTO menu_def VALUES(36,'Campaigns','link','campaign/report','Report');
INSERT INTO menu_def VALUES(37,'Campaigns','link','campaign/search','Search');
INSERT INTO menu_def VALUES(38,'Campaigns','link','campaign/create','Entry');
INSERT INTO menu_def VALUES(39,'Campaigns','link','staff_roles/report','Staff Roles');
INSERT INTO menu_def VALUES(40,'','separator',' ',' ');
INSERT INTO menu_def VALUES(91,'','submenu','Data Analysis','Data Analysis');
INSERT INTO menu_def VALUES(92,'Data Analysis','submenu','Data Analysis Reports','Reports (last 12 months)');
INSERT INTO menu_def VALUES(93,'Data Analysis Reports','link','analysis_job/report/-/-/-/-/-/-/-/-/52','All');
INSERT INTO menu_def VALUES(95,'Data Analysis Reports','link','analysis_job/report/-/-/StartsWith__MSGFPlus/-/-/-/-/-/52','MS-GF+');
INSERT INTO menu_def VALUES(97,'Data Analysis Reports','link','analysis_job/report/-/-/StartsWith__Decon2LS/-/-/-/-/-/52','DeconTools');
INSERT INTO menu_def VALUES(102,'Data Analysis Reports','link','analysis_job/report/-/-/StartsWith__MASIC/-/-/-/-/-/52','MASIC');
INSERT INTO menu_def VALUES(103,'Data Analysis Reports','link','analysis_job/report/-/-/StartsWith__MSAlign/-/-/-/-/-/52','MSAlign');
INSERT INTO menu_def VALUES(104,'Data Analysis Reports','link','analysis_job/report/-/-/StartsWith__XTandem/-/-/-/-/-/52','X!Tandem');
INSERT INTO menu_def VALUES(105,'Data Analysis','link','analysis_job/search','Search');
INSERT INTO menu_def VALUES(106,'Data Analysis','submenu','Data Analysis Requests','Job Requests');
INSERT INTO menu_def VALUES(107,'Data Analysis Requests','link','analysis_job_request/report/-/-/-/-','All');
INSERT INTO menu_def VALUES(108,'Data Analysis Requests','link','analysis_job_request/report/New','New');
INSERT INTO menu_def VALUES(109,'Data Analysis Requests','link','analysis_job_request/report/Used','Used');
INSERT INTO menu_def VALUES(111,'Data Analysis Requests','separator','','');
INSERT INTO menu_def VALUES(113,'Data Analysis Requests','link','analysis_job_request_psm/create','MS/MS Job Request Wizard');
INSERT INTO menu_def VALUES(114,'Data Analysis Requests','link','analysis_job_request/create','Create generic request');
INSERT INTO menu_def VALUES(116,'Data Analysis Requests','link','pipeline_job_steps/report/-/-/-/StartsWith__running','Running Job Steps');
INSERT INTO menu_def VALUES(117,'Data Analysis','submenu','MAC Jobs','MAC Jobs');
INSERT INTO menu_def VALUES(118,'MAC Jobs','link','pipeline_jobs/report/-/-/~Aggregation','Report');
INSERT INTO menu_def VALUES(119,'MAC Jobs','link','pipeline_jobs_history/report/-/-/~Aggregation','Report (older jobs)');
INSERT INTO menu_def VALUES(120,'MAC Jobs','link','mac_jobs/create','MAC Job Wizard');
INSERT INTO menu_def VALUES(121,'MAC Jobs','link','pipeline_jobs/create','Create generic MAC Job');
INSERT INTO menu_def VALUES(122,'Data Analysis','link','protein_collection/report','Protein Collections');
INSERT INTO menu_def VALUES(123,'Data Analysis','submenu','Analysis Job PSM Stats','PSM Stats');
INSERT INTO menu_def VALUES(124,'Analysis Job PSM Stats','link','analysis_job_psm/report/','Job PSM Stats');
INSERT INTO menu_def VALUES(125,'Analysis Job PSM Stats','link','data_package_analysis_job_psm/report/-/-/-/StartsWith__msgfplus','Data Pkg Job PSM Stats');
INSERT INTO menu_def VALUES(126,'Analysis Job PSM Stats','link','dataset_psm_and_pm/report/4/StartsWith__msgfplus','Dataset PSM Stats');
INSERT INTO menu_def VALUES(127,'Analysis Job PSM Stats','link','data_package_dataset_psm_and_pm/report/-/4/StartsWith__msgfplus','Data Pkg Dataset PSM Stats');
INSERT INTO menu_def VALUES(128,'','submenu','Data Packages','Data Packages');
INSERT INTO menu_def VALUES(129,'Data Packages','link','data_package/report','Report');
INSERT INTO menu_def VALUES(130,'Data Packages','link','data_package/create','Entry');
INSERT INTO menu_def VALUES(131,'','separator','','');
INSERT INTO menu_def VALUES(164,'','submenu','MS LC','MS LC');
INSERT INTO menu_def VALUES(165,'MS LC','submenu','LC Columns','LC Columns');
INSERT INTO menu_def VALUES(166,'LC Columns','link','lc_column/report','Report');
INSERT INTO menu_def VALUES(167,'LC Columns','link','lc_column/create','Entry');
INSERT INTO menu_def VALUES(168,'LC Columns','submenu','Special LC Columns Reports','Special Reports');
INSERT INTO menu_def VALUES(169,'Special LC Columns Reports','link','lc_column_dataset/report','Dataset Count');
INSERT INTO menu_def VALUES(170,'LC Columns','separator',' ',' ');
INSERT INTO menu_def VALUES(171,'MS LC','submenu','LC Carts','LC Carts');
INSERT INTO menu_def VALUES(172,'LC Carts','link','lc_cart/report','Report');
INSERT INTO menu_def VALUES(173,'LC Carts','link','lc_cart/create','Entry');
INSERT INTO menu_def VALUES(175,'LC Carts','link','lc_cart_request_loading/report','Configure loading (Req)');
INSERT INTO menu_def VALUES(176,'LC Carts','link','lc_cart_loading/report','Loading List');
INSERT INTO menu_def VALUES(177,'LC Carts','link','lc_cart_configuration/report','LC Cart Configurations');
INSERT INTO menu_def VALUES(178,'LC Carts','link','lc_cart_config_history/report','LC Cart Service Notes');
INSERT INTO menu_def VALUES(179,'LC Carts','separator','','');
INSERT INTO menu_def VALUES(180,'MS LC','submenu','Instrument Config','Instrument Config.');
INSERT INTO menu_def VALUES(181,'Instrument Config','link','instrument_config/report','Inst. List');
INSERT INTO menu_def VALUES(182,'Instrument Config','link','instrument_config_history/report','Config. History');
INSERT INTO menu_def VALUES(183,'Instrument Config','link','instrument_config_history/create','Service Note');
INSERT INTO menu_def VALUES(184,'Instrument Config','separator','','');
INSERT INTO menu_def VALUES(185,'MS LC','link','run_op_logs/grid','Operation Log Grid');
INSERT INTO menu_def VALUES(186,'MS LC','link','instrument_operation_history/report','Operation Notes ');
INSERT INTO menu_def VALUES(187,'','separator',' ',' ');
INSERT INTO menu_def VALUES(199,'','submenu','Search','Search');
INSERT INTO menu_def VALUES(200,'Search','link','analysis_job/search','Analysis Jobs');
INSERT INTO menu_def VALUES(201,'Search','link','dataset/search','Datasets');
INSERT INTO menu_def VALUES(203,'Search','link','requested_run/search','Requested Runs');
INSERT INTO menu_def VALUES(205,'Search','link','experiment/search','Experiments');
INSERT INTO menu_def VALUES(207,'Search','link','campaign/search','Campaigns');
INSERT INTO menu_def VALUES(208,'Search','separator','','');
INSERT INTO menu_def VALUES(209,'','submenu','Admin','Admin');
INSERT INTO menu_def VALUES(210,'Admin','submenu','Activity Reports','Activity Reports');
INSERT INTO menu_def VALUES(212,'Activity Reports','link','dataset_instrument_daily/param','Daily Dataset By Instrument');
INSERT INTO menu_def VALUES(213,'Activity Reports','link','request_daily/param','Daily Requests');
INSERT INTO menu_def VALUES(215,'Activity Reports','link','dataset_instrument_runtime/param','Dataset Inst. Runtime');
INSERT INTO menu_def VALUES(216,'Activity Reports','link','project_usage/report/__ThisYear__/__ThisWeek__/user','Project Usage Stats');
INSERT INTO menu_def VALUES(217,'Activity Reports','separator','','');
INSERT INTO menu_def VALUES(218,'Admin','submenu','Data Analysis Admin','Data Analysis');
INSERT INTO menu_def VALUES(219,'Data Analysis Admin','link','analysis_tools/report','Analysis Tools');
INSERT INTO menu_def VALUES(221,'Data Analysis Admin','link','get_paramfile_crosstab/param','Paramfile Crosstab');
INSERT INTO menu_def VALUES(222,'Data Analysis Admin','link','mass_correction_factors/report','Mass Correction Factors');
INSERT INTO menu_def VALUES(223,'Data Analysis Admin','link','param_file_mass_mods/report','Param File Mass Mods');
INSERT INTO menu_def VALUES(224,'Data Analysis Admin','link','update_analysis_jobs/create','Multi-Job Update');
INSERT INTO menu_def VALUES(225,'Data Analysis Admin','link','analysis_batch/report','Batches');
INSERT INTO menu_def VALUES(226,'Data Analysis Admin','link','analysis_group/create','Job Entry');
INSERT INTO menu_def VALUES(227,'Data Analysis Admin','submenu','Processor Groups Admin','Processor Groups');
INSERT INTO menu_def VALUES(228,'Processor Groups Admin','link','analysis_job_processor_group/report','Report');
INSERT INTO menu_def VALUES(229,'Processor Groups Admin','link','analysis_job_processor_group/create','Entry');
INSERT INTO menu_def VALUES(230,'Data Analysis Admin','submenu','Processors Admin','Processors');
INSERT INTO menu_def VALUES(231,'Processors Admin','link','analysis_job_processors/report','Report');
INSERT INTO menu_def VALUES(232,'Processors Admin','link','analysis_job_processors/create','Entry');
INSERT INTO menu_def VALUES(233,'Data Analysis Admin','submenu','Predefines Admin','Predefines');
INSERT INTO menu_def VALUES(234,'Predefines Admin','submenu','Predefines Admin Report','Report');
INSERT INTO menu_def VALUES(235,'Predefines Admin Report','link','predefined_analysis/report/-','All');
INSERT INTO menu_def VALUES(236,'Predefines Admin Report','link','predefined_analysis/report/Agilent_Ion_Trap','Agilent_Ion_Trap');
INSERT INTO menu_def VALUES(237,'Predefines Admin Report','link','predefined_analysis/report/Agilent_TOF','Agilent_TOF');
INSERT INTO menu_def VALUES(238,'Predefines Admin Report','link','predefined_analysis/report/BRUKERFTMS','BRUKERFTMS');
INSERT INTO menu_def VALUES(239,'Predefines Admin Report','link','predefined_analysis/report/Finnigan_FTICR','Finnigan_FTICR');
INSERT INTO menu_def VALUES(240,'Predefines Admin Report','link','predefined_analysis/report/Finnigan_Ion_Trap','Finnigan_Ion_Trap');
INSERT INTO menu_def VALUES(241,'Predefines Admin Report','link','predefined_analysis/report/LTQ_FT','LTQ_FT');
INSERT INTO menu_def VALUES(242,'Predefines Admin Report','link','predefined_analysis/report/Micromass_QTOF','Micromass_QTOF');
INSERT INTO menu_def VALUES(243,'Predefines Admin Report','link','predefined_analysis/report/QStar_QTOF','QStar_QTOF');
INSERT INTO menu_def VALUES(244,'Predefines Admin Report','link','predefined_analysis_disabled/report','(Disabled)');
INSERT INTO menu_def VALUES(245,'Predefines Admin','separator','','');
INSERT INTO menu_def VALUES(246,'Predefines Admin','link','predefined_analysis/create','Entry');
INSERT INTO menu_def VALUES(247,'Predefines Admin','submenu','Predefines Admin Preview','Preview');
INSERT INTO menu_def VALUES(248,'Predefines Admin Preview','link','predefined_analysis_preview/param','Jobs');
INSERT INTO menu_def VALUES(249,'Predefines Admin Preview','link','predefined_analysis_preview_mds/param','Jobs (MDS)');
INSERT INTO menu_def VALUES(250,'Predefines Admin Preview','link','predefined_analysis_datasets/param','Datasets');
INSERT INTO menu_def VALUES(251,'Predefines Admin Preview','separator',' ',' ');
INSERT INTO menu_def VALUES(252,'Predefines Admin','submenu','Predefines Admin Scheduling Rules','Scheduling Rules');
INSERT INTO menu_def VALUES(253,'Predefines Admin Scheduling Rules','link','predefined_analysis_scheduling_rules/report','Report');
INSERT INTO menu_def VALUES(254,'Predefines Admin Scheduling Rules','link','predefined_analysis_scheduling_rules/create','Entry');
INSERT INTO menu_def VALUES(255,'Predefines Admin Scheduling Rules','separator','','');
INSERT INTO menu_def VALUES(256,'Admin','submenu','Data Analysis Pipeline','Data Analysis Pipeline');
INSERT INTO menu_def VALUES(257,'Data Analysis Pipeline','link','settings_files/report','Settings Files');
INSERT INTO menu_def VALUES(258,'Data Analysis Pipeline','link','pipeline_script/report','Script');
INSERT INTO menu_def VALUES(259,'Data Analysis Pipeline','link','pipeline_jobs/report','Jobs');
INSERT INTO menu_def VALUES(260,'Data Analysis Pipeline','link','pipeline_job_steps/report','Job Steps');
INSERT INTO menu_def VALUES(261,'Data Analysis Pipeline','link','pipeline_jobs/create','Pipeline Job Entry');
INSERT INTO menu_def VALUES(262,'Data Analysis Pipeline','link','pipeline_local_processors/report','Local Processors');
INSERT INTO menu_def VALUES(263,'Data Analysis Pipeline','link','pipeline_step_tools/report','Step Tools');
INSERT INTO menu_def VALUES(264,'Data Analysis Pipeline','link','pipeline_processor_tool_crosstab/report','Processor Tool Crosstab');
INSERT INTO menu_def VALUES(265,'Data Analysis Pipeline','link','pipeline_processor_step_tools/report','Processor Step Tools');
INSERT INTO menu_def VALUES(266,'Admin','submenu','Capture Pipeline','Capture Pipeline');
INSERT INTO menu_def VALUES(267,'Capture Pipeline','link','capture_script/report','Script');
INSERT INTO menu_def VALUES(268,'Capture Pipeline','link','capture_jobs/report','Jobs');
INSERT INTO menu_def VALUES(269,'Capture Pipeline','link','capture_job_steps/report','Job Steps');
INSERT INTO menu_def VALUES(270,'Capture Pipeline','link','capture_local_processors/report','Local Processors');
INSERT INTO menu_def VALUES(271,'Capture Pipeline','link','capture_step_tools/report','Step Tools');
INSERT INTO menu_def VALUES(273,'Capture Pipeline','link','capture_processor_step_tools/report','Processor Step Tools');
INSERT INTO menu_def VALUES(274,'Admin','submenu','Capture Status Checks','Capture Status Checks');
INSERT INTO menu_def VALUES(275,'Admin','submenu','Dataset Admin','Dataset');
INSERT INTO menu_def VALUES(278,'Dataset Admin','link','dataset_redisposition/create','Redisposition Dataset');
INSERT INTO menu_def VALUES(279,'Dataset Admin','separator','','');
INSERT INTO menu_def VALUES(296,'Admin','submenu','Event Log','Event Log');
INSERT INTO menu_def VALUES(297,'Event Log','link','event_log_dataset/report','Dataset');
INSERT INTO menu_def VALUES(298,'Event Log','link','event_log_analysis_job/report','Analyses');
INSERT INTO menu_def VALUES(299,'Event Log','link','event_log_archive/report','Archive');
INSERT INTO menu_def VALUES(300,'Admin','submenu','Instruments Admin','Instruments');
INSERT INTO menu_def VALUES(301,'Instruments Admin','link','instrument/report','Report');
INSERT INTO menu_def VALUES(302,'Instruments Admin','link','new_instrument/create','New');
INSERT INTO menu_def VALUES(303,'Instruments Admin','link','run_op_logs/grid','Operation Log Grid');
INSERT INTO menu_def VALUES(304,'Admin','submenu','Instrument Class','Instrument Class');
INSERT INTO menu_def VALUES(305,'Instrument Class','link','instrumentclass/report','Report');
INSERT INTO menu_def VALUES(306,'Instrument Class','link','new_instrumentclass/create','Entry');
INSERT INTO menu_def VALUES(329,'EMSL Admin Instrument Usage','linke','project_usage/report/__ThisYear__/__ThisWeek__/user','Weekly usage by project');
INSERT INTO menu_def VALUES(330,'Admin','submenu','Ontology','Ontology / Unimod');
INSERT INTO menu_def VALUES(331,'Ontology','link','ncbi_taxonomy/report','NCBI Taxonomy Names');
INSERT INTO menu_def VALUES(332,'Ontology','link','ontology/report/NEWT/-/-/mus mus/-/-/','Species (NEWT)');
INSERT INTO menu_def VALUES(333,'Ontology','link','tissue/report','Tissue (BTO)');
INSERT INTO menu_def VALUES(334,'Ontology','link','ontology/report/CL/-/-/blood/-/-/','Cell Type (CL)');
INSERT INTO menu_def VALUES(335,'Ontology','link','ontology/report/DOID/-/-/diab/-/-/','Disease (DOID)');
INSERT INTO menu_def VALUES(336,'Ontology','link','unimod/report/','Unimod Mods');
INSERT INTO menu_def VALUES(337,'Admin','submenu','Organisms Admin','Organisms');
INSERT INTO menu_def VALUES(338,'Organisms Admin','link','organism/report','Report');
INSERT INTO menu_def VALUES(339,'Organisms Admin','link','organism/create','Entry');
INSERT INTO menu_def VALUES(340,'Organisms Admin','link','ncbi_taxonomy/report','NCBI Taxonomy Names');
INSERT INTO menu_def VALUES(341,'Organisms Admin','link','protein_collection/report','Protein Collections');
INSERT INTO menu_def VALUES(342,'Admin','submenu','File Storage','Storage');
INSERT INTO menu_def VALUES(343,'File Storage','link','storage/report','Report');
INSERT INTO menu_def VALUES(344,'File Storage','link','storage/create','Entry');
INSERT INTO menu_def VALUES(345,'File Storage','link','storage_recent_changes/report','Most recent changes');
INSERT INTO menu_def VALUES(346,'Admin','submenu','User Admin','Users');
INSERT INTO menu_def VALUES(347,'User Admin','link','user/report','Report');
INSERT INTO menu_def VALUES(348,'User Admin','link','user/create','Entry');
INSERT INTO menu_def VALUES(349,'User Admin','link','user_operation/report','Operations');
INSERT INTO menu_def VALUES(350,'Admin','submenu','Internal Standards Admin','Internal Standards');
INSERT INTO menu_def VALUES(351,'Internal Standards Admin','link','internal_standards/report','Report');
INSERT INTO menu_def VALUES(352,'Admin','submenu','Manager Control','Manager Control');
INSERT INTO menu_def VALUES(353,'Manager Control','link','mc_params/report','Parameters');
INSERT INTO menu_def VALUES(354,'Manager Control','link','mc_enable_control_by_manager/report','Manager Control');
INSERT INTO menu_def VALUES(355,'Manager Control','link','mc_enable_control_by_manager_type/report','Manager Type Control');
INSERT INTO menu_def VALUES(356,'Admin','submenu','Metadata Dump','Metadata Dump');
INSERT INTO menu_def VALUES(357,'Metadata Dump','link','dump_metadata_for_multiple_experiments/param','Experiment Metadata');
INSERT INTO menu_def VALUES(358,'Metadata Dump','link','dump_metadata_for_multiple_datasets/param','Dataset Metadata');
INSERT INTO menu_def VALUES(364,'Admin','submenu','Spreadsheet Loader','Spreadsheet Loader');
INSERT INTO menu_def VALUES(365,'Spreadsheet Loader','link','upload/main','Load Spreadsheet');
INSERT INTO menu_def VALUES(366,'Capture Status Checks','link','capture_daily_check/report/-','All');
INSERT INTO menu_def VALUES(367,'Capture Status Checks','link','capture_daily_check/report/DatasetCapture','Dataset Capture');
INSERT INTO menu_def VALUES(368,'Capture Status Checks','link','capture_daily_check/report/ArchiveUpdate','Archive Update');
INSERT INTO menu_def VALUES(369,'Capture Status Checks','link','capture_daily_check/report/DatasetArchive','Dataset Archive');
INSERT INTO menu_def VALUES(370,'Capture Status Checks','link','capture_daily_check/report/SourceFileRename','Source File Rename');
INSERT INTO menu_def VALUES(371,'Capture Pipeline','link','capture_multi_job_update/create','Multi-Job Update');
INSERT INTO menu_def VALUES(372,'Capture Pipeline','link','capture_log/report','Capture Log');
INSERT INTO menu_def VALUES(373,'Requested Run Reports','link','requested_run/report/-/-/-/-','Requests - All');
INSERT INTO menu_def VALUES(374,'Requested Run Reports','link','requested_run/report/-/-/Active','Requests - Active');
INSERT INTO menu_def VALUES(375,'Requested Run Reports','link','requested_run/report/-/-/Inactive','Requests - Inactive');
INSERT INTO menu_def VALUES(376,'Requested Run Reports','link','requested_run/report/-/-/Completed','Requests - Completed');
INSERT INTO menu_def VALUES(378,'Requested Run Reports','link','requested_run_admin/report','Admin Report');
INSERT INTO menu_def VALUES(379,'Requested Run Reports','link','dataset_instrument_runtime/param','Instrument Runtimes');
CREATE TABLE nav_def (
    "id" INTEGER PRIMARY KEY,
    "owner_menu" TEXT,
    "item_type" TEXT,
    "item_name" TEXT,
    "item_label" TEXT,
    "item_help" TEXT
);
INSERT INTO nav_def VALUES(1,'','header_context','side_panel_toggle','','');
INSERT INTO nav_def VALUES(2,'','header_context','home_link','','');
INSERT INTO nav_def VALUES(3,'','header_context','admin_page_link','','');
INSERT INTO nav_def VALUES(4,'','submenu','General','General','');
INSERT INTO nav_def VALUES(5,'General','separator','','Navigation','');
INSERT INTO nav_def VALUES(6,'General','link','gen/welcome','Home','');
INSERT INTO nav_def VALUES(7,'General','link','javascript:gamma.kill_frames()','Hide Side Menu','');
INSERT INTO nav_def VALUES(8,'General','link','javascript:gamma.open_frames()','Show Side Menu','');
INSERT INTO nav_def VALUES(9,'General','link','http://prismwiki.pnl.gov/wiki/PRISM_QuickStart_Guide','PRISM Wiki','');
INSERT INTO nav_def VALUES(10,'General','separator','','Preferences','');
INSERT INTO nav_def VALUES(11,'General','link','preferences','Preferences','');
INSERT INTO nav_def VALUES(12,'General','link_context','save_settings_link','Save Page Settings','Save current settings as defaults');
INSERT INTO nav_def VALUES(13,'General','link_context','clear_settings_link','Clear Page Settings','Clear any saved defaults');
INSERT INTO nav_def VALUES(17,'General','separator','','Campaigns','');
INSERT INTO nav_def VALUES(18,'General','link','campaign/report','Report','Display list of campaigns');
INSERT INTO nav_def VALUES(19,'General','link','campaign/search','Search','');
INSERT INTO nav_def VALUES(20,'General','link','campaign/create','Entry','Create a new campaign');
INSERT INTO nav_def VALUES(21,'General','link','staff_roles/report','Staff Roles','Display staff roles and responsibilities for campaigns');
INSERT INTO nav_def VALUES(22,'General','separator','','Data Packages','');
INSERT INTO nav_def VALUES(23,'General','link','data_package/report','Report','Display list of data packages');
INSERT INTO nav_def VALUES(24,'General','link','data_package/create','Entry','Create a new data package');
INSERT INTO nav_def VALUES(25,'General','separator','','File Attachments','');
INSERT INTO nav_def VALUES(26,'General','link','file_attachment/report','Report','Display list of file attachments');
INSERT INTO nav_def VALUES(27,'','submenu','Samples','Samples','');
INSERT INTO nav_def VALUES(42,'Samples','separator','','Experiments','');
INSERT INTO nav_def VALUES(43,'Samples','link','experiment/report','Report','Display a list of experiments');
INSERT INTO nav_def VALUES(44,'Samples','link','experiment/search','Search','Search for experiments');
INSERT INTO nav_def VALUES(45,'Samples','link','experiment/create','Entry','Create a new experiment');
INSERT INTO nav_def VALUES(46,'Samples','separator','','Experiment Groups','');
INSERT INTO nav_def VALUES(47,'Samples','link','experiment_group/report','Report','Display a list of experiment fractionation groups');
INSERT INTO nav_def VALUES(48,'Samples','link','experiment_fraction/create','Entry - Fractions','Create a new experiment fractionation group');
INSERT INTO nav_def VALUES(49,'Samples','link','experiment_group/create','Entry - General','Create a new general experiment group');
INSERT INTO nav_def VALUES(50,'Samples','separator','','Biomaterial and Ref Comp','');
INSERT INTO nav_def VALUES(51,'Samples','link','biomaterial/report','Biomaterial Report','Display list of biomaterial items');
INSERT INTO nav_def VALUES(52,'Samples','link','biomaterial/create','Biomaterial Entry','Create a new biomaterial item');
INSERT INTO nav_def VALUES(53,'Samples','link','reference_compound/report','Reference Compounds','Show list of reference compounds');
INSERT INTO nav_def VALUES(54,'','submenu','Instrument Runs','Instrument Runs','');
INSERT INTO nav_def VALUES(55,'Instrument Runs','separator','','Requested Runs','');
INSERT INTO nav_def VALUES(56,'Instrument Runs','link','requested_run/report/-/-/Active','Report - Active','Display list of active requested runs');
INSERT INTO nav_def VALUES(57,'Instrument Runs','link','requested_run/report/-/-/Completed','Report - Completed','Display list of requesed runs that have been completed by datasets');
INSERT INTO nav_def VALUES(58,'Instrument Runs','link','requested_run/create','Single Entry','Create a new requested run for a single experiment');
INSERT INTO nav_def VALUES(59,'Instrument Runs','link','requested_run_group/create','Group Entry','Create a new requested run for an experiment fractionation group');
INSERT INTO nav_def VALUES(75,'Instrument Runs','separator','','Datasets','');
INSERT INTO nav_def VALUES(77,'Instrument Runs','link','dataset/search','Search','Search for datasets');
INSERT INTO nav_def VALUES(78,'Instrument Runs','link','dataset_disposition/search','Disposition','Disposition datasets that are waiting for inspection');
INSERT INTO nav_def VALUES(79,'Instrument Runs','link','dataset_disposition_lite/report','Disposition (No plots)','Disposition datasets that are waiting for inspection');
INSERT INTO nav_def VALUES(80,'Instrument Runs','link','dataset/create','Entry','Create a new dataset');
INSERT INTO nav_def VALUES(81,'Instrument Runs','link','main_log/report','Log','Show log of dataset creation and capture');
INSERT INTO nav_def VALUES(82,'Instrument Runs','separator','','Usage Tracking','');
INSERT INTO nav_def VALUES(83,'Instrument Runs','link','run_tracking/cal','Inst. Usage Tracking','');
INSERT INTO nav_def VALUES(84,'','submenu','Data Analysis','Data Analysis','');
INSERT INTO nav_def VALUES(85,'Data Analysis','separator','','Analysis Requests','');
INSERT INTO nav_def VALUES(86,'Data Analysis','link','analysis_job_request/report/-/-/-','Report All','Display list of analysis requests');
INSERT INTO nav_def VALUES(87,'Data Analysis','link','analysis_job_request/report/New','Report - New','Display list of analysis requests that are in New state');
INSERT INTO nav_def VALUES(88,'Data Analysis','link','analysis_job_request/report/Used','Report - Used','Display list of analysis requests that are in Used state');
INSERT INTO nav_def VALUES(89,'Data Analysis','link','analysis_job_request_psm/create','MS/MS Job Wizard','Create a new MS/MS analysis job request based on suggested defaults');
INSERT INTO nav_def VALUES(90,'Data Analysis','link','analysis_job_request/create','Generic Entry','Create a new analysis job request');
INSERT INTO nav_def VALUES(91,'Data Analysis','separator','','Analysis Jobs','');
INSERT INTO nav_def VALUES(92,'Data Analysis','link','analysis_job/search','Search','Search for analysis jobs');
INSERT INTO nav_def VALUES(93,'Data Analysis','separator','','Analysis Job Reports','');
INSERT INTO nav_def VALUES(96,'Data Analysis','link','analysis_job/report/-/-/StartsWith__MSGFPlus/-/-/-/-/-/52','MS-GF+','Display list of MS-GF+ analysis jobs (last 12 months)');
INSERT INTO nav_def VALUES(97,'Data Analysis','link','analysis_job/report/-/-/StartsWith__Decon2LS/-/-/-/-/-/52','DeconTools','Display list of DeconTools analysis jobs (last 12 months)');
INSERT INTO nav_def VALUES(98,'Data Analysis','link','analysis_job/report/-/-/StartsWith__MASIC/-/-/-/-/-/52','MASIC','Display list of MASIC analysis jobs (last 12 months)');
INSERT INTO nav_def VALUES(99,'Data Analysis','link','analysis_job/report/-/-/StartsWith__MSAlign/-/-/-/-/-/52','MSAlign','Display list of MSAlign analysis jobs (last 12 months)');
INSERT INTO nav_def VALUES(100,'Data Analysis','link','analysis_job/report/-/-/StartsWith__XTandem/-/-/-/-/-/52','X!Tandem','Display list of X!Tandem analysis jobs (last 12 months)');
INSERT INTO nav_def VALUES(102,'Data Analysis','separator','','PSM Stats','');
INSERT INTO nav_def VALUES(103,'Data Analysis','link','analysis_job_psm/report/','Job PSM Stats','');
INSERT INTO nav_def VALUES(104,'Data Analysis','link','data_package_analysis_job_psm/report/-/-/-/StartsWith__msgfplus','Data Pkg Job PSM Stats','');
INSERT INTO nav_def VALUES(105,'Data Analysis','link','dataset_psm_and_pm/report/4/StartsWith__msgfplus','Dataset PSM Stats','');
INSERT INTO nav_def VALUES(106,'Data Analysis','link','data_package_dataset_psm_and_pm/report/-/4/StartsWith__msgfplus','Data Pkg Dataset PSM Stats','');
INSERT INTO nav_def VALUES(107,'','submenu','LC','LC','');
INSERT INTO nav_def VALUES(108,'LC','separator','','Columns','');
INSERT INTO nav_def VALUES(109,'LC','link','lc_column/report','Report','Display list of LC columns');
INSERT INTO nav_def VALUES(110,'LC','link','lc_column/create','Entry','Create a new LC column');
INSERT INTO nav_def VALUES(111,'LC','link','lc_column_dataset/report','Dataset Count','Display list of LC columns showing number of samples run');
INSERT INTO nav_def VALUES(112,'LC','separator','','Carts','');
INSERT INTO nav_def VALUES(113,'LC','link','lc_cart/report','Report','Display list of LC carts');
INSERT INTO nav_def VALUES(114,'LC','link','lc_cart/create','Entry','Create new LC Cart');
INSERT INTO nav_def VALUES(117,'LC','link','lc_cart_request_loading/report','Configure loading (Req)','Prepare sample loading for LC Cart by requested runs');
INSERT INTO nav_def VALUES(118,'LC','link','lc_cart_loading/report','Loading List','Display requested run queue');
INSERT INTO nav_def VALUES(120,'LC','link','lc_cart_configuration/report','Cart Configurations','Display LC Cart configurations');
INSERT INTO nav_def VALUES(121,'LC','separator','','Cart Maintenance','');
INSERT INTO nav_def VALUES(122,'LC','link','lc_cart_config_history/report','Service Notes','Display LC cart service notes');
INSERT INTO nav_def VALUES(123,'LC','link','lc_cart_config_history/create','New Service Note','Add a new cart service note');
INSERT INTO nav_def VALUES(124,'LC','separator','','Instrument Config.','');
INSERT INTO nav_def VALUES(125,'LC','link','instrument_config/report','Inst. List','Display list of instruments');
INSERT INTO nav_def VALUES(126,'LC','link','instrument_config_history/report','Config. History','Display instrument config history');
INSERT INTO nav_def VALUES(127,'LC','link','instrument_config_history/Create','Service Note','Create new instrument config note');
INSERT INTO nav_def VALUES(128,'LC','link','instrument_operation_history/report','Operation Notes','Display instrument operation notes');
INSERT INTO nav_def VALUES(129,'LC','link','instrument_operation_history/create','Add Operation Note..','Add new instrument operation notes');
INSERT INTO nav_def VALUES(130,'','submenu','Search','Search','');
INSERT INTO nav_def VALUES(131,'Search','separator','','Simple Search','');
INSERT INTO nav_def VALUES(132,'Search','link','analysis_job/search','Analysis Jobs','');
INSERT INTO nav_def VALUES(133,'Search','link','dataset/search','Datasets','');
INSERT INTO nav_def VALUES(135,'Search','link','requested_run/search','Requested Runs','');
INSERT INTO nav_def VALUES(137,'Search','link','experiment/search','Experiments','');
INSERT INTO nav_def VALUES(139,'Search','link','campaign/search','Campaigns','');
INSERT INTO nav_def VALUES(140,'Search','link','custom_factors/search','Factors','');
INSERT INTO nav_def VALUES(150,'','submenu','Help',' Help','');
INSERT INTO nav_def VALUES(151,'Help','separator','','Help','');
INSERT INTO nav_def VALUES(152,'Help','link_context','help_basic_link','Help for page type','Show help page for this type of DMS page');
INSERT INTO nav_def VALUES(153,'Help','link_context','help_page_link','Help for specific page','Show help page for this DMS page');
INSERT INTO nav_def VALUES(154,'Help','separator','','Info','');
INSERT INTO nav_def VALUES(155,'Help','link_context','page_info_link','Page info','');
INSERT INTO nav_def VALUES(156,'Help','link_context','config_db_link','Page config','');
INSERT INTO nav_def VALUES(157,'','header_context','server_info','Page config','');
INSERT INTO nav_def VALUES(158,'Help','link_context','sql_link','SQL','Show SQL that returned data for this page');
INSERT INTO nav_def VALUES(159,'Help','link_context','url_link','URL','Show URL and filter information');
COMMIT;
