PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('list_report_sproc','GetParamFileCrosstab');
CREATE TABLE form_fields ( id INTEGER PRIMARY KEY, "name"  text, "label" text, "type" text, "size" text, "maxlength" text, "rows" text, "cols" text, "default" text, "rules" text);
INSERT INTO form_fields VALUES(1,'ParameterFileTypeName','Parameter File Type Name','text','60','64','','','','trim|required|max_length[64]');
INSERT INTO form_fields VALUES(2,'ParameterFileFilter','Parameter File Filter','text','60','128','','','','trim|max_length[128]');
INSERT INTO form_fields VALUES(3,'ShowValidOnly','Show Valid Only','text','1','1','','','0','trim|required|max_length[1]');
INSERT INTO form_fields VALUES(4,'ShowModSymbol','Show Mod Symbol','text','1','1','','','0','trim|required|max_length[1]');
INSERT INTO form_fields VALUES(5,'ShowModName','Show Mod Name','text','1','1','','','1','trim|required|max_length[1]');
INSERT INTO form_fields VALUES(6,'ShowModMass','Show Mod Mass','text','1','1','','','1','trim|required|max_length[1]');
INSERT INTO form_fields VALUES(7,'UseModMassAlternativeName','Use Mod Mass Alternative Name','text','1','1','','','1','trim|required|max_length[1]');
INSERT INTO form_fields VALUES(8,'MassModFilterTextColumn','Mass Mod Filter Text Column','text','60','64','','','','trim|max_length[64]');
INSERT INTO form_fields VALUES(9,'MassModFilterText','Mass Mod Filter Text','text','60','64','','','','trim|max_length[64]');
INSERT INTO form_fields VALUES(10,'previewSql','','hidden','','','','','0','trim');
CREATE TABLE form_field_choosers ( id INTEGER PRIMARY KEY,  "field" text, "type" text, "PickListName" text, "Target" text, "XRef" text, "Delimiter" text, "Label" text);
INSERT INTO form_field_choosers VALUES(1,'ParameterFileTypeName','picker.replace','analysisToolPickList','','',',','');
INSERT INTO form_field_choosers VALUES(2,'ShowModSymbol','picker.replace','yesNoAsOneZeroPickList','','',',','');
INSERT INTO form_field_choosers VALUES(3,'ShowModName','picker.replace','yesNoAsOneZeroPickList','','',',','');
INSERT INTO form_field_choosers VALUES(4,'ShowModMass','picker.replace','yesNoAsOneZeroPickList','','',',','');
INSERT INTO form_field_choosers VALUES(5,'UseModMassAlternativeName','picker.replace','yesNoAsOneZeroPickList','','',',','');
CREATE TABLE sproc_args ( id INTEGER PRIMARY KEY, "field" text, "name" text, "type" text, "dir" text, "size" text, "procedure" text);
INSERT INTO sproc_args VALUES(1,'ParameterFileTypeName','ParameterFileTypeName','varchar','input','64','GetParamFileCrosstab');
INSERT INTO sproc_args VALUES(2,'ParameterFileFilter','ParameterFileFilter','varchar','input','128','GetParamFileCrosstab');
INSERT INTO sproc_args VALUES(3,'ShowValidOnly','ShowValidOnly','tinyint','input','','GetParamFileCrosstab');
INSERT INTO sproc_args VALUES(4,'ShowModSymbol','ShowModSymbol','tinyint','input','','GetParamFileCrosstab');
INSERT INTO sproc_args VALUES(5,'ShowModName','ShowModName','tinyint','input','','GetParamFileCrosstab');
INSERT INTO sproc_args VALUES(6,'ShowModMass','ShowModMass','tinyint','input','','GetParamFileCrosstab');
INSERT INTO sproc_args VALUES(7,'UseModMassAlternativeName','UseModMassAlternativeName','tinyint','input','','GetParamFileCrosstab');
INSERT INTO sproc_args VALUES(8,'<local>','message','varchar','output','512','GetParamFileCrosstab');
INSERT INTO sproc_args VALUES(9,'previewSql','previewSql','tinyint','input','','GetParamFileCrosstab');
INSERT INTO sproc_args VALUES(10,'MassModFilterTextColumn','MassModFilterTextColumn','varchar','input','64','GetParamFileCrosstab');
INSERT INTO sproc_args VALUES(11,'MassModFilterText','MassModFilterText','varchar','input','64','GetParamFileCrosstab');
COMMIT;
