PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','V_Sample_Prep_Request_List_Report');
INSERT INTO general_params VALUES('list_report_data_sort_dir','DESC');
INSERT INTO general_params VALUES('list_report_data_cols','ID,RequestName,Created,Priority,State, CONVERT(char(42),Reason) as Reason,NumSamples,PrepMethod,AssignedPersonnel,Organism,Campaign');
INSERT INTO general_params VALUES('list_report_helper_multiple_selection','yes');
INSERT INTO general_params VALUES('list_report_data_cols','ID AS Sel, *');
INSERT INTO general_params VALUES('list_report_data_sort_col','ID');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_state','State','32','','State','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_requestname','RequestName','32','','RequestName','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_reason','Reason','32','','Reason','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_assignedpersonnel','AssignedPersonnel','32','','AssignedPersonnel','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_prepmethod','PrepMethod','32','','PrepMethod','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_campaign','Campaign','32','','Campaign','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_organism','Organism','32','','Organism','ContainsText','text','128','','');
INSERT INTO list_report_primary_filter VALUES(8,'pf_priority','Priority','32','','Priority','ContainsText','text','128','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'ID','update_opener','value','','');
INSERT INTO list_report_hotlinks VALUES(2,'Sel','CHECKBOX','ID','','');
COMMIT;
