PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('base_table','T_Mass_Correction_Factors');
INSERT INTO general_params VALUES('list_report_data_table','V_Mass_Correction_Factors');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_id','ID','','','Mass_Correction_ID','Equals','text','','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_name','Name','','','Mass_Correction_Tag','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_description','Description','','','Description','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_mono_mass_min','Min Mass','','','Monoisotopic_Mass','GreaterThanOrEqualTo','text','','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_mono_mass_max','Max Mass','','','Monoisotopic_Mass','LessThanOrEqualTo','text','','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_original_source_name','Source Name','35!','','Original_Source_Name','ContainsText','text','','','');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'Mass_Correction_ID','invoke_entity','value','param_file_mass_mods/report/-/','');
INSERT INTO list_report_hotlinks VALUES(2,'Original_Source_Name','invoke_entity','value','unimod/report/~','');
COMMIT;
