PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE general_params ( "name" text, "value" text );
INSERT INTO general_params VALUES('list_report_data_table','V_Protein_Collection_List_Report');
INSERT INTO general_params VALUES('list_report_data_sort_dir','desc');
INSERT INTO general_params VALUES('detail_report_data_table','V_Protein_Collection_List_Report');
INSERT INTO general_params VALUES('detail_report_data_id_col','ID');
INSERT INTO general_params VALUES('detail_report_data_id_type','integer');
CREATE TABLE list_report_hotlinks ( id INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Options" text );
INSERT INTO list_report_hotlinks VALUES(1,'Organism Name','invoke_entity','value','organism/report/~','');
INSERT INTO list_report_hotlinks VALUES(2,'Usage Last 12 Months','invoke_entity','Name','analysis_job/report/-/-/-/-/-/-/@/-/52','');
INSERT INTO list_report_hotlinks VALUES(3,'Usage All Years','invoke_entity','Name','analysis_job/report/-/-/-/-/-/-/@','');
INSERT INTO list_report_hotlinks VALUES(4,'ID','invoke_entity','value','/protein_collection/show/','');
INSERT INTO list_report_hotlinks VALUES(5,'Entries','invoke_entity','ID','protein_collection_members/report/@','');
INSERT INTO list_report_hotlinks VALUES(6,'+Entries','format_commas','value','','{"Decimals":"0"}');
INSERT INTO list_report_hotlinks VALUES(7,'Residues','format_commas','value','','{"Decimals":"0"}');
INSERT INTO list_report_hotlinks VALUES(8,'Description','min_col_width','value','60','');
CREATE TABLE list_report_primary_filter ( id INTEGER PRIMARY KEY,  "name" text, "label" text, "size" text, "value" text, "col" text, "cmp" text, "type" text, "maxlength" text, "rows" text, "cols" text );
INSERT INTO list_report_primary_filter VALUES(1,'pf_Name','Name','40!','','Name','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(2,'pf_Organism','Organism','15!','','Organism Name','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(3,'pf_Usage','Most recent weeks','2!','','Most Recent Usage','MostRecentWeeks','text','','','');
INSERT INTO list_report_primary_filter VALUES(4,'pf_Min_Entries','Min entries','5!','','Entries','GreaterThanOrEqualTo','text','','','');
INSERT INTO list_report_primary_filter VALUES(5,'pf_Max_Entries','Max entries','5!','','Entries','LessThanOrEqualTo','text','','','');
INSERT INTO list_report_primary_filter VALUES(6,'pf_Description','Description','','','Description','ContainsText','text','','','');
INSERT INTO list_report_primary_filter VALUES(7,'pf_Source','Source','20!','','Source','ContainsText','text','','','');
CREATE TABLE detail_report_hotlinks ( idx INTEGER PRIMARY KEY,  "name" text, "LinkType" text, "WhichArg" text, "Target" text, "Placement" text, "id" text , options text);
INSERT INTO detail_report_hotlinks VALUES(1,'Organism Name','detail-report','Organism Name','organism/report/~','labelCol','dl_organism',NULL);
INSERT INTO detail_report_hotlinks VALUES(2,'Usage Last 12 Months','detail-report','Name','analysis_job/report/-/-/-/-/-/-/@/-/52','labelCol','dl_usage_12_months','');
INSERT INTO detail_report_hotlinks VALUES(3,'Usage All Years','detail-report','Name','analysis_job/report/-/-/-/-/-/-/@/-/-','labelCol','dl_usage_all_years','');
INSERT INTO detail_report_hotlinks VALUES(4,'Entries','detail-report','ID','protein_collection_members/report/@/-/-/-','labelCol','dl_entries','');
INSERT INTO detail_report_hotlinks VALUES(5,'+Entries','format_commas','Entries','','valueCol','dl_entries_formatter','{"Decimals":"0"}');
INSERT INTO detail_report_hotlinks VALUES(6,'Residues','format_commas','Residues','','valueCol','dl_residues_formatter','{"Decimals":"0"}');
INSERT INTO detail_report_hotlinks VALUES(7,'Name','detail-report','Name','protein_collection/report/~','valueCol','dl_name',NULL);
INSERT INTO detail_report_hotlinks VALUES(8,'ID','detail-report','ID','protein_collection_members/report/@/-/-/-','valueCol','dl_entries_2','');
COMMIT;
