<script  src="<?= base_url('javascript/sortablejs/Sortable.min.js') ?>"></script>
<script  src="<?= base_url('javascript/SlickGrid/slick.core.js?version=300') ?>"></script>
<script  src="<?= base_url('javascript/SlickGrid/slick.interactions.js?version=300') ?>"></script>
<script  src="<?= base_url('javascript/SlickGrid/slick.grid.js?version=300') ?>"></script>
<script  src="<?= base_url('javascript/SlickGrid/plugins/slick.cellrangedecorator.js?version=300') ?>"></script>
<script  src="<?= base_url('javascript/SlickGrid/plugins/slick.cellrangeselector.js?version=300') ?>"></script>
<script  src="<?= base_url('javascript/SlickGrid/plugins/slick.cellselectionmodel.js?version=300') ?>"></script>
<script  src="<?= base_url('javascript/SlickGrid/plugins/slick.headerbuttons.js?version=300') ?>"></script>
<script  src="<?= base_url('javascript/SlickGrid/plugins/slick.headermenu.js?version=300') ?>"></script>
<script  src="<?= base_url('javascript/SlickGrid/plugins/slick.autotooltips.js?version=300') ?>"></script>
<script  src="<?= base_url('javascript/SlickGrid/slick.formatters.js?version=300') ?>"></script>
<script  src="<?= base_url('javascript/SlickGrid/slick.editors.js?version=300') ?>"></script>
