<script  src="<?= base_url().'SlickGrid/slick.core.js' ?>"></script>
<script  src="<?= base_url().'SlickGrid/slick.grid.js' ?>"></script>
<script  src="<?= base_url().'SlickGrid/plugins/slick.cellrangedecorator.js' ?>"></script>
<script  src="<?= base_url().'SlickGrid/plugins/slick.cellrangeselector.js' ?>"></script>
<script  src="<?= base_url().'SlickGrid/plugins/slick.cellselectionmodel.js' ?>"></script>
<script  src="<?= base_url().'SlickGrid/plugins/slick.headerbuttons.js' ?>"></script>
<script  src="<?= base_url().'SlickGrid/plugins/slick.headermenu.js' ?>"></script>
<script  src="<?= base_url().'SlickGrid/plugins/slick.autotooltips.js' ?>"></script>
<script  src="<?= base_url().'SlickGrid/slick.formatters.js' ?>"></script>
<script  src="<?= base_url().'SlickGrid/slick.editors.js' ?>"></script>
